### ISSUE TITLE
Hotkeys don't persist between Wesnoth session

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#1016]
Release: 	1.13.7+dev	Operating System: 	Win 7 x64

As of commit: https://github.com/wesnoth/wesnoth/commit/40138d4c164864bf9a1b6afcfd8345d2165602f3
Using a Dvorak English layout, 
I set Scenario Objectives to ' . This works fine, until I quit wesnoth.exe and then restart it. The programmed key is lost. 
See also https://gna.org/bugs/?25683 ???

**Comment by sigurdfdragon** [comment]
@Wedge009 Looking at the preferences file, it looks to be a case of not being saved to the preferences file

**Comment by Wedge009** [comment]
I know there was a change to hot-keys recently but I don't know the details. I had a go at SDL1 hot-keys and made a mess of it, SDL2 hot-keys is even more complex to me.

Anyway, the issue seems quite bad - it looks like the key value is no longer saved in the preferences file. Everything else seems to be recorded: Alt, Ctrl, Shift, Disabled, etc, just not the key itself. At first I thought it was just limited to special, non-alphanumeric characters, but it fails to record letters and numbers as well now. Oh, and I'm using a 'standard' US QWERTY keyboard, with US keyboard layout in OS.

**Comment by sigurdfdragon** [comment]
this bug was introduced in https://github.com/wesnoth/wesnoth/commit/af1326d19bc995671e6430cb232d1192f8b4c37b

**Comment by sigurdfdragon** [comment]
fixed, thanks
