### ISSUE TITLE
fixed point macros can't be turned off anymore (GNA #4932)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1058]
**[Original submission](https://gna.org/bugs/index.php?4932)** by jbreiden on 2005-12-21

in src/util.hpp, there are some macros that allow fixed and floating point calculations to be swapped back and forth. scale_image (in sdl_utils.cpp) and display::draw_bar (in display.cpp) both will break if fixed point is turned off. Can be fixed with some macroificicaion. Maybe it doesn't matter.

(Reproduced on Linux)
Release: head (1.1?)
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by GregoryLundberg** [comment]
Can this be closed?

* the OP is from 2005
* there is no src/utils.hpp any more.
* src/display.cpp has no deisplay::draw_bar any more.

**Comment by CelticMinstrel** [comment]
I seem to recall those macros being removed, as well.

**Comment by jyrkive** [comment]
These macros still exist: https://github.com/wesnoth/wesnoth/blob/d78ed1c36d50146568e8cc34049b5e10e00ecd53/src/utils/math.hpp#L312-L335

And they are still being used by `scale_surface()`.

**Comment by CelticMinstrel** [comment]
Ah, okay. Well, presumably we can just remove the `#if` and stuff, then.

**Comment by GregoryLundberg** [comment]
Um. WTF? We seriously were doing a de-normalizing floating-point implementation? What, did one of the target machines lack a working floating-point unit?

I'd strongly suggest change `#if 1` to `#if 0`, debug, then reduce until the macros meet their long-overdue demise.

**Comment by CelticMinstrel** [comment]
I believe one of the target machines actually _did_ lack a floating-point unit - OpenPandora possibly? Support for that has been dropped now, though.

**Comment by jyrkive** [comment]
My guess would be that the fixed-point implementation is used for performance.

**Comment by GregoryLundberg** [comment]
Well, take the junk out and see if the game crawls.

While I agree, it's possible someone's attempt at an optimization, but if so it smells highly of premature optimization. I'd want a comment block with A/B test results proving a significant improvement. Otherwise, this is just an obscure way to hide basic errors.

**Comment by GregoryLundberg** [comment]
Near as I can tell, all this junk is being used in stuff having to do with pixel values R G B and Alpha.  The idea is to do some of the math in a fixed-point representation where we have and int32_t holding a 24 bits left of the decimal and 8 bits to the right. Of course, it's sorta lame to be doing signed math on unsigned values, but whatever. Most of the uses are creating the values 0x00000000 and 0x00000100 (0.0 and 1.0).

In at least one place, the int32_t value is stored in an int16_t so I hope whoever did that made very sure to avoid any implicit sign extension errors.

Is this a code smell? Yes.

Is it screaming to be fixed? No. It doesn't seem to be causing any problems.

Is it premature optimization? Probably. But, considering where it's used, in the few places it actually does anything, it's probably actually speeding things up enough to be warranted.

My recommendation would be to hold our noses, leave things as they are and put the entire src/utils/math.hpp file on the list of good projects for a new programmer to work on because it's probably not causing issues, but it's just asking for cleanup and/or elimination.
