### ISSUE TITLE
Setting game name shouldn't show when playing a local game (GNA #10785)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1122]
**[Original submission](https://gna.org/bugs/index.php?10785)** by blueblaze on 2008-01-15

Another minor issue, the name of the game shouldn't show when playing a local game, as it's just a pointless option that I can tell. Unless the game name has some effect on the save file, then I don't think it should even be selectable when playing locally.

(Reproduced on XP)
Release: 1.3.14
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Wedge009** [comment]
As best as I can tell there is no name option showing for local MP games in the current (1.14) lobby, which had a pretty major redesign since this report. Feel free to re-open if this is not the case.

**Comment by Wedge009** [comment]
Ah, even in the current design I found the 'name of game' option is still present. Re-opening.

**Comment by jostephd** [comment]
> Another minor issue, the name of the game shouldn't show when playing a local game, as it's just a pointless option that I can tell. Unless the game name has some effect on the save file, then I don't think it should even be selectable when playing locally.

The name does actually get stored in the savefile, under `[multiplayer]scenario=`. It's not easy to check if anything uses that, unfortunately, because grepping for `"scenario"` has many unrelated matches. But we could use it in the Load Game dialog, in principle... make save_index.cpp remember it (like it saves `active_mods`) and then make game_load.cpp show the value, instead of just "Multiplayer". Anyway, low priority either way.
