### ISSUE TITLE
Make zoom option easier to find (GNA #16027)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1213]
**[Original submission](https://gna.org/bugs/index.php?16027)** by bhudson on 2010-05-15

I had no idea that one could zoom in and out in wesnoth until my cat walked over the keyboard.  And then I couldn't figure out how to undo the zoom-out that she did, since it's not listed in any menu.

I'd have expected it under Actions, or under right-click, or preferences -> display.

Barring those, I'd have expected it to be the mouse scroll wheel, or shift-scrollwheel, or apple--/apple-=.

(Reproduced on any)
Release: 1.8.1
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-05-16**

**soliton changed severity:** 2 - Minor -> 1 - Wish

**soliton changed OS:** OSX -> any

**soliton changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-05-16**

**anonymous wrote:**

> It's + and -.
> 
> preferences/general/hotkeys

**Comment by beetlenaut** [comment]
"Nil" might be an exaggeration, but if you have to read through a list of a couple hundred hotkeys to discover a feature, it's a little too hidden. There probably should be a slider in preferences, especially with large screens becoming more common.

**Comment by CelticMinstrel** [comment]
Aren't there zoom buttons in the theme near the minimap?

**Comment by beetlenaut** [comment]
Not really. The magnifying glass under the minimap toggles between the default zoom, and whatever you last selected with the + and - keys. It might be better to have two magnifying glasses so you could zoom in or out. However, the toggling behavior is sometimes useful, so I would prefer to keep the magnifying glass as it is and have a slider you could _set_ in the preferences. (As it is, you need to reset the zoom level to whatever you like every time you open the game, which is annoying and doesn't make any sense.)

**Comment by CelticMinstrel** [comment]
I guess making it remember your preferred zoom level would be easy (even without putting a slider in preferences). Should the zoom in/out buttons be added to the theme too, though?

**Comment by beetlenaut** [comment]
In order to address the OP's complaint, we should have either buttons or a slider. I slightly prefer a slider in display preferences because it just seems like the most logical place to look for this setting. (The OP thought so, too.) Also, it would probably be easier than trying to fit more buttons into the theme somewhere.

**Comment by Wedge009** [comment]
We used to have a zoom slider under the mini-map but that was removed - I'm still not sure why that decision was made but it doesn't bother me personally as I'm fine with 100% scaling most of the time anyway. Still, this is a valid request and all the more pertinent as of 1.14.x since the slider's removal.

**Comment by cooljeanius** [comment]
it's still rather difficult to find
