### ISSUE TITLE
When no advancement nor AMLA is defined the xp needed should be infinite and showed in the ui as a "-" (GNA #17262)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1244]
**[Original submission](https://gna.org/bugs/index.php?17262)** by iwontbecreative on 2010-12-07

When a unit doesn't have any advancement and doesn't define any kind of AMLA, the xp should be unlimited. (Because the unit will never level) and showed in the ui as "-" so people can understand it.

 You can see an example of this bug in the tutorial: The fighter/fighteress needs 28 xp to "level" and his xp bar is light blue. Both are confusing because the unit won't level (Will show e.g 34/28 instead) and that the light blue is for units with an advancement.

(Reproduced on Linux)
Release: trunk. (rev47854)
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by hryniuk** [comment]
@sevu is it still a problem? I'd like to fix it, but... it seems it's changed since 2010.

I've played a tutorial, version 1.14.4, and the fighter just advances to the next level. I've used debug commands to add him up to 27 of experience and then I've attacked some Quintain. I'm attaching the save file with that situation.

As I've checked in `data/core/units/` (I hope I haven't missed any other directory) each unit has either `advances_to` or `AMLA_DEFAULT` entry, so it seems that there's no need of implementing the described change.

Commands I've used:
```shell
$ grep "AMLA_DEFAULT\|advances_to" -R -l data/core/units/* | sort | uniq | wc -l
245
$ find data/core/units/ -name "*.cfg" | sort | uniq | wc -l
245
```
[Wesnoth Tutorial — Part I Turn 4.gz](https://github.com/wesnoth/wesnoth/files/2342727/Wesnoth.Tutorial.Part.I.Turn.4.gz)

**Comment by gfgtdf** [comment]
> As I've checked in data/core/units/ (I hope I haven't missed any other directory) each unit has either advances_to or AMLA_DEFAULT entry, so it seems that there's no need of implementing the described change.

may still be units in umc without advances. also it is possible that a scenarios script manually removes advancements froma a single unit.
