### ISSUE TITLE
Image cache also keeps negative results (GNA #19410)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1291]
**[Original submission](https://gna.org/bugs/index.php?19410)** by shadowmaster on 2012-02-04

While investigating how to fix bug #18683 for units in campaigns and eras, I discovered that the image cache mechanism remembers images that could not be loaded from disk, even after loading a campaign and thus processing a [binary_path] definition that would normally enable the image to be loaded.

- To reproduce, you'll first have to break HttT; open data/campaigns/Heir_to_the_Throne/_main.cfg, and change the icon attribute under [campaign] to "units/konrad-fighter.png"

- Start Wesnoth and go to the campaign menu; the HttT entry will not have a visible icon and there'll be an image load error in stderr

- Select HttT and start the campaign; Konrad's unit baseframe will be missing from the map view and sidebar

I'd like confirmation as to whether this is working as intended, or just an oversight, since it is hindering the remainder of bug #18683.

(Reproduced on Most likely all)
Release: 1.10.0+svn, 1.11.0-svn
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Wedge009** [comment]
Follow-up comment from shadowm on 2012-04-14 that was missed in the import:

> Make leader_image paths in the saved games index binary path-independent
> 
> This makes it possible to store in the save_index image paths that can be used in the Load Game dialog even when displaying units whose graphics are in binary paths not currently loaded. This alleviates the effect of this bug on the whole mechanism, but not completely.
> 
> When the save_index is missing, this won't work properly; we'll need to add the leader_image attribute to the saved game config itself later.

**Comment by Vultraz** [comment]
This bug was mitigated 52db950e94a5e09bdfb3ccc7056db3da90d70483 by purging the image cache when reloading the game config for a specific game. However, the underlying issue (negative results in the cache) still remains.

I'm not sure what @shikadiqueen was speaking of at the time regarding the save_index, but I've done extensive work since then to do by damndest to ensure the leader sprites always correctly display in the Load Game dialog. I have succeeded as far as I can tell.

It is worth noting that even *with* the negative cache issue reproduced as described, the Game Load dialog still successfully displays the leader sprite for Konrad when viewing a save generated in that session. :D

**Comment by shikadiqueen** [comment]
I _believe_ at the time the save_index was the only place that would get binary path-neutral sprite paths (e.g. `data/campaigns/Foo/images/bar.png`), which are the only ones with a strong guarantee of working as long as the files are present on disk. I imagine that might have changed since then.

(It's been literally years so I might remember the story completely wrong.)

**Comment by Vultraz** [comment]
FTR, when I was investigating this last weekend I think I figured out the issue, at least how it affects debug mode. If you're in debug mode, and you try to fetch a non-existent entry, the "image not found" image will be cached for that path. I think in non-debug mode, it's simply an empty image being cached. The latter is easy to fix (don't cache if surface is null), but the former needs (just a bit) more work. I'll get to it when I return from wesbreak.

**Comment by AI0867** [comment]
Wouldn't it be a better idea to cache things and simply clear the cache of missing/placeholder images when adding a new binary_path?

**Comment by Vultraz** [comment]
That's essentially what is done by the commit referenced above. Not specifically on the addition of a new `[binary_path]` though, but the effect is basically the same.

**Comment by mesilliac** [comment]
The problem as stated in the OP is fixed. If there's some other reason it matters, a new issue can be opened.
