### ISSUE TITLE
invalid map files: no error reported, then segfault (GNA #21158)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1346]
**[Original submission](https://gna.org/bugs/index.php?21158)** by thunderstruck on 2013-09-22

The gamemap class which is located in map.?pp should handle empty files by throwing "incorrect_map_format_error".

Currently, it still creates a gamemap object and thus "Create Game" window is not able to display a proper error message as with usual map formatting errors.

(Reproduced on All)
Release: 1.11.6+
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-06**

**mordante wrote:**

> This seems to be introduced by rev 52641/d75e320e5aa4b801cb9d0f4ef6722e1d4f37635a

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-15**

**anonymissimus wrote:**

> >This seems to be introduced by rev 52641/d75e320e5aa4b801cb9d0f4ef6722e1d4f37635a
> 
> 
> 
> I don't think so. It should already have happened before that; the default I added (allow_invalid = true) just matches the previous behavior. I was working on the [replace_map] and [terrain_mask] callstacks only when fixing https://gna.org/bugs/?19018 and didn't consider the "mp create game" callstack, perhaps an invalid map should be disallowed as well or  never be allowed. Then gamemap::read would likely throw the incorrect_map_format_error after catching a t_translation::error.

**Comment by jostephd** [comment]
Another version of this: if I create a new scenario and set `map_data="foobar"` in the cfg file, the create game screen doesn't show map size at all (with `map_data=""` it did show size as 0x0), and when I press Create Game I get `error config: map could not be loaded: Condition 'size <= 4' failed at src/terrain/translation.cpp:711 in function 'string_to_layer_'.` and a segfault.

https://github.com/wesnoth/wesnoth/blob/2eccbab9708526ab289f201d40b613c5f25a5a06/src/terrain/translation.cpp#L709-L711

**Comment by gfgtdf** [comment]
> The gamemap class which is located in map.?pp should handle empty files by throwing "incorrect_map_format_error".

im actually inclined to say that generating a 0x0 map for empty map data is the expected behaviour, in particular considering that the gamemap class is not only used in the mp greate screen, but probably also when cutting/pasting things in wml via [terrain_mask]

**Comment by jostephd** [comment]
OK, retitled the issue.

**Comment by mattsc** [comment]
I just tried this in 1.16 by replacing `map_file=multiplayer/maps/2p_The_Freelands.map` with `map_data="foo"` in the Freelands scenario, as described in one of the comments above.  When selecting that map, the left side of the Create Game dialog shows this:
<img width="425" alt="Screen Shot 2022-07-03 at 13 00 09" src="https://user-images.githubusercontent.com/2106424/177055499-4b71fdc5-4957-4695-8571-b8ea7dbf4f37.png">
and when clicking on it you get this dialog:
<img width="468" alt="Screen Shot 2022-07-03 at 13 00 24" src="https://user-images.githubusercontent.com/2106424/177055504-c23b7e0c-32dd-4d54-aae5-e5d723ae84ef.png">
which you can dismiss and continue on to selecting another map.

So it looks to me like this is fixed.

**Comment by soliton-** [comment]
But `foo` is a perfectly valid terrain string? It's just unknown. `foobar` on the other hand is longer than 4 characters. With `foobar` I get the error from the code jostephd mentioned and when I press OK I get back to the main menu. Not a segfault but nicer would be to stay in the create game screen.

**Comment by mattsc** [comment]
Hmm, I had not thought of that.  It also fails differently for 1.16 and 1.17.  In 1.16 you get the message when you enter the Create Game screen and there is no indication which map causes the problem.  In 1.17, you only get the message when you click on the map with the error, so it's obvious.

I don't really care whether we keep this closed or reopen it (the segfault is fixed after all), but I'll have a look and see if this can be improved.  Invalid WML errors usually fall back to the main menu, if I remember correctly, I am not sure how easy it is to change that.  But at least it would be nice to get the same behavior in 1.16 as in 1.17.  Again, not sure how hard that is and if that can be done in the stable series.

**Comment by mattsc** [comment]
I figured out a solution to this issue, but I do not know at this time if it has other implications.  If I change [these 2 lines](https://github.com/wesnoth/wesnoth/blob/master/src/terrain/translation.cpp#L713)
from
```
VALIDATE(str.size() <= 4, _("A terrain with a string with more "
		"than 4 characters has been found, the affected terrain is:") + std::string(str));
```
to
```
throw error("A terrain with a string with more etcetc.");
```
the behavior is as I described above for just using `map_data="foo"`: when clicking on the map, the error message is displayed under the minimap, but otherwise nothing happens.  If you try to start the game with this map, you get the same in a pop-up dialog, which you can dismiss and choose a different map instead.

So I think this is the desired behavior, but I have no idea why this previously used `VALIDATE()`, while almost everything else uses `throw()`.  So I wonder whether this will break something else.  Does anybody know?

**Comment by mattsc** [comment]
One thing I noticed is that if the terrain with more than 4 characters is in a map file, rather than in `map_data`, you still get the error message under the map, but the Create Game dialog actually lets you click the "Create Game" button and the error does not pop up until you click "I'm ready" in the next screen.  FTR, that is the same behavior as is already the case when there is an unknown terrain code of 4 or less characters in a map file.
