### ISSUE TITLE
The Statistics menu is using the wrong data to seed the Recall gold value (GNA #22213)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1395]
**[Original submission](https://gna.org/bugs/index.php?22213)** by skystriker on 2014-06-17

The Statistics menu ingame is using unit cost rather than recall cost to seed the recall value. The Recall value in mainline should simply be 20*Recalls. E.g. in a new scenario, if you recall a White Mage, the value should be 20. However it is 40, as that is the gold cost of a White Mage.

(Reproduced on Windows)
Release: 1.11.12
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-19**

**rjaguar3 wrote:**

> I want to say that this is not a bug.  The statistics window is not intended to be an accounting ledger.  Rather, the aggregate gold values (including using the nominal gold values for level 2 and higher units) for recruits, recalls, losses, and kills are intended to estimate the overall power of the units involved.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-20**

**skystriker wrote:**

> Ah - I had talked with AI on IRC and he said he considered it a bug. Sorry for any confusion.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-25**

**involution wrote:**

> rjaguar3: I think I see your point of view here, it might be good to have both the power estimate and the accounting ledger versions. I think the ledger version seems useful though, for campaign play. 
> 
> 
> 
> In truth the "costs" of level 2 and 3 units that one is typically recalling aren't as rigorously balanced as the level 1 units anyways, so I would say their use for "equal cost equal power" estimates is somewhat noisy.

**Comment by Wedge009** [comment]
Looking at the conversation history, it seems there are arguments for the replacement gold cost of the units in the player's recall list vs a straight calculation of the recall cost of those same units (presumably 0 if loyal, 20 otherwise). Does the fact that this issue is still open suggest that we would want to switch the recall amount in the statistics dialogue to actually be the aforementioned 'accounting ledger'.

If so, is there a place where the recall cost is actually defined? I wouldn't think it a good idea that a first-time contributor should hard-code the 20 gold recall cost in whatever calculations the statistics menu does to generate its content.

**Comment by Pentarctagon** [comment]
Reading the previous conversation again now, it sounds like there was never really a consensus on what (if anything) needs to change.

**Comment by CelticMinstrel** [comment]
If it's not clear what the change should be, I guess it's not a good first issue?

**Comment by Pentarctagon** [comment]
Yeah, not so much. To be honest I wonder if this can just be closed given the last activity is almost 9 years old now.

**Comment by Wedge009** [comment]
I think it's fine to leave it as-is. I don't particularly find the information that useful, but I'd find the 'recall cost of all non-loyal units in the recall list' to be even less useful.
