### ISSUE TITLE
custom timers for lua gui2 dialogs (GNA #23271)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1449]
**[Original submission](https://gna.org/bugs/index.php?23271)** by anonymous on 2015-02-13

It would be nice to have an invisible timer widget available in wesnoth.show_dialog which could be used like this:

```

local dialog = {

...

  T.timer {

    interval = 1000,

    id = "timer_1"

  },

...

}

local function on_timer()

end

local function preshow()

  wesnoth.set_dialog_value(timer, "timer_1")

end

wesnoth.show_dialog(dialog, preshow)

```

which would mean that the function 'on_timer' is called every 1000 miliseconds (every second) while the dialog is open.

(Reproduced on all)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by stevecotton** [comment]
I think we should reject this, because what it's asking for is an implementation detail, rather than a UI feature. Someone's got halfway through a problem, worked out a way to implement what they want, and asked for the low-level feature that would let them implement it that way.

Maybe they want an animation, or a countdown timer, or a way to cancel the dialog in multiplayer if the user is AFK. We should look at the best way to implement the end-goal, rather than the implementation detail.
