### ISSUE TITLE
unhighlighting combined enemy reach (GNA #23658)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1488]
**[Original submission](https://gna.org/bugs/index.php?23658)** by anonymissimus on 2015-06-23

Press ctrl-v to show the joined reaches of enemy units.

In 1.10, hovering the mouse over an own unit does not unhighlight this reach until the hovered unit is (left-)clicked.

In 1.12 it does immediately when starting to hover, so that it's not possible to view the stats of own units in the side panel while still displaying the enemy units reach.

Moreover, in 1.10 the reach can be unhighlighted by left-clicking an empty hex, this doesn't work in 1.12.

Moreover, right-clicking to open the right mouse button menu onto an empty hex, then left-clicking onto another empty hex to close the menu unexpectedly unhighlights the reach in 1.12, in 1.10 it doesn't.

These issues are present since the changes to the "commanding units on the main map" interface and their reversal, it was something about ordering moves with right click IIRC. There are several subtle bugs present since then I believe, making the interface less user friendly (kiss) than it was.

(Reproduced on Lubuntu trusty)
Release: 1.12.2+dev@669b9bb05e40fff0c25efc68ff965
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by CelticMinstrel** [comment]
Is this issue still present in 1.13.x?

**Comment by Wedge009** [comment]
These have carried to 1.14.7, but I'm not sure they're necessarily a problem - maybe a difficulty for people at the time to become accustomed to the then-new 1.12.

- Hovering the mouse cursor over own units does disable the enemy reach but it is still possible to see both enemy reach and own unit statistics in the side-bar simultaneously.
- Cancelling enemy reach is not possible with left-click but is with right-click (things must have been  different in 1.10 because I am used to this now).
- And since right-click closes the enemy reach highlighting, the left-click in the fourth point above is not possible.

It doesn't look like anything will change in this regard, and I'm not sure that it should. With that view, I'm inclined to close this.

**Comment by Wedge009** [comment]
Please re-open if it's deemed to be valid after all.
