### ISSUE TITLE
add advanced configuration option: "not try to overwrite saves" (GNA #23920)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1513]
**[Original submission](https://gna.org/bugs/index.php?23920)** by tekelili on 2015-10-03

Some scenarios and campaigns are prone to be replayed a lot, and some users can even limit their whole fW usage to just one add on. Such users often have several saved games with different mates if is a multiplayer add on.

For some of such users, BfW trying to overwrite save and replay files can be quite unconvenient (and question before do it quite irritating). An option in advanced configuration to make BfW automatically save such files with a different name (by ading something like and index to file name) could be very handly.

(Reproduced on any)
Release: 1.13
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-03**

**tekelili wrote:**

> Just to be clear, I am talking about autosaves.

**Comment by Wedge009** [comment]
I find this happens to me as well when testing. I suppose any preference check should happen here:
https://github.com/wesnoth/wesnoth/blob/2d16a3b4101b66e068c98411345e02401cab4e29/src/savegame.cpp#L399-L402

**Comment by jostephd** [comment]
Related: #4164 

@Wedge009 I think that piece of code is about manual saves? tekelili was talking about autosaves (which get silently overwritten) and replays (where you're prompted to overwrite or enter a different name manually).

**Comment by Wedge009** [comment]
I'm not sure that's why I'm asking.

...oh I see, I was indeed thinking of the #4164 case, rather than auto-saves which don't have the prompt.

Honestly if I was expecting to find myself in this sort of situation I wouldn't rely on auto-saves to keep my progress I'd make my own manual save files. Relying on auto-saves from different concurrent play-throughs is just going to be too confusing, especially since they're all labelled the same way (scenario name, turn number, etc).

**Comment by Wedge009** [comment]
So this request is really two parts:
1. Add option to not silently overwrite auto-saves but instead rename them.
2. Add (another?) option to silently rename replays upon saving.

For part one, I wonder if this can't simply be worked around by setting the maximum auto-saves number to infinite in the preferences. Otherwise I suppose one has to look at the `save_game_automatic()` instances in `playcampaign.cpp` and/or `play_controller.cpp`.

For part two, this is covered/duplicated by #4164.

**Comment by jostephd** [comment]
> For part one, I wonder if this can't simply be worked around by setting the maximum auto-saves number to infinite in the preferences.

That would just make it so if you play a scenario and it reaches turn 99999, the `Auto-Save1.gz` file won't be deleted. But if you start the scenario again, auto-saves from the new playthrough will still overwrite auto-saves from the old one, one turn at a time.

Honestly, I'm not sure I'd change this. It's perfectly standard for auto-saves to be overwritten by newer auto-saves. Auto-saves are just meant to be a way to easily return to a previous turn, if you want to try a different strategy, or had a power cut in the middle of playing, or something like that. They aren't meant to be a log of every game one has ever played (all the more so because auto-saves are created every turn, so they're wasteful on disk space). To have such a log, I would suggest that when one of the following happens:

1. Player exits the scenario to main menu or to OS
2. Player wins the scenario
3. Player loses the scenario

then (if a new, off-by-default preference is set) either prompt the player to save, or just create a non-auto-overwritable save without prompting. The save would need to be named uniquely up front. #4164 is basically a special case of this for the "wins" case only.

> Add (another?) option to silently rename replays upon saving.

Not sure what you mean here. If you mean saving the replay under a unique name up front, yes, that's what #4164 is about. If you mean renaming the previous playthrough's replay upon re-beating a scenario, I would object. Old files shouldn't be renamed automatically.

**Comment by Wedge009** [comment]
It sounds like we're in agreement that Part 1 is not a helpful thing to implement. (Close close? :D)

For Part 2, I meant a new unique name for the replay if there's an old replay already present - I think that's what the requester was asking for. 

Either way, I think #4164 covers what might be sensible to do from this one.

**Comment by jostephd** [comment]
Agreed.
