### ISSUE TITLE
[move_units_fake]: fake units disappear between steps (GNA #23995)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1516]
**[Original submission](https://gna.org/bugs/index.php?23995)** by elvish_hunter on 2015-10-28

Some months ago, it was reported [this bug](://forums.wesnoth.org/viewtopic.php?f#4&t42446) in the forums, which caused a segfault when trying to use [move_units_fake].

Following this report, I pushed a fix which got rid of the segfault, but instead showed another problem: after each step, the fake units don't stay on screen like they're supposed to do, but instead they disappear.

I investigated the issue, and found out that the culprit seems to be the line in action_wml.cpp:

+verbatim

units[un]->anim_comp().set_standing();

-verbatim

I noticed that the temporary object _anim_comp_ is destroyed before its _set_standing_ method is called, but I wasn't able to determine why that happens.

In order to supply a test case, I modified the first scenario of Two Brothers (which I'm attaching) by adding a [move_units_fake] in the start event.

(Reproduced on Any)
Release: 1.13.1
Priority: 5 - Normal
Severity: 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-28**

**elvish_hunter added attachment:** [01_Rooting_Out_a_Mage.cfg](http://gna.org/bugs/download.php?file_id=25512)

**Comment by Vultraz** [comment]
It seems to be something to do with the `unit_mover` class not keeping the temporary unit on-screen, but i can't find the cause.

**Comment by Vultraz** [comment]
Update, copied from discord:

`move_units_fake` creates `fake_unit_ptrs` for each unit moving. The underlying `unit_ptr` is then passed to `unit_mover`, which creates a new `fake_unit_ptr`. Both (should) be pointing to the same unit. The second FUP is destroyed in `unit_mover::update_shown_unit()`, which is called from the `unit_mover` dtor (which is destroyed since we're using `move_unit()`). The `fake_unit_ptr` dtor calls `remove_from_fake_unit_manager`. That removes the underlying unit from `resources::fake_units`, which is a `fake_unit_manager`.  Since the unit isn't in the manager anymore, it doesn't get drawn anymore between steps.

Calling `place_on_fake_unit_manager` again after using move_unit with an early exit in the latter in case it's already in a manager seems to fix the problem
