### ISSUE TITLE
LoW unbalanced in MP. (GNA #24685)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1555]
**[Original submission](https://gna.org/bugs/index.php?24685)** by gfgtdf on 2016-05-18

It is known that the LoW mp campaigns is not very balanced in mp.

One of the main problems was that each side got the full carryover gold, this was already fixed by devinding the carryover gold by the number of players, but still noone tried to realy playtest and balance the campaign in mp mode yet.

Besides this, there are also some other problems:

1) In some scenarios each player gets only very few starting gold (45 iirc) which is only enough to recall 2 unit or to recuit 3 units.

2) Leadership only work for your own units, not for allies which makes leadership qute useless, specially in a case like above where every side has only very few units.

(Reproduced on all)
Release: 1.13.4+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-05-18**

**gfgtdf wrote:**

> 3) It mixes the old (80%) and the new (40%) carryover system

**Comment by nemaara** [comment]
The solution is pretty simple: use the new carryover system, and raise the gold in MP to reasonable values. Yes, it makes LoW a bit harder in SP compared to MP, but playing through at least a couple scenarios, I do feel that it's necessary to raise MP gold, otherwise players really won't feel like they're commanding any reasonable number of units. This will also offset the lack of leadership, although I tend to find that leadership isn't quite as useful as mass healers in MP.

(Anyway, LoW doesn't need to be an extremely hard campaign, just needs to feel better wrt MP gold values since it'll be a bit lame if each player only gets 3 units).

**Comment by gfgtdf** [comment]
> The solution is pretty simple: use the new carryover system

You'd need to tested it then though iirc done it these scenarios are banking assuming you have a lot of gold left from the previous scenarios.

**Comment by nemaara** [comment]
> You'd need to tested it then though iirc done it these scenarios are banking assuming you have a lot of gold left from the previous scenarios.
That's actually a design flaw for this level of campaign, because minus for some more challenging or really in depth campaigns, it should be possible to use the minimum gold and still win the scenario (and also the carryover should not be very large). I'll test it, though.

**Comment by gfgtdf** [comment]
> That's actually a design flaw for this level of campaign, because minus for some more challenging or really in depth campaigns, it should be possible to use the minimum gold and still win the scenario 

Yes i know, im just telling you what fendin told me when i asked him why it uses te old carryover system.

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/compare/af05f6f0e802...f4e0b619cfc09174. Using the new carryover hurts you more right when you get that gold, so I've raised the player gold to compensate for that in S6-7. Over time, it ends up giving you a similar amount of gold since the gold is added to the next scenario's minimum. 

Closing this issue soon if there are no other comments.
