### ISSUE TITLE
tutorial: getting stuck sometimes, have to undo turn or reload (GNA #25111)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1584]
**[Original submission](https://gna.org/bugs/index.php?25111)** by matthiaskrgr on 2016-09-24

For example in the very beginning, when I move konrad into a village, I can't move him further next to Delfador.

The game does not let me end the turn, I have to undo the move action, newbies might find this confusing.

Even worse, when I am supposed to move Konrad into the keep to recruit units, but I attack the dummy instead, I CANNOT UNDO (due to attack action) but I also cannot end the turn and get stuck.

The only way to resolve is to reload the save/restart

(Reproduced on linux)
Release: git
Priority: 5 - Normal
Severity: 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-09-28**

**lvzheng wrote:**

> It's design of the game. When your unit occupy a village (which did not belong to you), it will lose all its moving points. Attacking also costs all moving points of a unit.
> 
> 
> 
> It's really not a bug. It's just how wesnoth is designed to be.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-09-28**

**matthiaskrgr wrote:**

> Yes, but usually you can end you turn whenever you want but the tutorial keeps you from doing so.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-09-28**

**lvzheng wrote:**

> I see. It think it is not a bug, as it does not affect gameplay. You should have post it as a Feature Request. Maybe this feature should be further discussed.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-09-28**

**matthiaskrgr wrote:**

> It's completely unrelated to regular (non-tutorial) gameplay.
> 
> 
> 
> It only affects the tutorial.
> 
> The problem is not that units can no longer move after attacking/capturing villages.
> 
> 
> 
> The problem is that the tutorial, and only the tutorial, requires the player to do exactly as planned. If a player plays around a bit or misclicks and accidentally moves the unit somewhere where the tutorial did not foresee it, which can totally happen since new player are new to the game, they will get into a situation where you no longer progress unless by doing (for new people) advanced things like undoing actions (in the best case) or completely reloading a turn (in the worst case).
> 
> 
> 
> People are NOT supposed to get frustrated in the tutorial already, they might just quit the game forever.
> 
> 
> 
> Did you actually try to reproduce this ingame?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-10-20**

**wedge009 wrote:**

> Sort of reported in bug #21940 as well.

**Comment by sevu** [comment]
I work on this

**Comment by CelticMinstrel** [comment]
#1012 is related, but does that fix this entirely or only partially address it?

**Comment by sevu** [comment]
only partially
will need a few more PRs

**Comment by sevu** [comment]
Current state of the tutorial's issues, and my thoughts on how to fix them.

**1a)** `If you don't know that you can undo a move you are screwed up if you do sth. wrong in the first turns`. E.g. if you just walk somewhere else than you are told to do. Probably a common thing.
_possible fix:_ let the player end the turn to regain movement points; count the turns which were wasted that way and delay the later turn x events by that (or nest all the events together);
_However_, there should be then some guidance to the player if he just walks around the map and doesn't know what to do - **this means string changes.**

the other things are relatively easy to resolve:
**1b)** player can `end turns by capturing villages` or with above change `capture them all and thus screw up the later part teaching villages`.
_possible fix:_ use a tutorial specific custom terrain, which replaces the village in the early rounds, acting as impassable overlay and village. This terrain should be hidden from the help, and if it is placed in a (pre)start event rather than in the map file, the real village terrain will probably be saved in the help.

**1c)** When Delfador summons the puppet, `it may happen that you have 0 MP left and the puppet is not adjacent to you`.
_possible fix:_ take this into account when placing the puppet, with some longer piece of code
_alternative1:_ Just place the puppet on the player and let the engine place it in an adjacent hex
_alternative2:_ 1a) would solve this too. The puppet may attack Delfador then, but they can be on the same team.

**2a)** In the 2nd part of the tutorials are no known bugs left, besides, ... in an seldom case the turn 7 event could fire while there are no troops in the river
_possible fix:_ add additionally a location filter to the event, or more precisely, the 2nd part of the event.

I'm pretty sure that there are no other bugs. I'm eventually getting back on this, but I won't make it in time with the next freeze.

**Comment by bandita137** [comment]
For the 1c issue I also faced: how about making Delfador step away two steps (two so unnecessary to check Konrad's position) and summon the puppet in Delfador's original place, that was surely next to Konrad?

**Comment by bandita137** [comment]
Hi, here's a version that fixes 1c and another display issue where the Keep's name overlaps the message,  hopefully not breaking anything meanwhile. Delfador starts in the quintain's position, then moves away to really face the quintain to be summoned, and at then at the end of the turn goes to the place it traditionally did.

Can somebody please check it? I never developed anything for Wesnoth so maybe it's not the way to do it. But it seemed so straightforward.

[01_Tutorial_part_1.zip](https://github.com/wesnoth/wesnoth/files/2108345/01_Tutorial_part_1.zip)

**Comment by CelticMinstrel** [comment]
If by "more than possible" you mean "more than his MP", you could always just give him the quick trait (or something similar) so he has enough MP.

**Comment by bandita137** [comment]
Actually it should not matter. His MP does not get reduced by the scripted movements, and just realized that a few turns later when he leaves the map he moves a lot more than his MPs again. So it happened in the earlier revision also. Yet added the quick trait as you suggested, and the 7 MP he gains this way makes his very first steps valid.

[01_Tutorial_part_1_v2.zip](https://github.com/wesnoth/wesnoth/files/2108696/01_Tutorial_part_1_v2.zip)

Why is it that his character can't look upwards by the way?

**Comment by CelticMinstrel** [comment]
Most units currently don't have a north-facing sprite. There's not really anything you can do about that unless you're able to draw a new sprite as good as the existing ones.

**Comment by sevu** [comment]
Reminder for me, the only unfixed thing left is 2b.

**Comment by stevecotton** [comment]
@sevu, I assume you mean 2a) the warning about orcs crossing the river?

I'm wondering about making it not turn-dependent, but instead trigger it when there's an orc that could move to either 18,13 or 19,14 next turn. A quick wolf rider could cross the entire river in a single turn, starting on the non-water hexes 17,18 or 18,18.
