### ISSUE TITLE
swamp/water transition - use the correct water for it (GNA #25389)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1616]
**[Original submission](https://gna.org/bugs/index.php?25389)** by shiki on 2016-12-14

Wesnoth has different types of water, it looks not all time the same.

In the transition between tropical water and swamp, it uses the wrong (standard) water for the transition.

Which looks then as seen on the picture.

(Reproduced on Archlinux)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-12-14**

**shiki added attachment:** [swampandwater.png](http://gna.org/bugs/download.php?file_id=29571)

**Comment by sevu** [comment]
Yes, that's me 👋 
It's S1 & S2 of Dead Water, in the bottom-right corner.

**Comment by Wedge009** [comment]
Thanks - yes, I can see this is still an issue for 1.14 and master, and is worth recording.

**Comment by ln-zookeeper** [comment]
For what it's worth, I don't see what's wrong in the screenshot. I don't see standard water being used in the swamp<->water transitions.

**Comment by Wedge009** [comment]
I think the issue is the choice of the general water here - tropical? - is quite a light blue and the murky dark water of the swamp clashes quite a bit with it. I don't know the details of Wesnoth terrain but maybe it's worth making the 'river' near the undead keep a darker kind of water to ease the transition. I suppose it doesn't make sense for swamp vegetation to overlay pristine tropical water.

**Comment by jostephd** [comment]
I'm not sure if it's related, but in the transition between swamp and void, the streams of water running down the cliff-face are the blue, which is appropriate for normal water but not for swamps:

![2019-10-14-043800_329x260_scrot](https://user-images.githubusercontent.com/24784687/66729684-80ed6200-ee3c-11e9-9bc5-9ceb54f1b1b2.png)

I'm not sure if that's part of this bug or just that we don't have a version of those graphics with murkier water.

That transition can be seen at the east and west edges of Auction X.

**Comment by Wedge009** [comment]
Maybe I need to clear my cache, but I just tested 1.16 branch at b34b8a9 and don't see any apparent change in the transition.

**Comment by doofus-01** [comment]
Lower your expectations, it was only supposed to get rid of the bright blue in the waterfall.  We could change it further in the future, but that was the only part that looked "broken".

The transition of swamp to blue water seemed fine to zookeeper and still seems fine to me, so nothing to do there.

**Comment by Wedge009** [comment]
I didn't really have expectations, I was just checking @sevu's original report on the water/swamp transition and I thought that was what was being closed by your commit at b34b8a9dcd. If that was deemed a non-issue, this report should have been closed separately.

But looking specifically at the Auction-X example that @jostephd mentioned, I don't see any change there either. The south-west facing waterfalls on the opposite side look darker but then it's already that way in 1.14.17. The south-east facing waterfalls still look bright blue to me.

Not sure if I'm doing something wrong - maybe someone else can check?

**Comment by doofus-01** [comment]
I don't know about Auction-X, I was just looking at swamp to chasm transition, which is what I thought his point was.  If Auction-X does something strange and that's relevant to mainline/core, then I guess this can be reopened.

**Comment by Wedge009** [comment]
I thought Auction-X is the image that jostephd used... but I don't see the same mix of swamp, water, and chasm that's in the image above. Nonetheless I can see the difference at the south end now - water to chasm remains the same, but swamp to chasm now lacks the waterfall (or it's at least muted now), which I think is the change you made.

1.14.17:
![1 14 17](https://user-images.githubusercontent.com/13679322/132947290-54e030fb-45bf-4446-9d54-6dc0c5b82e98.png)

1.15.17+dev
![1 15 17](https://user-images.githubusercontent.com/13679322/132947300-66060576-16a2-4d7f-a883-9e95d28b9496.png)

(Is it an intentional lighting direction decision to have south-east facing waterfalls brighter than south-west facing ones?)

**Comment by doofus-01** [comment]
Right, I just muted the bright blue.  The brightness was probably intentional.  They could probably use some image variations to break that up a bit.
