### ISSUE TITLE
manpages: microai test scenarios (GNA #25559)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1630]
**[Original submission](https://gna.org/bugs/index.php?25559)** by shiki on 2017-03-04

There exists the command line option -tmicro_ai_test

to launch the micro AI test scenarios. This should be listed in the manpage.

(Reproduced on Linux)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by CelticMinstrel** [comment]
This is part of the `-t` option, which takes an optional argument. I suppose the manpage could give a few examples of common test scenarios though...

There's also now a way to launch a test scenario from the titlescreen, so I'm not sure how important this is.

@sevu

**Comment by sevu** [comment]
How can you launch them from the titlescreen?
And are there more than test and micro_ai_test?

**Comment by mattsc** [comment]
>  And are there more than test and micro_ai_test?

The micro_ai_test scenario is really a collection of quite a few (see [here](https://github.com/wesnoth/wesnoth/tree/master/data/ai/micro_ais/scenarios)).  All of these can be launched directly from the commandline, but since they are all accessible from micro_ai_test, there's no need for that.

There are a few more in various places throughout the data/ directory, but those are really meant as development test frameworks to test new functionality.  They cannot really be played.

**Comment by CelticMinstrel** [comment]
> How can you launch them from the titlescreen?

In Preferences there's a "Start Test Scenario" hotkey which can be assigned a key of your choice. Once assigned, press that key at the titlescreen and you will be presented with a list of available test scenarios. Unit test scenarios are excluded from the list.

**Comment by sevu** [comment]
closed by 9b7db05
