### ISSUE TITLE
path of the executable - listing it as well in the paths list (GNA #25642)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1654]
**[Original submission](https://gna.org/bugs/index.php?25642)** by shiki on 2017-04-10

I think the path to the executable should be listed as well in the list of locations which is available at the [i] on the titlescreen. Many Linux distributions use different locations for it.

Maybe we could only show this if it differs from the game data directory, since it's for windows not of interest.

(Reproduced on Linux)
Release: 1.13.7+dev
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Wedge009** [comment]
Relevant sections:
https://github.com/wesnoth/wesnoth/blob/a8c96ba1f45f0659de0db8dd2bb4c184f0ccbd84/data/gui/window/game_version.cfg#L126-L136

https://github.com/wesnoth/wesnoth/blob/a8c96ba1f45f0659de0db8dd2bb4c184f0ccbd84/src/gui/dialogs/game_version_dialog.cpp#L100-L105

Most of these are dependent on the `filesystem` class and it doesn't look like there's a cross-platform method for obtaining the application binary location yet.

**Comment by jostephd** [comment]
> Most of these are dependent on the `filesystem` class and it doesn't look like there's a cross-platform method for obtaining the application binary location yet.

I think argv[0] in main is accurate enough for our purposes here. (It can lie, but since we aren't actually trying to execute it as a program name, it doesn't matter.)

**Comment by GregoryLundberg** [comment]
If you're going to show argv[0] you'll also want to show the current working directory and the PATH environment variable. And even then you might not find the executable.

Personally, I'd just close this issue as Wont Fix because it's too hard to accurately determine the executable's complete pathname, not to mention doing it portably. on the principle that saying nothing is better that saying the wrong thing.

**Comment by jostephd** [comment]
@GregoryLundberg I agree with the principle, but I don't _necessarily_ agree we should close this as won't fix. Can we first consider showing the executable name only if we're reasonably sure it's accurate, and not otherwise? Would /proc/self/exe be acceptable, if it exists? Or argv[0], but only when it's an absolute path? They can lie too, of course, so maybe they're not good enough.

CC @sevu

**Comment by soliton-** [comment]
What’s the use case for showing the binary path?

If it‘s just a nice-to-have then I agree with won‘t fix since this is not trivial to implement and not guaranteed to be correct in any case.

This is for example how qt does it in `QCoreApplication::applicationFilePath()` (there’s still more platform dependent code behind `qAppFileName()`):
https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qcoreapplication.cpp#n2312

**Comment by GregoryLundberg** [comment]
From the man page.

> The execv(), execvp(), and execvpe() functions provide an array of pointers to null-terminated strings that represent the argument list available to the new program. The first argument, by convention, should point to the filename associated with the file being executed. The array of pointers must be terminated by a NULL pointer.

Note: "by convention", therein lies the problem

**Comment by jostephd** [comment]
I'm well aware that argv[0] can be set to any value, in fact, I already acknowledged that in a previous comment. Let's wait for @sevu to answer @soliton-'s question.

**Comment by Wedge009** [comment]
I'm aware of the difficulties of having a reliable, cross-platform method to find the application path (just noticed https://stackoverflow.com/questions/7941536/windows-vs-linux-gcc-argv0-value, for example), which is why I was hoping `filesystem` to have already done the hard work. It seems to be a common task to work through so if there's a sensible way that another project has done this maybe we can base it on that.

Although, I also wonder how this information might be useful. Indeed, would be interesting to see what sevu had in mind.

**Comment by sevu** [comment]
The reason I opened this issue is that the binary location is configurable, and all other configurable paths are listed there.
For whom does it matter? I once wasn't sure which binary I currently run, my own or the distributors one, and intended to look it up there. Aside probably nobody runs into that issue.
I'm fine with closing this as won't fix, it's not an important matter.
