### ISSUE TITLE
Cleanup of transferred GNA issues

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#1676]
We need to go through the GNA issues and modify some of them. In particular:

* [x] The OS labels should be removed unless it is clear that the bug only affects that OS
* [ ] The milestones attached to many issues are wrong; these can be fixed as they're closed, probably?
* [ ] Fixed issues should be assigned a milestone and closed
* [ ] There are some issues with formatting and such that can be fixed as we come across them
* [ ] Some issues are rather old and obsolete; they probably should have been closed long ago.
* [ ] Other stuff?

**Comment by gfgtdf** [comment]
did you see my comment in irc? a lt of issues were given wrong mlilestones, it seems like the tool converted the release field (which specifies when thre bug was observerd) to the milestones which specified when it shoudl be fixed which is somethign completeley diferent.

**Comment by CelticMinstrel** [comment]
Yeah, we can probably fix that as we close them. That's also the problem with the OS field - on GNA it indicated the platform it was observed on, not that it was specific to that platform. I ported the OS anyway because it stands to reason that some of the bugs observed on a given platform would be specific to that platform, and it's easier to remove labels than add them (because this way you only need to look through the ones that have the label, rather than everything).

**Comment by gfgtdf** [comment]
hmm ye but unlike the os files in this case the gna release field _never_ matches the milestone it should be fixed in, exactly becasue the gna release filed means exqactly it was observed ot be borken in that version.

> Yeah, we can probably fix that as we close them

since we mostlikely aren't going to close them soon unless oneone accidently suddenly fixes them, this doesn't sound lieka  good plan

**Comment by CelticMinstrel** [comment]
You could also just go through the open bugs attached to each closed milestone and reassign them; or even just batch remove them from the milestone if that seems appropriate.

**Comment by gfgtdf** [comment]
> You could also just go through the open bugs attached to each closed milestone and reassign them; or even just batch remove them from the milestone if that seems appropriate.


did that

**Comment by Wedge009** [comment]
I can help with this, just give me a few days.

* Aye, I generally change reports to 'All' for OS unless it's actually specific to one OS. I also only have Windows and Linux, which means I tend to ignore bugs marked as OSX-specific.
* Should I mark 'fixed' reports with 1.13.8 or 1.14.0?
* More than happy to close old ones, especially if I've asked for input and haven't received any.

**Comment by Vultraz** [comment]
Fixed should be marked 1.13.8.

**Comment by Vultraz** [comment]
Just closed everything marked fixed and 1.13.8.

**Comment by CelticMinstrel** [comment]
I've finally finished transferring all the attachments from GNA to GitHub.

**Comment by Wedge009** [comment]
Thanks for that, really helpful. I don't plan on doing anything more in GNA - should I need to pay attention to anything there?

What's policy with reports marked Fixed now? Are we no longer leaving them open till the release has been made?

**Comment by CelticMinstrel** [comment]
See #1013 for details on that. It hasn't been finalized yet, but I did delete the "fixed" label now that all the fixed bugs are closed.

There should be no need to pay attention to GNA anymore since Zookeeper locked it from further updates.

**Comment by Wedge009** [comment]
Yep, I just noticed the Fixed label disappeared.

**Comment by Vultraz** [comment]
@Wedge009 quick note if hadn't noticed, when you do mass bug changes, GH has those checkboxes so you can select and perform an action on multiple ones, unlike GNA. Much convenient.

**Comment by Wedge009** [comment]
Sounds good, thanks. Haven't had to do any bulk changes yet, but would be useful.

**Comment by Wedge009** [comment]
I'm finding a few of the issues are missing entire conversations from the original GNA bug reports. So far I've found this on issues with no further comments than the initial post. I don't know if there are issues with conversations only partially copied from GNA.

**Comment by CelticMinstrel** [comment]
Have you found more issues like that than the one I just saw that you commented on? We should try to fix the missing comments; I can probably automate it by tweaking my script.

**Comment by Wedge009** [comment]
So far just #1289 and #1291. I'll try to note this as I go along.

**Comment by CelticMinstrel** [comment]
I also forgot which one I commented on earlier where you had reposted two of your own comments...

**Comment by Wedge009** [comment]
It was #1314 - just for posterity since you had already merged my PR which mitigated it.

**Comment by sigurdfdragon** [comment]
I've started going through the old GNA issues. Here is a first list of ones I recommend closed, followed by a reason:

https://github.com/wesnoth/wesnoth/issues/1035 - Too complex, this is just how the AI works
https://github.com/wesnoth/wesnoth/issues/1036 - Superfluous
https://github.com/wesnoth/wesnoth/issues/1038 - Too much has changed since then
https://github.com/wesnoth/wesnoth/issues/1039 - First half implemented, second half pointless/too much has changed since then
https://github.com/wesnoth/wesnoth/issues/1040 - It's the wml author's responsibility to make sure objects are displayed to the user
https://github.com/wesnoth/wesnoth/issues/1042 - Too much has changed since then
https://github.com/wesnoth/wesnoth/issues/1043 - Don't see how to do reasonably, you need more than just a gold amount to make a determination if you need to replay a scenario, & what about MP campaigns?
https://github.com/wesnoth/wesnoth/issues/1044 - Implemented by UMC add-on Custom Campaign v2.0.0

**Comment by gfgtdf** [comment]
i disagree most of these most of them still make sense and should not be closed.

**Comment by CelticMinstrel** [comment]
Okay, I closed #1039, but I don't really agree with closing most of these. I'm not sure about #1044 or #1042 though.

**Comment by sigurdfdragon** [comment]
Ok, I need to rethink how I can contribute to this.
I’ll endeavor to have a better understanding of what classifies as ‘old and obsolete’ before I suggest any more to close.

For cleanup of transferred GNA issues, I think it may be useful to include a long term approach that considers the following:
1. A vision/roadmap for what the game should look like/be (so it’s easier to determine what is a valid enhancement/feature request and what is not.)

2. A ratio of development / bug fixing (aka “feature freeze”) that has more dedicated bug fixing.
For 1.12 & 1.14 the ratio is something like approximately 2+ years / 2-4-months
To have a better ratio, here are two possibilities:
a. Having shorter development cycles while maintaining the same length feature freeze (ie 9 months development/ 3 months dedicated bug fixing)
b. Declare a feature freeze mid development cycle every so often in order to clear some of the bugs.

**Comment by sigurdfdragon** [comment]
> #1044 i don't know custom campaign exactly but the request seem to be to allow arbitary scenarios while campaign sounds liek it's only allow a given set of maps. (i' still don't think that #1044 makes sense in it's current form, it'll just make it much easier for the play who won the first match to also win the secodn macth which doesn't sound like much fun)

The name might not be ideal for what it does, but Custom Campaign can handle abiratary mp scenarios and # of players

**Comment by Wedge009** [comment]
I noticed that people aren't going to be notified of updates on issues they previously reported on GNA. Well, I suppose it encourages people to be more active - not sure what we can do to work around this short of adding people on each issue (assuming they even have a GH account).

**Comment by CelticMinstrel** [comment]
Yeah, unfortunately there's probably not much we can do about that... unless we can somehow set up something to subscribe arbitrary emails to an issue (through webhooks or something).

**Comment by Wedge009** [comment]
#1177 - I don't think this happens in the new lobby but @gfgtdf seems to think it might not be fixed.
#1426 - @gfgtdf marked this as non-fixed, I can only guess is because it's still an issue for 1.12, but I thought if they're resolved in master then that makes it a candidate for closure.
#1523 - @gfgtdf reported this a while ago, but not much detail to go on.
#1550 - Haven't had any updates on this one and I didn't find the issue on my own builds. #1434 is another audio bug report which seems to suggest some Windows set-ups have issues with libvorbis.

And while looking at audio labels, I saw this one:
#1182 - Sounds nice, but not really related to the game.

**Comment by CelticMinstrel** [comment]
For #1182, it's not really important, but it would be trivial to simply commit the m3u that the poster attached, if people want it. I don't really have an opinion either way,

**Comment by CelticMinstrel** [comment]
Just as a note... I think I noticed some people saying they would focus on bugs rather than enhancements, but I think both need cleaning up.

**Comment by gfgtdf** [comment]
> #1177 - I don't think this happens in the new lobby but @gfgtdf seems to think it might not be fixed.

can be marked s fixed, we have https://github.com/wesnoth/wesnoth/commit/19358294be01c2718d71abbde3b89eab3aba99ad and https://github.com/wesnoth/wesnoth/commit/667064a8af6d6d65d7af981edc2a7fbe4cc8ba16

> #1426 - @gfgtdf marked this as non-fixed, I can only guess is because it's still an issue for 1.12, but I thought if they're resolved in master then that makes it a candidate for closure.

yes i's because of 1.12. it is makred as 'backport' though which means it's fixed in master, the current plan is to mark surch bugs as backport and close them when 1.14 is released.

#1523 - @gfgtdf reported this a while ago, but not much detail to go on.

Ye i didn't nanage to reprpduce since then, it's 1.12 so it could be fixed.

**Comment by gfgtdf** [comment]
actaully i think #1042 can be marked as fixed, from the discussion is seemed liek it was mostly about the mp case wehich we adressed already as i said eariler.

**Comment by Wedge009** [comment]
We seem to be pretty stable with using GH issues now. Is there any more work to be done here?

**Comment by CelticMinstrel** [comment]
That's a good question. Should we close this?

**Comment by CelticMinstrel** [comment]
There have been no objections for a whole year, so I'm closing it.

**Comment by Wedge009** [comment]
I have trouble keeping up with all the new issues! But yes, good idea to close this. Thanks.
