### ISSUE TITLE
msgfmt does not like  $percent|%

### ISSUE THREAD

**Issue by gunchleoc** [wesnoth/wesnoth#1741]
I have difficulty translating this string:

    $percent|% accuracy

as

    Pongalachd dhe $percent|%

msgfmt doesn't like it that $percent|% is at the end of the string.

![msgfmt](https://cloud.githubusercontent.com/assets/4095570/26542790/2c273330-4453-11e7-9871-78614ab66e6c.PNG)

**Comment by gfgtdf** [comment]
you could try to to replace the trailing `%´ with `%%`

**Comment by gunchleoc** [comment]
No, that doesn't help. I also tried `$percent%%`, no joy.

And the tool is using the standard gettext `msgfmt` command itself to generate the error message, so fat chance of changing that.

**Comment by CelticMinstrel** [comment]
Looks like one way to fix this would be to not pass `-c` to `msgfmt` (but instead pass `--check-domain --check-header`).

**Comment by ivanovic** [comment]
At least the cmake recipe already does use --check-domain and --check-header. I guess the problem here is how it was created. I have no idea where the c-format actually originates from. I just ran a pot-update and suddenly this c-format is no longer there. Maybe someone did something wrong during the last pot-update?

**Comment by loonycyborg** [comment]
You didn't specify file and line where this issue occurred. I see this string in po/wesnoth.pot and in the source file where it comes from in 1.13.8 but not in master. So this issue seems fixed.
