### ISSUE TITLE
mp create looks bad at some resolutions

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1780]
Observed on 1.13.8 release

wesnoth on a 838x978 resulution, (which i usually use for debugging) looks like this:

![grafik](https://user-images.githubusercontent.com/4893136/27052540-41eccd48-4fba-11e7-8130-42999df74366.png)

as you can see the scroll label on the left side doesn't wrap at all.

**Comment by CelticMinstrel** [comment]
I think this is more likely caused by something on the right half rather than something on the left - basically, something on the right requests more space than there is, causing the window to need a scrollbar, which then causes the scroll label to believe it has an infinite amount of space available, which causes it to not wrap and make the scroll bar even worse.

**Comment by gfgtdf** [comment]
one of the probelm is that this code https://github.com/wesnoth/wesnoth/blob/1.13.8/src/gui/widgets/settings.cpp#L650 doesn't seem to choose the 'small' window resulution. It onyl chooses the 'small resolution' if the with _and_ the height are smaller than the screens.

Also i just tested that even the 'small' mp lobby resolution (800x600) needs a scrollbar.

**Comment by gfgtdf** [comment]
> one of the probelm is that this code https://github.com/wesnoth/wesnoth/blob/1.13.8/src/gui/widgets/settings.cpp#L650 doesn't seem to choose the 'small' window resulution. It onyl chooses the 'small resolution' if the with and the height are smaller than the screens.

Made pr #1790 to pfix this

**Comment by gfgtdf** [comment]
that pr was merged
