### ISSUE TITLE
regression: wmlxgettext needs better error message

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1785]
I'm having an problem with a specific sign in line 103 of some file - 1.12 (perl) wmlxgettext gives me this error message:

```
utf8 "\x92" does not map to Unicode at /home/space/git/wesnoth/utils/wmlxgettext line 168, <FILE> line 103.
Malformed UTF-8 character: \x92 (unexpected continuation byte 0x92, with no preceding start byte) in pattern match (m//) at /home/space/git/wesnoth/utils/wmlxgettext line 90, <FILE> line 103.
```
Note the 103 mentioned - though no idea in which file.

This is what 1.13 (python) wmlxgettext gives me:

```
Traceback (most recent call last):
  File "/home/space/git/wesnoth/utils/wmlxgettext", line 259, in <module>
    main()
  File "/home/space/git/wesnoth/utils/wmlxgettext", line 215, in main
    fileno=fileno, startstate='wml_idle', waitwml=True)
  File "/home/space/git/wesnoth/utils/pywmlx/state/machine.py", line 338, in run
    for xline in filebuf:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 4043: invalid start byte

```
This error message doesn't give me any useful information - no idea how this would help me is, not useful for finding the culprit.
With the 1.12 error message I was clueless too, but it told at least what this 0x92 is and - what I didn't understand at that time - it told me the line.

said line 103 looks in my editor like this:
text= _ "You dont have enough gold to activate the rune aura!"
github displays the code it like that:
text= _ "You don’t have enough gold to activate the rune aura!"

**Comment by sevu** [comment]
Looking further into this tool, it's absolutely great, better than the old one.

**Comment by CelticMinstrel** [comment]
I guess we need to catch the exception and somehow print a better error message.

**Comment by AncientLich** [comment]
Thank for the bug report (and thank to Elvish Hunter to notify me this discussion). I will try to add an exception to allow a better error message report. 
@sevu: Currently this issue is not managed, this is why you see a message like that (a standard python traceback error). I will re-translate it to a standard wmlxgettext error as soon as possible.

**Comment by AncientLich** [comment]
I added a PR wich should fix the issue.
I tested with an old WML file I did in past wich contained an UTF-8 error too and wmlxgettext on a first test seems to fix the problem.
Try to make other test, if you can, and let me know if you discover some other issues or if you find some corner cases wich are not managed by the fix itself.

**Comment by sevu** [comment]
looks good.

There's is indeed another issue which I have, happens with the perl version from the 1.12 branch.
1) When I create a .pot file for the current Ageless Era, it contains some strings twice.
`msgattrib foo.pot` tells me which strings it are, and the comments in the pot file let me know where they come from, but I find nothing unusual in this files. Didn't happen with the former Ageless Era version. The command I use for creating the pot files looks like this.
`find eras images/ sounds/ data/ factions/ text/ units/ \( -name \*.cfg -o -name \*.lua \) -print0 | xargs -0 wmlxgettext --directory=. --domain=wesnoth-Ageless_Era > AE.pot`

When loading the file in poedit it offered me to 'fix' it (erasing duplicates), which solved the problem.
Not sure how to troubleshoot this down. Since this is about the perl script, I think I best look into this later again with the new one.

2) However, I found by the way another problem (with the 1.13 script), when I search in the whole era folder [ I didn't formerly because the old script has a problem with some complicated animation macros]
`find  \( -name \*.cfg -o -name \*.lua \) -print0 | xargs -0 wmlxgettext --directory=. --domain=wesnoth-Ageless_Era > AE.pot`

```
Traceback (most recent call last):
  File "/home/space/git/wesnoth/utils/wmlxgettext", line 259, in <module>
    main()
  File "/home/space/git/wesnoth/utils/wmlxgettext", line 249, in main
    posentence.write(outfile, args.fuzzy)
  File "/home/space/git/wesnoth/utils/pywmlx/postring.py", line 70, in write
    print('msgid', self.sentence, file=filebuf)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/space/git/wesnoth/utils/wmlxgettext", line 259, in <module>
    main()
  File "/home/space/git/wesnoth/utils/wmlxgettext", line 249, in main
    posentence.write(outfile, args.fuzzy)
  File "/home/space/git/wesnoth/utils/pywmlx/postring.py", line 70, in write
    print('msgid', self.sentence, file=filebuf)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 19: ordinal not in range(128)
```
`wmlxgettext text/special_notes.cfg --directory=. --domain=wesnoth-Ageless_Era > AE.pot`
gives only the latter error, it seems to be the file which triggers the 2nd error. Though I don't see anything suspicious in it.

`find data/ text/  \( -name \*.cfg -o -name \*.lua \) -print0 | xargs -0 wmlxgettext --directory=. --domain=wesnoth-Ageless_Era > AE.pot`
gives only the upper error. swapping the order of text/ and data/ in the command would give only the latter one.

data/EoMa_data/summon.cfg would be another file causing such a problem (third trace).

3) last but not least, if I misstype the command and forget a space
```
wmlxgettext _main.cfg --directory=. --domain=wesnoth-Ageless_Era
wmlxgettext _main.cfg--directory=. --domain=wesnoth-Ageless_Era
```
Maybe adding an error message here, like when no filename is given

**Comment by AncientLich** [comment]
1) I cannot reply to you first report. I don't know perl. I am the developer/maintainer only of the python3 version of wmlxgettext (the new one)

2) 
> find data/ text/ \( -name \*.cfg -o -name \*.lua \) -print0 | xargs -0 wmlxgettext --directory=. --domain=wesnoth-Ageless_Era > AE.pot

No no no... this is not the way of invoking my version of wmlxgettext (the 1.3 one). You are using stdin and stdout wich is something you should NEVER NEVER do, becouse using stdin / stout will can create issues on text encoding, wich will be controlled by the terminal itself instead of letting the script to control it.
In my script I have a proper way to scan recursively a directory. Moreover it is HIGLY recomended to use the new -o parameter (for file output name) instead of stoud redirection (that you used in past with the perl version of wmlxgettext). The reason is the one I already explained.

So try this command, instead, ad verify if the issue still happens (but shouldn't)
> wmlxgettext -o AE.pot --domain=wesnoth-Ageless_Era --directory=Ageless --recursive

This way wmlxgettext will scan the directory for you (you can use also directory=. if you find confortable). The order of the parameters does not matter.

3) Sorry but I don't understand the point 3. Can you explain it?

**Comment by Arcanister** [comment]
Just to point out:

1. Command uses xargs -0, which means that input is passed to wmlgettext as command line arguments. So actual command line it receives will be something like:
```bash
wmlxgettext --directory=. --domain=wesnoth-Ageless_Era data/some_file.cfg
```
Outputs from all invocations of the command will be concatenated and put into AE.pot

2. You said
> becouse using stdin / stout will can create issues on text encoding, wich will be controlled by the terminal itself
And [this page](https://wmlxgettext-unoff.readthedocs.io/en/latest/enduser/usage.html#wmlxgettext-with-explicit-list-of-files-and-output-redirection):
> since output redirection can create issues. When writing to stoud, infact, the console will use its own text codify instead of the UTF-8 codify you could expect.

Not really. If you use output redirection operator like `> file.pot` in Linux console, the output of the script will be written there exactly as program spit it out. If it was UTF-8, it will be written as UTF-8.

Garbled output could only happen in Windows CMD.exe.

> For this reason, starting from version 2017.06.25.py3 the -o parameter is becomed mandatory

I suggest to revert this, at least for non-windows platforms.

**Comment by CelticMinstrel** [comment]
@Arcanister - If I recall correctly, we already ended up talking him down from making `-o` mandatory on IRC.

**Comment by AncientLich** [comment]
[quote]Problem in Python stdout could be caused by python itself too. In order to mitigate the problem, sys.stdout.encoding should be set to UTF-8 prior to output. Then > file.pot redirection should be alright even on Windows[/quote]
Probably you are right, but in my personal experience, when you use input and output text redirection, usually the text encoding used is the text encoding used by the OS console (so... in Linux it is ascii, on Windows is ISO-something-I-don't-remember-now). 
However the -o parameter will remain mandatory.
You can still use output redirection, at your own risk, if you use this syntax
[code]
./wmlxgettext ... -o - > file.po
[/code]
The main reason why the -o parameter is now mandatory, it is becouse, on standard usage, it should be used instead of redirection, becouse it is safest (you can be sure 100% that script works as expected and as it was programmed).
However output redirection is still possible, as far as you can see.... but this way the user will use redirection only if he actually wants to do the redirection, and not only becouse it was used to do so in past.
