### ISSUE TITLE
Game crashes when specific units try to level up

### ISSUE THREAD

**Issue by Battlecruiser** [wesnoth/wesnoth#1820]
Linux Mint 18.1, wesnoth built from sources (6aada96)

with addons: https://github.com/Battlecruiser/wesnoth-bug-addons
with save: [LotI2-Tundra-Automatické_uložení27.gz](https://github.com/wesnoth/wesnoth/files/1099575/LotI2-Tundra-Automaticke_ulozeni27.gz)
Try to level up Elvish Assassin at 47,37 The game crashes on SIGSEGV afterwards

backtrace: https://gist.github.com/Battlecruiser/cf6ad89c0cbb965a455a8f93678c6615

**Comment by Wedge009** [comment]
I couldn't get the save game to work - maybe because I don't have those add-ons - but it says it's from 1.13.7+dev.

At any rate, I recall @jyrkive mentioning in #1792 something about units getting close to gaining levels and fixing a crash related to that. Do you still get this issue on a more recent build?

**Comment by jyrkive** [comment]
#1792 was a crash in attack prediction code. This one is UI, and unrelated to that crash.

**Comment by Wedge009** [comment]
Thanks for the confirmation.

**Comment by Battlecruiser** [comment]
All used addons are attached, just clone that repo.

**Comment by gfgtdf** [comment]
please test https://github.com/wesnoth/wesnoth/commit/b68a23c4802e13121836df88ea353db7d01ad3bb

**Comment by Battlecruiser** [comment]
Ok it's fixed. It looks like the problem was triggered by an advancement without a description.
