### ISSUE TITLE
remove whitepaces from unittype ids

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1847]
Currently most mainline units is use whitespaces instead of underscores, the reason is that back in some anicent wesnoth version there was no name= key and the id= key was used for displaying (or maybe there was no id= key and the name= key was used to identify a unittype).

This comes with some problems, in particular when you want to use unit ids as wml variable names. Even if wml documents itself would support whitepaces in it, the $<varname> syntax doesn't. I have seen multiple addons that tried to do stuff like this.

The obviously problem why we cannot simply change all unit type ids is backwards compability. This can partly be fixed by making ids handled by the engine (in [unit] etc) cases insensitive. But that fix is not complete for exmaple if wml code manually compared the unittpye of a given unit with wml code, that code would then be broken.

Are there any opinion on this, in particular:
1) Does anyone have a better idea on how to preserve compabily after chaning unit ids?
2) How had would it be if people would have to update their code that does a manual check for unittypes?

**Comment by ln-zookeeper** [comment]
I really don't think we should change all unit type id's just because there are people who mistakenly try to use them as part of variable names. If trying to set a variable that has spaces in its name doesn't currently produce a warning, then couldn't it be made to do so? Doesn't seem like something that would have any drawbacks. If it does produce a warning, then I don't really see a problem.

Now, I agree it can be unwieldy to be unable to easily use unit type id's as part of variable names (in a safe manner), so it sounds like a good idea to add something to help with that, for example an easy way to have [set_variable] replace all occurrences of a given character in a string. That ought to have other uses, too.

**Comment by doofus-01** [comment]
I agree with ln-zookeeper.  If you do go ahead with making white-spaces no longer supported, could you save it for BfW 1.15?

**Comment by CelticMinstrel** [comment]
Agreed, regardless of whether this is a good idea, it should probably not be done for 1.14.

**Comment by gfgtdf** [comment]
> Now, I agree it can be unwieldy to be unable to easily use unit type id's as part of variable names (in a safe manner), so it sounds like a good idea to add something to help with that

If you remove all information about whether a character was whitespace or underscore in the variablename it might make it harder to do th reverse thing, that is deducing the unittype from the variablename.

**Comment by doofus-01** [comment]
Well, you don't need to use just whitespace and underscore, right?  Can't you use some special character like "&"?  I don't know the underlying code, so maybe that doesn't work directly, but the general idea of a third character or string should work, as long as it is documented.

**Comment by CelticMinstrel** [comment]
Valid characters in WML key and tag names are letters, digits, and underscores. WML variable names are effectively key or tag names.

It's still possible to deduce the unit type in most cases even if you remove information about whether it's a space or an underscore - just try all the possibilities. Generally you won't have two units whose type ID differs only by transposition of spaces and underscores.

**Comment by gfgtdf** [comment]
> Well, you don't need to use just whitespace and underscore, right? Can't you use some special character like "&"? I don't know the underlying code

It won't work liek this but you can use _ as an escape character cahrater and  for example trasnlate ` ` to `_a` and `_` to `_b`

> It's still possible to deduce the unit type in most cases even if you remove information about whether it's a space or an underscore - just try all the possibilities

Yes that why i said make is much harder and not make it impossible, still i think checking ever osibility woudl be a ridicilous thing to do, in particula  since the numer of posibilities goes with 2^(number of spaces)

**Comment by CelticMinstrel** [comment]
Sure, but the most likely possibilities are "all spaces" and "all underscores", so in most cases you won't have to try every possibility. Furthermore, 2^n isn't that bad when n is small, which it generally would be.

**Comment by gfgtdf** [comment]
> Sure, but the most likely possibilities are "all spaces" and "all underscores", so in most cases you won't have to try every possibility

This woould probably make the code to implement those tries even more complicated...

> Furthermore, 2^n isn't that bad when n is small, which it generally would be.

Well for example example `AE_bem_wood_warriors_Golem_Wood_Defender` is a unit with 6 underscores in it which already is 64 tries.



Ok since there seem to be quite some resistence against my proposal for 1.14 to just to just make all core functions that take unit type ids whitespace/underscore insensitive. This will not break any current wml conent.

**Comment by CelticMinstrel** [comment]
> This woould probably make the code to implement those tries even more complicated...

In an ordered list of permutations, "all spaces" and "all underscores" are the first and last permutation, so I don't think it would be any more complicated.

I don't quite get your alternate proposal for 1.14.

**Comment by sapientN3T** [comment]
Here is the proposal as it currently stands, if I understand correctly:

1. Leave all existing unit type IDs as they are now, to prevent breakage of string equality checks in existing WML content
2. Make it easier to replace spaces with underscores via [set_variable]
3. Make all core functions that take unit type ids whitespace/underscore insensitive, so there is no need to reverse the transformed id

While I don't have a problem with this proposal, I would like to point out that it is kinda unnecessary.
1. N/A
2. This can already be done via [set_variables] [split] separator=" " followed by [set_variable] [join] separator="_". As a side note, I thought there was a simple way to do it via WFL, but I  just checked and apparently replace() doesn't do what I thought. So it would be nice to fave something like [set_variable] value="$(replaceall('$unit.id','_',' '))" or at least a WFL function to transform a string into a list of characters.
3. It's not perfect, but you can easily store the untransformed unit type id in a WML variable named after the transformed unit type id

**Comment by gfgtdf** [comment]
>Here is the proposal as it currently stands, if I understand correctly:

Yes you understood correctly.

> It's not perfect, but you can easily store the untransformed unit type id in a WML variable named after the transformed unit type id

How would that work? variablenames are not allowed to contain whitespaces and `$original_type_ids.$transformed_type_id` coudl contains whitespaces just like `$original_type_ids` does.

**Comment by sapientN3T** [comment]
@gfgtdf I meant that you could have something like this:

```
[original_type_ids]
    BOB_Giant_Swampcrawler="BOB_Giant Swampcrawler"
    BOB_Wose_Sapling="BOB_Wose Sapling"
    # etc...
[/original_type_ids]
```

**Comment by gfgtdf** [comment]
heh yes you could, in fact i also had this idea already, but i still think the my idea in theis pr is good since that'd be rather complicated and this prs sugegstion comes without disadvantages.

**Comment by Arcanister** [comment]
Why do we need to support such an idea even if somebody wants to use it? If we want to have certain variable indexed by unit type why not instead implement hash-tables (arrays with arbitrary string as index) which can take spaces inside index string?

And of course a string variable should be able to hold a value with spaces in in it.

**Comment by CelticMinstrel** [comment]
I need to point out that the syntax `S(blah blah blah)` is already taken and indicates a WFL expression to be evaluated and substituted into the string.

**Comment by Arcanister** [comment]
So, anyway, is it possible/desirable to support spaces inside variable name? It is possible with some programming languages at least.

If it's not desirable, then is it possible to implement array variables indexed by arbitrary string? Or maybe they are already available?

I don't like the idea to make engine insensitive to "_" and " " distinction.

**Comment by sapientN3T** [comment]
> is it possible/desirable to support spaces inside variable name?

Well, I guess anything is possible. It would however break a longheld tenet of WML structure, thus may break some things in non-obvious places, e.g. the confusing preprocessor code. Then depending on how implemented it may fail to generalize to other special characters, such as commas and equals. Generalizing to other special characters, a logical next step, would undoubtably cause more breakage in more places, e.g. maintenance tools. Finally, it is of questionable benefit, since one would have to remember to use the special syntax to guard against spaces-- not significantly easier than the level of awareness to workaround it-- so the feature likely would not have prevented the original bugs that prompted this FR.

> is it possible to implement array variables indexed by arbitrary string

It is already possible to LOOKUP_VALUE (see macros/utils.cfg), so what you are proposing is improved performance and more convenient syntax. While not impossible, this presents several design challenges, for example how to serialize and deserialize the new type, how to handle special characters within the brackets, etc. Keep in mind that WML design is not geared toward optimized computation tasks, and in the rare event that a WML author needs to perform intensive computation they can fallback to engine level (now pluggable via Lua, formerly new tag implemented via C++ patch).

> I don't like the idea to make engine insensitive to "_" and " " distinction.

There is already precedent with event names allowing interchangeability. But I do wonder about performance hits that might touch AI turns when it gets added to more and more places. That is worth considering. As for unit type IDs that differ only by space vs. underscore, I don't see any need to support that; allowing it is just as much or more confusing than disallowing it.

**Comment by soliton-** [comment]
@gfgtdf is it useful to keep this open? Any specific actions from this you still think are desirable?

**Comment by gfgtdf** [comment]
I'm currently not that involved in wml writing so I cannot say for sure, but I wouldn't say my standpoint has changed a lot. It's currently certainly not sometging on my wesnotg priority list though.

**Comment by Wedge009** [comment]
I noticed this about IDs when I was reviewing apostrophes recently ('straight' vs 'curly' versions). For example:
https://github.com/wesnoth/wesnoth/blob/3fcba6aa1c3636e531a159bd5e55fd959f17232b/data/campaigns/Son_Of_The_Black_Eye/scenarios/01_End_of_Peace.cfg#L55-L56
Arguably if the ID is not used for display there's no real need to include even the straight apostrophe there, it just complicates things unnecessarily. But then there's the issue of backwards compatibility and potential regressions if these are just changed in a blanket fashion...

**Comment by soliton-** [comment]
Encoding information in variable names is not a great practice and changing all unit type IDs to make this workable is going to be a big annoyance for everyone. If a unit type ID and some more info needs to be stored then that can be done in a WML container for example. If this is currently too cumbersome then it would be better to improve on that but suggestions for that would be better in new issues.
