### ISSUE TITLE
wesnothd stopping behavior

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1948]
Is it possible to stop wesnothd gracefully?
Whatever signal you use to stop it results in something like:
`20170906 18:07:50 info server: SIGINT caught, exiting without cleanup immediately.`
I think only the pipe in (/var)/run/wesnothd needs to be removed.

How is the stopping behaviour if the process has enough time?
When starting the server through the wesnoth UI a message tells:
`... The server will run as a background process until all users have disconnected. ...`
With 1.12 I saw that:
`Lan server has been empty for  71 seconds. Shutting down!`
I didn't had the luck of seeing that on 1.13 yet, server remains for ages. How exactly is this working?

How are the official servers avoiding to shut down when they are unused?

When starting the server standalone, should the -d option be used there too?
Are there any more differences than that the process forks then any you end up with two processes.

**Comment by soliton-** [comment]
1) You can request wesnothd to stop gracefully via the pipe: `echo shut_down > pipe`
2) The code would exit `main()` normally instead of calling `exit()`
3) The lan_server feature was gone for a while.
4) The official servers do not use the lan_server feature.
5) The -d option should probably not be used at all. Rather use a service manager to run wesnothd.

I think questions are better asked in chat or at the forum.
