### ISSUE TITLE
upgrade pop-up dialog unexpected for a droided side

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1963]
Steps to reproduce:
* open wesnoth-1.13
* on any human-controlled side get a unit that is about to upgrade, and has multiple advancement options
* droid this side

Expected:
* the droided side takes turn, eventually gets the unit upgrade and decides how to upgrade the unit by itself. This is also wesnoth-1.12 behavior.

Actually:
* the human player gets a pop-up dialog asking how to upgrade the unit.

**Comment by gfgtdf** [comment]
somehow  i was assiged  to this... 


Well, fixing this is rather easy, just add a check for `t.is_droid()` at https://github.com/wesnoth/wesnoth/blob/1.13.8/src/actions/advancement.cpp#L181 . Still i'm not that convinced what the  bahviour should be, i think there are cases where the would want to make such decisions wven if they droided the side.

**Comment by CelticMinstrel** [comment]
I really think that this might be a feature, rather than a bug...

**Comment by sevu** [comment]
I think one use case of droid is used when somebody leaves a MP game and other people want to continue.
What happens if there is an advancement then? Will the host have to choose?

**Comment by gfgtdf** [comment]
> I think one use case of droid is used when somebody leaves a MP game and other people want to continue.
What happens if there is an advancement then? Will the host have to choose?

It's possible that givin a side to an ai in the the 'player x left, what do you want to do' already bahved different and that you don't get advancement choices in that case.

**Comment by Vultraz** [comment]
If you droid a side why should you be able to control it?

**Comment by CelticMinstrel** [comment]
I think "droiding a side" in Wesnoth literally means "switching it to be an ordinary AI-controlled side", but I feel that there could be a distinction between the two. A droided side could be seen as still owned by a particular client, even though it's controlled by the AI. The player might still want to make choices for that side... or they might want to undroid it at a later point so that they can continue playing.

**Comment by Vultraz** [comment]
If they want to take control back later we should allow that, but I don't think we should pester the player with popups if they already ceded control to the AI. It's unexpected and I'd personally find it annoying.

**Comment by gfgtdf** [comment]
> I think "droiding a side" in Wesnoth literally means "switching it to be an ordinary AI-controlled side", but I feel that there could be a distinction between the two. A droided side could be seen as still owned by a particular client

Since 1.13 a droided side is no longer meant to be an ordinary ai controlled side. It is a human controlled sidefor thatis somwhow helped by the ai, this ihas the follwing consequences
1) If a droided side win you now get a victory dialog (in 1.12 you'd get a defeat dialog)
2) [store_side] controller= returns human (in particular it is more or less sycned now)
3) This isue.
4) the 'droided' state is not saved in a savegame, (when you reload the game you automaitcally get controll back)



We have thought about adding a ommand that does make a side an oridinary ai side, but the usecases for that outside debugging were quite limited, and it can done via wml ([set_menu_item] + [modify_side])so it's not a priority.

**Comment by sapientN3T** [comment]
I agree with @gfgtdf 's breakdown of the four points and the reasoning behind them. All good. EXCEPT for this issue. I feel pretty strongly that it is the wrong behavior.

Here's an example use case: I am playing wesnoth against my 5 little nephews, have to take an important phone call, I droid my side. when I come back to the PC they are all upset because they are waiting for me to pick an upgrade.

**Comment by gfgtdf** [comment]
hmm ye maybe, actually i currently don't have an opinion on this. I currently still cannot compile wesnoth locally so i probably won't do it soon. Feel free to change it, second post shows what to do.
