### ISSUE TITLE
killing a unit with debug :kill lets the halo remain

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1987]
until you click another unit. I guess it misses a redraw?

![debugkill](https://user-images.githubusercontent.com/21158813/30350983-7bd5daca-9819-11e7-8674-cbbadf66cd3a.png)

**Comment by Vultraz** [comment]
I...thought this was just fixed?

**Comment by sevu** [comment]
No, that not. I'm at 3b5880f. However, this only affects :kill as far as I can see, battle is not affected. That would be #1960.

**Comment by Wedge009** [comment]
If I kill with the default hot-key shift+k I can see an ever-so-slight hesitation before the halo is removed, but it is removed. But if I right-click and select kill from the menu, the halo remains.

Tested a bit later at 8d0282a6.

**Comment by sevu** [comment]
I used as well shift+k for it, in my case it remained.

**Comment by Wedge009** [comment]
Confirmed resolved, thanks!

**Comment by newfrenchy83** [comment]
i put the declaration of kill in amla advance and udiplay (unit_die) to extent your soluce to advance amla and all unit die where the bug remained, but the idea is good.

**Comment by newfrenchy83** [comment]
@jyrkive notify the whiteboard in advance_unit after resources::gameboard->units().erase(loc);, unit_die(), game_lua_kernel::intf_erase_unit(), debug_unit and debug-create_unit, and you re also extent  the fix to all unit die. event, unit_die() called in attack.cpp when unit hitpoints=0.
game_lua_kernel::intf_erase_unit() called in store_unit kill=yes and(kill].
In wml_action.unstore_unit insert local old_unit = wesnoth.get_unit(x, y)
if old_unit and not cfg.find_vacant or cfg.find_vacant == "no" then
old_unit:erase()
if old_unit==nil then
end
end
line 827-832 for call erase_unit and whiteboard. the insert is necessary because halo remain also when unit killed by another, or advance.
