### ISSUE TITLE
Error "min(list): list is empty" in ingame chat while playing LoW

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#1999]
Wesnoth 1.13.8+dev, GNU/Linux

In-game chat is flooded with messages in 4th turn of side 5:

<wfl> Error while parsing formula:
<wfl> min(list): list is empty

Steps to reproduce:
1. Load [LoW-The_Uprooting-Auto-Save4.gz.zip](https://github.com/wesnoth/wesnoth/files/1302248/LoW-The_Uprooting-Auto-Save4.gz.zip), renaming to remove zip extension first
2. Finish your turn and wait. When side 5 turn starts, several messages appear within in-game chat, but not in stdout/stderr.

Reproducible both in SP and MP mode.

The messages cannot be found in chat log accessible by Alt-C. 
Looking through Wesnoth code indicates that message is probably coming from [src/formula/function.cpp:206](https://github.com/wesnoth/wesnoth/blob/master/src/formula/function.cpp#L206)

**Comment by CelticMinstrel** [comment]
Sounds like an AI formula error.

**Comment by Arcanister** [comment]
I have noticed same messages, several in same time in A Tale of Two Brothers, closer to the middle of first scenario.

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/commit/eccd3d8e7eeb79a86ae538c9b469fd8c291763ec https://github.com/wesnoth/wesnoth/commit/fd9f1153f74da77f86f8732a7191c457c6ea4ac5

**Comment by gfgtdf** [comment]
the commits above by @CelticMinstrel changed the min/max frunction from returning 0 to giving an erros in that case, from looking at the second commit it seems like it was intentional.

**Comment by Arcanister** [comment]
Then min function is used incorrectly somewhere.

**Comment by CelticMinstrel** [comment]
Try running the game with formula logging enabled (I think that'd be `--log-warning=scripting/formula`, possibly replacing warning with debug. I'm pretty sure WFL errors come with a stack trace in the console (so on Windows you'll also need `--wconsole`), so that might give a clue as to where this error is occurring.

**Comment by Arcanister** [comment]
Nothing is printed on the console with options you suggested, however, when I enable all "ai"-related domain I get results which suggest that it could be related with poisoning, since side 5 is only one units with poison and:
```
debug ai/stage/rca: Evaluating candidate action: candidate action with name [poisoning]
info ai/engine/fai: Error while parsing formula: 
info ai/engine/fai: min(list): list is empty
```

**Comment by mattsc** [comment]
This is indeed caused by the change mentioned above and originates in the min() function in [data/ai/formula/poisoner_eval.fai#L7](https://github.com/wesnoth/wesnoth/blob/master/data/ai/formula/poisoner_eval.fai#L7).
The fix is to concatenate a list containing zero by adding `.. [0]` to the argument of min().  I have tested that that works and fixes the problem, can commit later.

**Comment by Arcanister** [comment]
Do you mean change in poisoner_eval.fai or in C++ code?

**Comment by mattsc** [comment]
You need to adapt the poisoner_eval.fai code to deal correctly with the (intentionally) changed behavior of the min() function.  It does not make sense for min() to return 0 for an empty list, so I agree with the change that was made in the C++ code.
