### ISSUE TITLE
Crash in addon manager: gzip error: iostream error

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2024]
GNU/Linux, boost 1.60, Wesnoth 1.13.8+dev.

Crash message is:
Caught general 'N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_9iostreams10gzip_errorEEEEE' exception: gzip error: iostream error

Two ways to reproduce:
1) Create dummy addon with valid _server.pbl and empty _main.cfg as in #2023
2) Install or remove any addon from its description dialog
3) Observe dummy addon incorrectly changes status to "Published"
4) Try to remove it from server from its description.

Another way is:
1) Start installing any addon
2) Interrupt while it's downloaded (by Esc key or clicking Cancel)
3) Start installing it again but don't interrupt this time.

**Comment by gfgtdf** [comment]
i took a look at this  (the 'Observe dummy addon incorrectly changes status to "Published"" part, not the crash itself) and the issue may be the here https://github.com/wesnoth/wesnoth/blob/1.13.8/src/addon/state.cpp#L60 whether an addon is published in checked depoending on a `t.remote_version == version_info()` check but in case that `installed_version` is also empty the `t.remote_version == t.installed_version` case above is used. git blame points to @jyrkive maybe he knows more.

**Comment by jyrkive** [comment]
No, I don't really know more. I just added the check, that's all. I put it down there to minimize interference with existing code.

**Comment by Vultraz** [comment]
The "Observe dummy addon incorrectly changes status to "Published"" issue I just fixed today: c1841e3fe84fcffd896b282b3596a696b5a717b7.

The first method was a symptom of the above issue, actually. Since the addon's state was incorrect, the Delete button became active, but it didn't work properly. However, if that somehow happens, an error pops up about the addon not being found on the server. There is no crash.

The second method seems like it was a symptom of #2203, which has since been fixed.

Closing.
