### ISSUE TITLE
Add-on rejected:  the add-on already exists, and your passphrase was incorrect.

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#2068]
Trying to update some add-ons that haven't been updated since early July, I get an error after the upload progress bar is completed.  It says:

>**Error**
The server responded with an error:
Add-on rejected:  the add-on already exists, and your passphrase was incorrect.

I'm using the same .pbl file as ever, so the passphrase must be correct.  I know there was some add-on server issue reported here 
https://forums.wesnoth.org/viewtopic.php?f=17&t=46830
but I don't think it applies to me, but what do I know.

It's possible that I've just missed something, or done something wrong, but this looks like a pretty critical bug, so I'll label it appropriately.

**Comment by shikadilord** [comment]
Please PM me on the forums to get your passphrase amended. I have actually tried to reproduce this bug to no avail -- I assure you it is completely unrelated to the one from the announcement, otherwise your add-on wouldn't even be listed on the server.

Until then I'm marking this Needs Info and dropping the Blocker label.

**Comment by shikadilord** [comment]
@loonycyborg Could you re-review PR #449 and compare with the current state of the codebase in case something went wrong with the hashing algorithm?

**Comment by doofus-01** [comment]
This just affects the 1.13 server, the 1.14 server will be a fresh start, right?

**Comment by shikadilord** [comment]
Since @loonycyborg has been silent for these past few days, I decided to have another look at it and I found that commit 98648ddf636bf4725d17334addac57850c478315 from @CelticMinstrel changes the implementation of `utils::md5::hex_digest()`, which is what `<unnamed>::set_passphrase()` in src/campaign_server/campaign_server.cpp uses to generate the hash, as per the PR linked above.

@CelticMinstrel Sooooo, what do?

**Comment by shikadilord** [comment]
(To clarify, the reason why that's the prime suspect is that it's the one hash-related commit that didn't get deployed until I rebuilt the server in September -- the previous build was from the end of May and the commit was conveniently written on the 2nd of August.)

**Comment by gfgtdf** [comment]
well the previous implementation is still in base64_digest(), the obvious attempt would e to make set_passphrase use base64_digest. But i wonder whether we should check both ways to be compabible with addons that were publiches between 2nd of august and now.

**Comment by CelticMinstrel** [comment]
Yeah, what @gfgtdf describes seems about right.

**Comment by shikadilord** [comment]
Instead of polluting the codebase with checks for a hash format that was only in use for a couple of months, I'd prefer if someone gave me instructions to write a script that converts the hashes produced after the 10-20 password change requests I've received in the meantime directly on the `server.cfg` without campaignd's involvement.

However, before we get to that point, is one particular format objectively superior than the other for this use case? Also, I'm guessing that the format that was in use before the September deployment was already different from the format 1.12 campaignd (which had PR #449 backported to it last year or so) uses.

**Comment by CelticMinstrel** [comment]
If I understand correctly (which admittedly I may not), a conversion script would need to:

1. Parse the hex digest into an array of integers. You'd basically take it in chunks of 8 hex digits, so it'd be easy to split up.
2. Convert that array to base64 using the same charset as Wesnoth (which may not be the standard base64 charset; see the implementation of `base64_digest`).

**Comment by shikadilord** [comment]
Well, in any case I need to know which format to use from now on to convert the hashes in the other format to it.

**Comment by CelticMinstrel** [comment]
The base64 format does use less space (4/3 the original rather than twice the original), though I don't know to what extent that matters since "the original" in this case is already quite short (being a hashed digest of the passcode).
