### ISSUE TITLE
Carpet overlay terrain

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2088]
Would *really* be good for interior scenarios. I tried to make one at one point, and it honestly kinda sucked. :(

Assigning to to doofus in case he wants to work on it, but anyone can pick this up.

**Comment by doofus-01** [comment]
How do you envision this working?  Sort of like the interior terrains, with rectangular edges, or it should be follow the hexes somehow?  

From the title, I guess you intend this to be an embellishment overlay (*^Ecp or something like that), but then you can't put other things on top, at least via overlay terrain.  I suppose [item] would still be available.

Do you have a mainline map in mind where this would go, as an example?

**Comment by Vultraz** [comment]
I envision it as a terrain that would sit as a perfect rectangle to allow straight line placement either vertically or diagonally in either direction. Perhaps the outside edge could have some frills, and there should be some pattern.

A good scenario for it would be the epilogue in EI.

**Comment by Vultraz** [comment]
Essentially, a better version of this (my own carpet terrain), but able to smoothly tile horizontally:
![carpet](https://user-images.githubusercontent.com/3558659/31575808-615ee6e8-b13a-11e7-80ba-5234be557c0c.PNG)

**Comment by CelticMinstrel** [comment]
That looks like awesome lava. :P

**Comment by ln-zookeeper** [comment]
I don't think it necessarily even needs to support concave corners; being limited to strictly rectangular pieces doesn't sound like an unreasonable limitation for carpets.

I'm not sure how much easier (if at all) that would make it, though, especially if a straight horizontal/vertical orientation was supported anyway.

**Comment by doofus-01** [comment]
Hi,
I've thought about this some, and want to know what others think before I start.  

 - I believe it would be nice to keep this as a base terrain, instead of an overlay.

 - Also, I will float the notion that a lot of carpet-* transitions don't make sense and can be handled by other interior terrains.  For example: carpet-mountains transition is silly; carpet-flat/chasm/water/ice could be some other interior-flat/chasm/water/ice transition (stone or wood?); carpet-sand/snow could favor the sand/snow transitions.  A single carpet tile in the middle of other terrain will just be stone or wood floor, there will need to be adjacent carpet terrains for the carpet to actually show up.

 - To give the player/map-maker some freedom, there could be two types:  wooden floor and stone floor underlayer.  If we want two colors (I can see "royal" purple and "common" red-brown as being useful) that is four terrains.  The transition hell that would create can be avoided by relying on the wood/stone transitions, for the most part at least.  Purple would overlay red-brown, where they met.  Restricting this to two terrains, we can have purple-over-stone and brown-over-wood.

As for the vertical/horizontal/diagonal issue, I hope that can be addressed by the "adjacent-only" rule in my second bullet point, but I haven't completely worked it through yet.  

Does that make sense?  I'll try to work on this this weekend.

**Comment by CelticMinstrel** [comment]
Or carpets could be an overlay terrain?

**Comment by Vultraz** [comment]
Tried out the carpets. Looking good! Few small issues I noticed, though:

Castle under carpet:
![carpet issue](https://user-images.githubusercontent.com/3558659/32696012-fe37dd58-c7bf-11e7-8975-c638a8fb51fa.PNG)

Thicker border than rest of images:
![carpet issue 2](https://user-images.githubusercontent.com/3558659/32696026-5cd9810e-c7c0-11e7-8847-3d31cdbed7bc.PNG)

Border extends slightly into carpet:
![carpet issue 3](https://user-images.githubusercontent.com/3558659/32696027-644bb2c2-c7c0-11e7-8841-6fa085f2233f.PNG)

**Comment by doofus-01** [comment]
Awwe crap.  I have a sinking feeling for a couple of those, but I'll see what I can do.  Thanks.

**Comment by Vultraz** [comment]
Closing this, since the carpets have been merged and the issues addressed.

**Comment by Vultraz** [comment]
Thanks for undertaking this, BTW :)
