### ISSUE TITLE
Add an appdata file

### ISSUE THREAD

**Issue by baimafeima** [wesnoth/wesnoth#2160]
For reference: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

**Comment by GregoryLundberg** [comment]
What good does this do?

On my system, the only software providing these files are the pieces and parts of KDE.

The web page claims all software centers use this but does not give any examples.

Is this really anything more than a KDE-only thing? A quick Google search indicates so. A number of other systems use __*different*__ "standard" places.

**Comment by baimafeima** [comment]
Look at the example from Red Eclipse in the Solus Software Center: https://github.com/solus-project/solus-sc/releases
Wesnoth currently has no entries at all there.

**Comment by GregoryLundberg** [comment]
I don't see that it makes sense to attempt to support the myriad package managers out there. If a packaging system needs it, I would expect the package maintainer for that system to implement it.

I did, finally, find some references to GNOME attempting a wide-spread deployment back around 2013; the most recent comments I see about it explain it is being dumped because it is "neglected" and "deteriorating".

**Comment by baimafeima** [comment]
It's not related to package managers.

**Comment by GregoryLundberg** [comment]
Whatever.

I am having a hard time finding information on this file format other than at the source site, and those references I did find are seem to be more about deprecation than deployment. Can you point me to several major distribution's documentation about this feature and show it's widely enough deployed (and in a consistent enough format) to make the effort of creating and maintaining the file, and all its translations, worthwhile?

**Comment by sevu** [comment]
@baimafeima have a look at #2291
