### ISSUE TITLE
build cmake: -Ox cflags get overwritten automatically

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2165]
````
mkdir build
cd build
CFLAGS="-O1" CXXFLAGS="-O1" cmake .. -G Ninja
ninja-build
````
execution will look like this:
````
clang++ -DHAS_RELATIVE_LOCALEDIR=1 -DHAVE_CONFIG_H -DHAVE_FRIBIDI -DHAVE_LIBDBUS -DHAVE_LIBPNG -DLUA_USE_POSIX -D_X11 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/pango-1.0 -isystem /usr/include/harfbuzz -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/libdrm -isystem /usr/include/dbus-1.0 -isystem /usr/lib64/dbus-1.0/include -isystem /usr/include/SDL2 -I../src -Isrc -isystem /usr/include/fribidi -std=c++11 -W -Wall -O1 -O3 -I/usr/include/SDL2 -D_REENTRANT -DWESNOTH_PATH="/usr/local/share/wesnoth" -DLOCALEDIR="translations" -DFIFODIR="/var/run/wesnothd" -MD -MT src/CMakeFiles/wesnoth-game.dir/sound_music_track.cpp.o -MF src/CMakeFiles/wesnoth-game.dir/sound_music_track.cpp.o.d -o src/CMakeFiles/wesnoth-game.dir/sound_music_track.cpp.o -c ../src/sound_music_track.cpp
````
the problem is the ```` -O1 -O3 ````
I have no idea where the -O3 is comming from but it is annoying when debugging since it overrides -Og or -O0 or whatever :/

**Comment by sevu** [comment]
I think this is intentional, does it work if you specify the Flags with -DCXX_FLAGS_USER ?

**Comment by GregoryLundberg** [comment]
Don't select a Release build.

Release forces optimization to -O3. 

Can you can get where you want to be with a Debug build?

**Comment by Pentarctagon** [comment]
cmake's [Release](https://github.com/wesnoth/wesnoth/blob/master/CMakeLists.txt#L525-L528) build is forced to `-O3`

and the [Debug](https://github.com/wesnoth/wesnoth/blob/master/CMakeLists.txt#L620-L624) build is forced to `-O0 -DDEBUG -ggdb3`

in order to make the compilation flags use between scons and cmake be consistent.  For scons, there are [separate options available](https://github.com/wesnoth/wesnoth/blob/master/SConstruct#L52-L55) for adding your own flags to the build, which would be appended rather than prepended.  Cmake doesn't have any options to specify additional flags though, and to be honest I didn't realize you could pass them in on the command line like that.

**Comment by Pentarctagon** [comment]
The same EXTRA_FLAGS_(RELEASE|DEBUG|PROFILE) options are now available for cmake, to mimic scons' flags.  Cmake also has the similar LINK_* options for passing additional flags to the linker.
