### ISSUE TITLE
HttT: "initiative" special causes sync/checksum errors in recalls

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#2216]
Hi,

1. In HttT Hasty Alliance, recall a merman onto (8,16).
2. Undo.
3. Redo.

This causes a sync error:

`20171118 20:25:44 error replay: SYNC: In recruit Merman Fighter: has checksum LHN.tzsQ<sDdie22e<JgbggA.t-U-+ki9oW01p2mJlc.-d5k8Q2H-f<lnd>j9le.m-b2k5cc<191192l7>,lg60O0>a3b>5-b>9Ojqj3d0VXa8lsHoOUbefgkkd1g40k while datasource has checksum 73.NLbK,CKjB3ijY7csj1Z0d>m4Zg7l11Xbii2pJm<X68We7-Dhw8,d64<c0i65e5g0h>mX>li+ia+p<kc76-lbxbcZgYcez.DnmriTlRE5dywt0>,6gLC5<<2NtosEs`

Adding --log-debug=unit reveals:

```diff
--- /tmp/one	2017-11-18 20:27:11.744358997 +0000
+++ /tmp/two	2017-11-18 20:27:14.016343193 +0000
@@ -1,4 +1,4 @@
-20171118 20:25:43 debug unit: advances_to = Merman Warrior
+20171118 20:25:44 debug unit: advances_to = Merman Warrior
 alignment = lawful
 cost = 14
 experience = 0
@@ -23,6 +23,15 @@
 	range = melee
 	type = pierce
 	[specials]
+		[firststrike]
+			id = initiative
+			name = 
+			[filter_self]
+				[filter_adjacent]
+					id = Li'sar
+				[/filter_adjacent]
+			[/filter_self]
+		[/firststrike]
 	[/specials]
 [/attack]
 [abilities]
```

The issue only occurs in current master since ca0b5033f06ad83868dc569e973897083042f90b; prior to that commit "Undo" was not possible at all.  (That commit just uncovered the bug, not caused it.)

**Comment by gfgtdf** [comment]
>That commit just uncovered the bug, not caused it.

No idea how you come to that conclusion, if you allow undoing on a action that changes that gamestate (by adding such an ability) that that is the cause of that bug not just an uncovering. In this particular scenario it probably won't be that problematic since due to theat wml filter the recruit event that is exceuted on recll won't add the ability  a second time, and even if, a second firststrike ability will have no effect.

To fix this message in wml currently afaik your only chane is to remove that weapon special in [on_undo] code that is executed. we coudl prbably also add an option to wml to simpyl mute that wanring, but i don't really like that idea though,

**Comment by jostephd** [comment]
> To fix this message in wml currently afaik your only chane is to remove that weapon special in [on_undo] code that is executed.

Like this? https://github.com/wesnoth/wesnoth/compare/master...jostephd:httt-undo-recall-initiative

**Comment by gfgtdf** [comment]
probably, i don't know this wml good enough to veryfy that it really works.

**Comment by gfgtdf** [comment]
note that you code might remove a initiative special if none was added (because the unit had the initiative special in an earlier scenario) which might then againgive checsum error messages

**Comment by jostephd** [comment]
Good catch.  I won't have time to fix that this week.

**Comment by gfgtdf** [comment]
Oh i just noticed that the event does have a lacks initiative filter to itmight actually eork like that (for some reason i thought before that it was the INITIATIVE_OBJECT marco that checks whether it slready has that ability in its tilter)
