### ISSUE TITLE
I don't understand story. (Warning spoiler)

### ISSUE THREAD

**Issue by kikaio96** [wesnoth/wesnoth#2230]
Hello I'm korean translator. I'm intereated in wesnoth story.
I don't understand this sentence.

#. [message]: id=Tallin
#:data/campaigns/Northern_Rebirth/scenarios/14a_Epilogue.cfg:418

Once again I thank all of you. For those of you who are leaving, may the Lords of Light — or Darkness — guide you on your path. For those of you who are staying — come, we have much to do.

I can understand 'Lords of Light guide you on your path'. But why add 'or Darkness'?

Please give me any advice. I'll accept to irrelevant answer to the question.

Thank you.

**Comment by Vultraz** [comment]
From a quick read of the file, I think it refers to "Lords of Darkness" since you can have two Liches (Ro'Sothian and Ro'Arthian) on your team by the epilogue. The Lords of Darkness would guide the two liches, not the Lords of Light.

**Comment by Wedge009** [comment]
Agreed, the story of the Northern Rebirth is about the beginnings of the Northern Alliance - instead of holding to narrow definitions of 'good' and 'evil', the Alliance draws upon several races and backgrounds. You have Mages of Light Morvin and Thera supporting you, but also Liches Ro'Sothian and Ro'Arthian - about as far apart as you can get in terms of ideological opposites! So as Vultraz said, with respect to the Lich allies, Tallin remarks upon Lords of Darkness.

**Comment by GregoryLundberg** [comment]
Asked and answered. I am closing this. If there are additional questions, feel free to follow-up

**Comment by Wedge009** [comment]
Agreed, thanks.
