### ISSUE TITLE
fix for issue #2137 doesn't work when compliling on build server

### ISSUE THREAD

**Issue by ForestDragon-wesnoth** [wesnoth/wesnoth#2256]
There was an issue with sdl2_mixer v2.02 and the ogg vorbis check https://github.com/wesnoth/wesnoth/issues/2137, but the fix in commit c4d78f8fc649f0e0eb1c6516c0555e2503a867fd https://github.com/wesnoth/wesnoth/commit/c4d78f8fc649f0e0eb1c6516c0555e2503a867fd introduced another issue. 

When compiling for AltLinux, it's required to use the build server, but the build server does not have a sound device in it's chroot, meaning that the check fails. 

The previous version didn't need a sound device for testing. We need either a ogg check that doesn't require a sound device, or a command line option to disable this check.

**Comment by GregoryLundberg** [comment]
As far as I'm concerned this is an upstream regression introduced in 2.0.2 because there is no need to have a sound device simply to initialize the codec.

That said, our only option seems to be to take the later advice and add flags for force passing certain tests.

Once bitten, twice shy: I'd recommend adding a command-line option to force a pass on every SDL/SDL2 test.

I'm assigning  @AI0867 and @loonycyborg because they seem to me to know more about how SCons works than I do.

**Comment by nvlasenko** [comment]
Thanks for the quick reply. I made a quick fix for myself, but it's merely a hack that cuts out the test itself, and thus it's unfit for uploading. It would be nice to know the sdl2 developers' opinion on the subject.

**Comment by AI0867** [comment]
Could you test https://github.com/AI0867/wesnoth/tree/sdl-mix-ogg-test?

**Comment by GregoryLundberg** [comment]
Been there, done that. No workie.

```
[lundberg@lundberg-arch wesnoth]$ git fetch https://github.com/AI0867/wesnoth HEAD:I2256
From https://github.com/AI0867/wesnoth
 * [new ref]                          -> I2256
[lundberg@lundberg-arch wesnoth]$ git checkout I2256
Switched to branch 'I2256'
[lundberg@lundberg-arch wesnoth]$ scons --config=force
scons: Reading SConscript files ...
.
.
.
Checking for Ogg Vorbis support in SDL... no
.
.
.
```

**Comment by AI0867** [comment]
Yeah, I saw the previous issue. Which error do you get if you run the check by hand?

**Comment by GregoryLundberg** [comment]
[lundberg@lundberg-arch sconf_temp]$ ./conftest_26 
Cannot initialize OGG codec: OGG support not available

**Comment by AI0867** [comment]
According to my read of the code, the main thing that can fail is the loading of a shared library. If that's not the problem, it's probably some failing bookkeeping shenanigans.
I have some code here that allows you to test that. You may have to change the OGG_DYNAMIC define and link flags to get it to work, but I'd like to see your results:

    #include "SDL.h"
    
    #define OGG_DYNAMIC "libvorbisfile.so"
    
    int main(){
        void *obj = SDL_LoadObject(OGG_DYNAMIC);
    
        if(obj){
            printf("Loaded library %s\n", OGG_DYNAMIC);
        } else {
            printf("Failed to load %s: %s\n", OGG_DYNAMIC, SDL_GetError());
        }
        return 0;
    }

to compile:

    $ gcc -I/usr/include/SDL2 -lvorbisfile -lSDL sdl_mix.c -o sdl_mix
    $ ./sdl_mix
    Loaded library libvorbisfile.so

Possible names for the library: `libvorbisfile.so`, `libvorbisidec.so`, possibly with numerical suffixes before the `.so`.

**Comment by GregoryLundberg** [comment]
My output looks like yours. And I don't see that it helped.
```
[lundberg@lundberg-arch test]$ cat sdl_mix.c 
#include <stdlib.h>
#include <stdio.h>

#include <SDL.h>
#include <SDL_mixer.h>

#define OGG_DYNAMIC "libvorbisfile.so"

int main(int argc, char ** argv)
{
    void *obj = SDL_LoadObject(OGG_DYNAMIC);

    if(obj){
        printf("Loaded library %s\n", OGG_DYNAMIC);
    } else {
        printf("Failed to load %s: %s\n", OGG_DYNAMIC, SDL_GetError());
    }

 if (Mix_Init(MIX_INIT_OGG) != MIX_INIT_OGG) {
        fprintf(stdout, "Cannot initialize OGG codec: %s\n", Mix_GetError());
        Mix_CloseAudio();
        return (EXIT_FAILURE);
    }

 Mix_Music* music = Mix_LoadMUS("/home/lundberg/wesnoth/data/core/music/main_menu.ogg");
 if (music == NULL) {
        fprintf(stdout, "Cannot load music file: %s\n", Mix_GetError());
        Mix_CloseAudio();
        return (EXIT_FAILURE);
    }

    fprintf(stdout, "Success\n");
    Mix_FreeMusic(music);
    Mix_CloseAudio();
    return (EXIT_SUCCESS);
}

[lundberg@lundberg-arch test]$ gcc -I/usr/include/SDL2 -lvorbisfile -lSDL2 -lSDL2_mixer sdl_mix.c -o sdl_mix

[lundberg@lundberg-arch test]$ ./sdl_mix 
Loaded library libvorbisfile.so
Cannot initialize OGG codec: OGG support not available
```

**Comment by GregoryLundberg** [comment]
```
[lundberg@lundberg-arch test]$ pacman -Q libvorbis sdl2 sdl2_mixer
libvorbis 1.3.5-1
sdl2 2.0.7-1
sdl2_mixer 2.0.2-2
```

My thinking is it's a regression in sdl2_mixer 2.0.2. As I read the commit logs for the project, my suspicion is the change to delay initialization is the culprit; but I am not that familiar with their code, that's just a guess based upon reading the logs from 2.0.1 -> 2.0.2

**Comment by GregoryLundberg** [comment]
For reference
```
[lundberg@lundberg-arch test]$ cat sdl_mix.c 
#include <stdlib.h>
#include <stdio.h>

#include <SDL.h>
#include <SDL_mixer.h>

#define OGG_DYNAMIC "libvorbisfile.so"

int main(int argc, char ** argv)
{
    void *obj = SDL_LoadObject(OGG_DYNAMIC);

    if(obj){
        printf("Loaded library %s\n", OGG_DYNAMIC);
    } else {
        printf("Failed to load %s: %s\n", OGG_DYNAMIC, SDL_GetError());
    }

 if (Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 1024) == -1) {
        fprintf(stdout, "Cannot initialize SDL Mixer: %s\n", Mix_GetError());
        return (EXIT_FAILURE);
    }

 if (Mix_Init(MIX_INIT_OGG) != MIX_INIT_OGG) {
        fprintf(stdout, "Cannot initialize OGG codec: %s\n", Mix_GetError());
        Mix_CloseAudio();
        return (EXIT_FAILURE);
    }

 Mix_Music* music = Mix_LoadMUS("/home/lundberg/wesnoth/data/core/music/main_menu.ogg");
 if (music == NULL) {
        fprintf(stdout, "Cannot load music file: %s\n", Mix_GetError());
        Mix_CloseAudio();
        return (EXIT_FAILURE);
    }

    fprintf(stdout, "Success\n");
    Mix_FreeMusic(music);
    Mix_CloseAudio();
    return (EXIT_SUCCESS);
}

[lundberg@lundberg-arch test]$ gcc -I/usr/include/SDL2 -lvorbisfile -lSDL2 -lSDL2_mixer sdl_mix.c -o sdl_mix

[lundberg@lundberg-arch test]$ ./sdl_mix 
Loaded library libvorbisfile.so
Success
```

**Comment by AI0867** [comment]
Okay, well here's my analysis:

[Mix_Init](https://hg.libsdl.org/SDL_mixer/file/7fa15b556953/mixer.c#l149) will return something other than `MIX_INIT_OGG` only if `load_music_type(MUS_OGG)` returns false.
[load_music_type](https://hg.libsdl.org/SDL_mixer/file/7fa15b556953/music.c#l269) will do so if

- [s_music_interfaces](https://hg.libsdl.org/SDL_mixer/file/7fa15b556953/music.c#l76) does not contain `Mix_MusicInterface_OGG` because it's not compiled in.
- if the "SDL_MIXER_DISABLE_OGG" SDL hint is true
- if the `Load` member of the struct is null, or returns `< 0`

The Load member of this struct is [OGG_Load](https://hg.libsdl.org/SDL_mixer/file/7fa15b556953/music_ogg.c#l73).
It can only return -1 on OSX or if `SDL_LoadObject(OGG_DYNAMIC)` returns `NULL`.

Reference: [SDL_LoadObject](https://hg.libsdl.org/SDL/file/93edd752e966/src/loadso/dlopen/SDL_sysloadso.c#l38)

Those are the other things you might want to test.

**Comment by nvlasenko** [comment]
In the build server, when using your script, I get the following:
$ ./sdl_mix
Loaded library libvorbisfile.so
Cannot initialize SDL Mixer: No such audio device

**Comment by GregoryLundberg** [comment]
@nvlasenko please also run the version which does __not__ include the call to `MIx_OpenAudio` and also provide the version numbers for SDL2 and SDL2_mixer on your build server.

@AI0867 It seems to me that all your conditions indicate the program should pass, yet it fails.

Obviously, MIX_Init is required. On the build server it fails because there is no audio device, as stated in the OP.

So, is there some way to tell Mix_Init to not probe for one, and simply assume there is a device available. Perhaps an environment variable?

Or is there some alternate to Mix_Init which will perform whatever side-effect MIX_LoadMUS requires?

N.B.: This is only an issue on SDL2_mixer version 2.0.2 (the latest released version). On version 2.0.1 all we needed was the call to Mix_LoadMUS.

**Comment by nvlasenko** [comment]
"please also run the version which does not include the call to MIx_OpenAudio and also provide the version numbers for SDL2 and SDL2_mixer on your build server."
here it is:

$ ./sdl_mix_noinit
Loaded library libvorbisfile.so
Cannot initialize OGG codec: OGG support not available

$ diff -u sdl_mix.c sdl_mix_noinit.c
--- sdl_mix.c   2017-12-01 16:11:24.707840927 +0000
+++ sdl_mix_noinit.c    2017-12-01 16:12:19.330562121 +0000
@@ -16,11 +16,12 @@
         printf("Failed to load %s: %s\n", OGG_DYNAMIC, SDL_GetError());
     }

+    /*
  if (Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 1024) == -1) {
         fprintf(stdout, "Cannot initialize SDL Mixer: %s\n", Mix_GetError());
         return (EXIT_FAILURE);
     }
-
+*/
  if (Mix_Init(MIX_INIT_OGG) != MIX_INIT_OGG) {
         fprintf(stdout, "Cannot initialize OGG codec: %s\n", Mix_GetError());
         Mix_CloseAudio();


$ rpm -q libSDL2-devel libSDL2_mixer libvorbis-devel
libSDL2-devel-2.0.7-alt2.S1.x86_64
libSDL2_mixer-2.0.2-alt2.S1.x86_64
libvorbis-devel-1.3.5-alt1.x86_64

**Comment by AI0867** [comment]
> 2.0.3:
>  * Fixed regression where Mix_Init() would return 0 for available music formats

Is this still an issue in versions other than 2.0.2?

**Comment by Wedge009** [comment]
Any update for this? Current Wesnoth release is using SDL_mixer 2.0.2, current SDL_mixer release is 2.0.4. Also, should this be labelled Upstream Issue?

**Comment by soliton-** [comment]
@ForestDragon-wesnoth please comment if the issue still persists with SDL2_mixer 2.0.3 or newer.
