### ISSUE TITLE
Map labels in editor vanish

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2273]
Been around for awhile in 1.13. Map labels created with the label tool don't show up at all, and creating a new one causes any existing starting position labels to vanish. They do exist, though, and appear in the saved files.

**Comment by GregoryLundberg** [comment]
There was a discussion about labels on the forums.

Specifically, the request was to add an "Are you sure?" popup to the "Clear labels" right-click menu option.

The complaint is that clearing labels not only removes player-made map labels, but also UMC designer map labels.

My thinking is that asking if they're sure is all well and good, but the heart of the problem is the failure to differentiate the two.

So, my suggestion would be to make them different types of labels, add a menu-option to 'Clear Map Labels' to compliment the current 'Clear Player Labels', and add 'Are you sure?' verification to both.

**Comment by jyrkive** [comment]
Related to #2154?

**Comment by Vultraz** [comment]
No, this issue is that the map labels don't appear when placed at all.

**Comment by jyrkive** [comment]
I mean that #2154 may have been caused by the same underlying bug. You simply worked around that bug by forcing the destructor of `floating_label_context()` to return even if the label map and context set weren't in sync.

**Comment by Vultraz** [comment]
I see... well, I don't know where they would go OOS, though.

**Comment by CelticMinstrel** [comment]
> The complaint is that clearing labels not only removes player-made map labels, but also UMC designer map labels.

I'm pretty sure labels placed by WML are immutable by default? I don't recall ever seeing the random map place labels being removed by Clear Labels, for example. There are already different types of labels - each label has a player and/or a category.
