### ISSUE TITLE
Boost 1.66: does not compile with it

### ISSUE THREAD

**Issue by t-zuehlsdorff** [wesnoth/wesnoth#2280]
Aloha,

i'm the maintainer of Wesnoth at FreeBSD. FreeBSD is going to update Boost to 1.66. It was found, that Wesnoth doesn't compile with it. Logs can be found here:

http://package23.nyi.freebsd.org/data/103i386-default-PR223922/2017-12-02_11h06m37s/logs/errors/wesnoth-1.12.6_7,1.log
http://package22.nyi.freebsd.org/data/103amd64-default-PR223922/2017-12-02_11h06m39s/logs/errors/wesnoth-1.12.6_7,1.log
http://package22.nyi.freebsd.org/data/111amd64-default-PR223922/2017-12-03_09h31m05s/logs/errors/wesnoth-1.12.6_7,1.log
http://package23.nyi.freebsd.org/data/111i386-default-PR223922/2017-12-03_09h31m14s/logs/errors/wesnoth-1.12.6_7,1.log

It would be great if this could be fixed. This doesn't require a full release. I'm able to commit patches with fixes it, until a new release is done.

Greetings,
Torsten

**Comment by GregoryLundberg** [comment]
I am marking this Invalid and closing it because the errors are in building the 'tools' target.

Please repeat without the 'tools' target and if the problem recurs, report back and I'll reopen.

The current master (1.13.10+) does not even provide the option to compile the tools target at all. The tools were all hopelessly way out-of-date, nobody used them, and many of them were for features or facilities which disappeared long ago.

**Comment by Pentarctagon** [comment]
It's also very unlikely at this point that there will be another 1.12.x release.
