### ISSUE TITLE
[set_menu_item] fires when changed in [command]

### ISSUE THREAD

**Issue by matsjoyce** [wesnoth/wesnoth#2310]
Version: git from today
Example:
```
{GENERIC_UNIT_TEST testsmi (
    [event]
        name=start
        [set_menu_item]
            id=mi
            [command]
                [message]
                    speaker=narrator
                    message="Hai from a"
                [/message]
                [set_menu_item]
                    id=mi
                    [command]
                        [message]
                            speaker=narrator
                            message="Hai from b"
                        [/message]
                    [/command]
                [/set_menu_item]
            [/command]
        [/set_menu_item]
    [/event]
    [event]
        name=hai
        id=hai
        [message]
            speaker=narrator
            message="Hai from a"
        [/message]
        [remove_event]
            id=hai
        [/remove_event]
        [event]
            name=hai
            id=hai
            [message]
                speaker=narrator
                message="Hai from b"
            [/message]
        [/event]
    [/event]
)}
```
Behaviour: `wesnoth --debug -t testsmi`, right click on anything, select menu item. Message `Hai from a` is directly followed by `Hai from b` without any action.
Expected: Second right click and menu select before `Hai from b` is shown. This is what 1.12 did.

A similar thing happens with events, `:fire hai` will present both messages instead of requiring a second fire.

**Comment by gfgtdf** [comment]
I wonder what the behavior is for normal events? If you create an event inside an event with the same name,die the child event gets fired immediately or not, and what  is the expected behavior there?

**Comment by matsjoyce** [comment]
@gfgtdf Same thing happens. I don't know what 1.12 does but I would expect that the child should not be fired until a new stimulus fires it. I've updated the initial issue with that as well.

**Comment by sapientN3T** [comment]
When I was in charge of the game events code of the WML engine (which I gave some fixes and improvements while writing the set_menu_item feature) I deliberately made it so that event handlers added during a game event would not be triggered by that same occurrence of that event. The code also contained comments making it clear that behavior was intentional. (Keep in mind that menu item commands are also event handlers.)

**Comment by sapientN3T** [comment]
another piece of my memory just came back to me. I also recall that pending menu_item changes went into a queue and weren’t processed until the active game event trigger had completey finished processing. there were a few reasoms for this. one reason was to prevent a crash: the piece of memory holding the original commands could be freed when you set the new commands (“volatility”). another reason was to prevent the user accidentally putting themselves in an infinite loop. however the obvious drawback is if you want to explicitly fire that handler immediately after adding it... the drawback can be worked around however, e.g. insert_tag

**Comment by gfgtdf** [comment]
Unfortunately there were many changes to that code since you worked on it most notably 
1) a refactoring by jamit that for example also contained this commit https://github.com/wesnoth/wesnoth/commit/3a78062d3e0cc8b48d4e5e5bc226fc3aac0a37d9 which does not say _why_ it is no longer needed 
2) a reactor by iceiceice that also broke something related to menu items, although I can't find that report in the tracker so maybe it was fixed?
3) a refractor by vultraz, which  most likely broke event names with variables in it.

So i don't think that there is currently someone that knows how it works in detail

**Comment by sapientN3T** [comment]
Ah, is there any way for me to view gna#23545? 

I don’t have time to test it now, but I suspect Jamit’s change may have made it possible to crash wesnoth by playing around with volatile config events, i.e. [insert_tag] name=event. 

I admit that the original behavior could be incorrect, but at least it was well defined and didn’t crash.

Probably the correct behavior is for new handlers to  be excluded from iterations of that event name which are already in progress, but still available to anything else which happens sequentially after they are defined, regardless of position in the pump stack.

**Comment by Ja-MiT** [comment]
It was not longer needed because of an earlier commit (the grandparent commit, bfe219f9451104eee508692156fcfd5473bc5b0f, to be precise -- sorry, it was in such close proximity, I had not realized I should have mentioned the earlier commit). Instead of buffering event handlers, the new loop cached the end of the list of handlers at the time the loop started. So new handlers could be immediately added to the list, and the loop would ignore them because they came after the cached end point. From one perspective, the buffer was moved to the end of the list.

My commit did mention fixing feature request #18713 (on Gna!). While I forget exactly what the issue was, I think it had something to do with an event handler defining a new event handler, then immediately firing the new event. Before my changes, the new event handler was hanging out in the buffer when the event was fired, so it was not handling the event. After my changes, it was in the list of handlers, so it could, but it was not included in the first loop through event handlers, preserving the functionality @sapientN3T mentioned.

I haven't checked the current version of the code to see if I can spot the problem (not enough time at the moment).

**Comment by gfgtdf** [comment]
here issues gna#23545 and gna#18713 https://pastebin.com/k8479zeJ from my local gna tracker backup. (it's not that fun to read in that xml form though,)

**Comment by gfgtdf** [comment]
thx for the explnation @Ja-MiT , then this was clearyl borken in https://github.com/wesnoth/wesnoth/commit/056d7ac8f88ca4614b22d10894235a93c1637eb2#diff-f40a027a6ead4b6803070ddf381604bd which just removed removed iteration::end_, obviously not knowing what it does.


@Vultraz please fix this.

**Comment by matsjoyce** [comment]
Thanks, works great now.

**Comment by Pentarctagon** [comment]
@sapientN3T 

> I don’t have time to test it now, but I suspect Jamit’s change may have made it possible to crash wesnoth by playing around with volatile config events, i.e. [insert_tag] name=event.

Was it possible at one point/should it still be possible to do `[insert_tag] name=event`?  I had tried doing that once a month or two ago, and trying again now the below code does not display a [message]:
```
[event]
  name="start"
  
  [set_variables]
    name=test
    
    [value]
      name="turn 1"
      
      [message]
        message="hi"
      [/message]
    [/value]
  [/set_variables]
[/event]

[insert_tag]
  name=event
  variable=test
[/insert_tag]
```
