### ISSUE TITLE
Map Editor [label] creates undocumented fields

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2315]
Steps:
* open map editor
* place a label
* save the map and see its source in a text editor

There will be a code like this:
```
[label]
	category=""
	color="221,221,221"
	immutable=yes
	side=0
	team_name=""
	text="Scoreboard:"
	tooltip=""
	visible_in_fog=yes
	visible_in_shroud=yes
	x=18
	y=4
[/label]
```

However, the wesnoth wiki has no documentation for `category`, `side`, `tooltip`. https://wiki.wesnoth.org/InterfaceActionsWML#.5Blabel.5D

Can you please document those properties, or "clean" the map editor? I don't know how to do that myself since I don't know what these fields do. (I see no way to configure `side` or `tooltip` in editor either.)

**Comment by CelticMinstrel** [comment]
Not sure what tooltip is, but side and category should probably be documented. The latter is something I added so that you could specifically hide (for example) the place names generated by the random map generator, without hiding any other labels. The former is for mutable labels, probably indicating which side placed them.

**Comment by jostephd** [comment]
Documented in the wiki https://wiki.wesnoth.org/InterfaceActionsWML#.5Blabel.5D

**Comment by vgaming** [comment]
@jostephd thanks!
