### ISSUE TITLE
Labels for Labeled hexes can be made to jump around the map

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#2333]
To reproduce:

Start Den of Onis and Set Label at 15,13 (this is just for easy tracking of where it should be, any hex will do.) (Can also use DiD S05 Orc War, with the 'River Longiler' label that is placed)

Move the cursor diagonally back and forth to trigger map scrolling (you may need to adjust zoom first)

the label will jump around and appear to be over other hexes at times.
It can come back to where it is supposed to be, and adjusting the zoom will make it return to the proper spot.

On current master built with MinGW64 5.3.0/Boost 1.61/SDL 2.0.7 on Win 7 x64

**Comment by vgaming** [comment]
Confirming this in both Map Editor and during Normal games on "Creep Wars" map.

In Map Editor, it reproduces by opening a map (possibly any map, but tested on Creep Wars) with a label. The problem is that I don't know an exact repro steps that would make the bug appear deterministically. It's just there 10% of the time. Scrolling around and/or maximising/minimising window usually helps to put the labels back in place (presuming you know where they _should_ be).

**Comment by sigurdfdragon** [comment]
confirmed fixed, thanks
