### ISSUE TITLE
iterating over unit_types is extremely slow

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2339]
Consider the following code:
```lua
for i=1,10 do
  for k,v in pairs(wesnoth.unit_types) do end
end
```

We iterate 10 times over all units here. This code takes about 3-4 seconds (UPD: 380 seconds for Ageless) to run on my (modern) computer. I think that's a bit too much. Wesnoth was started with a new clean `--userdata-dir`. Wesnoth version is v1.13.10+dev (393ac9bd-Clean)

Thoughts?

**Comment by ProditorMagnus** [comment]
Testing shows that this with 1.12 this outer loop can reach around 1000 iterations per second. With 1.13 single iteration took 39 seconds.

Testing done with lua wesnoth.message(os.time()) for i=1,10 do for k,v in pairs(wesnoth.unit_types) do end end wesnoth.message(os.time())

**Comment by sigurdfdragon** [comment]
I can confirm the slow times on 1.13 as well. There's two add-ons I know that do an iteration over all the unit_types to assemble a usable table of cfg's, and with a modest number of add-on eras it takes about 4-5 seconds on my system for each of them. When I add ageless era to the mix, it takes 40 seconds.

@gfgtdf I saw in some other recent github thread where you mentioned the time in lua vs c++ in some formula fashion for this issue, so would having a lua function executed in c++ to make such a table be applicable here?

**Comment by vgaming** [comment]
Another thing that can be interesting: actually accessing `wesnoth.unit_types` fields is quick.
So, for example, consider this code:
```lua
-- preparation
all_keys = {}
for k, _ in pairs(wesnoth.unit_types) do all_keys[#all_keys + 1] = k end
-- real measurements begin here
for i=1,1000 do for _, u in ipairs(all_keys) do if wesnoth.unit_types[u].cost < 0 then print("hm?") end end end
```
the last line runs under 1 second, even though it's 1000 iterations, as well as an additional `if` and field access.

**Comment by GregoryLundberg** [comment]
I'm not surprised, having done a code-read.

This problem is number two on the flight line, waiting for the MP moderation PR to clear the runway.

**Comment by GregoryLundberg** [comment]
Most likely, the issue is the performance of `std::map` is O(log n).

The obvious first attempt at a solution is to change to using `std::unordered_map` instead. This should drastically improve performance since it is O(1).

Unfortunately, while the implementation of the `class unit_type` compiles when using a `std::map`, it violates a constraint of C++ which, when we switch to `std::unordered_map` prevents compilation. The fact that we compile using `std::map` is unspecified behavior. All current targets support it, but there is no requirement that others do, or that they continue to do so.

This this constraint is found in the following rule (17.6.4.8) which applies to our code:
```
In certain cases (replacement functions, handler functions, operations on types used to
instantiate standard library template components), the C++ standard library depends on
components supplied by a C++ program. If these components do not meet their
requirements, the Standard places no requirements on the implementation.

In particular, the effects are undefined in the following cases:

...

if an incomplete type is used as a template argument when instantiating a template
component, unless specifically allowed for that component.
```

Thus, to improve performance by switching to `std::unordered_map` I would need to refactor the `class unit_type` to avoid the use of the not-yet-complete `class unit_type` in the member element `variations_` and the member function `variation_types()`.

While I consider that option, I am looking for others. I must say, however, that the refactoring appeals to me since it avoids use of unspecified behavior.

**Comment by vgaming** [comment]
@GregoryLundberg My answer may seem silly or too quick comparing to yours, but I don't really get it.

First of all, I don't know CPP, but I can use google/searx: http://en.cppreference.com/w/cpp/container/map
This page says "Maps are usually implemented as red-black trees."
Iterating a tree should be O(1) per iteration step. Accessing element is O(log(n)) for sure, but for iteration you don't need general-purpose `get`.

Second, IDK about cpp again, but in Java, there is "linked hash map", which is the same as hash map, but the keys are additionally double-linked. There's no way CPP doesn't have this. Or will it not compile in some way? Why shoudn't it, conceptually?

Third, `log(n)` is small. For 200 elements (~ all units in Default Era), it equals 5.23. But, as shown above in Lua code, iterating using pre-sorted _array_ keys of unit types is 300-2000 times faster. These numbers don't add up. Could it be that in order to get "next" element we actually iterate through _all_ previous elements in the tree?

Fourth, this is something I came up to while writing the post. Consider this code:
```
unit_types = {}
for k,v in pairs(wesnoth.unit_types) do unit_types[k] = v end
for i=1,10000 do for k,v in pairs(unit_types) do end end -- this line runs in under 1 second
```
Maybe _this_ is what we should do, instead of a `userdata`? I guess this won't work with new units being add on-the-fly though? There's now way we're the first project using Lua and have a problems with iterating.. Something's wrong here, I can't believe the problem is a simple `log(n)` which equals `10` for `22000` unit types...

**Comment by vgaming** [comment]
EDIT: formatting and some typos.

**Comment by GregoryLundberg** [comment]
The problem is the iteration is, at present, __*not*__ a step to the next node. It is a find() followed by a step.  Find is O(log N). In other words, we're (almost) doing what you suggest:

```
unit_types = {}
for k,v in pairs(wesnoth.unit_types) do unit_types[k] = v end

-- this line runs in under 5 seconds
for i=1,100000 do for k,v in pairs(unit_types) do emit wesnoth.unit_types[v.unit_type] end end
```

That leads to the other approach I'm considering: changing the `int` index to a userdata `std::map::iterator`. As I read the Lua documentation, that should be workable. The issue is that I cannot be sure nobody took the index as an integer somewhere. But this is what I plan to test later today.

Your pre-scan approach is workable for the individual UMC author, who knows not to change the `wesnoth.unit_types` until after the second `pairs()` iteration. Unfortunately it does not fit the Lua requirement that one can safely delete from `wesnoth.unit_types` while iterating your local copy.

No matter what the interim solution is, for 1.14, I'm afraid the correct long-term solution is to perform a major refactoring so that we are no longer dependent upon unspecified behavior.

**Comment by GregoryLundberg** [comment]
Actually, I'd have to do the math but I think our present implementation is on the higher side of O(log n) and O(n log n). Not that it matters whether our implementation is just slow or whether it's glacially slow.

**Comment by CelticMinstrel** [comment]
Storing an iterator instead of an index seems like a reasonable plan to me, though I'm not sure how that would make it safe to delete while iterating...

**Comment by GregoryLundberg** [comment]
Well, since this is just for `unit_type` we simply need to clearly state the caveats in the documentation. While it would be nice to perform fully to the Lua documentation, I don't have a problem with saying that you cannot delete the current unit_type within a `pairs()` loop.

**Comment by ProditorMagnus** [comment]
Unless something has changed, unit types cannot be altered during game.

**Comment by CelticMinstrel** [comment]
Oh yeah, that's true, we're iterating over what is basically a read-only array, so the inability to delete from it isn't actually a problem anyway.

**Comment by vgaming** [comment]
So `wesnoth.unit_types = our_unit_types_lua_copy` and problem solved? I'm just kidding though, I wouldn't like `unit_types` which mutates its type as scripts run myself. Then again, we can maybe add elements to Lua map directly from C++?

**Comment by vgaming** [comment]
EDIT: wording.

**Comment by GregoryLundberg** [comment]
What he's saying is that your fast workaround is a viable solution for a UMC author (but not for me). For me, it means I don't need to worry about using an old C++ STL iterator passed to Lua and retrieved: it will still be valid.

So, if you need a solution, or need to support older clients, use your workaround.

When I'm done and you're good with a requirement of 1.14 or later, you can switch then.

**Comment by vgaming** [comment]
@GregoryLundberg I don't object and fully support the idea of using well defined & maintainable data structures.
I was just thinking whether we need to have `wesnoth.unit_types` in C++ at all. I'm not sure whether `wesnoth.unit_types` is static and immutable, but it seems so. I think you know both answers better than I can guess.

**Comment by GregoryLundberg** [comment]
I've been sort of put this on the back burner this since there is a viable workaround. I consider it daily, but haven't yet felt motivated to start all the work needed store an iterator as Lua userdata it's not hard, but it's tedious.

**Comment by vgaming** [comment]
@GregoryLundberg Even if there's a work-around, the work-around still needs to be done. The current situation doesn't seem acceptable to me. For example, if I add Ageless Era, a **single** iteration on my new computer takes **38** seconds.

Obviously, no one would like that to happen even once. If we go the work-around way, we still have to populate the table incrementally. Either directly adding into Lua while we parse new units, or asking Lua to add by giving fast access to a particular unit.

Also, maybe it doesn't make sense to leave a slow data structure lying around in code. This I don't know though, just mentioning as a possibility. If it's indeed slow, anyway.

**Comment by ProditorMagnus** [comment]
Only real workaround I can see here is me generating such table with each ageless release, so this delay would not happen in game.

I don't consider that as viable workaround.

**Comment by ProditorMagnus** [comment]
I see, that might work indeed.

**Comment by GregoryLundberg** [comment]
Ah. I misunderstood. I was under the impression that no existing content suffered from the issue. That does up its priority in my mind.

**Comment by GregoryLundberg** [comment]
@ProditorMagnus Can you point to me where/how to hit that slowdown in Ageless Era?

All I see when I install it and use a Random Map is a bazillion messages on the console and a couple on-screen; but I had a breakpoint set at the Lua next function for the unit_types and never hit it.

I think I can solve the speed issue by storing a userdata for the 'index', storing a C++ iterator in it. and adding metamethods so you can add and subtract integers to move forward and back 'as if' the unit type table were an array instead of a red/black tree.

**Comment by CelticMinstrel** [comment]
The vconfig iterators already do something similar: https://github.com/wesnoth/wesnoth/blob/master/src/scripting/lua_common.cpp#L283

I don't think the metamethods you describe would actually be necessary?

**Comment by GregoryLundberg** [comment]
I can consider storing the iterator because the map is, basically, read-only by the time any Lua can run.

I can skip making the iterator work like an 'index' if the only use of pairs() and next() is in a for-loop and the only thing you can do is start at the beginning and step forward to the end, where your only other option is to break out of the loop early and abandon the iterator. No skipping forward or back. And no saving the 'index' for later use. I _might_ be able to get away with adding a counter and letting you have that (as the 'index' "value") so you can store something which might get you back to a given item at a later time.

**Comment by CelticMinstrel** [comment]
Hmm. You can't actually access the unit list by index though, can you? You can only look up a specific unit type, right? In other words, the Lua view of it isn't an array; you typically access it via eg `wesnoth.unit_types.Elvish_Ranger`.

**Comment by ProditorMagnus** [comment]
Ageless itself doesnt need to know its units at runtime, that might be needed for other addons that rely on ageless. For example currently I generate lists of certain level units https://github.com/ProditorMagnus/OrociaRandomMod/blob/master/lua/data_unit_types.lua for each release.

**Comment by GregoryLundberg** [comment]
@CelticMinstrel At the heart of your last comment is why this issue exists.

The question is what is the mental model for 'index'?

I could treat it as a unsigned integer. Offseting is O(N), setting is O(N + log n)

I could treat it as a string, as we currently do. O(log n), in a for-loop that's O((1+2+..+n) log n)

I could deny all changes and have the table-index operation accept my userdata iterator as well as a string for the `index` and convert the O(log n) access to "the selected unit type which happens to be 'Elvish Ranger'" into O(0) "the selected unit type as given by this userdata"

**Comment by CelticMinstrel** [comment]
Why not just use the `__pairs` metamethod like I did for vconfigs? Doesn't that solve the problem of the index? If they use a string index, it works and is O(log n). If they iterate using `for id,ut in pairs(wesnoth.unit_types)`, it works and is O(n). No intersection between the two methods of accessing the map. I'm not sure if you can get the `next` function to work with this method, mind you, but I don't consider that very important; idiomatic Lua generally doesn't use the `next` function.

**Comment by GregoryLundberg** [comment]
I am studying your code. Looks like it's what is needed with only minor modifications. I was thinking along thise lines so your code gives me an example.

**Comment by vgaming** [comment]
Minor off-topic comment. I think it's written as `O(1)` instead of `O(0)`. `O(0)` means no operations at all, not even a single simplest. `O(1)` is a finite pre-defined number of operations for any N.
> O(0)

**Comment by vgaming** [comment]
@CelticMinstrel
> idiomatic Lua generally doesn't use the `next` function.
Well, I know one simple use case: it is to check whether a table has any elements at all. (You can do it by checking `next(table)`.)

Also, IDK if it's relevant, but some developers prefer to write `for k, v in next, table, nil do end` IIRC. Again, not sure if it's relevant to your considerations.

**Comment by vgaming** [comment]
EDIT: markdown.

**Comment by CelticMinstrel** [comment]
>Well, I know one simple use case: it is to check whether a table has any elements at all. (You can do it by checking next(table).)

I guess that's true, but I'd say you should at least ensure it's a table first... (which would mean the units table should be a userdata, not a table with a custom metatable)

> Also, IDK if it's relevant, but some developers prefer to write for k, v in next, table, nil do end IIRC. Again, not sure if it's relevant to your considerations.

That's kinda like shooting yourself in the foot.

**Comment by GregoryLundberg** [comment]
/me rolls his eyes and wishes a few C++ programmers would do what they "should"

**Comment by GregoryLundberg** [comment]
In response to code-reading for #2381 and looking at the comment thread, I'm channeling my inner Linus and declaring it "all crap"

Not only do we need to use an iterator (convertible to and from string) for this, we need to create an entirely new class for the genders and variants.

My original estimate was a week or so to handle the slowdown and fix the crash from #2381, but with all the work it will probably be more like a month to chase down what needs doing, do it, and test it all.

**Comment by jyrkive** [comment]
@GregoryLundberg How about the approach I suggested in Discord?

Instead of having this stupid proxy, make `wesnoth.unit_types` a real Lua table. Construct it once in C++ code, write-protect it (by overriding `__newindex` *and only it*) and you're done. No need to implement all kinds of accessor and iterator functions.

**Comment by vgaming** [comment]
@jyrkive yes, similar to this https://github.com/wesnoth/wesnoth/issues/2339#issuecomment-357497816  but in more detail. The thing we will still need to care about is avoiding C++ iterating even once. Because even a single slow (current) iteration takes 35secs. Otherwise, seems like it'll work.

**Comment by jyrkive** [comment]
@vgaming Indeed, that approach would completely avoid C++ iterating once the table has been constructed. If we don't override `__index`, `__pairs` etc., our C++ code won't even be called when a developer is iterating the table.

**Comment by GregoryLundberg** [comment]
You would need a table for unit types with a table (nil 1 or 2 entries) for gender and another table (nil or many entries) for variations.

A pre-build table with sub tables sounds fine if you don't mind the time and expense since you're doing a deep copy from C++ struct/class plus containers to Lua tables and elements.

**Comment by GregoryLundberg** [comment]
I will hold off on what I was going to do to give you a chance. IT will be cleaner on the Lua side and probably look a lot cleaning on the C++ side since you're trading C++ marshalling to Lua for memory.

**Comment by jyrkive** [comment]
All right, I can try to implement it tomorrow.

**Comment by CelticMinstrel** [comment]
A prebuilt table works for `wesnoth.unit_types`, at least. I'm not sure if it's good for `some_unit_type.variations` though, as that table would most likely end up being rebuilt every time the `variations` key is accessed. Then again, it would generally only have a few entries, so it might still be okay.

I don't think we need a separate table for genders and variations, personally. Genders are basically variations themselves, so I think it makes sense to put them at `some_unit_type.variations.male` and `some_unit_type.variations.female`. (Relatedly, ideally the `[female]` tag would be equivalent to having a `[variation]` tag with `id=female`. I suspect this isn't currently the case though...)

**Comment by CelticMinstrel** [comment]
Also @jyrkive, in case you missed my checklist: https://github.com/wesnoth/wesnoth/issues/2381#issuecomment-359138811

**Comment by AI0867** [comment]
In the C++, the genders and variations are in different lists, and they are each full unit types themselves. Theoretically, you could nest them forever, though I haven't checked whether they would actually be accessible.

So, I'm not sure if merging the genders and variations is a good idea. It sounds kind of like the decision to merge variations and types in the lua API.

**Comment by jyrkive** [comment]
My work so far is in [this branch](https://github.com/wesnoth/wesnoth/commits/unit-types-table). `wesnoth.unit_types` is loaded lazily on first access: when it's accessed, the whole table is generated in one go, and any further operations such as iterating the table are lighting fast.

Variations and genders aren't yet implemented, but at this point the time to construct the table is about 700 microseconds per unit type; with Ageless Era, it makes two seconds in total. For reference, right now in master the time to iterate the table is ~14 milliseconds per unit type, i.e. 20 times slower. And that's on every iteration - it doesn't get any faster if the developer wants to iterate the table a second time.

I don't have more time to work on Wesnoth until Sunday, so I'm leaving the branch to this state for now (and I'm not even going to open a pull request until/unless the branch is finished.)

**Comment by CelticMinstrel** [comment]
...wait, you're removing not only the problematic "unit type list" userdata but also the "unit type" userdata itself? Wouldn't it make more sense to keep the latter? Iterating over it isn't really necessary...

**Comment by GregoryLundberg** [comment]
I see a work in progress. It doesn't really matter but he's lazy loading. If it were read/write then the userdata and metatable would be needed. If most or all of the units are visited when iterating, he'll have a net gain in speed by avoiding the marshalling functions; its even possible the gain would appear at just one unit type being visited.

If we want to support Lua creation or modification of unit types and variants, we will need to come back to doing all the marshalling. But, if we do, it would be best to start with a clean slate.

I'm happy to see it moving so fast. My one-month estimate was based upon what I expect my interruption level to be. But even today's plan was blown out of the water with another all-afternoon doctor visit for the wife.

**Comment by vgaming** [comment]
Other facts that may be of interested:
1. It was confirmed that the performance regression indeed happened here: https://github.com/wesnoth/wesnoth/commit/b5c5e21895dabbdd0e239968d0d8697c626b72f7
2. There is an alternative proposal to lazy loading: make `wesnoth.unit_types` a Lua table, but make entries e.g. `wesnoth.unit_types["Mage"]` be userdata. So only iteration and partially access would be moved to Lua.
Or, we can try to understand what part of the commit above caused the regression, and somehow undo that part, if that's possible.

**Comment by CelticMinstrel** [comment]
Option 2 would mean that the unit variations table is rebuilt every time someone accesses `wesnoth.unit_types[unit_id].variations`. That might not be a problem though, since most units have very few variations, so building that table is likely pretty fast.

**Comment by vgaming** [comment]
@CelticMinstrel maybe. I'm most encouraged by this stat: https://github.com/wesnoth/wesnoth/issues/2339#issuecomment-354644098 (5 seconds for 100k iterations)

**Comment by ilyapopov** [comment]
The actual problem is here: https://github.com/wesnoth/wesnoth/blob/7a6c39380ed5972f0fc059a00bc2c42e910fffa4/src/scripting/lua_unit_type.cpp#L138

The whole map is copied every time. Did the author intend `auto &`?

**Comment by CelticMinstrel** [comment]
I seem to recall issues getting that line to work. Maybe using `auto&` even raised a compile error. You're right though, it should have been taken by reference, even if it meant writing a helper function to do it.

**Comment by Ja-MiT** [comment]
I wouldn't be surprised by `auto&` raising a compiler error here. That line evaluates to either a `variations_map` (if base is not null) or a `unit_type_map` (otherwise). Both are typedefs for the same thing, but they are separate typedefs. References are probably picky about that. Not a good time to rely on `auto` to figure out what the programmer cannot.

From the looks of it, this line of code violates the black box of the `unit_type` class (where `variations_map` is a private type), and probably violates the black box of the `unit_type_data` class (where `unit_type_map` is a public type, but there is no documentation as to how much of the definition should be considered implementation details). Possibly, this function and the types involved should be re-evaluated to see what should be public, what should be private, and how many typedefs for the same map type are warranted.

That might seem like busy work, but it sometimes uncovers fragile and/or buggy code. (I'd look more, but I'm out of time at the moment.)

**Comment by GregoryLundberg** [comment]
Hey, is that one month estimate of mine still being questioned?

The basic problem is expressed in that single line.

Someone, I think it was @CelticMinstrel, wanted to do far to much in one function. The issue would never had arisen if the two pairs() concepts has been kept separate:

- pairs(wesnoth.unit_type)

- pairs(wesnoth.unit_type["name"].variations)

And if someone wanted to know the total number of variations across all unit types they would have to iterate both and count, unless we eliminate the inner pairs() by defining

- #wesnoth.unit_type["name"].variations

to return the number of variations for a unit type, rather than the Lua standard of zero since we do not have numeric integer unit type names.

As it was, the present implementation is trying to magically compress it all into one pairs() function by using some global state to imply the caller's intention.

It's an utter mess and needs to be completely replaced.

My estimate, based upon considerations of my RL as well as the needs of the project is that it would take me a month or more to fix.

So, @jyrkive stepped in to do a quick-and-dirty replacement which gets it working.

The clock is running. Unless there is a serious show-stopper in his work, it needs to merge in the next day or two to make it into 1.13.11.

That merge closes this Issue (the crash is solved). If someone wants to note that it should still be rewritten, then open a new Issue and take it Feature Request.

**Comment by ilyapopov** [comment]
This change compiles fine: 

```
diff --git a/src/scripting/lua_unit_type.cpp b/src/scripting/lua_unit_type.cpp
index a5c7d4ed05..3f2a8ce2e0 100644
--- a/src/scripting/lua_unit_type.cpp
+++ b/src/scripting/lua_unit_type.cpp
@@ -135,8 +135,8 @@ static int impl_unit_type_count(lua_State* L)
 static int impl_unit_type_next(lua_State* L)
 {
        const unit_type* base = *static_cast<const unit_type**>(luaL_checkudata(L, 1, UnitTypeTable));
-       auto unit_map = base ? base->variation_types() : unit_types.types();
-       decltype(unit_map)::const_iterator it = unit_map.end();
+    const auto &unit_map = base ? base->variation_types() : unit_types.types();
+    auto it = unit_map.end();
        if(lua_isnoneornil(L, 2)) {
                if(base) {
                        if(base->has_gender_variation(unit_race::MALE)) {
```

**Comment by GregoryLundberg** [comment]
Yes, this probably speeds things up. But does it really matter how quickly you get to the wrong answer?

**Comment by jyrkive** [comment]
Celticminstrel's code in master appears to work correctly - the only real problem is that it copies all unit types every time you call `next(wesnoth.unit_types)` in Lua.

I think @ilyapopov 's fix is the best option we have if we can get it to compile on all platforms. Rewriting `wesnoth.unit_types` would still be a good idea in the long run, but for now I think it's best to just take the fastest fix.

**Comment by GregoryLundberg** [comment]
OK. I won't object if you kill your PR and direct-push the two-liner above, so long as you're confident the iteration provides rational results.

One of us can revisit the issue someday.

**Comment by sigurdfdragon** [comment]
> I can confirm the slow times on 1.13 as well. There's two add-ons I know that do an iteration over all the unit_types to assemble a usable table of cfg's, and with a modest number of add-on eras it takes about 4-5 seconds on my system for each of them. When I add ageless era to the mix, they take 40 seconds.

Compared to the above,
With https://github.com/wesnoth/wesnoth/commit/4685aed6a58fb234cc9de6304016c76539bc07d8
Showing a dialog allowing selection of all existing units handling a modest number of eras on my system, the difference in time taken is almost imperceptible (maybe 0.1-0.4s?) between a run with table creation and with the table already existing.
Adding in ageless era it's something like 0.5-1s & with that, the work of showing the dialog seems to come close to taking as long as table creation. (Total of about 1.0-1.5s on first table creation run to show dialog, 0.75-1s on subsequent runs

So confirming it is solved in practice.

**Comment by vgaming** [comment]
Confirming, too. Unit iteration works and is fast.  \o/
Thanks everyone involved.
