### ISSUE TITLE
Wrong terrain defense display for Horseman on Snowy Mountains

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#2353]
1. Start HttT.
2. :change_level to The Dwarven Doors.
3. Click on the Horseman unit.
4. Mouseover the frozen mountains (9,33) (terrain code "Ms").

The hex is highlighted as "30%" terrain defense, even though Horsemen can't enter that hex at all. This is different to the adjacent regular mountains (10,33 "Mt") that are also unreachable but show as "0%". In contrast, the infobox at the top of the sidebar shows a dash for both Ms and Mt.

**Comment by soliton-** [comment]
This seems like a misguided fix. Yes, the Horseman cannot go on mountains and has 0% defense there. Also snowy mountains have worst-of movement so they cannot move there either. Nevertheless they do indeed have 30% defense there since it's best-of defense.

Normally this does not matter but should a horseman get on a snowy mountain anyway via some special mechanic then the now shown value of 0% is simply wrong and also not what will be used.
