### ISSUE TITLE
Crash when creating a scenario in the map editor

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2523]
When I create a scenario in the map editor, the game crashes in an attempt to access the AI  manager.

It only happens if I've already entered a game in the current session; if I start up the game, go straight to the editor, and create a scenario, there's no crash.

**Comment by Vultraz** [comment]
Almost certainly this is use-after-free, since `ai::manager::singleton` is never reset to `nullptr` once the AI manager is destroyed. So, game starts, manager created, game ends, manager destroyed, but the singleton is not reset to `ai::manager::has_manager()` returns true when `team_data` is initialized for a new side in the editor.

Assigning to @jyrkive since it was his refactor originally.
