### ISSUE TITLE
Whitespace errors in repository

### ISSUE THREAD

**Issue by jyrkive** [wesnoth/wesnoth#2613]
Found with instructions in http://peter.eisentraut.org/blog/2014/11/04/checking-whitespace-with-git/

Captured at commit 5e272829fa73603e55c383eafe20b108666a44f2.

~~[Complete list of whitespace errors (1.2MB)](https://github.com/wesnoth/wesnoth/files/1793172/whitespace-errors.txt)~~ See comments for the latest list.

**Comment by jyrkive** [comment]
[Updated list (1.1MB)](https://github.com/wesnoth/wesnoth/files/1800540/whitespace-errors.txt)

Captured at commit 733b76241d2e1cd180f5f1f0ffb139dcbd3d4222.

**Comment by jostephd** [comment]
Updated list:

- 2 false positive warnings about conflict markers
- 7 `space before tab in indent` in src and utils/travis. I reviewed them all, they're all harmless, the indentation isn't wrong or misleading in any of them.
- 1660 `space before tab in indent` warnings in utils/umc_dev. That tree hasn't had a meaningful change since 2016 (084853e262e31c2be497a69fff01c87aeca74001), and it requires "Java 7 (8 won't work yet)" and "Python 2", both of which are near or past end of life.

All in all, it seems whatever needed to be done here has been done, so closing.
