### ISSUE TITLE
Undocumented API methods

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2653]
The following methods do not seem to be currently documented in LuaWML ( https://wiki.wesnoth.org/LuaWML ) :

- [x] wesnoth.show_menu
- [x] wesnoth.get_viewing_side
- [ ] wesnoth.open_help
- [ ] wesnoth.cancel_action
- [x] wesnoth.end_turn
- [ ] wesnoth.get_mouseover_tile
- [ ] wesnoth.allow_undo
- [ ] wesnoth.replace_schedule
- [ ] wesnoth.get_end_level_data
- [ ] wesnoth.kernel_type
- [ ] wesnoth.package
- [x] wesnoth.synchronize_choices
- [x] wesnoth.format_disjunct_list
- [ ] wesnoth.print
- [x] wesnoth.format_conjunct_list
- [x] wesnoth.format
- [ ] wesnoth.modify_ai
- [ ] wesnoth.allow_end_turn
- [ ] wesnoth.deprecate_api
- [ ] wesnoth.teleport
- [x] wesnoth.micro_ais
- [ ] wesnoth.gamestate_inspector
- [x] wesnoth.confirm
- [x] wesnoth.alert
- [x] wesnoth.delete_ai_component
- [x] wesnoth.special_locations
- [ ] wesnoth.color_adjust
- [x] wesnoth.advance_unit
- [ ] wesnoth.create_weapon
- [x] wesnoth.unsynced
- [x] wesnoth.set_side_variable
- [x] wesnoth.show_message_box
- [x] wesnoth.get_side_variable
- [x] wesnoth.remove_modifications
- [ ] wesnoth.set_end_campaign_text
- [ ] wesnoth.show_lua_console
- [ ] wesnoth.set_end_campaign_credits
- [ ] wesnoth.set_time_of_day
- [ ] wesnoth.log_replay
- [ ] wesnoth.debug_ai
- [ ] wesnoth.end_level
- [x] wesnoth.add_known_unit
- [x] wesnoth.add_widget_definition
- [x] wesnoth.wml_matches_filter
- [ ] wesnoth.deprecated_message

Additional things needing documentation (found out manually or elsehow):
- [ ] wesnoth.package
- [ ] wesnoth.game_events.on_mouse_move

For each of them, we need to document it, or move to a non-user-facing package, or make some other decision.

**Comment by vgaming** [comment]
The list was generated half-automatically using this script:
```bash
cat wesnoth_fields.txt | while read -r line; do grep "$line" wiki-clean.html 1>/dev/null || echo "$line" ; done
```
where file "wesnoth_fields.txt" contains all wesnoth fields that I could find by pressing <TAB> in Lua console, and wiki-clean.html is a cut down version of the wiki page.

**Comment by gfgtdf** [comment]
some general things first: Some function might be documented but don't appear on the wiki overview page i know for exampel for sure that this is the case for `wesnoth.synchronize_choices`. Also i think some functions that are used in the implamentation of wml tags don't need to be documented/shoudl not be used if they offer no advantage over just using the wml tag (wesnoth.wml_actions.tagname { ... }) in particular since we at some point might want to improve them to have a more lua friendly interface and it'd be annoying if we had to worry about compability then, for example at some point i added `wesnoth.redraw` to the 'functions that should no be used becasue it has quite a bad interface in particular it has a completeley redundent boolean prameter. 

now in some detail:
```
wesnoth.show_menu -ask celmin
wesnoth.get_viewing_side -important function must be documented
wesnoth.open_help
wesnoth.cancel_action -does the same as the wml tag, can be documented
wesnoth.end_turnn -does the same as the wml tag, but has a parmaeter that allows specifying whihc side gets the next turn
wesnoth.get_mouseover_tile -clear, should be documented i'd say
wesnoth.allow_undo - has boolean prameter the the correpsonding wml tag doean't offer, so it'd be nice if it was diocumented
wesnoth.replace_schedule  - just an alias for wml_actions.replace_schedule, don't document i'd say
wesnoth.get_end_level_data - hmm not sure, iirc it bascially returns a table if [endlevel] was already called
wesnoth.kernel_type - hmm i actually don't see ow this coudl be usable for umc ?
wesnoth.package - ask celmin
wesnoth.synchronize_choices -is already ducmented
wesnoth.format_disjunct_list -ask celmin
wesnoth.print - global 'print' is luas own function, we just redirect it's ouput, or are you talking about a wesnoth.print here ?
wesnoth.format_conjunct_list -ask celmin
wesnoth.format -important function must be documneted
wesnoth.modify_ai -not sure, this might be even deprecated? mattsc might know
wesnoth.allow_end_turn - has a boolean paramter, doument i'd say
wesnoth.deprecate_api i don't really think this has use for umc, not sure though
wesnoth.teleport - same as actionwml [teleport] but with a more lua firendly api, shoudol be documented
wesnoth.micro_ais -dontknowwhatthisdoes als celmin or mattsc
wesnoth.gamestate_inspector- this is a ui dialog i'd guess ? ask cemin
wesnoth.confirm -same
wesnoth.alert -same
wesnoth.delete_ai_component
wesnoth.special_locations - this is a table that in particular allows you to to lookup the sides starting positions as they are defined on the map data.

-will probably contie commenting later
wesnoth.color_adjust
wesnoth.advance_unit
wesnoth.create_weapon
wesnoth.unsynced
wesnoth.set_side_variable
wesnoth.show_message_box
wesnoth.get_side_variable
wesnoth.remove_modifications
wesnoth.set_end_campaign_text
wesnoth.show_lua_console
wesnoth.set_end_campaign_credits
wesnoth.set_time_of_day
wesnoth.log_replay
wesnoth.debug_ai
wesnoth.end_level
wesnoth.add_known_unit
wesnoth.add_widget_definition
wesnoth.wml_matches_filter
wesnoth.deprecated_message
```

**Comment by CelticMinstrel** [comment]
@gfgtdf Can you please edit your post to make it a list (with asterisks) instead of "code"? That just makes it harder to read.

**Comment by CelticMinstrel** [comment]
As a general preference, I'd say that any function that takes a config as its sole argument, and whose WML tag wrapper does nothing but forward its config argument to the function, should not be documented.

* `wesnoth.show_menu` shows a popup menu at the current mouse location, identical to the right-click menu. The idea behind adding it was to allow a way to fake a submenu for options added with `[set_menu_item]`.
* `wesnoth.kernel_type` is required to conditionally load some things in _core.lua_. It probably wouldn't be of much use in addons, but I'm sure someone will eventually think of a use.
* `wesnoth.package` is (and as far as I know has always been) mainly an internal implementation detail of `wesnoth.require`. Basically, when `require` is called, it first checks if the package is already loaded and stored in `wesnoth.package`; if it is, it just returns it, otherwise it loads it and stores it.
* `wesnoth.format_conjunct_list` and `wesnoth.format_disjunct_list` take in an array and output a translated string of the form "A, B, and C" or "A, B, or C" respectively.
* `wesnoth.modify_ai` is deprecated in favour of the three `*_ai_component` functions.
* `wesnoth.deprecate_api` is primarily intended for internal use but could be useful for someone creating a Lua resource pack, so I'd say document it. The same probably applies to `wesnoth.deprecated_message`, which basically has the same interface as the preprocessor and ActionWML deprecation functions.
* `wesnoth.micro_ais` is a table where users can install additional MicroAI definitions, to be used by the `[micro_ai]` tag. You can look at the existing definitions (in _data/ai/micro_ai/mai_defs/) for details of how this works.
* `wesnoth.gamestate_inspector` shows the gamestate inspector, identical to `[inspect]`.
* `wesnoth.create_weapon` creates a weapon userdata from a config; I believe it's currently used to fake weapons for certain animations, possibly? I'm not sure if there's any other legitimate use for it. You could assign the created weapon to a unit, of course, but you could also assign the config directly. I guess with this you could assign the same weapon to multiple units and changes to both would affect it, but that would be weird and I wouldn't really recommend it. I'd say leave it undocumented unless someone can come up with a good use-case.
* `wesnoth.show_message_box` shows a standard confirm dialog box with one (or possibly two) buttons. It takes three parameters (the title, the message, and the button), and supports several special button names: "ok", "cancel", "close", "ok_cancel", "yes_no", "". The latter actually shows now button but makes the dialog close automatically after a delay; "ok_cancel" and "yes_no" show two buttons. Any other value for the button would show one button with that string. The function `wesnoth.alert` is an alias for this, passing "ok" as the button; similarly, `wesnoth.confirm` passes "yes_no" and returns true or false. These should be documented.
* `wesnoth.show_lua_console` does exactly what it says and should probably be documented.
* `wesnoth.log_replay` is used internally for something or other. I'm not actually entirely sure what the point of it was, so maybe it's better to leave it undocumented for now.
* `wesnoth.debug_ai` is probably already documented somewhere in the AI pages. It basically returns a side's AI config, with the stages and candidate actions exposed as callable functions, and all the data and functions in the `ai` module can also be found under there.
* `wesnoth.wml_matches_filter` is basically `[filter_wml]` - it tests whether a config matches a `[filter_wml]` tag. It's currently used in `[remove_object]` if I recall correctly.
* `wesnoth.print` might be the logic behind `[print]`? I'm not entirely sure on that one, but I do suspect it's poorly named, in which case I'd leave it undocumented for now.

**Comment by CelticMinstrel** [comment]
Other things that may or may not be documented:

* [] cave_map_generator.lua - I'm not sure if this is mature enough for documenting though
* [] functional.lua - Lua equivalents of a number higher-order functions available to WFL; should probably be documented
* [] mapgen_helper.lua - Again, not sure if this is mature enough
* [] on_event.lua - In my opinion this should be replaced with something more general later (in particular, multicast events would render it semi-redundant)

The files _core.lua_ and _package.lua_ are not intended to be required, and most of their contents _is_ documented. The _wml-*.lua_ files are likewise not intended to be required; they define all the WML tags. And finally _feeding.lua_ is the implementation of the feeding ability.

There's also some Lua stuff under _data/ai/lua_ which is not documented; @mattsc says that _ai_helper.lua_ is best left undocumented though, and most of the other stuff is code for specific AIs. The file _stdlib.lua_ is the standard Lua AI engine code; it modifies the `ai` table a bit, and I think the modifications it makes are not documented but probably should be. And the stuff under _data/ai/micro_ais_ is mostly internals of the `[micro_ai]` tag.

**Comment by gfgtdf** [comment]
> cave_map_generator.lua

This needs to be documented as it's the replacement for the deprecated old scenario_generation=cave generator

> mapgen_helper.lua

Hmm even it it should maybe be not used as-is it can still be used as some type of sample implementation, maybe we can tell people to make a copy if it in their addon if tey need it?

> on_event.lua

this is quite handy and should be documented

**Comment by CelticMinstrel** [comment]
Yeah, I thought `on_event` probably was, didn't think the cave generator was though. Anyway, for the cave generator it's very similar to the old one, so maybe it's fine to just note that.

**Comment by gfgtdf** [comment]
cave_map_generator.lua is briefly documented here https://wiki.wesnoth.org/MapGeneratorWML#The_Cave_Generator at the end of tha section.

**Comment by CelticMinstrel** [comment]
More stuff to document (mostly recently added):

* [ ] The wml module (might be partially documented already on the WIP LuaAPI page?)
* [ ] wesnoth.custom_synced_commands
* [ ] wesnoth.invoke_synced_command
* [ ] wesnoth.persistent_tags

I checked, and `wesnoth.debug_ai` is indeed documented [on the wiki](https://wiki.wesnoth.org/LuaAI#Debug_access_to_the_AI_tree), though that documentation is quite sparse. Still, it's only intended for developers as an aid to debugging.

(Most of the AI stuff is actually not linked from LuaWML; `debug_ai` just happened to be one that's in the main `wesnoth` module rather than the `ai` module.)

Speaking about the LuaAPI page that I was working on, at some point I'd like to make that the central point for Lua reference, rather than LuaWML; then the LuaWML page could be dedicated solely to how to include Lua in WML (ie the `[lua]` tag).

**Comment by CelticMinstrel** [comment]
Just noticed that `wesnoth.micro_ais` is already documented [https://wiki.wesnoth.org/Micro_AIs#Custom_Micro_AIs](here), along with a couple of the other MicroAI helper functions.

**Comment by CelticMinstrel** [comment]
Another thing that needs documenting; `wesnoth.get_units` additional parameters.

**Comment by CelticMinstrel** [comment]
In addition to `wesnoth.special_locations`, I have also updated the documentation of the map format to explain how the special locations are indicated.

**Comment by CelticMinstrel** [comment]
I'm also going to post undocumented WML API stuff here that I'm not sure about.

* [ ] `[modify_unit]mode=` should probably be documented.
* [ ] `[item]name=` and `write_name=` are not documented and I'm not sure they should be.
* [ ] `[set_variable]` has several new, undocumented keys
* [ ] `[recall]reassign=` (also `facing=` under `[auto_recall]` but that's only new for 1.15 if I recall correctly)
* [ ] `[add_ai_behaviour]` is mentioned in one place, I think, but never properly documented. It may also be deprecated though.
* [ ] `[unsynced]` doesn't seem to be documented, or at least I couldn't find where it is documented.
* [ ] `[set_global_variable]` and its two cousins... I'm not sure whether or not they are documented, but I couldn't find them via the ActionWML page.
* [ ] `[store_rotate_map_location]`
* [ ] `[proceed_to_next_scenario]` I don't recall seeing documentation for, but I might be mistaken?
* [ ] `[lua]` ConditionWML was recently added but hasn't been documented yet (not sure if it made it into 1.14 though)
* [ ] `[side]turns=` shockingly seems to be missing from the SideWML page? When adding it we should also note that turns=unlimited is valid and does what you'd expect.
* [ ] SUF `name=` is not documented; might be better to leave it that way, though
* [ ] SUF `variation`, `has_variation`
* [ ] SUF `vision_cost`, `movement_cost`
* [ ] SUF `ai_special=guardian`
* [ ] SUF `recall_cost`
* [ ] `[effect]generate_description`
* [ ] `[effect]apply_to=max_experience`
* [ ] `[effect]apply_to=hitpoints`, keys `set` and `set_total`
* [ ] `[effect]apply_to=max_attacks`
* [ ] `[effect]apply_to=fearless` and `healthy`
* [ ] `[effect]apply_to=type`, key `heal_full`
* [ ] `[effect]apply_to=new_animation`, key `id`
* [ ] `[unit]jamming=` and `[jamming_costs]` (the latter also in `[movetype]`)
* [ ] `[unit]flying=` and `[vision_costs]` (movetype overrides)
* [ ] `[generator]` for the Lua cave generator
* [ ] `[scenario]` subtags - `[sound_source]` (documented but not mentioned as valid in `[scenario]`), `[display]`, `[variables]`, `[menu_item]`, `[undo_stack]`, `[color_palette]`, `[color_range]`, a few others
* [ ] `[effect]apply_to=image_mod` can also contain `[color_palette]` and `[color_range]`
* [ ] #2315

Most of these undocumented things were found by perusing the source code. Some were found by noticing them in core WML (thanks to the schema validator), particularly the test scenario.

**Comment by ProditorMagnus** [comment]
Global variables are documented https://wiki.wesnoth.org/PersistenceWML.

**Comment by CelticMinstrel** [comment]
I thought I remembered seeing that somewhere, yeah; but they do probably need to be linked from the main ActionWML page (so does `[micro_ai]` probably).

**Comment by ProditorMagnus** [comment]
From my experience [color_palette] has to be toplevel tag.

**Comment by gfgtdf** [comment]
it also parses them at [scenario] see https://github.com/wesnoth/wesnoth/blob/master/src/play_controller.cpp#L179 , but im actuall unsure whetezhr this really works, that is whether it is also persistent in saveload etc.

**Comment by CelticMinstrel** [comment]
Uh. `[side]turns=` sets the turn limit, does it not?

As for the other scenario tags, other than maybe `[undo_stack]` (and maybe some I didn't mention) I see no reason to disallow them outside of saved games. Even `[undo_stack]` could in theory be used for something interesting.

Regarding `[color_range]` and `[color_palette]`, they are indeed supported in `[scenario]` and in `[effect]apply_to=image_mod`; I don't know whether they fully work, but the test scenario has examples of both uses.

**Comment by gfgtdf** [comment]
> Uh. [side]turns= sets the turn limit, does it not?

 no turns= is a  propert of scenario not of side.

>As for the other scenario tags, other than maybe [undo_stack] (and maybe some I didn't mention) I see no reason to disallow them outside of saved games

Well it forces us to keep compabiltiy for them, and on the other hand they offer no advantages for umc devs sinceeverything they do can also be done with actionwml in prestart events.

**Comment by CelticMinstrel** [comment]
*facepalm* No wonder I couldn't find it, I was looking at the wrong page! Still should mention `turns=unlimited` on ScenarioWML though. (And I'd better make sure I didn't put it in the wrong place in the schema...)

**Comment by CelticMinstrel** [comment]
As for the other scenario tags... `[variables]` will never break compatibility because it's just arbitrary WML content, and the color tags are precedented elsewhere (and parsed by the same code) so they're never going to change; the same applies to `[sound_source]`. I could accept your argument for the other three I explicitly named, though I don't think `[menu_item]` is likely to change much (but who knows).

**Comment by gfgtdf** [comment]
added [unsynced] to the wiki. 

> [variables] will never break compatibility

in fact we (tempararily? not sure actually) broke [variables] during 1.13 since it soemhow clashed with options variables.

**Comment by CelticMinstrel** [comment]
Options variables and saved game variables should in theory be the exact same tag, so there's no reason for them to conflict. In fact, I'd argue that options variables are a reason why we _must not_ drop support for `[variables]` in `[scenario]` (ie outside of SaveWML).

**Comment by gfgtdf** [comment]
every thing that happens after the game is loaded first is basicially the savegame path, in particular expanding variabels from options.

**Comment by ProditorMagnus** [comment]
Entire wml module seems undocumented, nothing is linked from LuaWML page. There is https://wiki.wesnoth.org/LuaWML/Reorganization, but those names are not accurate.

**Comment by gfgtdf** [comment]
> Not Lua, but could use documentation ff31a99.

ye i was still unsure how to do it, currently other values than 0 (which sets it to the 1.12 position and is the main reason it was added) don't work correctly with zoom, so i could eigher say 0 is the only suppted value or call it a 'bug' and say that all integer values are supported

**Comment by ProditorMagnus** [comment]
Event scenario_end https://github.com/wesnoth/wesnoth/commit/341c31a6b902803d7d3792ccebb2fa2b2ba8df7c

**Comment by ProditorMagnus** [comment]
About wesnoth.get_end_level_data https://github.com/wesnoth/wesnoth/commit/ceea75cf0a6baf535c731a7b6f132d4317471909

**Comment by ProditorMagnus** [comment]
WFL has str_upper function.

**Comment by ProditorMagnus** [comment]
Races can have icon - create images/icons/unit-groups, and name your icons race_[insert race id here]_30.png

**Comment by vgaming** [comment]
Probably this issue doesn't help wesnoth anymore.
(Feel free to re-raise if you think otherwise.)

**Comment by ProditorMagnus** [comment]
I will use this one as reference when I find something more.

**Comment by CelticMinstrel** [comment]
I think most of the important things mentioned here have indeed been documented, but there was probably _something_ listed here that was missed.

**Comment by vgaming** [comment]
My reasoning for closing is that the situation has probably diverged considerably. So even if one would want to fix the docs, they probably wouldn't go here first or base the fix on this issue.

The overall approaches that were discussed here could be useful for future though.

**Comment by stevecotton** [comment]
@ProditorMagnus maybe document it on the wiki itself, using a template so that the template's category page becomes the todo list?
