### ISSUE TITLE
xcode travis build cache times out during upload

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#2670]
More than once([[1]](https://travis-ci.org/wesnoth/wesnoth/jobs/353493779#L4488) [[2]](https://travis-ci.org/wesnoth/wesnoth/jobs/353450254#L4489) [[3]](https://travis-ci.org/wesnoth/wesnoth/jobs/353119696)), the xcode build on travis has failed to upload its cache due to exceeding the default timeout of 3 minutes.  This occurs because the ccache max size limit for xcode is 2 GB, rather than the 200 MB limit set for ccache+cmake, which is necessary in order to get xcode's ccache hit rate to 95%+ consistently, which is because the xcode build by default uses the `-g` flag.  Decreasing the ccache max size to 1.5 GB, for example, results in only a ~75% hit rate even for builds where there has no been code change.

While [it is possible](https://docs.travis-ci.com/user/caching/#Setting-the-timeout) to increase the timeout, since there is no actual need for the debugging information on the travis build, I would prefer if the travis xcode job could be set to not use the `-g` flag.  This would then also speed up the xcode job by 1-3 minutes.

**Comment by GregoryLundberg** [comment]
To me, it's most important that the CI tools ensure we can make Release builds.

I do like having a Debug build, or two, in the mix because that can expose some issues. But the probability of that is low. Also, I imagine we have some developers making their own Debug builds, so they're likely to catch problems as well (I, for one, do that for Linux and Windows, occasionally).

So, I would not object to changing the XCode CI run to Release and omitting debugging information.

**Comment by Pentarctagon** [comment]
My understanding is that this is actually the Release build - xcode just uses `-g` by default for it.

**Comment by CelticMinstrel** [comment]
Has anyone brought this to the attention of @hrubymar10?

**Comment by hrubymar10** [comment]
Xcode travis does RELEASE builds

**Comment by CelticMinstrel** [comment]
I think it's reasonable to use `-g` for the actual releases (since you get better crash reports), but maybe it can be set to not use `-g` on Travis? Is that possible?

**Comment by hrubymar10** [comment]
It's because of this setting:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/2218817/37793188-2b6e6c6a-2e0e-11e8-960d-c1b44d889aa8.png">

I can force it by https://github.com/wesnoth/wesnoth/pull/2714

so we can add to travis' script smt like `sed -i -e 's/GCC_GENERATE_DEBUGGING_SYMBOLS = YES;/GCC_GENERATE_DEBUGGING_SYMBOLS = NO;/g'`

**Comment by CelticMinstrel** [comment]
If the idea is to disable it on Travis only, I think you could probably do even better than that with (untested) `xcodebuild GCC_GENERATE_DEBUGGING_SYMBOLS=NO`.

**Comment by hrubymar10** [comment]
Indeed. Your option works @CelticMinstrel . I'll update my PR
