### ISSUE TITLE
wesnothd problems in macOS Wesnoth 1.13.12 package

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#2720]
There are several problems with wesnothd in macOS package. I can reproduce it with 1.13.12 but it may exist since older version

```
The Battle for Wesnoth version 1.13.12
Running on Apple macOS 10.13.4

Game paths
==========

Data dir:        /Users/USER/Do_not_backup/wesnoth_1.13.12/Wesnoth.app/Contents/Resources
User config dir: /Users/USER/Library/Application Support/Wesnoth_1.13
User data dir:   /Users/USER/Library/Application Support/Wesnoth_1.13
Saves dir:       /Users/USER/Library/Application Support/Wesnoth_1.13/saves
Add-ons dir:     /Users/USER/Library/Application Support/Wesnoth_1.13/data/add-ons
Cache dir:       /Users/USER/Library/Application Support/Wesnoth_1.13/cache

Libraries
=========

Boost:             1.60
OpenSSL/libcrypto: 1.0.2j  (runtime 1.0.2j)
Cairo:             1.12.16 (runtime 1.14.6)
Pango:             1.36.3  (runtime 1.40.1)
SDL:               2.0.7   (runtime 2.0.7)
SDL_image:         2.0.2   (runtime 2.0.2)
SDL_mixer:         2.0.2   (runtime 2.0.2)
SDL_ttf:           2.0.14  (runtime 2.0.14)

Features
========

Experimental OpenMP support:    no
JPG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: no
Cocoa notifications back end:   yes
Growl notifications back end:   no
```

## Description of problem
I start Wesnoth and want to host local game. I verified that port 15000/TCP is closed before openning Wesnoth.
```
MacBook-Pro:~ user$ nmap localhost -p 15000

Starting Nmap 7.60 ( https://nmap.org ) at 2018-03-23 16:55 CET
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00023s latency).
Other addresses for localhost (not scanned): ::1

PORT      STATE  SERVICE
15000/tcp closed hydap

Nmap done: 1 IP address (1 host up) scanned in 0.05 seconds
```

I click *Multiplayer* and then *Host networked game*.

Wesnoth successfully spawns wesnothd process and bind port 15000/TCP **but** it ask you about path to `wesnothd` because it can't find it...
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2218817/37840770-4752d01e-2ebe-11e8-99d5-cdd111e52b58.png">

You manually select path to `wesnothd`, click *Select* but the window just closes.

When you exit Wesnoth and try scan port 15000/TCP again:
```
MacBook-Pro:~ user$ nmap localhost -p 15000

Starting Nmap 7.60 ( https://nmap.org ) at 2018-03-23 17:24 CET
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00028s latency).
Other addresses for localhost (not scanned): ::1

PORT      STATE SERVICE
15000/tcp open  hydap

Nmap done: 1 IP address (1 host up) scanned in 0.04 seconds
```

**END**

This is full game log:
```
MacBook-Pro:MacOS user$ ./Wesnoth 
objc[63085]: Class SDLApplication is implemented in both /Users/user/Do_not_backup/wesnoth_1.13.12/Wesnoth.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1109ab280) and /Users/user/Do_not_backup/wesnoth_1.13.12/Wesnoth.app/Contents/MacOS/./Wesnoth (0x10fc68b78). One of the two will be used. Which one is undefined.
Battle for Wesnoth v1.13.12
Started on Fri Mar 23 17:21:14 2018

Automatically found a possible data directory at /Users/USER/Do_not_backup/wesnoth_1.13.12/Wesnoth.app/Contents/Resources
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf

Data directory:               /Users/USER/Do_not_backup/wesnoth_1.13.12/Wesnoth.app/Contents/Resources
User configuration directory: /Users/USER/Library/Application Support/Wesnoth_1.13
User data directory:          /Users/USER/Library/Application Support/Wesnoth_1.13
Cache directory:              /Users/USER/Library/Application Support/Wesnoth_1.13/cache

Setting mode to 1440x878
Checking lua scripts... ok
sh: ./wesnothd: No such file or directory
20180323 17:21:21 warning general: Failed to run server start script
Started wesnothd as a daemon with process id 63095
20180323 17:21:27 warning general: Failed to run server start script
20180323 17:21:27 info server: Server configuration from file: '/Users/user/Library/Application Support/Wesnoth_1.13/lan_server.cfg' read.
20180323 17:21:27 error server: could not make fifo at '/var/run/wesnothd/socket' (No such file or directory)
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >: bind: Address already in use
```

**Comment by GregoryLundberg** [comment]
```
20180323 17:21:27 error server: could not make fifo at '/var/run/wesnothd/socket' (No such file or directory)
```
This is not related to the port-in-use failure but should also be addressed.

From Discord, I learned that there is no directory /var/run/wesnothd

I also have had message about inability to create the named FIFO socket. In my case, the cause was the directory existed but was owned by root and not the user (me) running wesnothd. The solution for me was to chown the directory.

The bug, however, is that the FIFO is not required and we should not be complaining about it if we cannot create or open it.

This, however, is not acceptable for the 'official' wesnothd. There we definitely want to see any errors concerning creating or opening the named FIFO socket because it is required to allow control of the MP server from IRC.

So. what we need is:

* By default, suppress all errors concerning failures creating or opening the named FIFO socket.

* Add a command-line option to issue (the existing) diagnostic messages concerning problems creating or opening the named FIFO socket.

* Consider another command-line option which can specify a different name for the named FIFO socket. (Might be there but I looked and didn't see it.)

**Comment by hrubymar10** [comment]
on macOS, only sudo can create dir in `/var/run`, so Wesnoth will **never** be able to use this location...

`.app` can use sudo privileges but it is really problematic and insecure

**Comment by hrubymar10** [comment]
Another thing:

I tried let one `wesnothd` in `MacOS` (default location) and I copied it also to `Resources` where it seems to be expected by path select. Again it spawns `wesnothd` process from `MacOS` and asks you, if path to `wesnothd` in `Resources` is correct:
![image](https://user-images.githubusercontent.com/2218817/37842242-e5a42558-2ec1-11e8-87cb-faf5f0766392.png)

This screen shows you two processes of Wesnoth (main and wesnothd from MacOS) before I clicked `Select` button

**Comment by CelticMinstrel** [comment]
1. As far as I know, the FIFO isn't supposed to be used at all on the Mac, but even if it is, I'd say it should be placed somewhere in the user data directory.
2. The Mac version of the game is supposed to expect `wesnothd` to be in the same directory as `wesnoth` (i.e. _Wesnoth.app/Contents/MacOS_). If that doesn't work, it's a bug that needs to be fixed asap.

**Comment by hrubymar10** [comment]
```
MacBook-Pro:wesnoth_1.13.12 user$ tree Wesnoth.app -L 3
Wesnoth.app
└── Contents
    ├── Frameworks
    │   ├── Growl.framework
    │   ├── SDL2.framework
    │   ├── SDL2_image.framework
    │   ├── SDL2_mixer.framework
    │   ├── SDL2_ttf.framework
    │   ├── libboost_filesystem-mt.dylib
    │   ├── libboost_iostreams-mt.dylib
    │   ├── libboost_locale-mt.dylib
    │   ├── libboost_program_options-mt.dylib
    │   ├── libboost_random-mt.dylib
    │   ├── libboost_regex-mt.dylib
    │   ├── libboost_system-mt.dylib
    │   ├── libboost_thread-mt.dylib
    │   ├── libcairo.2.dylib
    │   ├── libcrypto.1.0.0.dylib
    │   ├── libffi.6.dylib
    │   ├── libfontconfig.1.dylib
    │   ├── libfreetype.6.dylib
    │   ├── libglib-2.0.0.dylib
    │   ├── libgmodule-2.0.0.dylib
    │   ├── libgobject-2.0.0.dylib
    │   ├── libgraphite2.3.dylib
    │   ├── libgthread-2.0.0.dylib
    │   ├── libharfbuzz.0.dylib
    │   ├── libintl.8.dylib
    │   ├── libpango-1.0.0.dylib
    │   ├── libpangocairo-1.0.0.dylib
    │   ├── libpangoft2-1.0.0.dylib
    │   ├── libpcre.1.dylib
    │   ├── libpixman-1.0.dylib
    │   ├── libpng16.16.dylib
    │   └── libreadline.6.3.dylib
    ├── Info.plist
    ├── MacOS
    │   ├── Wesnoth
    │   └── wesnothd
    ├── PkgInfo
    ├── Resources
    │   ├── English.lproj
    │   ├── Growl\ Registration\ Ticket.growlRegDict
    │   ├── SDLMain.nib
    │   ├── data
    │   ├── fonts
    │   ├── fonts.conf
    │   ├── icon.icns
    │   ├── images
    │   ├── sounds
    │   └── translations
    └── _CodeSignature
        └── CodeResources

16 directories, 36 files
```

It is placed in `Wesnoth.app/Contents/MacOS`

**Comment by GregoryLundberg** [comment]
For most (probably all, but who knows what screwed up distros are out there) sudo is needed for /var/run .. but if Wesnoth gets installed by root, or during initial installation, the installer will already have superuser privileges. It's probably the same on macOS except that the App Store can't handle multiple installs so you'd have to do a non-standard process..

Why does everyone keep thing that just because they don't expect users to do it, it doesn't need to be supported?

Besides, it's not a macOS specific feature. It's an every-platform feature. And leaving an error message does not mean it's an unused/unneeded feature. What it means is you expect your uses to not check and, if they do check, to not care.

Some of us DO check for errors and DO assume that if it was important enough to tell us about it, you expect us to fix it.

So stop complaining about the FIFO, and give the 'official' wesnothd team the tools to know when THEY need to fix it.

**Comment by hrubymar10** [comment]
There is no such thing as installer on macOS. Wesnoth on macOS never gets admin privileges.

**Comment by soliton-** [comment]
You can decide the socket path with the FIFODIR define at compile time.

**Comment by sevu** [comment]
On linux, the (/var)`/run/wesnoth` dir is created by systemd-tmpfiles. I forgot whether this is just done by everyone downstream , or if it is part of the cmake/scons scripts.
For this issue, does FIFODIR =./ work?

1.13.12 has been a while, still relevant?

**Comment by hrubymar10** [comment]
It is probably still reproducible with 1.14.8 (1.14.7).

**Comment by hrubymar10** [comment]
I cannot reproduce it with 1.15.4 .

Closing
