### ISSUE TITLE
Wesnoth blocks desktop effects

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#2823]
If Battle for Wesnoth is running, desktop effects do not work on the Plasma desktop (also known as KDE). It doesn't matter if BfW is full screen, windowed, or even minimized and on another virtual desktop. All effects and animations stop working everywhere until BfW is closed. This seems like a blocker because it effects the whole system, and because it could be an accessibility problem for some people as well: There are effects to magnify the screen and make visual mouse clicks for example.

I'm using openSUSE Tumbleweed Linux, which means I have up-to-the-minute versions of Mesa openGL, the Wayland compositor, KDE5, the Linux kernel etc. I don't know when this started exactly, but it's been this way for a couple weeks.

**Comment by shikadiqueen** [comment]
Upstream considers this a feature and would rather have applications set the correct hint to block compositing like SDL 2 already does, rather than do otherwise. This is not specific to Wesnoth by any means.

If it inconveniences you, you can either add an application-specific rule for Wesnoth (right click on the titlebar → More Actions → Special Application Settings) where Block compositing is set to Force = Yes, or go into the compositor settings and disable the option to allow applications to block compositing.

**Comment by beetlenaut** [comment]
Thanks. It didn't even occur to me that an application would be allowed to do something like that, so I never would have figured it out. Block compositing was actually set to "Do not Affect," but it still allowed me to create a "Force = No" rule, which worked.
