### ISSUE TITLE
error filesystem: Trying to open file with empty name.

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#2825]
Thrown by https://github.com/wesnoth/wesnoth/blob/master/src/filesystem_boost.cpp#L804

When you are using language such as:
* `cs_CZ` - Čeština
* Dansk
* Nederlands
* ...

It seems to be reproducible with every language which has localized main menu `The Battle for Wesnoth` image text:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/2218817/38244852-389d207a-373c-11e8-9012-d2dfffde7d94.png">
<img width="387" alt="image" src="https://user-images.githubusercontent.com/2218817/38244864-41e822d8-373c-11e8-9983-36a87701c354.png">

Problem is that here:
https://github.com/wesnoth/wesnoth/blob/master/src/image.cpp#L497

`filesystem::get_binary_file_location("", "l10n-track")` returns "".
And later here https://github.com/wesnoth/wesnoth/blob/master/src/filesystem_boost.cpp#L804 it causes `error filesystem: Trying to open file with empty name.` error.

I mentioned it first around Wesnoth 1.13.6 and it is reproducible with latest Wesnoth 1.13.13 and 1.15.0

I can reproduce it on macOS. not sure if also on other systems.

**Comment by hrubymar10** [comment]
Update:
`filesystem::get_binary_file_location()` function works for every file (music, terrain, ...) except localized logo text.

It returns `std::string()` here:
https://github.com/wesnoth/wesnoth/blob/master/src/filesystem_boost.cpp#L1243

after non-passing for loop here:
https://github.com/wesnoth/wesnoth/blob/master/src/filesystem_boost.cpp#L1231-L1240

**Comment by gfgtdf** [comment]
if you are are linking into wesnoths source like that it's often better to link to a specific version or commit instead of master because otherwise those lines will be outdated as soon as someone changes those files, for example `https://github.com/wesnoth/wesnoth/blob/1.13.13/src/filesystem_boost.cpp#L1243` (specific  version) or `https://github.com/wesnoth/wesnoth/blob/596f3f1bda5e09b2f2d29ae5d1c4a1a5f635ae5b/src/filesystem_boost.cpp#L1243` (specific commit)

**Comment by hrubymar10** [comment]
**Update:**
We had discussion on Discord and we found these new facts:

* When I manually included both files `l10n-spec` and `l10n-track` from wesnoth's root into package data root (on macOS it is `Resources` folder) then it started working. (Well, not really started working as it worked every time before but now I can't reproduce this error.)
* This could be solution. Regarding to vultraz's message scons does it so `SConstruct:    env.InstallData("datadir", "wesnoth", "l10n-track")`
* CMake also `CMakeLists.txt: install(FILES l10n-track DESTINATION ${CMAKE_INSTALL_DATADIR}/${DATADIRNAME})`


**Problem is:**
```
l10n-spec
l10n-track
```
These two files weren't updated since `November 5 2015 at commit c281b3af085ef6c30f1ea253e6432c6ecefeefd4`.

I believe that these files could be useless now, but they are still included inside project.

**Summarry:**
@shikadiqueen told, that he will dig around these two files more so I will not update Xcode project yet

**Comment by shikadiqueen** [comment]
After digging deeper into the history surrounding this, I found out a few things:

* `/l10n-track` contains a list of fuzzy localized images, used to prevent the game from using them when the originals are modified and the localized versions start to fall behind. A script run "periodically" on the repository (see [ImageLocalization](https://wiki.wesnoth.org/ImageLocalization) on the wiki) would update this file with new information as needed.
* Because the intent here is to prevent obsolete images from behind used by translations, `/l10n-track` is supposed to be included by the `install` targets for CMake and SCons (see the build toolchain changes in commit 18dd3c5871e56a0a21bc503957becb1321846e80) and installed to the data dir (that is to say, the **parent** for `data/`, `fonts/`, etc., which just so happens to coincide with the working dir root in a normal Git clone).
* If `/l10n-track` is missing for any reason, or the files Wesnoth is trying to load are not listed in it, or have a status value other than `fuzzy`, Wesnoth will assume the localized image is usable in its current state (see commit 9c4e55ecf2913f84b1a0b58572723c60252c84c7).
* `/l10n-spec` is the configuration file for the script. The script is not in the repository (yet).
* The script that @caslav-ilic  (the guy who came up with the image localizations mechanism in the first place — see commit 18dd3c5871e56a0a21bc503957becb1321846e80) used to update `/l10n-track` back in the day appears to be <http://websvn.kde.org/*checkout*/trunk/l10n-support/scripts/lbundle-check.py> (possibly a newer version exists since this comes from a KDE SVN repository from before they started migrating their repositories to Git). For some mysterious reason, this fact was excluded from the [ImageLocalization](https://wiki.wesnoth.org/ImageLocalization) page on the wiki [while revising it at one point](https://wiki.wesnoth.org/index.php?title=ImageLocalization&diff=prev&oldid=30158). I had to track down [a forum post](https://forums.wesnoth.org/viewtopic.php?p=349012#p349012) and then look at the page's history from around that time to find this out.
* The latest available version of the script from the KDE SVN repository requires Python 2, which is not ideal for us right now. I have yet to check if a Git repository in the newer KDE forge platform might have a newer version that will work with Python 3, or whether the script is still maintained even or compatible with the format Wesnoth expects from `/l10n-track`.

As I understand things, `/l10n-track` contains lines that are either comments (start with `#`) or image path entries in the following format (whitespace around the first field is stripped by the engine, and while the third field is ignored by the engine, it **is** used by `lbundle-check.py`):

```
<status>      ¦<localized path>¦ <file MD5 for the original unlocalized image> <VCS commit id for the last known change to the original unlocalized image that the localized version is supposed to match>
```

Do note that the only value for `<status>` that Wesnoth cares about is `fuzzy` — any other status values are ignored and the image is assumed up-to-date and usable. On 1.14 you can check `image::localized_file_uptodate()` in `src/image.cpp` to see the code behind this — Wesnoth populates its internal list of fuzzies by reading `/l10n-track` the very first time it needs to load an image from disk and searches for a localized version in the process.

-----------

Considering all this, I feel that there might be some value in **not** dropping `/l10n-track`, ensuring it is included in all official packages where the game expects it to be, adding `lbundle-check.py` to the repository, and making it part of the `pot-update` targets for CMake and SCons. It would then become the release team's responsibility to inform the translators (through the i18n mailing list) of any new fuzzied localized images.

I intend to look into finding a newer version of the script and taking a closer look at the changes it currently wants to make to `/l10n-track` (you can see an example [diff](https://gist.github.com/shikadiqueen/3aee766df42f0fd245368325b7f7ced1) and [console output](https://gist.github.com/shikadiqueen/00749da2f8d15ab461a7f0e401bcc4bc) from a run I did earlier with the SVN version, against master — do note that it will bail out if you try to run it on a Git working tree created using `git worktree`.

Of course, if other people have strong opinions against this plan, then that means less work for me. @Vultraz (release manager), @ivanovic (i18n manager) or @loonycyborg (release technician) perhaps? Do note that it's currently the latter's responsibility to run pot-updates, so he'd be the one in charge of informing the i18n mailing list of new fuzzies.

**Comment by loonycyborg** [comment]
I don't mind it getting added to pot-update target and I can send updates to i18n ml if it's part of pot-update.
