### ISSUE TITLE
Internationalize ‘N×’ in the statistics dialog

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2893]
I just realized that, in the statistics dialog that you can open during a game, the per-unit-type counters are not internationalized.

I believe the corresponding source code line is `src/gui/dialogs/statistics_dialog.cpp:268`:
```
item["label"] = (formatter() << i.second << font::unicode_multiplication_sign).str();
```

They are forced to use the ‘N×’ format (3×, 2×). I would like to be able to switch from N× to ×N in Galician (gl).

![statistics-dialog](https://user-images.githubusercontent.com/705211/38771254-1a8885f6-4020-11e8-802e-856767062389.png)

_In Galician, the × should be in the opposite order (×N) or, if the counted object is always on a specific side of the counter, the × should be between the count number and the counted object (object ×N, N× object)._

**Comment by CelticMinstrel** [comment]
This seems like an edge case to me... I think for English, either order would work equally fine. I'm not actually sure what it's multiplying either...

**Comment by CelticMinstrel** [comment]
Oh, that's just specifying how many of a particular type of unit was involved in a particular type of action, right? For example in your image we're seeing how many of each unit type were recalled in the current scenario.

In that case, I think the best option is to simply remove the multiplication sign altogether, as it's not really needed. Would that be acceptable to you?

**Comment by Ja-MiT** [comment]
I wouldn't say that either order works _equally_ fine in English. They both work, maybe even both work fine, but the current order seems inferior to me. When it reads "2x", it's saying that the action of recalling an Elf  Shaman occurred "two times". This is valid, but not very intuitive, given that the number is listed right next to the unit in question. I think "x2" would be better since the more natural reading has the number modifying the unit--as in "two units"--instead of modifying the action (@Gallaecio is probably assuming this more natural way of reading it). Or perhaps put the quantity before the name to get "2x Elf Shaman" and have a more consistent amount of space between the two pieces (not sure if the image would go before or after the quantity).

Getting rid of the multiplication sign sounds like a good options as well. The dialog used to be that way. It looks like the sign was introduced as part of moving the dialog to GUI2 in 049f06707355fa68e8ee1096c34967864b4186a9. Maybe @Vultraz can explain why it's "2x" instead of "x2"?

**Comment by Gallaecio** [comment]
I don’t think the English string is incorrect. When on its own, or being the value of a label (e.g. for playback speed), in English I have often found N× and had to change its order in the translation into Galician. 

That said, any of the proposed solutions that involve changing the original string work for me (changing the column order or removing the sign). I wonder, however, if keeping the sign and not internationalizing the string could be a problem for other languages.
