### ISSUE TITLE
wesnoth crash if click on preference menu

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#2924]
if preferences files is deleted to wesnoth1.13 folder in mygames folfer then wesnoth crash when click on preference button and tge preference file generated is not complete.  i don't know when this problems appear but i must to signale this.

**Comment by shikadiqueen** [comment]
Can we assume that you are using Windows and 1.14 RC 3? It'd be nice if you included this information in the future.

**Comment by newfrenchy83** [comment]
yes i do. and the problem is more old in 1.13.

**Comment by Wedge009** [comment]
I recognise English might not be a native language, so I understood this to mean:
- Start Wesnoth (otherwise a fresh start with no preference file is just like a clean installation)
- Delete/move/rename preference file while Wesnoth is still running
- Attempt to open Preferences in Wesnoth

Testing on 1.14.0 I didn't have any crash and the in-memory copy of the preferences was saved to the preference file in the normal location.

**Comment by newfrenchy83** [comment]
@Wedge009 no i don't a crash problem in 1.14 and 1.15.

**Comment by Wedge009** [comment]
Thank you.
