### ISSUE TITLE
untranslatable string in new dialogue

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2949]
Btw, these new settings are a splendid idea
![](https://cdn.discordapp.com/attachments/326136523970052098/437750993745084436/Labels.PNG)

It is reachable through this menu:
![](https://cdn.discordapp.com/attachments/326136523970052098/437748297638346754/menu.png)

**Comment by Vultraz** [comment]
That's odd... it's supposed to be `OK`... and I can't find anything setting it to "Okay"...

**Comment by Vultraz** [comment]
Oh. You meant "villages". NEVERMIND xD

**Comment by Wedge009** [comment]
I added Editor label because of the map generation aspect. I couldn't find this problem on pre-defined campaign scenarios but generating a random map for MP allowed me to find it.

Speaking of map generation - I understand scenario 17 of HttT (Sceptre of Fire) is supposed to be randomly generated too, but doesn't appear to have the villages option in the selection.

**Comment by CelticMinstrel** [comment]
That would be because it uses the cave generator, which doesn't generate labels... or something like that.
