### ISSUE TITLE
Help contains dead links

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2963]
There are a few links in the help to the Great River, but no such Topic exists. Or does it only exist in a campaign?

(There is as well an dead link for Castle, but this should just be removed)

**Comment by Vultraz** [comment]
I've tried many times to fix those... never been able to :(

**Comment by sevu** [comment]
Cave (as topic containing different ones) and cave hills link to an non-existent _illuminated_

**Comment by sevu** [comment]
> <italic>text='Deserts'</italic> have a somewhat different composition than small sand pits or beaches, however for gameplay purposes they are identical. See <ref>dst='terrain_sand' text='sand'</ref>.

`terrain_sand_beach` would be a valid destination. How can I find out what the dst would have to be if I want to link to the page in the help which contains all sand terrains?

**Comment by jostephd** [comment]
@sevu There were four separate bugs identified here:

- [x] Dead links to "Great River" (fixed by me)
- [ ] Dead links to "Castle" - is that still a problem? What help page are the links on? How can I find out?
- [x] Broken link from Desert to Sand (fixed by me)
- [ ] Cave broken link to illuminated (outstanding)

Could you open a new issue for the outstanding parts?

**Comment by sevu** [comment]
I checked, they are fixed as well

**Comment by jostephd** [comment]
> I checked, they are fixed as well

So did I. I couldn't check the castle link because you never said where it was, but the cave link is _not_ fixed, see for yourself:

![2019-03-30-161237_432x164_scrot](https://user-images.githubusercontent.com/24784687/55278626-b4382b80-5306-11e9-9dc9-782e6f300baf.png)

That's with master as of today. Note that you need to run `wesnoth --debug` to see it in red. Without `--debug` the text appears as a non-link (white font).

**Comment by sevu** [comment]
> That's with master as of today. Note that you need to run wesnoth --debug to see it in red. Without --debug the text appears as a non-link (white font).

That explains things… I'll check about it again.

**Comment by sevu** [comment]
Nice list.
The link to the castle in gamplay -> recruiting is corrcet
terrain_illuminated_cave I changed.
About the loyal trait … works for me with and without debug mode as link

The editor ones … probably they are just not generated because the help pages have been deactivated, with a #define because they contain only TODO comments

**Comment by stevecotton** [comment]
I see the same problems as @jostephd for the loyal trait - without `--debug`, that topic seems to be hidden. This happens even if I recall a loyal unit - I can click on the traits in the sidebar, for which `intelligent` opens that trait's help page, but `loyal` opens the help at the top-level.

This is close to a blocker for #4455 , where I'm adding additional documentation that should link to the loyal trait.

Testing on 1.15.4+dev (67dfb4f23 + local changes),

**Comment by stevecotton** [comment]
The loyal trait not showing up is bug #1935, which has been closed with the known issue of it only working in debug mode. I feel this is a blocker for #4455, but don't want to investigate a new (to me) area of the code to solve it. Alternatives from #4455's perspective would be careful wording (or just cut & pasting) to describe the trait without linking to its dedicated topic.

@sigurdfdragon, did you investigate other solutions to that bug and find that they were too much effort for the task at hand?

**Comment by stevecotton** [comment]
The loyal trait has been fixed in #5123. That leaves the editor help, which will be changed by the editor changes that are roadmapped for 1.15.11. I think we can close this ticket now, just adding a note to #2964 to check for dead links.

**Comment by sigurdfdragon** [comment]
@stevecotton No, didn't investigate any other solutions.
