### ISSUE TITLE
Fullscreen toggle on fresh 1.14 install left window bounds out of view

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2967]
The first time I switched off fullscreen in my new 1.14 build, the window boundaries (titlebar, etc) remained outside the view area. Resizing to a lower resolution and maximizing restored the correct behavior when toggling fullscreen.

Need others to confirm.

**Comment by jostephd** [comment]
I see _an_ issue but I'm not sure whether it's what you're seeing:

1. rm -rf foo
2. ./wesnoth --userconfig-dir=foo
3. Ctrl+F
4. Alt+F4
5. ./wesnoth --userconfig-dir=foo
6. The window size is 1280x720 and position is top left corner. Unmaximize the window. The window is now the same size, at the center of the screen, and shows the 1280x720 top-left pixels of what a maximized or fullscreen wesnoth would show. Pressing Ctrl+F twice corrects this.

**Comment by Wedge009** [comment]
I don't know if this is still an issue. I followed the steps that josteph wrote back in 2018 and at step 6 I have the window maximised (as opposed to windowed - I think this is because the window resolution was still at maximum after toggling full screen) but obviously not out of bounds. Tested on 1.14.9+dev.

**Comment by Wedge009** [comment]
No further feedback. Re-open if it's still an issue.
