### ISSUE TITLE
animations during prestart events block the game

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2970]
this report is a bit of a guess. What i observed in 1.14.0 windows 'release' is that the scenario "Hereoes: The Iron Bulwark" blocks the game during the loadingscreeen, so that closing the application is the only option the user has, from loooking at the code my suspect is the [animate_unit] in the prestart event. from the forum thread of that addon it seems like peole succesfully played this campaign not too long ago so this could be a very recent regression in the wesnoth engine.

**Comment by Vultraz** [comment]
Can you confirm if it is indeed the `[animate_unit]` block?

**Comment by gfgtdf** [comment]
ye justtested, if i remove this lines 
```

	[animate_unit]
		[filter]
			id={ID_STRING}
		[/filter]
		flag=recruited
	[/animate_unit]
```

it works

**Comment by Vultraz** [comment]
I'm not sure why you would want this in prestart anyway, though?

**Comment by CelticMinstrel** [comment]
The `animator:run()` call should probably be made to raise an error if called from prestart or earlier, as it happens before the map is rendered if I understand correctly.

**Comment by gfgtdf** [comment]
Because it comes from a macro that can be used in both Prestart and normal events

**Comment by gfgtdf** [comment]
[animate_unit] should basically to nothing during Prestart, (this applies to [delay] well)

**Comment by CelticMinstrel** [comment]
Well, I still think `animator:run()` should raise an error, but of course `[animate_unit]` (and other WML tags) could call it in a protected context and just return if it errors.

**Comment by gfgtdf** [comment]
ok i just tested that this effects 1.13.10 aswell so it' not a that recent regression in our code, the author of "heroes" probably just uploaded a completely untested version. 

This is still a bug of course, fixing [animate_unit] to do nothing in case of a prestart event would be rather easy (`if wesnoth.current_event_conext.name = "prestart" then return end` in the easiest case) but i wonder whether this effects other actions aswell, note that things like for example `[recall], [unstore_unit], [harm_unit]` all can invoke animations and do this by default.

**Comment by CelticMinstrel** [comment]
Indeed, that's why I said it should be fixed at the Lua API / WML API level. My suspicion though is that this won't affect tags implemented in C++ (so, `[unit]` and `[recall]` are probably safe). Checking the current event context is probably not a sufficient fix, as I imagine you could still produce the hang by calling `animator:run()` from an `onload` event or a global `[lua]` tag. (Admittedly this would be a much less common situation, but we should still guard against it.)

**Comment by gfgtdf** [comment]
hmm ye i tested with both [recall] and [unstore_unit] and didn't get problems, i have no idea why that is though, from what i see they use exacty the same unit_animator class in the same way as animator:run.

**Comment by CelticMinstrel** [comment]
Does `[unstore_unit]` actually do animations? It's implemented in Lua, and uses `wesnoth.put_unit` if I recall correctly. The tags I'd be worried about are mainly `[kill]` and `[heal_unit]`... possibly also `[harm_unit]`, not sure. I think `[recall]` uses the wrapper function for the specific animation rather than directly creating an animator, right? Maybe that has some built-in checks that animations can be done at this time?

**Comment by gfgtdf** [comment]
Unstore_unit does animations to if the unit advances, (if it has enough XP)
