### ISSUE TITLE
Horizontal scrollbar in MP lobby with recommended resolution

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2995]
Wesnoth started with -r 1024x768 -w, using size suggested from https://wesnoth.org/ system requirements.

Then lobby has horizontal scrollbar https://i.imgur.com/ovIGDsY.png.
![image](https://user-images.githubusercontent.com/7848963/39540403-3af4ad68-4e4b-11e8-8032-0666e45f32f5.png)

**Comment by ProditorMagnus** [comment]
One cause of this seems to be long game title: https://i.imgur.com/SijKAGB.png vs https://i.imgur.com/HaoUT2x.png.

**Comment by Wedge009** [comment]
Many places where there are longer-elements-than-expected produce horizontal scroll bars where they perhaps shouldn't be present, like #1665.

**Comment by Wedge009** [comment]
I know things have improved at least a little during 1.15.x and testing specifically against 1024x768 on 1.15.17+dev (1.16 beta) this is not an issue any more. I checked against German too, since I know that often has longer strings than the source English texts, as well as couple of other languages.

Of course, if this is still an issue for anyone, go ahead and re-open.
