### ISSUE TITLE
[1.14] Small typo in french

### ISSUE THREAD

**Issue by FractalWire** [wesnoth/wesnoth#3007]
In the main menu when playing :

"Quitter pour l'écran d'acceuil" -> "Quitter pour l'écran d'accueil"

Not sure where to report this.

**Comment by sevu** [comment]
To the French Translation team:
https://wiki.wesnoth.org/WesnothTranslations
https://wiki.wesnoth.org/FrenchTranslation

That said, I don't know if the mailing list mentioned in the first link does still exist, but there _is_ someone working on the French translation. In case the mailing list doesn't exist anymore, please let them know that they have to update the information.
(mentioning this because I remember someone complaining about it)

**Comment by sevu** [comment]
Closings, as it is a translation issue.
