### ISSUE TITLE
turns must be limited in time.

### ISSUE THREAD

**Issue by brigazvi** [wesnoth/wesnoth#3053]
There is no rhythm to the game.

**Comment by sevu** [comment]
I'm afraid I don't understand.
What Rhythm you miss? And Why? What has it to do with the time limit of turns?

**Comment by brigazvi** [comment]
I hope I can explain. (My English is not good)
The experience of the game is impaired because the player is not stressed. He can make decisions for two hours. Limiting the turns time can help the player dive into the experience of the game. That's what I mean when I say "rhythm."

**Comment by sevu** [comment]
For multiplayer it is possible to set a _chess timer_ when creating the game. For the timer exist different options, by default a player has several minutes, but you may want to adjust this value on smaller maps.
![timer](https://user-images.githubusercontent.com/21158813/39706909-1bc68ac6-5213-11e8-9219-209f0233cb82.png)

**Comment by brigazvi** [comment]
Why just for a multiplayer?

**Comment by brigazvi** [comment]
Why is not this a default?

**Comment by Ja-MiT** [comment]
The time limit exists for multiplayer so that the other players are not left waiting for hours between turns. There is no limit for single-player because the computer does not mind waiting.

The game was designed as a turn-based strategy game, where the player can enjoy figuring out the best thing to do. If the player enjoys taking two hours per turn, great. If the player enjoys playing faster to better follow the story, (maybe select a lower difficulty and) great. If the player prefers a faster pace but ends up playing slow... I suppose a single-player timer could help, but I would not like seeing that become the default. Not everyone plays a game because they want to become stressed (in fact, many play in order to reduce stress). For those that do, maybe a real-time strategy game would be more suitable?

**Comment by brigazvi** [comment]
I think that even stressed people who play to relax, want to dive into the game. A moderate time limit can add to the experience.
I think that real-time strategy games can not be an alternative, because they have almost no thinking.

**Comment by CelticMinstrel** [comment]
I mean, if someone wants the "chess timer" in single-player, I see no reason not to make that possible. I don't imagine it would be terribly hard. Low priority though.

**Comment by Ja-MiT** [comment]
My point is that those who want to dive into the game in the manner you like are free to do so. (There is no minimum time between turns. Set an external timer if you need to.) Those that prefer to focus on the strategy elements are free to do so. I see no need to force one way of playing on the other group.

I'm not saying that your way of playing is wrong or bad, only that it is not universal. Hence, the reason why the timer is not currently used in single-player. (That is the question you asked, no?)

My view is similar to CelticMinstrel's: if a timer can be added without too much effort and maintenance, it could be a nifty _option_ (and since there is a multiplayer timer, it might be easy). However, it's far enough from the focus of the game that I do not see a compelling reason to make a single-player timer a priority.

**Comment by brigazvi** [comment]
The argument about the possibility of an external timer is not related here. It is also possible for everyone to draw their soldiers and their progress on a piece of paper and thus we will not force any player to play in a way that he does not want to play with.
We try to create an experience, and time constraints add to it.
In my opinion.

**Comment by Ja-MiT** [comment]
Huh?

**Comment by gfgtdf** [comment]
> The time limit exists for multiplayer 

note that in 1.14 you can actually start all sp campaign fom the multiplayer menu, so if you want you can use that play sp campaigns with a timer (multiplayer -> local game -> sp campaigns).

**Comment by Ja-MiT** [comment]
After thinking about this some more, @brigazvi, I guess you would take about the same amount of time to draw the game's progress as you would to set up a timer? (Otherwise, I still totally fail to see your point.) If so, either you are incredibly fast with a pen or I withdraw that suggestion. I had assumed that the typical player would be able to set up a timer in under a minute, probably a few taps on a phone lying within arm's reach. Sorry, I should not have assumed that the task would be trivial for every player. It was not my intent to suggest an onerous course of action, certainly not one as labor-intensive as I would find drawing the game's progress to be.
