### ISSUE TITLE
The South Guard - Endings of both choices lack a victory message

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3058]
Both last scenarios end very...lackluster. Like. You fulfill the scenario objective and bam, would you like to save the replay? No 'Victory'. Just...cut. It's very different from every other campaign ending and it's very unsatisfying...

**Comment by sevu** [comment]
Why is it unsatisfying?
I don't see it as a problem that you instead of linger mode have a epilogue.
I don't see a reasons to skip linger mode either though.
Saving a replay should probably be enabled.

Is TSG differently handled than other scenarios which are followed by an story scenario? Should probably changed then.

**Comment by Konrad22** [comment]
UtbS is the first example that comes to my mind. You defeat the endboss, they talk a few sentences and then comes the story scenario.
Next up is AtotB. Same as UtbS.
AOI: They talk a bit, but there is no story scenario afterwards.
DiD: Same as AOI.
SotA: Same as UtbS.
DW: Same as UtbS.

So yeah, after checking it, TSG is handled differently than (at least three) other scenarios of it's kind.

**Comment by Konrad22** [comment]
I forgot NR. So let's say five other scenarios.

**Comment by sevu** [comment]
I enabled linger mode, please reopen if it needs new text.

**Comment by Konrad22** [comment]
I think that it is okay. :)
