### ISSUE TITLE
Time of Day Schedule Help only displays the lawful bonus

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3064]
Considering wesnoth has lawful, chaotic, neutral and liminal units...it seems incomplete.
![dawn](https://user-images.githubusercontent.com/39015360/39834752-39ca796c-53ce-11e8-9846-2dcea1a8352f.png)
![night](https://user-images.githubusercontent.com/39015360/39834753-39ed0f68-53ce-11e8-81fe-86667862506a.png)
![schedule](https://user-images.githubusercontent.com/39015360/39834754-3a0a8cdc-53ce-11e8-9cf8-531d8b60d6dc.png)

**Comment by Wedge009** [comment]
Thanks for that. I thought I could try adding the other type bonuses but it turns out the `time_of_day` struct only defines `lawful_bonus`. Looking even further, it looks like the configuration files only use `lawful_bonus` as well - my guess is that everything is defined around `lawful_bonus`: chaotic is just the inverse of `lawful_bonus`, neutral is always 0...  though I don't know how liminal bonuses are defined.

Anyway, the point is that adding the other bonus types turns out to be non-trivial, at least from what I can see.

**Comment by jostephd** [comment]
I think it's basically these two:

https://github.com/wesnoth/wesnoth/blob/b4f09d13534d4d7698bd548fd013baa5dc0784fe/src/actions/attack.cpp#L1787-L1802
https://github.com/wesnoth/wesnoth/blob/b4f09d13534d4d7698bd548fd013baa5dc0784fe/src/tod_manager.cpp#L55-L59

I suppose we could at least add explicit lines for chaotic, neutral, and even liminal (the time of day schedule itself is scenario-dependent, so there's no problem with showing scenario-dependent bonus values), even if the first two are technically redundant. This is a game, not a compression algorithm :stuck_out_tongue:

**Comment by Wedge009** [comment]
Interesting calculation for liminal bonus... and it's still dependent on `lawful_bonus` although I suppose that's the only way to maintain backwards compatibility with existing unit definitions.

What do you mean by adding explicit lines? As in, where? I was trying to do something like this in `help_impl.cpp` and that's when I realised we only ever have `lawful_bonus` defined.

**Comment by jostephd** [comment]
Something like

```
print "Lawful bonus:", lawful_bonus
print "Chaotic bonus:", -lawful_bonus
print "Netural bonus:", 0
```

It would be nice for the help to re-use use the logic in generic_combat_modifier, but honestly, it's sufficiently unlikely to change that we could just duplicate it, if re-use isn't easy to achieve. But maybe we do need to do re-use to compute the liminal bonus? :thinking:

**Comment by Wedge009** [comment]
For my PRs:
- I removed the Lawful Bonus from the root page because if I was to list the bonuses for all alignments on that root page I think it would make the individual time-of-day sub-pages redundant.
- I tried to make things consistent between master and 1.14. That meant marking the 'Time of Day Schedule' and bonus strings for translation and removing the string freeze hacks in 1.14. I don't know if I need to explicitly declare the text-domain, though - does it go to `wesnoth-help` by default?
- I re-used `generic_combat_modifier()` even though it might not seem necessary: 'bring the pain forward' - someone may want to change the bonuses some day and then find the Help saying something different to their bonus change.
- I know the lines get quite long, especially in master with the additional `max_liminal_bonus` parameter, but I find it's easier to read the output keeping it all on one line. Personally I prefer longer lines vs line breaks, but Wesnoth code appears to use the convention of line breaks.
- I considered separating the colon from the `Lawful Bonus:` string but then realised not all translators might want to use a colon for their punctuation (and there's precedent of other strings like 'xxxx:').
- Perhaps Liminal Bonus should be excluded from 1.14?

**Comment by jostephd** [comment]
> I removed the Lawful Bonus from the root page because if I was to list the bonuses for all alignments on that root page I think it would make the individual time-of-day sub-pages redundant.

Sorry, but I don't think that's a good idea. DiD S7:

![2019-10-22-055030_357x193_scrot](https://user-images.githubusercontent.com/24784687/67261373-e4f0d580-f48f-11e9-8b75-46f544856d42.png)
![2019-10-22-055040_353x238_scrot](https://user-images.githubusercontent.com/24784687/67261375-e6220280-f48f-11e9-8d38-2ffdb75b9b0f.png)

Without the bonuses on the root page, there's _no_ way, I believe, to know what the time of day bonus at future turns will be. (The tod_stats report tooltip doesn't have that information.) That's not particular to that scenario, it's true for any custom tod schedule, or even a standard tod schedule the player hasn't seen before.

> I tried to make things consistent between master and 1.14. That meant marking the 'Time of Day Schedule' and bonus strings for translation and removing the string freeze hacks in 1.14. I don't know if I need to explicitly declare the text-domain, though - does it go to `wesnoth-help` by default?

No:

https://github.com/wesnoth/wesnoth/blob/4ceabf1458a7efc96a8e68ebb8a00ffd0b14240d/src/gettext.hpp#L23-L28

> I re-used `generic_combat_modifier()` even though it might not seem necessary: 'bring the pain forward' - someone may want to change the bonuses some day and then find the Help saying something different to their bonus change.

:+1: 

> Perhaps Liminal Bonus should be excluded from 1.14?

Why?

**Comment by Wedge009** [comment]
I don't remember DiD having variable ToD bonuses. But anyway, does it make sense to just leave the 'lawful bonus' on the root page? Doesn't this information still get shown on the sub-pages (I'll check in a moment).

I'll add the text-domain then.

I thought there aren't any liminal units in 1.14 (couldn't remember if Dunefolk are in there or not) but if there are liminal units then fine, it can stay as-is.

**Comment by jostephd** [comment]
> But anyway, does it make sense to just leave the 'lawful bonus' on the root page?

I think it does make sense to have an overview on the root page, but we can tweak the presentation to treat lawful/chaotic more symmetrically.

> I thought there aren't any liminal units in 1.14 (couldn't remember if Dunefolk are in there or not) but if there are liminal units then fine, it can stay as-is.

The `liminal` alignment is [documented](https://github.com/wesnoth/wesnoth/blob/c7e84e1d494d9d6a9b83f802cb4ae09241236a55/data/core/help.cfg#L401) in 1.14 and might be in use by UMC even if it's not used by core. 1.14 has dunefolk and even 1.12 has khalifate.

**Comment by Wedge009** [comment]
I confirm even in the case of DiD S7, the sub-pages (from my PR) give the same information as the root page, but with all alignments instead of just lawful.

So my question on what to do for the root page still stands. Leave it as it currently is, with just the Lawful Bonus on its own (not even any description) or try to add other alignments in, even if it makes the sub-pages effectively redundant?

**Comment by jostephd** [comment]
By the way, what do you think of color-coding the bonus values? Something like this should do it:

```
int bonus = ...;
foo << font::span_color(game_config::red_to_green(50 + bonus)) << bonus << naps;
```

(or `50 + 2*bonus` depending on how we feel)

**Comment by jostephd** [comment]
> Leave it as it currently is, with just the Lawful Bonus on its own (not even any description) or try to add other alignments in, even if it makes the sub-pages effectively redundant?

Either of these would be fine by me. Just make sure the page is accessible not only to developers but also to casual users who see it for the first time, I suppose.

**Comment by Wedge009** [comment]
I'll go with lawful / neutral / chaotic / liminal notation, then, but without any description - leave that for the sub-pages.

I'll also give colouring a try.

**Comment by jostephd** [comment]
Thanks :D

**Comment by jostephd** [comment]
Just remembered that the four alignments also have icons representing them - used in unit_preview_pane, for example - we might be able to use these in the "condensed" representation.

**Comment by Wedge009** [comment]
I don't see that, in either 1.14 or master. Where is it?

I'm also realising that the time-of-day bonus colouring is inconsistent in between the time-of-day image tool-tip, and the unit description in the side-bar, just like the inconsistent defence percentage colouring we fixed recently. I'm not dealing with that for now.

**Comment by Wedge009** [comment]
I've added the text domain and colouring. I recognise it's probably not what you wanted but I kept it consistent with the existing time-of-day bonus colouring in the side-bar. Even I wouldn't have chosen those colours, I would prefer to use the time-of-day bonus colouring for the individual unit.

As for the alignment icons - if you can let me know how to use them I can try to add it to the PRs otherwise I think they're ready for further review and/or testing.

**Comment by jostephd** [comment]
> I don't see that, in either 1.14 or master. Where is it?

unit_preview_pane is used in the recruit dialog, recall dialog, attack enemy dialog, and a few other places. In the recruit dialog, for example, lawful units have this sun icon:

![2019-10-22-075308_165x54_scrot](https://user-images.githubusercontent.com/24784687/67267019-01493e00-f4a1-11e9-8e90-71e11af18839.png)

(Yes, this really is the recruit dialog, in the test scenario one can recruit White Mages.)

**Comment by jostephd** [comment]
> I've added the text domain and colouring. I recognise it's probably not what you wanted but I kept it consistent with the existing time-of-day bonus colouring in the side-bar. Even I wouldn't have chosen those colours, I would prefer to use the time-of-day bonus colouring for the individual unit.

No worries about my suggestion. What's the coloring you prefer, the one used by the unit_alignment report (in the sidebar) and by the damage-per-hit values of the unit_weapons report? I agree, that one would be nice. (I think the green hue it uses it is far more bright than the orange hue it uses, but that's a separate issue.)

> As for the alignment icons - if you can let me know how to use them I can try to add it to the PRs otherwise I think they're ready for further review and/or testing.

First of all, do you think the page would look better with the alignment icons?

If you do, then have the help pages include the images with text next to them. (I think the Orbs page in the Gameplay section is a good example?) The images are in images/icons/alignments/ (I found that by reading unit_preview_pane.cpp). Note the UPP uses small icons but the directory contains larger versions of the icons as well, which may be useful here.

**Comment by Wedge009** [comment]
Yes, I prefer the softer colours used for in the unit report in the side-bar. But I stuck with what the time-of-day tool-tip used because of the precedent in #1951.

I actually think the smaller icons are fine. I've added them now so I think it's ready for (hopefully) final review.

**Comment by Wedge009** [comment]
Whoops, didn't intend to 'close and comment'. Too used to Windows convention of having the 'OK' button on the left.
