### ISSUE TITLE
Instructable ai is doing badly with the combination of 'defensive' and 'protect side' 

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3066]
I instructed Helicrom to be defensive and focus on protecting me. And I really don't think he is doing a good job at following those orders.
I'm not sure if this means:
a) The ai isn't well implemented in that scenario.
b) The ai in general has trouble following instructions.
c) The ai is somehow doing his job but I'm completly missing how it has anything to do with my instructions.
[Liberty-Glory replay.gz](https://github.com/wesnoth/wesnoth/files/1989824/Liberty-Glory.replay.gz)
[Liberty-Glory-Auto-Save8.gz](https://github.com/wesnoth/wesnoth/files/1989825/Liberty-Glory-Auto-Save8.gz) (so you can check the my instructions for him)

**Comment by CelticMinstrel** [comment]
Assigning to mattsc since it's AI-related, but someone else is welcome to work on it if they want to. I'm guessing this is using the core macro which allows you to right-click allied units and give commands?

**Comment by Konrad22** [comment]
Exactly.

**Comment by mattsc** [comment]
Well, the answer is sort of your option c), but it is mostly that the AI is simply not very good at this sort of thing.  Also the two instructions you issued work a bit against each other.  Let me explain in a bit more detail:

Telling the AI to be defensive sets `aggression=0.1` and `caution=1`  That means the AI becomes rather careful.  You can check out [AiWML on the wiki](https://wiki.wesnoth.org/AiWML) for detailed explanations of what that does.

Focus on protecting the unit is done in the sense of `[goal]protect_unit=` (same wiki page as above), which is set to "protect" any unit of the player's side. However, pay attention to the part that states: "Note that the AI will not station any units around the protected locations/units. It will only send units toward enemy units that come within protect_radius of them."

Thus, the AI does what it is supposed to do, it is just not very good at this sort of behavior.  [I have actually argued before that it might make sense to remove these instructions, because they confuse players, but they do have some effect, so ...]

We can keep this open as a feature request (@CelticMinstrel added the enhancement label already), but it is rather unlikely that this will be implemented anytime soon.  This kind of AI behavior (the protecting, I mean) is _really_ hard to do well for an AI (any AI).

**Comment by Konrad22** [comment]
@mattsc Thanks for that explanation. This might also actually help me to issue better commands to my allied ais. ^^

**Comment by mattsc** [comment]
After discussing this several time since before this issue was posted, we finally decided to deprecate the AI Controller and remove it from mainline scenarios.  So that takes care of this issue as well, even if in the most drastic way possible (the main reasons for the decision were not this issue).  See also #3668.
