### ISSUE TITLE
Possible typo in intro text of Northern Rebirth? (Sc1)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3067]
Sixth intro text, last sentence/few words.
'...their utter subjugation could not be averted **for ever**.'
Seventh intro text (same)
'...of Dwarven Doors - **for ever**.'

I really believe it should be '**forever**', but as english is not my native language, I can't say for sure if this is really wrong, even though it fills me with  a lot of doubt. So..yeah. You guys decide.

**Comment by CelticMinstrel** [comment]
I think technically both could be seen as correct, but "forever" feels better to me as well.

**Comment by Wedge009** [comment]
In my experience American English favours forever while British English accepts either forever or for ever. There may be very subtle differences between the two, but I think most nuances have been lost to history. Since English is not your native language, I suspect you've picked up English from the Internet of which the English-speaking part is dominated by American influence and culture, which may be why for ever doesn't look 'right' to you.

It is, however, fine and unless the campaign author wants to make a statement on the issue I see no reason to keep this open. Thanks for the question, though, and if you're really concerned about it feel free to re-open.

**Comment by Konrad22** [comment]
Thanks for you answer, that's all I have to say. ^^
