### ISSUE TITLE
UtBS - the great tree in scenario one is now a Grassland (Flat) hex

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3075]
It does not make sense and I believe that this is just a simple mistake.

**Comment by sevu** [comment]
In 1.14.0 or 1.14.1? There was a change.

**Comment by Konrad22** [comment]
1.14.1
[UtBS-The Morning After Turn 1.gz](https://github.com/wesnoth/wesnoth/files/1991539/UtBS-The.Morning.After.Turn.1.gz)

**Comment by sevu** [comment]
Was actually done as you wished, though it has been changed to the way you see, and was discussed here:
https://github.com/wesnoth/wesnoth/pull/2976#issuecomment-385193548

**Comment by CelticMinstrel** [comment]
Could be changed in master, though. Then again does it really make sense for a smashed tree to give forest defence?

**Comment by Konrad22** [comment]
How about rubble defence instead? (That's the way it was.)

**Comment by sevu** [comment]
Advantages for Changing: 
* would have an help entry
* forest defence (like for `^Fetd`) - in this case only for aesthetic reasons

Disadvantages:
* load screen dialogue can't preview the map due to custom terrain

> How about rubble defence [...]

Surprisingly I can see no difference between with and without, can anyone? Going to commit this later.
![comparison](https://user-images.githubusercontent.com/21158813/39921389-feac1612-551a-11e8-9252-4fff8159f7aa.png)
