### ISSUE TITLE
NR - Infested Caves, unlogical dialogue

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3086]
And when Hamel died, Tallin said: 'Tallin, we have just received the news that the dwarvish Lord Hamel has just been slain. We are too late!' (and then he answers himself)
Please tell me, how did they receive that news while they are being sieged by hordes of undead? xD They didn't even know yet who Hamel is.

**Comment by sevu** [comment]
Please report different things as separate issues, even when they are in the same scenario, because different persons might want to work on it.

Would you have an suggestion how to change the prose? It does sound OK to me, but I never played NR. Eventually one could unshroud the area where the Dwarvish Lord died.

**Comment by Konrad22** [comment]
Has been solved quite some time ago.
