### ISSUE TITLE
NR - Infested Caves (Nightmare) allied AI will be defeated at about 2/3 of turns

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3090]
[NR-Infested Caves Turn 32.gz](https://github.com/wesnoth/wesnoth/files/1996092/NR-Infested.Caves.Turn.32.gz)
Looking at the replay I'd say the dwarves were defeated because they recruited scouts and thunderers and guardsman. Maybe also because their guards are stalwarts. All of those units are very ineffective against undead, who are the primary enemies in this whole scenario.
And losing like this...it seems undeserved. :/ (If you can point out mistakes I made or ways I could have played better, please do! Maybe I didn't lose because of the ai, but because I didn't play well enough.)

**Comment by Konrad22** [comment]
To be honest, the current setup tells the ai to roll over and die when he is attacked by undead. ._.
Allowing only Dwarvish Fighters would go a long way to keep this ai alive and useful (instead of a more limiting factor than the turn limit).

**Comment by sevu** [comment]
There are more ways to boost the AI. Going solo fighters would be lame.

Especially wrong about the recruitment & recruitment pattern combination is that it will never recruit scouts, because they are not covered by the pattern.

The culprit for the issue seems to be that in 1.12 dwarves had 14 villages, while they have now 4.

**Comment by CelticMinstrel** [comment]
I think there might be a facility to recruit scouts independent of the main recruiting algorithm? Something to do with the `villages_per_scout` aspect?

**Comment by Konrad22** [comment]
I've changed the title because I played this scenario again (with a bit more gold, hoping that I could break through the undead...as if). 
[NR-Infested Caves Turn 21.gz](https://github.com/wesnoth/wesnoth/files/1997804/NR-Infested.Caves.Turn.21.gz)
I didn't finish it this time, because just looking at the situation it's obvious that the dwarves will die soon. The can only survive by being very lucky.
And I can't reach them in time, no matter what I do. So yeah. The ai will lose against the undead, even with pretty much optimal conditions (black skeleton leader dead, only a small squad of undead). Considering the recruitment pattern, the small income and the terrain close to the dwarvish hideout (mostly flat, almost no cave): The undead will probably rip the dwarves apart 9/10. It's not really a matter of 'if' but more like 'when'.

**Comment by sevu** [comment]
Hope to make you happy.
One problem was that the troll leader in the east died, and then all the skeletons are against you and the dwarves. With the changes I did focus on keeping him alive.


Can you download both the scenario and map file from GitHub and replace them in 1.14.1?

Things which I have in mind if the Troll part needs a slight quirk:
- giving the troll leader a third guard (haven't found a position yet)
- let the guards return to their original position instead of eventually joining a counter-attack
- increasing distance between the the eastern troll side and the south-eastern skeleton side, e.g lengthening the cave wall or moving the whole south-eastern caste 1-2 hexes down

Nevertheless, there is a good chance that one of the three - the eastern troll and the skeletons next to him - will die between round 10 and 20.

What is not properly tested is how much the dwarves need to be strengthened in case the Troll leader died. Or in case the player is till round 40 busy with the western trolls.
I added two events to take care of strengthening the dwarves - when the troll dies or someone comes comes close to the dwarvish keep. The values how much gold they get are fictional. Have a look at a7e098f for details.

(You can see the recent commits if you click at the 72000 commits part, but change the branch to 1.14 before or after)

There are also at least two different approaches to play that scenario - in the bases of both western trolls is a way to open a path to the skeletons.

**Comment by CelticMinstrel** [comment]
When you view a specific file on GitHub, there is a "Raw" button. Click that, then use your browser to save it as a file.

**Comment by sevu** [comment]
Githubs UI is a mess:
* Click on the `code`Button on the top left
* Not far from there is a button to change the `branch` - select the 1.14 branch (though currently it doesn't really matter if you are on master or 1.14 branch)
* Then go through the directories to data/campaigns/Northern_Rebirth/scenarios/ and finally the click the file.
* There is a `Raw` button in the menubar, you could click it and copy paste the text displayed, or, better right-click on the file and choose "save target as .."

[Offtopic: there is also a `history` button where you can see the changes. And, if you click on one commit, there is on the top right a `browse files` button - if you click that you can look how things where at a specific time in the past]

So, you found the two files, where to save them? See here:
https://wiki.wesnoth.org/Editingwesnoth, or when you click in the titlescreen the top left button which looks like an `i` it is shown where the game data lies - the place where it belongs.

**Comment by Konrad22** [comment]
Don't worry, I indeed do know where to save it. And thanks to both of you. ^^

**Comment by CelticMinstrel** [comment]
You don't need to ask before editing the wiki. Just do it.

**Comment by Konrad22** [comment]
I've decided against editing it, because my pre steam path was also different from what is written there. It might make sense to ask more users as to where the data is stored right now, before any (wrong or incomplete) changes are made.

**Comment by Konrad22** [comment]
First wave of feedback incoming:
Your first event to strenghten the dwarves is somehow not working.
[NR-Infested Caves Turn 16.gz](https://github.com/wesnoth/wesnoth/files/1998054/NR-Infested.Caves.Turn.16.gz) (Just watch after ending the turn and observe the status table inbetween.
Your second event is working fine and the (first) replay proves that it is certainly enough to keep the dwarves alive. Which makes me question the lose condition of Hamels death a bit. I mean, sure the story won't work with him dead. But there is pretty much nothing I, the player, can do to prevent his death in any situation that is bad enough to endanger him.
First replay: 
[NR-Infested Caves Turn 46.gz](https://github.com/wesnoth/wesnoth/files/1998055/NR-Infested.Caves.Turn.46.gz)

There is a second replay, because I decided to try optimizing my positioning against the south west trolls, which is why at first I abandoned the first run (first replay) at turn 15. My second run was already vastly different from the first one though, which is why I decided to go through with the first run to the end, so you could compare them.
That's where how my second run looks so far: 
[NR-Infested Caves-Auto-Save15.gz](https://github.com/wesnoth/wesnoth/files/1998056/NR-Infested.Caves-Auto-Save15.gz)
Good night.

**Comment by sevu** [comment]
I consider this resolved - for the case of the dwarves dying at round 50 there is still the defeat condition.
