### ISSUE TITLE
SoF - Last Scenario bugged/not winnable

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3099]
https://steamcommunity.com/app/599390/discussions/0/2828702372999695509/
So, someone played until the the Vulcano Scenario (when they all die) and instead of winning after the Vulcano explodes, he loses. (More details in the link.)

**Comment by CelticMinstrel** [comment]
Hmm, that's a really odd error; it's just looping over a list of units and killing each one, so that shouldn't change the length of the array as far as I'm aware, unless `[kill]` fired an event which changed said array (which I guess is actually possible since some of this is in a die event, but I'm not sure that would cause exactly nine times which seems to be once for each instance of the loop, unless the numbers matching is a red herring).

The easiest fix would probably be to just replace all the `[foreach]` tags over `lavadead` with `[for]` tags (which also means some small changes to the contents, like `$this_item` -> `$lavadead[$i]`).

**Comment by ln-zookeeper** [comment]
Couldn't the [foreach] problem be caused by the fact that it's in a nested event..? Maybe all those cases of $this_item should be $|this_item instead.

**Comment by CelticMinstrel** [comment]
Hmm, I'm not sure. Certainly, if it's a nested event without `delayed_variable_substitution=yes`, then you'd need to use `$|this_item` instead of `$this_item`, but if that were the cause of this, surely it would've had the same problem with `{FOREACH}`?
