### ISSUE TITLE
NR S2, northern door doesn't open (properly) when opened from the skeletons side

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3113]
[NR-Infested Caves-Auto-Save34.gz](https://github.com/wesnoth/wesnoth/files/2003875/NR-Infested.Caves-Auto-Save34.gz)

![door](https://user-images.githubusercontent.com/39015360/40043354-889c4a3e-5824-11e8-8093-4f8a94af2935.png)

**Comment by sevu** [comment]
Glad you found this one, it would be annoying to have it in the next release. Fixed in ed1ced1.
To have less of an bottleneck I changed the hex above this door to flat too, I think it is fine if the door is only triggered from the hex where the Footpad stands? (and the other side of cause)

**Comment by Konrad22** [comment]
I think it would be fine. On nightmare you reach there very late in the game, it doesn't make much of a difference.

**Comment by sevu** [comment]
I mean, the door works now as it should and can be opened from both sides. I just wonder if one would intuitively expect to open it form 15,5 too.
![screenshot_20180515_163529](https://user-images.githubusercontent.com/21158813/40063697-3632bda2-585e-11e8-9a55-df4b3a7494c7.png)

(Also, I think the passage exists so that you could go south and north in the beginning of the game and ignore the main chamber for a while)

**Comment by Konrad22** [comment]
it doesn't look like it would, but still...maybe indicate the right hex by using the special floor tile?

(I can only speak for nightmare and in nightmare I won't possibly be able to arrive there before about 25-30 of 45 turns have gone by... I can't imagine any 'safe' way to get there faster.)
