### ISSUE TITLE
NR S5 - Orange undead is triggered when he moves into my vision

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3114]
Unlike every other undead those guys are 'activated' (as well) when they move into the part of the map that I've discovered. (The others only get triggered if I discover them.)
[NR-The Pursuit-Auto-Save11.gz](https://github.com/wesnoth/wesnoth/files/2004217/NR-The.Pursuit-Auto-Save11.gz)
(end turn)

**Comment by Wedge009** [comment]
Is it just because the orange team was the only one to move into an area uncovered by the shroud? I haven't looked at the save file but it sounds like it could be a fluke that you didn't discover any orange units when you entered their area and them moving randomly into your 'field of vision' could trigger their aggression.

**Comment by Konrad22** [comment]
No, it isn't. I can say so, because the other's did not get triggered, when they moved into an area uncovered by the shroud.

**Comment by sevu** [comment]
The code looks as follows:
```
    [event]
        name=sighted
        [filter]
            side=7
        [/filter]
        [filter_second]
            side=1
        [/filter_second]

        [message]
            speaker=unit
            message= _ "Halt! You’re not allowed to be here! Authorized undead only!"
        [/message]

        [gold]
            side=7
            amount={ON_DIFFICULTY 200 350 500}
        [/gold]
    [/event]
```
Probably an error prone fact is that the primary unit is the one which has been discovered, and the secondary is the one which did discover it.
So, this event fires if side 1 (you) discovers a unit of side 7, rather than the other way round.
It's the same for the other cases, though there it probably didn't interrupt as you discover the skeletons the same time they discover you. 

(picture of turn 10 for the people who don't want to download the save file)
![sighted](https://user-images.githubusercontent.com/21158813/41849861-ca81af10-7882-11e8-9a14-34c531dc834f.png)

**Comment by sevu** [comment]
Having the event trigger for the undeads sighting the player instead doesn't work,
because the undead play without fog enabled (and the AI plays always without shroud as well)

I guess we are out of options here.
