### ISSUE TITLE
"Unit with negative HP found" assertion in UtBS

### ISSUE THREAD

**Issue by singalen** [wesnoth/wesnoth#3123]
`Condition v > 0 failed at unit.cpp:633`

Happened in:

* "Blood is Thicker than Water", on capture ships stage. Don't remember what unit I attacked, cannot see it on a screenshot.
* In 	"The Final Confrontation", multiple times.

It's hard to get the saves out of iPad, but I can do it if needed.

**Comment by jyrkive** [comment]
I believe I fixed this in commits 15446acb2ad1fd7990e52e7194480820c4923596 and b0c1382693f4d72d7ad8f662ad91612da72b6781.

UtBS has a bunch of custom abilities, such as disengage (option to move after attacking instead of before). Those abilities use events like `attack end`, and some of them unstore the fighting units (whose HP may be negative at that point). Thus, this issue would occur e.g. when you move a unit with disengage ability (**not** using its ability), then attack someone with that unit and lose the fight.

As unstoring units with negative HP is again allowed in the relevant event handlers, this error should no longer occur.
