### ISSUE TITLE
NR Sc13 - Rakshas (main antagonist) doesn't/can't recruit properly

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3141]
6 of the units he recruits on the first turn never leave his castle = he can only recruit 4 units per turn.
[NR-Showdown-Auto-Save7.gz](https://github.com/wesnoth/wesnoth/files/2019735/NR-Showdown-Auto-Save7.gz)
(For replay purposes. Or just end turn and see how they do not leave.)

EDIT: They seem to move when they are able to grab a village.

**Comment by sevu** [comment]
Does this only happen when he has no vision to others because of fog?

**Comment by Konrad22** [comment]
There is neither fog nor shroud enabled for any side on this map. (I'm providing save files for information. :( )
[NR-Showdown Turn 14.gz](https://github.com/wesnoth/wesnoth/files/2022798/NR-Showdown.Turn.14.gz) (In this save he has 9 units that do not leave the castle.)

**Comment by mattsc** [comment]
I confirmed the behavior using your Turn 14 save.  The reason is [this `[goal]` tag](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Northern_Rebirth/scenarios/13a_Showdown.cfg#L60) in the scenario code, which is set to the center hex of Rakshas' castle and has a higher value than all the other `[goal]` tags.

I don't know why this was done.  My guess is that the purpose was to keep a good fraction of the units around their leader.  The easiest way of dealing with this would be to simply remove this tag, but then all the units storm out, as usual.  One could set up an `[avoid]` tag for the castle hexes, but that would mean they'll avoid those even for attacks.  The [Hang Out Micro AI](https://wiki.wesnoth.org/Micro_AIs#Hang_Out_Micro_AI_.28ai_type.3Dhang_out.29) is another option that is specifically set up for something like this, but we'd have to somehow set the `[filter]` to control only a subset of the units.

**Comment by Konrad22** [comment]
Would it be possible to (instead) set this kind of [goal] tag at mutliple locations around is castle (but still inside of the fortress), so his units would bulk up around them?
