### ISSUE TITLE
Reloading start-of-scenario save sets save_id to an empty string.

### ISSUE THREAD

**Issue by dacin21** [wesnoth/wesnoth#3152]
Reloading a start-of-scenario file (in a campaign) can cause the save_id variable to be set to "" instead of setting it to "scenarioid_somenumber". This can lead to recall lists being wrongly assigned if it happens on consecutive scenarios.

- Wesnoth version 1.14.1 from the installer from the website.
- Windows 10, version 1709, os build 16299.371
- The issue can be reproduced in the small attached campaign. (See the README.txt file for instructions)

[Recall_Test.zip](https://github.com/wesnoth/wesnoth/files/2023658/Recall_Test.zip)

**Comment by gfgtdf** [comment]
the problem here is that the connect_engine has a 'is_loaded_game' flag that was meant for the case when you reload a mid-scenario save to prevnt changing the gamestate in that case, but it is somehow set to true aswell for start-of-sceanrio saves. Afaik the is also atlease one owth bug caused by that.

**Comment by Vultraz** [comment]
But this check doesn't consider `is_loaded_game`... https://github.com/wesnoth/wesnoth/blob/master/src/saved_game.cpp#L197

**Comment by gfgtdf** [comment]
this report is about this code https://github.com/wesnoth/wesnoth/blob/1.14/src/game_initialization/connect_engine.cpp#L917
