### ISSUE TITLE
[remove_object] doesn't work for "image_mod" effect

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#3220]
**Steps to reproduce:**
* Add an object with "image_mod" effect and remove it. Code:
```lua
T = wesnoth.require("lua/helper.lua").set_wml_tag_metatable {}
unit = wesnoth.get_units {side=1}[1]
wesnoth.add_modification(unit, "object", {id = "afterlife_grayscale", T.effect { apply_to = "hitpoints", increase_total = 1000 },T.effect { apply_to = "image_mod", add="GS()" } })
wesnoth.wml_actions.remove_object { id = unit.id, object_id = "afterlife_grayscale"}
```

**Expected at this point:**
The unit should have it's visual appearance (`image_mod`) intact.

**Actually:**
The unit-s visual appearance changes to "grayscale". In other words, "image_mod" effect persists even though the object has been removed.

To be extra sure there's no mistake in the code, check out unit-s health. (You'll see it's being changed around when adding the object and removing it).

**Comment by sevu** [comment]
Eventually #3172 is related - it's not about [rmove_object], but about some object not fully being removed after the duration expires. In the cases you describe, I wonder if looking with :inspect, if the object is indeed gone, but it's effect is left in some other key.

**Comment by CelticMinstrel** [comment]
I know there are some exceptions to things being reset on unit rebuild. For example, the portrait; I'm not sure if effects can change that, but if they can, it wouldn't be reverted when the object is removed. Could image mods also be one of the exceptions?

**Comment by gfgtdf** [comment]
ye the observations in post2 match exactly what one would except if image_moid was not reset on rebuild, so it's probably that. The same things i said in #3172 whether/how to fix this also apply to this one . This one is actually a little worse since it also has an add= feature that might add things multiple times as noted in post 2. For ~NOP this is obviously not a huge problem but afaik tere are imagepath functions that have an effect if appled a second time and this bug would break them on units.

**Comment by CelticMinstrel** [comment]
Perhaps what we need is an "undo" function for effects that is run when it's removed? Most effects could just leave it as a no-op. In 1.15 it could also be exposed to Lua.

**Comment by vgaming** [comment]
@gfgtdf thanks!
