### ISSUE TITLE
Using :inspect after remove_event shows assertion failure

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3257]
After removing event with wesnoth.wml_actions.remove_event{id="AE_arc_stone_repetrify_advance"} from lua console and using inspect, I get https://vgy.me/kECBVs.png, when pressing ignore, game and inspect continues working.

Log has
20180616 01:18:42 error gui/layout: grid [] place: Failed to place a grid, we have 301,49 space but we need 318,49 space. This happened at a grid with the id '' in a 'N4gui214tree_view_nodeE' with the id '' in a 'N4gui29tree_viewE' with the id 'stuff_list' in a 'N4gui24gridE' with the id '' in a 'N4gui29generatorINS_6policy17minimum_selection7no_itemENS1_17maximum_selection10many_itemsENS1_9placement11independentENS1_13select_action4showEEE' with the id '_content_grid' in a 'N4gui24gridE' with the id '' in a 'N4gui214stacked_widgetE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'gamestate_inspector'.

**Comment by gfgtdf** [comment]
the image link doesn't seem to work

**Comment by ProditorMagnus** [comment]
vgy.me said something about hard disk failure.

I guess image will be back eventually, but first post also has the exact steps to reproduce the issue.

**Comment by mattsc** [comment]
I confirmed that this is still happening.  [This is the assert](https://github.com/wesnoth/wesnoth/blob/master/src/game_events/manager.cpp#L152) that triggers.

If you read the block of comments just before this, it is pretty clear what is going on here, and why the assert is there.  When the Lua interpreter is closed, events do not get cleaned up, and if you enter the inspector right afterward, that assert triggers because it thinks that this is a situation that should not be happening and therefore an indication of a bigger problem.  This was clearly written before the in-game Lua interpreter existed.

Note that if you do anything else in between removing the event and opening the inspector (moving one unit a single hex is enough), events get cleaned up and the assert does not happen.

I'm not sure how best to deal with this.  @CelticMinstrel Is it possible to clean events when exiting the Lua console?  Is it desirable?  The easiest solution would, of course, be to remove the assert, but then it might not catch some real problem, which isn't exactly good.

**Comment by CelticMinstrel** [comment]
Can this also be triggered by the `:lua` command?

Also, if you have time to check, does it still happen on #5663? (I can check later if you don't have time.)

**Comment by mattsc** [comment]
> Can this also be triggered by the `:lua` command?

Yes.

> Also, if you have time to check, does it still happen on #5663? (I can check later if you don't have time.)

Don't have time at the moment, maybe tonight.

**Comment by CelticMinstrel** [comment]
Looks like it _does_ occur on #5663. One of the changes included in that PR makes a fix easier, too, as there's a new argument to the function which (at least currently) is only true when called from the inspector.
