### ISSUE TITLE
SotA - The Mage, Ras-Tabahn can be healed for 8 hp

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3291]
That's the scenario where Ras-Tabahn is ill. He is permanently slowed, he takes 4 dmg per turn (2 when he is resting) and can (supposedly) only heal for 4 hp in a village. But villages and healers can heal him for 8 hp. So I guess that part didn't work.

**Comment by Wedge009** [comment]
I don't think this is a bug but perhaps the narration text can be confusing if one doesn't realise it is talking about the overall effect. That is, the scenario doesn't change the normal mechanics of healing or resting.

> Ras-Tabahn is sick. He is slowed, and will lose four hit-points every turn. He will die if he reaches zero. Villages will heal him four points, and he will lose only two if he is resting.

The text is correct: If Ras-Tabahn is at a village, he is healed 8 HP as per normal. But since he is sick he still loses 4 HP. So, overall, the village can only heal him 8 - 4 = 4 HP. Similarly, Vendraxis will only heal him 8 - 4 = 4 HP.

Also, it wouldn't really be fair if Ras-Tabahn could never be healed - that is, standing in a village means his gain and loss cancels out: 4 - 4 = 0 HP.

The normal mechanics of resting doesn't change either: 2 - 4 = -2 HP.

**Comment by Konrad22** [comment]
That's...true. In that case, could we please get rid of the last sentence in the narration text? I think it will only confuse people, as healing and losing health are separate issues. There is not green +4 at the beginning of the turn, instead there is a red -4 followed by a +8. Talking over the overall effect while only the seperate effects are displayed is bound to lead to confusion, or so I believe.
