### ISSUE TITLE
SotA - Against the World, Nagas are basically robbing the saurians of villages

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3293]
The naga arrive in turn one without gold, the saurians in turn two with gold. But the naga (because they have a leader) decide to take every village they can reach, denying them the saurians while they themselves can't make good use of those villages. Is there a way to change that?

**Comment by CelticMinstrel** [comment]
We could remove the village-seeking candidate action from the Nagas' AI.

**Comment by Konrad22** [comment]
That would be nice.

**Comment by sigurdfdragon** [comment]
Not sure what to do with this.
I could:
`
            [avoid]
                terrain=*^V*
            [/avoid]`
but it seemed kind of lackluster as the saurians only pick up about 4 villages, and there are some unclaimed ones early on.
or I could add another keep to the castle & give them recruits.

@beetlenaut Any thoughts on this? Part of it looks like you intended for the nagas to not recruit, but another part I'm not sure about.

**Comment by beetlenaut** [comment]
I didn't really intend for the naga to recruit, but I figured that if the saurian leader died early, the naga could take his place. That never came close to happening in my testing though, so maybe it's not likely enough to worry about. I didn't consider it a priority to stop the naga from grabbing villages because the difference probably adds up to only one or two extra saurians. I suppose we might as well get those though.

Using [avoid] for the naga is acceptable, but it would be better to remove the village-seeking candidate action so they can still use the villages for healing. It would also be fine to change the leader to a hero unit without canrecruit.
