### ISSUE TITLE
Assert in monte_carlo_combat_matrix::scale_probabilities

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#3321]
There's an assert in monte_carlo_combat_matrix::scale_probabilities
https://github.com/wesnoth/wesnoth/blob/51609d2cef4e42e067d09ebba7b0b0a30b7bce01/src/attack_prediction.cpp#L1660

It's just triggered during an AI turn, making three players each take over hosting and crash out (the fourth player had Monte Carlo simulations turned off).

Replay: https://replays.wesnoth.org/1.14/20180704/SXC_Attack_0.2.122_Turn_36_(17374).bz2
The crash happens during turn 35, and the game ends afterwards

**Comment by jyrkive** [comment]
All right, I can indeed reproduce this with the provided replay.

The probabilities the function is asked to scale are all zero. In addition, the divisor is almost zero, specifically 3.33067e-016. It looks like in this situation the target HP distribution vector isn't supposed to be used, but because of a rounding error of some kind, the calculated chance to be slowed (or alternatively, not slowed) isn't exactly zero, and things break.

**Comment by jyrkive** [comment]
Thinking about it, my suspicion is that it's caused by slowing indeed being almost but not fully guaranteed - to the extent that the actual probabilities are starting to fade under the noise caused by rounding errors. I might need to work around this by rounding slow probabilities. :(

**Comment by jyrkive** [comment]
After more testing, I can't tell where the 3.33067e-016 is coming from. It should be the probability to be slowed/not slowed, but only damage prediction code is capable of emitting slowed probabilities. In Monte Carlo mode it can't emit such a probability (the precision is increments of 0.0002; other values aren't possible), leaving only the `calculate_probability_of_debuff()` function. I added logging when it produces a problematic probability (less than a 1.0e-9 away from zero or one), but it didn't log anything.

**Comment by jyrkive** [comment]
Sigh. Turns out I can't debug with rr doe to the issue discussed in mozilla/rr#1579.

I guess I'll just normalize probabilities like that by force, then...
