### ISSUE TITLE
[1.15] EffectWML's interaction between vision and movement

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#3356]
In Wesnoth 1.14, the interactions between `[effect]apply_to=movement` and `[effect]apply_to=vision` depend on the order of the operations. Consider a unit with 5 moves and default vision:
* It has (effectively) 5 moves and 5 vp.
* After (mp + 1) (vp + 2), it will have 6 moves and 8 vp.
* After (vp + 2) (mp + 1), it will have 6 moves and 7 vp.

This is because vision defaults to -1 which means "the same as the max movement points". Using any effect with apply_to=vision sets the number of vision points, and from then on they're no longer affected by the movement points.

I suggest adding an `affects_vision` key to `apply_to=movement` with options
* `yes` (default for increase) - if vision is not -1, then the increase will be applied to vision as well
* what to call this, maybe `as_before` - the vision variable is ignored, so the effects are the same as Wesnoth 1.14.
* `no` - if vision is -1, sets it to the current movement before the effect is applied

Please would someone add the [low-priority] tag?

**Comment by CelticMinstrel** [comment]
If we can't think of a better descriptive name, then `affects_vision=legacy` seems like the best choice (which might have the implication of being deprecated and eventually removed).

**Comment by jostephd** [comment]
`affects_vision=hardcode`, as it replaces `vision=-1` with `vision=<whatever the current effective vision is>`.

**Comment by CelticMinstrel** [comment]
That doesn't really make sense to me. How does "hardcode" imply "increase vision only if different from default"?

**Comment by stevecotton** [comment]
Added to the roadmap for 1.15.9.

**Comment by stevecotton** [comment]
Updated the labels as this is now on the roadmap.

**Comment by gfgtdf** [comment]
> In Wesnoth 1.14, the interactions between [effect]apply_to=movement and [effect]apply_to=vision depend on the order of the operations

I don't see how this is a problem, as this happens all the time already. The most common examples are
1) hitpoint increasing effects where one of the increases it by a fixed amount (`increase_total=10`) and the other one increases it by a percentage (`increase_total=50%`) 
2) effect that add (`apply_to=new_attack`) and modify (`apply_to=attack`) weapons.

**Comment by stevecotton** [comment]
Those examples both apply to the same attribute, example 1 changes hitpoints and then changes hitpoints. Consider instead a 30 max hp unit drinking a potion that gives the unit +10 max hp.

1. Unit is recruited, and immediately drinks the potion. The unit now has 40/40 hp.
2. Unit is recruited, injured by 5 hp, fully heals in a village, and then drinks the potion. The unit now has 30/40 hp.

**Comment by CelticMinstrel** [comment]
I think in your examples it's expected that the order of operations matter, while in this case it's surprising that they matter, and the way they matter is weird.

**Comment by gfgtdf** [comment]
> ... potion. The unit now has 30/40 hp.

well yes.

> while in this case it's surprising that they matter, and the way they matter is weird.

okay right. i just saw the first comment, and din't read the example properly, i agree that it should be changed.

**Comment by stevecotton** [comment]
I'm now considering this alternative:

`[effect]apply_to=vision` gets a `link_with_movement` option, which sets a new flag in the unit.
If that flag is `yes`, then any subsequent `[effect]apply_to=movement` will also change the vision value. It would default to `yes`, using `[effect]apply_to=vision` with a `set=` attribute would set it to `no`, but with `increase=` would leave it unchanged. Using an explicit `vision=` in the `[unit_type]` would also set it to `no`.

My reason for this is in https://github.com/wesnoth/wesnoth/pull/5434#issuecomment-761300960 - there are a few add-ons that set the vision value and then won't want movement to change it. Except for those, a power-up that increases vision (and that would normally use the based-on-movement value) will leave the coupling enabled.

**Comment by Pentarctagon** [comment]
So:
* `[effect]apply_to=vision`, with a unit definition containing `[unit_type]vision=N`, would mean `link_with_movement=no` until the first time that `link_with_movement=yes` is provided or assumed.
* `[effect]apply_to=vision`, with a unit definition that **doesn't** contain `[unit_type]vision=N`, would implicitly mean `link_with_movement=yes` until the first time that `link_with_movement=no` is provided or assumed
* `[effect]apply_to=vision` with an explicit `link_with_movement=no` would affect all subsequent movement [effect]s until set otherwise regardless of the [unit_type] definition.
* `[effect]apply_to=vision set=N` would implicitly mean `link_with_movement=no` regardless of the [unit_type] definition and would affect all subsequent movement [effect]s until set otherwise.
* `[effect]apply_to=vision increase=N` would implicitly mean `link_with_movement=yes` regardless of the [unit_type] definition value and would affect all subsequent movement [effect]s until set otherwise.
---
If that's correct, that feels... unwieldy?  It seems like it would be simpler to have `[effect]apply_to=movement` always affect vision and then add an attribute that would allow preventing that specific movement [effect] from altering the unit's vision value.  Otherwise it sounds like a UMC author debugging why a particular unit is or isn't getting a particular vision value could end up having a very difficult time, for example, since they'd need to keep track of each time this internal flag was set and whether it was intentional or implicitly assumed.  Or another example: a unit from some era has 7 movement but 10 vision because they binoculars, then while playing an RPG scenario they get a ring of +1 movement - they'd end up with 8 movement but still 10 vision, right (since the explicit `vision=10` on the [unit_type] would mean `link_with_movement=no`, so an item that increases movement wouldn't also cause vision to increase)?

**Comment by stevecotton** [comment]
Thanks for the feedback, I'll rethink how to do this - my current plan is to take the Proper Flying Mod's vision behavior and work out how I would reimplement it to make it cleaner, given that engine changes are possible. Wondering if it's possible to have an effect that improves vision but has an ability-style filter so that it can be active or inactive based on an SUF that's recalculated for the current state of the map.

> It seems like it would be simpler to have `[effect]apply_to=movement` always affect vision and then add an attribute that would allow preventing that specific movement [effect] from altering the unit's vision value.

The reason for not making `apply_to_vision=` an attribute of the `[effect]apply_to=movement` is that the add-on providing the movement boost probably isn't the same as the one deciding to unlink vision from movement. For example, one add-on being the RPG scenario providing the movement ring, and the other add-on being the flying mod.

**Comment by Pentarctagon** [comment]
> The reason for not making apply_to_vision= an attribute of the [effect]apply_to=movement is that the add-on providing the movement boost probably isn't the same as the one deciding to unlink vision from movement. For example, one add-on being the RPG scenario providing the movement ring, and the other add-on being the flying mod.

To some extent I wonder how much this case needs to be solved in-engine rather than by the add-on itself - two add-ons by different authors modifying the same attribute in conflicting ways isn't a new or even really an unexpected occurrence.

**Comment by Pentarctagon** [comment]
More specifically, easily the most common case is that changing movement affects vision as well, so supporting that common case shouldn't be made more difficult or unpredictable in order to better support an edge case.  If the Proper Flying Mod's intention is to entirely decouple movement and vision from all units, then the simplest approach to that sounds like an attribute that could be explicitly set on units in a `unit placed` event by that mod.

**Comment by stevecotton** [comment]
> To some extent I wonder how much this case needs to be solved in-engine rather than by the add-on itself

Thanks for suggesting simplifying it. The more I look at it, the more I think `[effect]apply_to=movement` should always affect vision, except when the `[effect]` also includes `some_attribute=no`. Currently I'm considering whether `some_attribute` should be called `affect_vision` or `also_apply_to_vision`.
