### ISSUE TITLE
DW - Sc3, make the Storm Trident more obvious

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3400]
I didn't even notice it and only found out about it now by reading one of the reviews in the forum.
(Maybe let them say that they see something sparkle over there.)

**Comment by CelticMinstrel** [comment]
Does it really _need_ to be obvious? It's helpful, but not essential, right? I think I got it on my first playthrough, too.

If you must have it more obvious, I think I'd prefer a more indirect hint. Rather than any kind of dialogue, just have some event that causes the view to scroll over there, perhaps an enemy coming from that direction.

**Comment by Konrad22** [comment]
It doesn't have to, I just think that it would be a nice touch. :)

That works for me. I was just giving the first example that came to my mind. ^^

**Comment by CelticMinstrel** [comment]
If I recall correctly, this is the scenario where you fight wolves, right? So a wolf coming over from that direction seems perfectly believable to me. Maybe even use the red wolf, I don't think that's been used anywhere yet in mainline.

**Comment by CelticMinstrel** [comment]
No need for an image mod, it's a variation: https://github.com/CelticMinstrel/BlackCrossOfAleron/blob/master/scenarios/09-return-home.cfg#L53-L58

**Comment by nemaara** [comment]
Fixed by #3883.
