### ISSUE TITLE
SoF - Sc8, inaccurate timeframe

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3404]
Thursagen says upon reaching the forge that he will probably need 'a few days' to complete the sceptre. You are now supposed to survive until turns run out, which means on hard that you have to survive 10 more turns. A day = 6 turns, 10 turns = 1,6... days. Certainly less than a few days. Is there a chance to reword this?

**Comment by CelticMinstrel** [comment]
I think this isn't a huge deal - you need to survive for about two days, which I think works for "a few". A few can probably be anything more than one? Though I suppose I'd normally assume more than two...

I'm not opposed to changing this, however. "A couple of days" or "A day or two" could also work. Just make sure it works on all difficulty modes if the turns vary depending on the difficulty, otherwise there's just no point.

**Comment by Konrad22** [comment]
It's apparently independed from the difficulty.

**Comment by sevu** [comment]
I would like to note that there is no day/night rhythm in that cave.

**Comment by CelticMinstrel** [comment]
It's true that the 6 turns per day thing is not a constant - some scenarios may stretch it out.

**Comment by Konrad22** [comment]
In this case they'd instead shorten it. I'll look up wheter there was a normal day/night circle outside of the cave.
