### ISSUE TITLE
SoF - Sc9, bad choice of words for the intro text

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3405]
'There was no exit from the caves of Knalga. ... And there was no exit from those caves.'
The dots are only one sentence. So I think this is certainly somewhat awkward. ._.

**Comment by stevecotton** [comment]
If you include the second story screen, there's a total of 5 sentences of which 4 are just repeating the same fact. I think it's correct as-is, as a workaround for the problem at the end of the scenario where players don't understand that they've won.

The one question I have for it is why it says "of Knalga", because the caves they're in aren't Knalga. I think it should mean "there was no exit from the caverns they were in back to the tunnels of Knalga", or "there was no exit from the caverns for the dwarves of Knalga".

**Comment by Konrad22** [comment]
Maybe "...There was **truly** no exit from these caves." for more emphasis? I like it either way. ^^
