### ISSUE TITLE
Sceptre of Fire has different dmg values, SoF vs HttT

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3406]
In SoF it deals 15 - 4 fire damage, in HttT it deals 14 - 4 fire damage.

**Comment by sevu** [comment]
Is that still so? I recall that there was a change to address this in 1.13.

**Comment by sigurdfdragon** [comment]
What that change was to make the finished sceptre (shows up in SoF, EI) slightly more powerful than the Uncut Ruby of Fire in TRoW. With HttT it looks like the intent was to show the units gaining mastery over it (damage is different depending on what level Konrad & Li'sar are at). Also, there's charactization of those two being exceptional users of it, which is why their max is higher than the SoF macro that's used in SoF/EI

**Comment by Konrad22** [comment]
Thanks for the explanation. ^^
