### ISSUE TITLE
TSG - Sc8a, a large part of the map goes unused

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3411]
How about adding a second keep further south (with an enemy leader), so I don't go uncontested for half of the map? Also, an ambush close to Kerlath would be cool, to punish the player for sending Deoran ahead by himself.

**Comment by sevu** [comment]
Well well… that's kind of level redesign which could help here, rather than specific fixes… Not sure how though
Also, I want to mention the fact that it is possible to give a side multiple leaders – with their keep on the same castle, far away or even no second one. (The AI will split up it's recruits 50-50 between two leaders)

**Comment by GregoryLundberg** [comment]
Considering the rewrite, can this be closed?

I note that the maps are being re-worked by @nemaara at this time.

**Comment by nemaara** [comment]
I guess this is a reasonable time to say this.

I think both S6a and S8a are a bit superfluous; I'd say having one kept would be okay, but having both is a little bit meh, it feels like playing the same thing twice in a row without really adding too much to the story (e.g. I don't think having the nest of nagas in S6a or another bandit ambush in S8a really add anything to the story). However, there may be some merit to keeping a "traveling" scenario (i.e. reaching the target goal) in terms of gameplay, so keeping one of these may be reasonable.

As stated in my map PR (https://github.com/wesnoth/wesnoth/pull/3648), I am not really "redesigning" the scenarios, just making the maps a little prettier and maybe adding a bit more terrain variety, so I don't want to redraw S8a outside of adding a few embellishments (especially for a stable cycle release). For 1.15.0, I would actually suggest removing S8a altogether and I can add a few more lines of storytext to transition from S7a to S9a. Any thoughts?

**Comment by Konrad22** [comment]
As I don't remember S8a contributing, like, anything to the story, I can't say I'd dislike that change.

**Comment by nemaara** [comment]
I like the very first idea. 

In that case, I would actually suggest removing Merfolk altogether (you basically don't need them at all for the campaign; yes, there are some things you can do with them in rivers, but not much really) and removing S6a (turning it into a cutscene at most). Then in S8a, we could shorten the map and have the player fight elves instead of bandits as you suggest. 

Of course, I don't think any of this should be done for the 1.14 cycle, but maybe can be considered for 1.15?

**Comment by GregoryLundberg** [comment]
Personally, I don't have a problem with such radical changes to an SP campaign.

For 1.14 we don't want to break existing content and we can't do anything which changes MP results (like my mess-up last week with the campfires, which changes combat).

When considering deleting scenes for TSG, you want to consider the balance of the branches. You don't want people saying, 'Just blow through by (not) aligning with the Bandits!' So they can claim they beat it at Hard because one branch is so much easier than the other. So, maybe not delete the Naga scene but make it something else. Perhaps, since its on the Elvish branch, we give the Bandits one last Hurrah by having stragglers from the north and south set upon Sir Gerrick's troops?

**Comment by nemaara** [comment]
So I'm suggesting removing S6a or S8a because of gameplay redundancy and S6a really contributes very little to the storyline (with your suggested change to S8a, I think that one would have more content). Also, TSG is a little bit long (for a novice campaign) so reducing playtime would be better (imo), and it would also make both branches the same number of scenarios (8). Regarding balance, it wouldn't be too difficult to just make the Elvish branch a little bit harder, since I think people have said it's on the easy side (regardless of S6a or S8a). Changing or removing a scenario requires rebalancing anyway, so I would rather remove it entirely and then play through the rest of the scenarios and try to balance them accordingly (they probably could use the rebalancing even as is).

About your edit, I can't comment on that, that seems weird to me too. I guess the reasoning could be that everyone else made a mess of things, so Deoran's only comfortable seeing things through personally. Deoran's obviously the MC of TSG, so I don't think that should change. I seem to recall that he would dismount upon entering the caves once upon a time, but it doesn't seem like that's the case anymore? Perhaps we could bring that back?

**Comment by GregoryLundberg** [comment]
Or simply switch roles and have him head to town with the mounted units and have Gerrick lead the party underground. Perhaps have him force Mal'Brin above ground to the S6a or S8a map to confront Deoran's party then have Gerrick et al join up for S8a/S9a.  S6a might be eliminated or we could do a cavalry / open country thing for Deoran and his cavalry to romp around in putting down the last of the bandits?

**Comment by nemaara** [comment]
The cavalry/open country thing sounds neat, but might be too complicated for a novice level campaign (from a player perspective, I mean), and I also don't really want to program/balance something like that right now. 

Regarding Deoran vs. Gerrick going underground, actually I was thinking that there isn't much good reasoning for Sir Gerrick to break with Deoran's group and head back to Westin on his own (yes, both the original and revised text do provide some reasoning, but it's kind of iffy to me). Couldn't we just leave him with Deoran and everyone goes to confront Mebrin together? Then it would be very easy to get rid of S6a and fixes that plot hole too.

**Comment by GregoryLundberg** [comment]
I'd like someone who has been around longer to weigh in on this thread.

What I'm hearing is the suggestion to (1) eliminate the Mer and their village from S1 (2) eliminate S6a, have Gerrick and the rest continue into the cavern with Deoran and (3) change the antagonists in S8a (to become S7a) to elves, with more foreshadowing on what's coming in the final scene (to become S8a).

And I'd like some more opinions on whether to push this into 1.14 or wait for 1.15 (I'm for doing it sooner).

**Comment by nemaara** [comment]
Yes, that's all of my (and your) suggestions. I talked to Vultraz, he seems to think that it's okay for 1.14 as well.

**Comment by Konrad22** [comment]
Does my opinion count too, as I've been around for almost 8 years (as a player)?
Because I like those suggestions and they seem to make sense. I don't see them opening up plot holes at least, if they will be done well.

**Comment by sevu** [comment]
For the Mer: I think it's good that you can archive anything without them – that's the point why they can be an optional easter egg, and don't have to be added to the team if you didn't find them. On the other hand, the way the maps are currently done they are often rather useless. One thing I had in mind was adding somewhere (maybe S3, S2 fit's good, but it's too early, better to keep a surprise for later, no idea about the B-Branch) 1-2 Soulless Swimmers, which never leave the water (I thought about the Lurker MicroAI) And I think it is very good that they leave in the A-Branch after S6.
They can be removed, but I see no need for it.

S6a: I think it's gameplaywise quite a unique scenario, besides that the starting gold needs to be adjusted better. I found in the feedback forum many people having the problem that the use good units in this scenario which they miss in S7a. One could disable recalls for this scenario and send only a weak messenger troop. However, plot is another thing.

I think S7a is actually the final scenario, and what comes after more of a campaign fadeout. Too easy, too loose.

For eliminating scenarios… that best for 1.15 only. Because that would in most cases break some 1.14.x saves.

**Comment by nemaara** [comment]
I'm quite sure that all of the proposed changes will break saves (at least the way I'm thinking of implementing them); that's what I was afraid of when questioning whether to have these changes be targeted toward 1.14 or 1.15.

Again, since this is a novice campaign that newer players will be playing first, I think it would be best to keep things (relatively) simple and avoid any fancy mechanics. For the Elvish branch, I agree about S7a being the final scenario and the "Elvish vengeance" being a fadeout. So that would make the case for S6a staying. From a plot and gameplay perspective, I would prefer to have S8a stay, but I can make either one work. 

In any case, maybe I should save my PR (https://github.com/wesnoth/wesnoth/pull/3648) for 1.15 (although there doesn't seem to be a 1.15 branch yet)?

**Comment by GregoryLundberg** [comment]
The 1.15 branch is presently named 'master' and it should self-id as version 1.15-dev.

Not breaking replays is good. So 1.15 it is.

**Comment by nemaara** [comment]
@GregoryLundberg sevu just suggested a way for me to rework the scenarios while allowing start of scenario saves to still work. Replays may no longer be valid (? I'm actually not entirely sure how replays work), but at least saves will. Perhaps this is still reasonable for 1.14 then?

**Comment by gfgtdf** [comment]
if you change just the content of the [scenario] (in particular the map) then saves aswell as replays will still work, since both contain a copy the (old) scenario data from when the scenario was stated and will just use that.

**Comment by nemaara** [comment]
I think I'll be changing some events as well (e.g. adding/removing a couple), but nothing outside of the [scenario] tag.

**Comment by sevu** [comment]
I think S6a was removed, not S8a. But I'm not sure…

**Comment by Konrad22** [comment]
You are right. Sadly.

**Comment by Konrad22** [comment]
Buuuut, the scenario has been redesigned and my issue is fixed. :D
Sorry for the trouble.

**Comment by sevu** [comment]
Great =)
