### ISSUE TITLE
Eastern Invasion - All veterans gone - no units to recall

### ISSUE THREAD

**Issue by user240** [wesnoth/wesnoth#3420]
Between the end of "El-Lake Vrug" (capturing by the orks), "El-Captured" and "El-Evacuation" ALL veterans disapear. Only the 3 units from "El-Captured" are available in "El-Evacuation".

I played this campain in "Battle for Wesnoth" version 1.10.5 and there are all veterans available to recall in "El-Evacuation".

I repeated the szenarios 2 times in "Battle for Wesnoth" version 1.14.3, but there seems to be a bug or at least a missing description why all the previous veterans from "El-Lake Vrug" are gone.

Unfortunatley the upload dosn't work :-( no chance to upload the replay or save-games.

**Comment by ln-zookeeper** [comment]
This was a bug in 1.14.3 but it's already been fixed in 1.14.4. If you need to continue the campaign in 1.14.3 for some reason, [you can also fix the problem locally](https://forums.wesnoth.org/viewtopic.php?f=49&t=10312&start=45#p629923).

Apply the fix either by updating or the abovementioned local fix, and then restart the scenario (from the beginning-of-scenario save, not a turn 1 save), and it should work.
