### ISSUE TITLE
wmlxgettext does not recognize plural strings in some contexts

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3469]
I had a line similar to the following:

```
local var = wesnoth.format(_("one thing","$count things",count), {count = count})
```

When I ran wmlxgettext, the string was not gathered. Adding a space before the underscore allowed wmlxgettext to recognize it.

**Comment by AncientLich** [comment]
It was intentional that wmlxgettext requires a space before the underscore (_), but I never figured this particular usage case.

The explaination why wmlxgettext can't recognize it without space:
The underscore symbol could be a part of a variable name (example: variable_name, var_) and I also though that sytuations like 
   something_ (r_) and I also though that sytuations like 
   something_ ("one thing", "$count things",count) 
shouldn't be recognized as a valid translatable string

since wmlxgettext uses regular expressions in order to parse lua/wml code it is necessary to define some clear rules in order to avoid possible unwanted behaviors.

So... what should I consider a valid translatable, other than
_ at the beginning of the line
_ preceded by space and other things (like: something =  _ "translatable string")
also
[ I figure: _ preceded by parenthesis and other things.... like something(_ "translatable string") ]
other cases?

**Comment by CelticMinstrel** [comment]
You could just say _ at the beginning of a line or preceded by `[^a-zA-Z0-9]`, couldn't you? That said, the cases you listed are probably enough (I doubt people would use translatable strings as a table key, so no need to account for square brackets).

**Comment by jostephd** [comment]
I think you want to exclude not `A-Za-z0-9` but `A-Za-z0-9_`. You can also do `r'\b_\b'` to match `_` only as a whole word.

**Comment by CelticMinstrel** [comment]
By the way, while I have your attention @AncientLich - is it correct that all the wmlxgettext code (apart from the main file) is gathered into that single pywmlx directory?

**Comment by AncientLich** [comment]
Exactly. pywmlx directory contains all the code of wmlxgettext (imported in main file with 'import pywmlx').
The reason of this choice is that, splitting code in more files with a specific target can make easier to fix or improve the code.

Note:
Committed bugfix (very short change): https://github.com/wesnoth/wesnoth/pull/3481
I did some test and it seems it works fine. You are welcome to test it too :)
