### ISSUE TITLE
wmllint: translation mark placement

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3489]
```
-        label="<span color='green'>" + {LABEL} + "</span>"
+        label=_ "<span color=_ 'green'>" + {LABEL} + "</span>"
```
The first translation mark makes generally sense, may be hard for wmllint to detect such special cases.

The second one should not be placed though.

**Comment by CelticMinstrel** [comment]
WML strings can only use double quotes, so it shouldn't even see that as a string.

**Comment by gfgtdf** [comment]
see also https://github.com/wesnoth/wesnoth/issues/3080 in particular the third part there where wmlint removed a quites from a nested string.

**Comment by GregoryLundberg** [comment]
I'm confused. The idea here is to have WMLlint ensure we add meaningless work to the translation queue? I don't see any translatable strings at all in the OP example.

**Comment by Elvish-Hunter** [comment]
> I don't see any translatable strings at all in the OP example.

wmllint detects if a string has a translation mark by looking for a sequence composed by an underscore, any number of whitespaces and a double quote:

`translation_mark = re.compile(r'_ *"')`

Moreover, wmllint also checks if the name of the key is in a list of translatable keys (look for the function `is_translatable(key)`); however, wmllint doesn't have a real way to check the content of a string and determine if it's translatable or not. I suppose this is due to the fact that it was initially developed for the 1.4 series, and back then we didn't have support for Pango markup, so there was almost no need to perform string concatenations.
How else could we implement a system that checks if a string is translatable *based on its content*, keeping in mind that we also have to deal with multiline strings (and wmllint performs its checks line by line, so that's another problem)? And, above all, is it worth the effort?
