### ISSUE TITLE
Mages in Northern Rebirth are too immortal

### ISSUE THREAD

**Issue by AncientGeneral** [wesnoth/wesnoth#3501]
In some scenarios it is possible to get illogical win using immortal white mages. to implement this you need is send them ahead and hope they will be resurrected near enemy leader (or enemy leader will leave camp to attack mages).
It could be a special tactical move but there are no any logic. Mages can be beaten from all six hexs but they continue to respawn in center of enemy fortress/camp.
As example there is replay of last mission. unfortunately i can't convincingly demonstrate this bug/feature as I've seen it at my earlier games.

One of possible way to settle this is to set maybe a limit of resurrections or after first death mages will reject to continue fight but present in story.
[Showdown replay.gz](https://github.com/wesnoth/wesnoth/files/2324205/Showdown.replay.gz)

**Comment by Konrad22** [comment]
How about setting a revival point? The mages would have to concentrate (not moving/attacking/being attacked for one turn) to set a hex adjacent to both of  them as their new revival point.
Starting revival point would be Tallins start position.

**Comment by nemaara** [comment]
I'll set the revival point to Tallin's location, will do this for 1.14.7.

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/commit/8f23539834eb137a041e1beaaf4630004e63369c. There is a world in which you send Tallin ahead with both white magi now, but it's less of an illogical/cheesy win condition because you need Tallin to recruit, and because Tallin isn't that robust of a target so he's likely to die if you try that.
