### ISSUE TITLE
[show_if] is not correctly evaluated when objectives are shown on start

### ISSUE THREAD

**Issue by DisherProject** [wesnoth/wesnoth#3544]
I'm playing Wesnoth 1.14.4 on Windows 10

To reproduce:
1) Copy the following lines in any scenario (like the "Caves of the Basilisk")
 ```
   [event]
        name=prestart
        
        [objectives]
            side=1
            [objective]
                description="Say hello to my little friend"
                condition=win
                [show_if]
                    [have_unit]
                        id=LittleFriend
                    [/have_unit]
                [/show_if]
            [/objective]
            [objective]
                description="No little friend here"
                condition=win
                [show_if]
                    [not]
                        [have_unit]
                            id=LittleFriend
                        [/have_unit]
                    [/not]
                [/show_if]
            [/objective]
        [/objectives]
    [/event]
    
    [event]
        name=start
        
        [unit]
            side=1
            placement=leader
            type=Fire Dragon
            id=LittleFriend
            name= _ "My little friend"
        [/unit]
    [/event]
```
2) Start a game in the chosen scenario
3) Pay attention to the objectives when they are shown for the first time

You'll see "No little friend here" even though the dragon is on the map. If you re-open the objectives dialog (`ctrl + J` or via the menu) you'll see the the correct sentence

**Comment by GregoryLundberg** [comment]
The Wiki states "Scenario objectives are displayed on the player's first turn after the tag is used, or as part of the event if it triggers during that player's turn."

The prestart event and the start event are both prior to this.

The bug is that the objects [show_if] was evaluated at the time the [objectives] block appeared (in prestart), prior to conditions changing during the start event. So, when the display finally occurs (following the start event), the incorrect objectives appear.

Note that the [show_if] conditions are properly evaluated when [show_objectives] processes.

The fix would seem to be to do the full [show_objectives] processing at the time the objectives should first appear, just prior to the 'turn 1 begin' event,

**Comment by sevu** [comment]
Fix has been merged to 1.14, but can't directly be applied to master.

**Comment by jostephd** [comment]
Here you go - #3555

**Comment by sevu** [comment]
Thanks

**Comment by sevu** [comment]
For completeness I would like to mention one thing:
It is in some situations possible to show the objectives earlier by pressing ctrl+j if there is a break in the start event, for example when scrolling to some position.

TSG S4 would be an example.

**Comment by jostephd** [comment]
>  It is in some situations possible to show the objectives earlier by pressing ctrl+j if there is a break in the start event, for example when scrolling to some position.

This case should be handled correctly both before and after the patch.
