### ISSUE TITLE
remove_modifications does not properly revert current hitpoints

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#3545]
Steps to reproduce:
* start a new simple game/map
* execute:
```
T = wesnoth.require("lua/helper.lua").set_wml_tag_metatable {}
unit=wesnoth.get_units{side=1}[1]
wesnoth.add_modification(unit, "object", {
	id = "test",
	T.effect {
		apply_to = "hitpoints",
		increase_total = "100%",
		increase = "100%",
	},
})
wesnoth.remove_modifications(unit, { id = "test" })
```

Expected at this point: unit-s stays exactly the way it was

Actually: unit-s max_hitpoints is correctly restored but unit-s current hitpoints is doubled.

**Comment by jostephd** [comment]
Caused by e047564acdfac459a620951d2349d14458a6d2ed.

In THoT S11, in current 1.14 I end up with 86/43 HP (leader is resilient). If I revert that commit I end up with 42/43 HP which isn't right either.

**Comment by gfgtdf** [comment]
yes, this is not really suprising: there are differnt types of unit stats, basicially the stats of the 'type' (meaning max_hp map_expereince, attacks etc.), and some that only apply to single units (hp, xp, poisoned slowed etc.), remove_modifcation or modifications in generally only work well with the first type of attributes using the later in are only one-time effects when the modification is applied and in particular cannot really be undone in particular becasue they ate mostly changed directly. In your example it might look trivial, but usually quite some other things can happen (combat etc., other modifications) between the wesnoth.add_modification and the wesnoth.remove_modifications do a direct undoing of those effects is not generally possible.


> Caused by e047564.

hmm not really, the hp were never 'undone' in the way that is issuer expects, that commit coudl maybe be improve though by claming the hpo in the valid range [0, max_hp] after than `hit_points_ = hp;` but its not realyl realted to this commit

**Comment by vgaming** [comment]
@gfgtdf yes, the goal is not to come up with an easy perfect "remove_modification", but rather fix issues when they are found, if they are straight-forward to fix.
What do you think?

If there's a 100% feeling that this will not be fixed then the issue can be closed I guess. (?)

**Comment by gfgtdf** [comment]
hmm i think we shoudl at least update the wiki for that information before we close this.

**Comment by vgaming** [comment]
@gfgtdf I'm not sure where to change the docs then though... Any ideas?

**Comment by gfgtdf** [comment]
I'd say the documentation of the remove_modifications function of the remove_object tag

**Comment by vgaming** [comment]
@gfgtdf added this text for now:
https://wiki.wesnoth.org/DirectActionsWML#.5Bremove_object.5D
> Note that some unit properties are not restored ideally, e.g. current unit's health reversion might not work as expected (max_hitpoints will though).

(Further edits are quite OK, English is not my native language.)

**Comment by jostephd** [comment]
@vgaming The English is good; I'd only add a comma after "e.g.". "Ideally" often means "preferably" but the way you used it here is valid too :+1:

Shouldn't this issue remain open so the result where hitpoints>max_hitpoints would be fixed? I'm not asking for a perfect reversion but I can't think of a valid reason to let hitpoints to be >max_hitpoints. It's the kind of thing that will probably fail an assertion somewhere.

**Comment by vgaming** [comment]
@jostephd thanks.:) (Also added comma.)

Regarding HP: it's possible in wesnoth to have more hitpoints than max_hitpoints. When giving an object, there's even a key to "violate" the maxium (or not).
The problem is, however, that even small values (say 50% HP) can be changed this way and become 100%HP.

If anyone could make a smarter fix for simple hitpoints (not max), I'd support it totally of course...

**Comment by CelticMinstrel** [comment]
My view is that this issue basically isn't fixable because there's clear expected result. In your toy example, sure, it would make sense to return the unit to how it was. But in the general case, when the object is added and then removed several turns later? What then? Do you track all damage it received in the interim and then apply that over the HP it had before the object was applied? I doubt that would be worth the effort though.

**Comment by vgaming** [comment]
@CelticMinstrel I'd like to work it just the same as max_health modifications. If you're given an object +100% health, you double your health. If you were taken the +100% object back, you lose half of your health.
In other words, giving an object and removing it immediately should be NoOp.

**Comment by jostephd** [comment]
The difference is that max_health is a static property of the unit so it's easy to _define_ what removing an object that modifies it should do. As @CelticMinstrel said, it's not easy to define what removing an object that "doubles the hitpoints" should do. If a unit has 10/40HP, is given the object, and after some time the object is removed when the unit has 15/80HP, how many HP should the unit have after the removal?

I agree it would be intuitive for give-and-take-away to be a no-op but can't implement just one special case.

Maybe we should further clarify the wiki documentation to promise that `apply_to=hitpoints` effects are _not_ undone, the scenario author needs to implement the undo logic explicitly since we don't know what semantics the scenario expects.

**Comment by vgaming** [comment]
@jostephd Why not **define** hitpoints object removal as one that operates on the current HP value though? Seems natural to me. And it's a clear and precise definition.

The only doubtful question would be how negative HP work. Like what happens if your unit were given 100HP, lost almost all of it and only has 50HP now? The answer is still straightforward for me though: remove the 100HP back.
