### ISSUE TITLE
unit.advances_to is being reset with `remove_modifications`

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#3551]
Steps to repro:
* start a clean game as side 1
* enter debug mode (:debug), enter Lua console (`)
* execute this
```lua
unit = wesnoth.get_units {side = 1}[1]
unit.advances_to = { "Pikeman" }
unit.advances_to  -- check that it's indeed set. It is.
wesnoth.remove_modifications(unit, { id = "test" })
wesnoth.add_modification(unit, "object", { id = "test" })
unit.advances_to
```

Expected at last line: the advances of a unit remain { "Pikeman" }

Actually: possible advances are reset to default.

**Comment by gfgtdf** [comment]
the way remove_modifications work is the following: reset all units stats (except current hp, XP, status and maybe something else) then reapply all modifications that are left, this implicitly undoes all changes done via direct unit attribute manimulation. ( this also applies to removal of object via duration="scenario")

 Since many add-ons might use remove_modifications or duration=. it's reccomented to use [effect] over direct unit manipulation when possible.

**Comment by vgaming** [comment]
@gfgtdf what I'm wondering is why wesnoth doesn't automatically add an effect whenever `unit.advances_to = {}` is executed.  Sounds a bit like leaking implementation, but then again I could be wrong. Not sure, confused.

**Comment by CelticMinstrel** [comment]
It's two parts of the engine working against each other, I suppose. Direct assignment to units _is_ needed if you want to implement custom effects, but it's currently not particularly useful for actual permanent changes, which is... not a great state of affairs, but I don't know if there's a good way to fix it.
