### ISSUE TITLE
poison is preffered on 1HP enemy

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#3586]
See image:
![poison-prefered](https://user-images.githubusercontent.com/33452702/46247053-97ca3d80-c40e-11e8-87e9-292493b5a3c7.png)

Your unit prefers to use "poison" weapon even though it will get counter-attack. The chance to killis the same if the other weapon is used.

P.S. I know it's not strictly a bug because wesnoth is not guaranteed to pick the "best" weapon for you. Still, picking the obviously worse is bad for gameplay (especially for "quick to click" players), and may indicate some internal problem.
Thoughts?

**Comment by vgaming** [comment]
@jyrkive Do you have any feedback on this? (Basically mentioning you since you were/are the main AI / duel statistics developer I think?)

**Comment by jyrkive** [comment]
Probability of killing or being killed has highest priority. It's then followed by the poisoning probability (again, both ways), and only then the expected damage.

The opponent is considered to be poisoned even if the attack kills him; thus, the biting attack is considered better in this situation.

Improving the weapon choice in this situation would require changing the poisoning calculation so that it no longer considers killing attacks. It would be such a big change that I'm not willing to do it.

Marking as Won't Fix.

**Comment by mattsc** [comment]
I'm fine with having this marked as "Won't Fix", just one comment as this is something I had to deal with in one of my AI projects:

> Improving the weapon choice in this situation would require changing the poisoning calculation so that it no longer considers killing attacks.

There is an easier way that does not requite to change the calculation of probabilities: Instead of using the poisoning probability, one could use poisoning minus kill probability as the relevant quantity for the second term in the attack evaluation.  (In the mentioned example, both probabilities are the same, so there is no bonus for poisoning, and the expected damage serves as tie breaker.)

**Comment by jyrkive** [comment]
Note that it requires **knowing** the kill probability. In `battle_context::better_combat()` we have the probability *that the opponent is dead*, which is **not** the same thing! (The AI may simulate multiple battles in a row, and the resulting probability is the probability of being dead after **all** the battles.)

**Comment by mattsc** [comment]
That's true.  I was only thinking about the attack dialog here, not the AI.  (And for reference, in my AI I do it separately by individual battle in attack combinations by several units and then combine those.  And yes, it's quite complex.)

**Comment by jyrkive** [comment]
The attack dialog calls `better_combat()` to determine which weapon is better, and that function is used by both (it can't assume that the attack dialog is calling it).

**Comment by vgaming** [comment]
@jyrkive makes sense, thanks for the clarification.

**Comment by jostephd** [comment]
> Improving the weapon choice in this situation would require changing the poisoning calculation so that it no longer considers killing attacks. It would be such a big change that I'm not willing to do it.

Could you explain what the change would be? Even if this issue can't easily be fixed, I'd like to know this part of the code better

**Comment by jyrkive** [comment]
@jostephd Sure. The calculation is here: https://github.com/wesnoth/wesnoth/blob/75ab69d885163dd4bb40259cf91123394e2c12ee/src/attack_prediction.cpp#L2427-L2434

Changing it would require passing the probability that the opponent is *hit but not killed*, instead of just the probability that he/she/it is *hit*. In addition, the calculation for the slow probability below should also be changed for consistency.
