### ISSUE TITLE
No Wesnoth account required for official 1.15 MP server

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#3624]
master (post-October 2015 re-base) seems like it doesn't check for an actual Wesnoth account when logging on to the official MP server (or maybe it's an issue on the server itself?).

1. Select official MP server
2. Log-in as any non-Wesnoth account name - can just type in a random gibberish of alpha-numeric characters.
3. Log-in to lobby is successful.

Recording this as per discussion in #3622.

**Comment by CelticMinstrel** [comment]
I'd be inclined to leave this as intentional and close as wontfix, personally. At the very least, we shouldn't just assume 1.15 _must_ require an account solely because 1.14 does.

**Comment by Wedge009** [comment]
Okay, that's fine. Was just reporting it here because of the discussion in #3622. However, if it is no longer a requirement for 1.15 server then the log-in dialogue needs to be updated to remove the 'registered account required' message.

**Comment by ProditorMagnus** [comment]
Its part of server configuration, mp mods can change it in game.

**Comment by Wedge009** [comment]
Oh right. I suppose it's disabled for a development server. Closing, then.

**Comment by Pentarctagon** [comment]
I do expect 1.16 to have a forum account requirement though, to be clear.  And for better or worse, I doubt enough people will use the development MP server for it to really matter a whole lot.

**Comment by Wedge009** [comment]
Yep, that makes sense.

**Comment by CelticMinstrel** [comment]
That was similar to my reasoning, yes.

**Comment by Wedge009** [comment]
'Won't fix' because celmin said so.

**Comment by gfgtdf** [comment]
> I do expect 1.16 to have a forum account requirement though, to be clear. And for better or worse, I doubt enough people will use the development MP server for it to really matter a whole lot.


uhm what? Now we are going all thte way back to the even/odd development/stable thing? I though we already decided to drop that in favou of rolling release.

**Comment by CelticMinstrel** [comment]
Even if we're going with a rolling release model, 1.15.0 is not released yet. If we do go with a rolling release model by the time it is released, I suppose it would be fine to port the account requirement to 1.15.

**Comment by Pentarctagon** [comment]
The only really strong opinion I have about the rolling release model at this point is that it should definitely be called 1.15, rather than 1.14.6 or whatever minor 1.14 release we'd be on by then.

Personally, I think the ideal implementation of the WML/lua APIs for a rolling release would be to fully duplicate the API implementation for each API level that's supported, so that they are completely separated from each other.  I don't know how feasible that would be(or if it's actually a good idea at all, honestly) and it would obviously result in a fair bit of code duplication, but having them separated out like that would allow for doing any and all forms of breaking changes(whereas #3576 is for brand new APIs, if I'm understanding it correctly) as well as providing full backwards compatibility for all API levels that are kept around.

**Comment by gfgtdf** [comment]
> The only really strong opinion I have about the rolling release model at this point is that it should definitely be called 1.15, rather than 1.14.6 or whatever minor 1.14 release we'd be on by then.

While i agree that this has advantages in particular for us developers (in particular: c++14, and allows us to start from a more clean api) a 'major' version change is always annoying for users since the addons, savegames will be basicially lost unless you are  a wesnoth expert and know how to port them and the mp server is split for some time after a new release, as it happend in the 1.12->1.14 transition and every transition before.

The other main reason why i supported putting the rorlling release into 1.14 is that i bascicially don't know at all, how long it'll take until 1.15 actually comes out, the last time vultraz said something will come out in a  few months, it iirc took like 1.5 years in th end from that point on. And for developers, in paticular for new developers, it very demotivating knowing that a new feature you added will probably not be available for the next 2 years.

> Though personally, I think the ideal implementation of the WML/lua APIs for a rolling release would be to fully duplicate the API implementation for each API level that's supported

Hmm no, 'api' is basicialyl everything, new keys in attacks/lua function/wml tags are basicialy spread all over the code so this is impossible, Also it would make it very hard to have addons to support multiple apilevels, i made a pr for apilevels, which can actualyl be simplified quite a bit if we do it in 1.15 only  (it not compltete yet, in particular some addonserver admion commands might not be working), please add suggestions about that there.

**Comment by GregoryLundberg** [comment]
This is so not the right thread for speaking about rolling releases and version-compatibility checks but ...

My concern is how you propose to handle the following:

* Say, I presently have Wesnoth 1.14.631 installed.
* And say I have an add-on campaign installed (OldCampaign) which requires the add-on (NewStuff)
* OldCampaign requires Wesnoth 1.14.569, or later
* NewStuff requires Wesnoth 1.14.721 or earlier
* Now, say I update directly to Wesnoth 1.14.911

NewStuff should cease operation because I no longer meet the requirement that it be '721 or earlier.

OldCampaign, however, says it should work because I still meet the requirements of '569 or later.

How do you propose to disable OldCampaign and notify me that the reason is that it depends upon NewStuff, which can no longer work?

**Comment by gfgtdf** [comment]
I'm not sure what you mean by ealier/later,


there will be no option to require 'requires Wesnoth .. or earlier' because all changes during a release will be backwards comptible, basicially just new stuff is added no old stuff removes unless we change main version number.

**Comment by Pentarctagon** [comment]
> in particular some addonserver admion commands might not be working

You should probably ask shadowm or one of the other server admins about that then - I don't have access to run commands against the add-ons server.
