### ISSUE TITLE
Add OPUS codec support

### ISSUE THREAD

**Issue by Agno94** [wesnoth/wesnoth#3773]
Opus is an audio codec developed in 2012 that achieve a better compression than vorbis. It's used in new webm file and they say it's even better than AAC: https://www.opus-codec.org/comparison/. The reference encoder/decodes (libopus) is open-source. Using these codec might allow to reduce the space required by music data and add-ons.

**Comment by loonycyborg** [comment]
SDL2_mixer, the music lib we're using, supports opus playback since latest version. So probably support for using it in addons can be enabled using it easily enough. However I'm not skilled enough in actual music stuff to know whether it's good idea to recode wesnoth's own resources.

**Comment by shikadiqueen** [comment]
Currently Wesnoth supports any formats* supported by SDL_mixer and I believe SDL_mixer 2.0.4 supports Opus. So it boils down to deciding whether making said support mandatory is actually worth it or not — which means that someone would have to look into transcoding files and comparing results. A problem with this is that if you're recompressing a lossy stream with another lossy format, you're bound to start losing some data.

* (Note that it uses vorbis directly to read metadata from music tracks, but this functionality is AFAIK optional and rarely used)

**Comment by Wedge009** [comment]
Agree that there's no sense in re-encoding lossy formats as that just introduces more compression artefacts. However, also agree that the opus codec is supposed to supersede AAC and Vorbis. As already mentioned above, there's support for the format already included so I believe it's just a matter of whether or not audio contributors want to use it.

**Comment by CelticMinstrel** [comment]
> The metadata also can't be read on Windows or Macs, so that feature isn't even cross platform anyway.

Does it really only work on Linux? That code doesn't look like something that should be platform-dependent; has anyone actually tried it on Windows or Mac?

**Comment by Pentarctagon** [comment]
Someone on Windows/MacOS would need to recompile without lines 87 and 124, then try it out.

**Comment by Wedge009** [comment]
I gave it a quick try, but running into difficulty linking to libogg and libvorbis (using the libraries from https://xiph.org/downloads/). I'll try to have another go when I'm not so sleepy from a work day.

**Comment by Wedge009** [comment]
I got a compilation working but I'm not sure how to trigger those lines between 87 and 124. What is it even supposed to be doing? It _looks_ like it's pulling meta-data from the ogg file but where does it go to? Where should I be looking (from within the game) for this information? Haven't seen anything come up in the logs.

**Comment by CelticMinstrel** [comment]
@wedge009 - I think what you could do is remove the explicitly-set titles in the WML (in one of the folders in data/core/macros if I recall correctly) and then check in the editor that the title is still shown (by creating a new scenario and opening the music menu from the top toolbar).

(The first step is just to make sure that what you're seeing really is the title taken from the file rather than the title taken from WML.)

**Comment by Wedge009** [comment]
So it seems to work just fine in Ubuntu - I'm not sure what difference, if any, they do in their packages:
https://packages.ubuntu.com/cosmic/libvorbis0a
https://packages.ubuntu.com/cosmic/libvorbisfile3

I compiled the same version from xiph.org as mentioned above. Digging a bit more in Windows, the issue is ov_open fails:
https://github.com/wesnoth/wesnoth/blob/master/src/sound_music_track.cpp#L98

The problem seems to lie in vorbisfile.c:
https://github.com/xiph/vorbis/blob/master/lib/vorbisfile.c#L335

The return code is -2 after which OV_ENOTVORBIS - presumably 'error: not vorbis' - is passed all the way back to Wesnoth. I find it hard to read old-school C code with the heavy use of abbreviations, but is this the bit where people give up and just say 'upstream problem'?

**Comment by GregoryLundberg** [comment]
As of this morning, I see Arch Linux has pushed out a new sdl2_mixer library (2.0.4) which adds a new library: opusfile (0.11).

**Comment by gfgtdf** [comment]
> the issue is ov_open fails:

The documentation ( https://xiph.org/vorbis/doc/vorbisfile/ov_open.html ) explicitly says that it does not work on windoes, is says you have to use ov_open_callbacks, (which you probably have to use anyways to support utf filenames on windows, we actually doa very similar thing with our sdl calls)

**Comment by Wedge009** [comment]
That's a shame. I expected the code to be portable but clearly in this case it's not. I can't comment on whether or not it works on OSX, though.

**Comment by CelticMinstrel** [comment]
Hmm. I'd say someone should consider testing it on OSX and enabling there if it works... or maybe just rewrite it to use the more portable method.

**Comment by Wedge009** [comment]
I did a bit more reading of the Windows-specific caveat and it seems the issue is related to the myriad of C run-times that are usually running on a system ('DLL hell'). At any rate, it does mention `ov_fopen()` as another alternative to `ov_open()` - as best as I can tell this effectively combines the operations of `fopen()` and `ov_open()`, which is what [lines 89-103](https://github.com/wesnoth/wesnoth/blob/master/src/sound_music_track.cpp#L89-L103) is doing anyway. So I replaced that entire block with a single call to `ov_fopen()` - the subsequent ov operations only depend on the OggVorbis_File object anyway.

This seems to work on Windows and Linux - the only 'disadvantage' being that since the title strings are now read directly from the music ogg files instead of [sound-utils.cfg](https://github.com/wesnoth/wesnoth/blob/master/data/core/macros/sound-utils.cfg#L154), the strings are no longer translated. But that may well be as it should be.

I'd like this to be tested by someone who has OSX access, though, otherwise I'd submit my changes as a pull request. At the moment I've used the existing pre-processor commands to continue excluding `__APPLE__`.

**Comment by gfgtdf** [comment]
> So I replaced that entire block with a single call to ov_fopen() 

As i said before, this might not work with nonasii filenames on windows, I think to fully support this on windows, even for users which have uncommon chracters in their windows usernames we rally need ov_open_callbacks.


to construct the ov_callbacks, the file https://github.com/wesnoth/wesnoth/blob/master/src/filesystem_sdl.cpp can be pretty muhc used as a blueprint for what to do.

**Comment by Wedge009** [comment]
I didn't miss what you said before but it isn't clear to me what to do for call-backs so I just had a go with ov_fopen(). At the very least, (I think) this restores cross-platform portability. There are no exotic Unicode characters used in the music file names or track titles at present - if that's desired, I'd say that's another enhancement.

**Comment by Wedge009** [comment]
I just did a test with the ø character - it can't be read if it's used in the file name, but it's read just fine if used in the track title.

**Comment by gfgtdf** [comment]
> There are no exotic Unicode characters used in the music file names at present 

It is not nessesary that the 'bad' chracter appears in the filename, It'e enough if chracter appear anyhwere in the path, If an addons a uses a musicfile b.ogg, then the full path is usually c:/users/<username>/documents/My Games/Wesnoth 1.14/data/addons/a/music/b.ogg
or wheever the user put his userdata dir, If the username of a user is for example 'Wedge_ø' then reading the file will fail for him.


> or track titles 

The track names are irrelevant here,

**Comment by Wedge009** [comment]
I thought the file name string used here is only relative. Does fopen() handle unicode characters?

**Comment by Wedge009** [comment]
A quick research suggests handling of non-ASCII characters is inconsistent across different operating systems. Which says to me this is a limitation beyond what we're just focused on here with respect to supporting ogg files use of libvorbis.

**Comment by Wedge009** [comment]
I remember this discussion and given the software support is available, there's nothing further to do specifically on the software side, I don't think. If we get any further music contributions, opus is an option. The only way I'd be comfortable for Wesnoth to switch to opus for its existing music is if the artists provide lossless copies (assuming they aren't available for the project somewhere else already) and encode to opus format directly from the original source.

**Comment by CelticMinstrel** [comment]
Was the support for reading Vorbis metadata on Windows ever pushed to master? Do we have a separate issue tracking that?

I'm thinking it should be used only as a fallback if a title isn't explicitly set in WML, though.

**Comment by Wedge009** [comment]
#3851 seems to be against master. I suppose only using it as a last resort could be a separate issue, this one seems to be focused specifically on use of the opus codec.

**Comment by CelticMinstrel** [comment]
Yeah, I can see that, so I've no issue with closing this.

**Comment by AI0867** [comment]
Using `ov_open_callbacks` seems fairly straightforward, similar to what `SDL_RWops` does. Using `fopen` (and if `ov_fopen` falls back to that, `ov_fopen`) is *not* reliable on windows, it just appears to work fine if you're using ASCII-only paths.

Is there currently an issue open for that, or should I create a new one?

**Comment by Wedge009** [comment]
I recall the information was that Unicode path support was very much OS dependent, and you seem to have more knowledge than I do regarding its reliability in Windows. This issue was specific to opus support and I seem to recall the odd issue here or there discussing the complexities of non-ASCII characters in path names, but I can't find them again right now so maybe it's best to submit any concerns on this as a new issue.

(The closest I could find was #2037 but that's just dealing with spaces in relation to compiling.)
