### ISSUE TITLE
Error message uses absolute path

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3777]
This line prints the absolute path. Usually error messages don't do that.
https://github.com/wesnoth/wesnoth/blob/550c686e7b83e9465cd2811278c48f5c7db1069a/src/sound.cpp#L714

What does `track.file_path()` need to be replaced with?

**Comment by alan-llin** [comment]
I believe it was intentional that they used `track.file_path()` for easier debugging. otherwise they would probably use `track.id()`.

**Comment by CelticMinstrel** [comment]
Error messages really shouldn't ever print an absolute path since it could leak the user's login name.

**Comment by ProditorMagnus** [comment]
Some more

20181231 17:17:15 error config: error reading usermade add-on 'C:\Users\Ravana\Documents\My Games\Wesnoth1.14/data/add-ons/Ageless_Era/_main.cfg'
20181231 13:12:44 error filesystem: Not opening 'C:\Users\Ravana\Documents\My Games\Wesnoth1.14/data/add-ons/Ageless_Resources/general/images/attacks/sunburst.png' due to case mismatch.

**Comment by jostephd** [comment]
I don't understand why this is a problem. Errors should usually be verbose to make debugging easier, and they aren't sent to wesnothd or anything, only to the log file, so who exactly are we censoring them from?

**Comment by ProditorMagnus** [comment]
I believe it is in case some people use their real name as username.

**Comment by CelticMinstrel** [comment]
People paste log messages in error reports. Some people don't take care to ensure their username isn't in the log. Some people might not care, but we shouldn't create opportunities for people to accidentally include their username (which could be their real name) in a report.

For WML files, the WML-visible path (ie, relative to the data folder or the addons folder) is entirely sufficient to track down the offending file, so there's no need to give any more info than that. For assets (which includes translations), it's a bit more tricky since they're drawn from all over the place; you'd probably need to do some sort of sanitization similar to what I did in the report command-line option (the option that prints out all the versions of dependent libraries and stuff).
