### ISSUE TITLE
SoF - Sc7, Alanin apparently doesn't know what kind of unit he is

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3786]
https://forums.wesnoth.org/viewtopic.php?p=636373#p636373
Feedback from 'LordWolfDan', (4)

> - It seems good, but there could be some more. Just saying. Also, if you manage to turn Alanin from dragoon to cavalier, the same message pops out:
_"I'm a **dragoon**, with Haldric II's personal bodyguard. I was sent on a mission in the northlands, and now elvish horsemen are chasing me. I barely evaded them."_

So, changing the message to make it sensitive to what kind of unit he is seems appropriate.
~While I'm at it, how about changing '_with Haldric II's personal bodyguard_' to '_part/one of Haldric II's personal bodyguard._'~ I realize now that the meaning is 'I'm with [his] bodyguard.' Which makes sense. Oops.

**Comment by AI0867** [comment]
I'm rather late to the party, but this doesn't seem like a change that was actually needed to me. He's a cavalryman of some sort, in service to the crown. What level he is is irrelevant.

**Comment by Konrad22** [comment]
Cavalryman is a unit of a specific level. Your argument would apply if he claimed to be a rider or something like that.

**Comment by CelticMinstrel** [comment]
While this works, I kinda think it'd be better to do this via variable substitution.

Although... that might result in embedding something like `$(tolower('$type.name'))` which could be more confusing than helpful to the translators...?

**Comment by AI0867** [comment]
> Cavalryman is a unit of a specific level. Your argument would apply if he claimed to be a rider or something like that.

If a knight levels up during a scenario, should he suddenly no longer be referred to as a knight?

I intentionally referred to him as a cavalryman in my comment, because that certainly describes what he is, despite the fact that it's neither the original name nor the one you added.

I think you're focused excessively on [Gameplay and Story Integration](https://tvtropes.org/pmwiki/pmwiki.php/Main/SlidingScaleOfGameplayAndStoryIntegration) here. Unit type names are simply a convenient abstraction.
