### ISSUE TITLE
problems of negative value in heals ability

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#3811]
In heals ability, we find the same problem of negative values ​​with leadership, and if we can use sub as a substitute, then if a unit with positive heals and a unit with sub heals are adjacent to the same patient, both units will use healing_anim, which is not always desired. Finally the devellopeur of addons who use negative heals might not want to revisit the wml code.

```
[unit]
    type=Dark Adept
    side=1
    x,y=9,7
    [modifications]
        [object]
            apply_to=new_ability
           [abilities]
 [heals]
        value=-4
        id=healing
        affect_allies=yes
        name= _ "heals -4"
       
        affect_self=no
      affect_enemies=yes
        [affect_adjacent]
        [/affect_adjacent]
    [/heals]
[/abilities]
        [/object]
    [/modifications]
[/unit]
[unit]
    type=Elvish Fighter
    side=1
    x,y=10,6
[/unit]
[unit]
    type=Elvish Druid
    side=1
    x,y=10,8
[/unit]
[unit]
    type=Vampire Bat
    side=1
    x,y=10,7
[/unit]
```

**Comment by newfrenchy83** [comment]
i propose a fix here https://github.com/wesnoth/wesnoth/pull/3812

**Comment by jostephd** [comment]
Hi, first of all thank you for posting WML code, that's very helpful to us. However, you've identified two separate problems here, so let's take them one at a time.

> In heals ability, we find the same problem of negative values ​​with leadership,

Issues should be self-contained, @newfrenchy83, so let's spell this out: the problem you describe here is that if a unit is affectd both by a "heals -8" ability and by a "heals -4" ability, then "heals -4" gets applied because `-4 > -8`, but we'd like it to choose -8 because it's larger in absolute value. This was done recently for leadership in #3774.

In the code you posted, did you mean for the Druid to be on `side=2`? With that change, the Bat will be affected both by the Adept's `heals -4` and by the Druid's `heals +8`. I am guessing that on current master the Bat gets +8 and that we'd instead like the Bat to get +4 (max of positive healing plus max of negative healings, as done in #3774 for leadership). Is this correct? (When you opened the issue you should have spelled out explicitly what the current behavior is and what the desired behavior is.)

> and if we can use sub as a substitute, then if a unit with positive heals and a unit with sub heals are adjacent to the same patient, both units will use healing_anim, which is not always desired.

This is a slightly separate issue: it's only about graphics, not about game mechanics. We might fix the two issues separately.

However, what interests me is that you said the unit with positive heals shouldn't play healing animation. As I said above, I assumed the desired behavior, in your example modified so the Druid is on side=2, is for the Bat to be healed by the DA (negative healing) _and_ by the Druid (positive healing), for a grand total of +4 HP. That implies both the Druid and the Adept should play their healing animations. Do you agree? If not, what do you think should happen?

Perhaps I misunderstand here because I don't understand what the workaround with `sub` is, exactly.

> Finally the devellopeur of addons who use negative heals might not want to revisit the wml code.

Oh, definitely. Compatibility is important!

**Comment by newfrenchy83** [comment]
For the animations i think what this depend of the case, in case of positive value and a sub value, have both anim is a good idea, but if someone use negative value AND sub then, this will be a problem and also by example if heals value= -8 and other sub =4 then patient healed to -12.

**Comment by jostephd** [comment]
If unit A gets -12 because unit B had heals value-8 and unit C had heals sub-4, I think both B and C should animate, since they both contribute to the result. What I'm not sure about is what to do when a unit is adjacent, say, to two Druids, or to a Druid and a Shaman: should both helpers play their animations, or just one?

However, there's no sense in discussing what should be animated before we decided what should _happen_, so let's nail down the desired gameplay mechanics first. I asked some questions about that, particularly what the desired behavior is / what the rule should be. Please answer.

**Comment by newfrenchy83** [comment]
the rule should be if b heals value=-8 and c value=-4 then a healed -8, or if b value=8 and ce value=-4 then a healed +4, but actuallly, it is -4 or +8.

**Comment by newfrenchy83** [comment]
https://github.com/wesnoth/wesnoth/pull/3788 is another fix for this issue.

**Comment by jostephd** [comment]
> the rule should be if b heals value=-8 and c value=-4 then a healed -8, or if b value=8 and ce value=-4 then a healed +4, but actuallly, it is -4 or +8.

Agreed! Is that what #3812 implements? Does #3812 supersede #3788?

**Comment by newfrenchy83** [comment]
326/5000
In fact, I do not really know which one to choose, either specifically modify heals.cpp https://github.com/wesnoth/wesnoth/pull/3812 or modify effect constructor, replace the get_composite_value call with highest ("value"), and replace the change for leadership with a simple get_composite_value call https://github.com/wesnoth/wesnoth/pull/3788, although I would rather go for the second option.

**Comment by gfgtdf** [comment]
> Perhaps I misunderstand here because I don't understand what the workaround with sub is, exactly.

the 'workaround' is basicillay to _never_ use value= for negative values any always use sub= instead.
