### ISSUE TITLE
TRoW - Sc22, loyal Cuttle Fish lacks the 'loyal' marker

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3842]
![inky](https://user-images.githubusercontent.com/39015360/50729758-7da3a800-113f-11e9-8c9f-2263443f7bf6.png)

**Comment by Wedge009** [comment]
I not sure if the loyal markers should only really apply to your own team's units, so you know which ones are especially valuable because of that trait. On the other hand, I suppose you could argue it's good to know if an enemy is a loyal unit so you can deprive them of that advantage (then again, killing non-loyal enemies only reduces an enemy leader's upkeep costs...).

I wonder if this is another case of random monsters not having their own side, as the blue team in this scenario is Jevyan's undead.

**Comment by Konrad22** [comment]
I'm only filing an issue because it is inconsistent. The Cuttle Fishes(?) from the scenario before had their 'loyal' markers. Same for all those reinforcements they were getting.

**Comment by Konrad22** [comment]
Same for Inkys friend Squiddy.

**Comment by nemaara** [comment]
Addressed by fe105f9.
