### ISSUE TITLE
removing server 3 & 2 from list

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3873]
Server 2 & 3  can't be updated for some reason (ask shadowm why, but they seem to be permanently lost)

As they don't work with 1.14.x, there's no use having them shown on the server list ingame.

**Comment by shikadiqueen** [comment]
server2 is a lost cause because of the operating environment, but server3 is something that Soliton and I are looking into fixing hopefully soon.

**Comment by shikadiqueen** [comment]
server3 (basilic) was swapped with server2 (gonzo) since the latter can't be updated at this time, and upgraded and made to run a current 1.14 build. I've readded it.

I know there's a string-freeze on 1.14 right now, but one string for this particular case shouldn't kill anyone, and IIRC old translations for it may get resurrected on the next pot-update for translations that were msgmerged correctly.

**Comment by jostephd** [comment]
Maybe we should uncomment server3.wesnoth.org too but update the DNS? That way we'll be able to re-add server3 without players having to upgrade.

**Comment by soliton-** [comment]
What kind of DNS update do you have in mind?

**Comment by jostephd** [comment]
There are three servers, A, B, and C. Normally server.wesnoth.org points to A, server2.wesnoth.org to B, and server3.wesnoth.org to C. I propose to have the names server2.wesnoth.org and server3.wesnoth.org permanently uncommented in the cfg file, but when server B say is not available, make the DNS name server2.wesnoth.org point to server A's IP address rather than to server B's. This way, when say server2 is unusable it is made unavailable to all players without them needing to upgrade, and when it's returned to service it's made available to all players again without them needing to upgrade or downgrade.

**Comment by soliton-** [comment]
Seems a bit confusing to get to server.wesnoth.org when you select server2/3 but that could be done certainly.
