### ISSUE TITLE
Dark Forecast, enemy units can walk on unwalkable terrain/deep water

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3891]
That's probably not a bug, the real problem is that there is nothing telling the player(s) about it, so it's somewhat a tomato surprise once you run into it.

So, please add a note and warn the player(s).

**Comment by gfgtdf** [comment]
ftr, it seems like it can even walk impassable on https://github.com/wesnoth/wesnoth/blob/1.14/data/multiplayer/scenarios/2p_Dark_Forecast.lua#L225

**Comment by Pentarctagon** [comment]
Or alternatively just don't use terrain that units can't normally enter.

Either way though, having an enemy unit go onto "Impassable Mountains" to attack me was a very strange thing to see.

**Comment by jostephd** [comment]
Maybe it's because an enemy unit could in theory spawn on a void/impassable hex that's only adjacent to other void/impassable hexes? I think I saw once a replay where the players' units where in the NW corner just as an enemy wave spawned in that corner so some of the enemy units spawned inside the wall (and of course they had 0% terrain defense, so they got killed like sitting ducks).

**Comment by gfgtdf** [comment]
> Maybe it's because an enemy unit could in theory spawn on a void/impassable hex that's only adjacent to other void/impassable hexes

Hm yes that was my first thought aswell, in that case the better fix it proably just not to make the enemies spawn on such hexes, that are adjacent to at least one walkable hex, shouldnt be hard to implement.

> so they got killed like sitting ducks

Wait, if they got killed, doesnt that means that did alread spawn on a localtion where they coudl in theor escape from (since your unti can onyl walk on walkable tiles?)

**Comment by jostephd** [comment]
There were two enemy units. Unit A spawned on an impassable hex surrounded by impassable hexes. Unit B spawned on an impassable hex adjacent both to unit A and to some passable hexes. Unit B had 0% terrain defense and was easily killed on side 3's turn. On the subsequent side 1 turn unit A moved to where unit B was and was killed on the subsequent side 3 turn.

**Comment by Wedge009** [comment]
#3753 suggests the whole scenario is full of 'tomato surprises'.

**Comment by Pentarctagon** [comment]
Changed from Enhancement to Bug due to #5152.

**Comment by PiotrMakarewicz** [comment]
> to anyone who wants to try to fix this: Note that the 2p_Dark_Forecast.lua is loaded directly from the clients. So changing the spawn mechanics by just editing that lua file will cause OOS with older wesnoth versions.

Can this bug be left in 1.14 and fixed in the 1.15 only? It would solve the problem of the OOS error.

**Comment by gfgtdf** [comment]
> Can this bug be left in 1.14 and fixed in 1.15 only? It would solve the problem of the OOS error.

Its not like we cannot fix it in 1.14, it just means people that fix this have to be a little more careful.

**Comment by Pentarctagon** [comment]
Adding a fix to 1.14 that we know will cause OOS errors sounds more like trading one problem for another.

**Comment by gfgtdf** [comment]
> Adding a fix to 1.14 that we know will cause OOS errors sounds more like trading one problem for another.

What i was saying is that while the most obvious fix would indeed cause OOS erros, its not that hard to fix it without causing  OOS erros.

**Comment by Pentarctagon** [comment]
Would the fix to this simply be to remove the lines https://github.com/wesnoth/wesnoth/blob/f64af2e6a5c0578d32a969096a52acdaf2a84d2f/data/multiplayer/scenarios/2p_Dark_Forecast.lua#L225-L227 and then adding `passable = true` to the create_unit call above it?
