### ISSUE TITLE
wmlparser3 opens tmp file 2 times then crashes

### ISSUE THREAD

**Issue by LovCAPONE** [wesnoth/wesnoth#3927]
On the Windows platform, to recreate the issue simply call the wmlparser3.py script with "--test” as command line arguments (or parse wml fragments as is like in the script’s sample in its header).

The source of the problem is that on line 374 a temporary file is created:

```python
        temp = tempfile.NamedTemporaryFile(prefix="wmlparser_",
                                           suffix=".cfg")
```

And at line 622 it is opened again without being ever closed:

```python
        for rawline in open(input, "rb"):
```

This issue doesn’t affect Unix platforms as seen in the documentation for temporary files:
> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).

**Comment by jostephd** [comment]
If the problem is on line 622, we can simply do `temp.seek(0); self.temp = temp` in parse_binary, and then use self.temp (the already-open file handle) instead of calling `open` on self.path:

https://github.com/wesnoth/wesnoth/blob/267933c22f4cdfd6f99f8fe5ab562b4867cf08d9/data/tools/wesnoth/wmlparser3.py#L370-L381
https://github.com/wesnoth/wesnoth/blob/267933c22f4cdfd6f99f8fe5ab562b4867cf08d9/data/tools/wesnoth/wmlparser3.py#L620-L623

However, what's the value of self.no_preprocess in your case? If preprocessing is enabled self.preprocess passes the filename to wesnoth, which will try to open it:

https://github.com/wesnoth/wesnoth/blob/267933c22f4cdfd6f99f8fe5ab562b4867cf08d9/data/tools/wesnoth/wmlparser3.py#L407

and I suppose that would raise an error. I'm not sure if there's a better solution than using [mkstemp](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) or NamedTemporaryFile(delete=False) and manually removing the file afterwards?

**Comment by LovCAPONE** [comment]
@jostephd That’s the first solution I thought of, but then I realize that I didn’t consider the “preprocess” function that needs the wml code into a file and will reopen the temporary file.

So seems like the only solution, as you said, is to create a temporary file and delete it manually in order to support all target platforms. So if you give me the green light, I can restructure the parser to take this solution in account.

**Comment by jostephd** [comment]
Sure, go for it. How would we ensure the tempfile is always deleted? Using a [`__del__`](https://docs.python.org/3/reference/datamodel.html#object.__del__) method plus an [atexit](https://docs.python.org/3/library/atexit.html#atexit.register) callback (since `__del__` isn't guaranteed to be called)?

**Comment by LovCAPONE** [comment]
@jostephd I took the atexit choice to solve it, you can take a look at #3930.
