### ISSUE TITLE
Status table 'scroll to' malfunctions with hidden sides

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4029]
(I'm talking about this thing in the status table.)
Using 'scroll to' for side 2 does nothing and using 'scroll to' for side n > 2 scrolls to side n - 1.
[HttT-The Sceptre of Fire-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/3091670/HttT-The.Sceptre.of.Fire-Auto-Save1.gz)

**Comment by jostephd** [comment]
Probably because of this part:

https://github.com/wesnoth/wesnoth/blob/74c1f204e554ea6dad8879eec2bf42e880a00255/data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg#L438-L447

**Comment by jostephd** [comment]
Okay, it's pretty simple.

https://github.com/wesnoth/wesnoth/blob/74c1f204e554ea6dad8879eec2bf42e880a00255/src/menu_events.cpp#L162-L164

https://github.com/wesnoth/wesnoth/blob/74c1f204e554ea6dad8879eec2bf42e880a00255/src/gui/dialogs/game_stats.hpp#L38

https://github.com/wesnoth/wesnoth/blob/74c1f204e554ea6dad8879eec2bf42e880a00255/src/gui/dialogs/game_stats.cpp#L261

https://github.com/wesnoth/wesnoth/blob/74c1f204e554ea6dad8879eec2bf42e880a00255/src/menu_events.cpp#L165

`selected_index` is passed by reference. `game_stats` sets it to a _row index_ into the table, but `menu_events` interprets it as an index into the teams() vector, which doesn't work because the row index [doesn't count hidden teams](https://github.com/wesnoth/wesnoth/blob/74c1f204e554ea6dad8879eec2bf42e880a00255/src/gui/dialogs/game_stats.cpp#L84-L165). The easiest fix is probably to make `game_stats` return a reference to the team. (Note that "Scroll To" is the "OK" button of that dialog.)
