### ISSUE TITLE
Deprecate helper.get_sides

### ISSUE THREAD

**Issue by spixi** [wesnoth/wesnoth#4049]
`helper.lua` contains the method get_sides(cfg), which is member of the `wesnoth` table. `helper.get_sides(cfg)` should be deprecated in favor of `wesnoth.get_sides(cfg)`.

**Comment by CelticMinstrel** [comment]
I think there was a genuine reason for it not to be deprecated, but I'm not quite sure. Does `wesnoth.get_sides` do the exact same thing (returning an iterator over matching sides)? Or does it return a list rather than an iterator?

That said, even if it _should_ remain in use, it should at least be moved from the helper module to somewhere more appropriate.

**Comment by spixi** [comment]
`wesnoth.get_sides(cfg)` returns a list, but `ipairs` works for lists and iterators, so an explicit function, which returns an iterator is not really useful. As far, I can see, `helper.get_sides(cfg)` is unused in mainline. I don't know about UMCs, however.

There is actually a third `get_sides(cfg, key_name, filter_name)` function in `/data/lua/wml_utils.lua` which works somewhat different, because some WML tags like `[remove_shroud]`, `[place_shroud]`, `[scroll]`, `[scroll_to]`, `[scroll_to_unit]` and `[modify_ai]` support a standalone `side=` and a regular standard side filter. So I would keep this one, but only for internal usage in the WML engine.

**Comment by CelticMinstrel** [comment]
On the contrary, I'd say a function that returns an iterator _is_ useful at least in a general case, as it's more efficient than returning a list. That said, there's probably no discernible difference for short lists, which includes the sides list. I'm fine with marking `helper.get_sides` deprecated (probably at the bottom of the file with all the other deprecated things) in favour of using _ipairs_ on _wesnoth.get_sides_.

The other _get_sides_ you mention is basically for internal usage in the WML engine, yes (though it's placed in wml_utils so that others can use it in their custom WML tags if they so desire).

**Comment by spixi** [comment]
The table `wesnoth.sides` is redundant according to https://github.com/wesnoth/wesnoth/blob/02122f2eaef285c5f48ae6476b1869a3ae15a145/src/scripting/game_lua_kernel.cpp#L4427 The iterator uses that buffer instead of determine the current values each time.

I guess, the length of the lists does not really matter, because appending values to a vector and looping them has O(N), the same run-time behavior like an iterator over a vector. There is also no copy of values involved, references are cheap.

I also saw that `std::vector<int> get_sides_vector(const vconfig& cfg)` actually supports a single inline `side=` and a standard side filter. The only purpose of `wml_utils.get_sides` seems to be providing support for WML tags with non-standard names for `[filter_side]` and `side=`.

**Comment by CelticMinstrel** [comment]
> I guess, the length of the lists does not really matter, because appending values to a vector and looping them has O(N), the same run-time behavior like an iterator over a vector. There is also no copy of values involved, references are cheap.

It probably matters for large lists where you break early - you're only processing the first few elements. If it's a list, the entire list needs to be generated first, including the many elements you don't even need, but if it's an iterator, that's not an issue.

I guess there's some truth in the "references are cheap", but I'm not sure if that's relevant when you're _generating_ the list, which is probably what `wesnoth.get_sides()` does. True it's a list of references, but it still needs to be generated.

**Comment by stevecotton** [comment]
Can this be closed as done in aed779fb6aca8b8d01faf1a5094d0e5792b4cac7 ?

**Comment by CelticMinstrel** [comment]
That, plus there's now `wesnoth.sides.iter` which fills in for both `helper.get_sides` and `helper.all_teams`. As for `wesnoth.get_sides`, that's now `wesnoth.sides.find`.
