### ISSUE TITLE
[TSG] Using --campaign-scenario misses characters, and entering bandit branch using :next

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4050]
Please would someone add a [low-priority] tag? I'm logging this one so that I can omit the details from https://r.wesnoth.org/t49772 .

Trying to skip the early scenarios with `--campaign="The_South_Guard"` `--campaign-scenario="07b_Pebbles_in_the_Flood"` doesn't work, as the later scenarios don't add the necessary characters. To reach that scenario with debug mode, you have to
* collect Sir Gerrick in 01 before doing the :next
* in 05, trigger the [sighted] events to get the bandit to join
* in 05, finish by killing the undead leaders instead of using :next

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/compare/fda67b043678...bf9a2503c044.

**Comment by nemaara** [comment]
I forgot to mention that I don't think it's possible to use :n to get to the bandit path since there doesn't seem to be a way to change the default next_scenario tag, but you can just use :cl instead.

I also missed a small thing in the above commits: https://github.com/wesnoth/wesnoth/compare/bf9a2503c044...7df36dc6adb6..

**Comment by stevecotton** [comment]
Thanks!

**Comment by sevu** [comment]
But `:cl`
