### ISSUE TITLE
wmllint: asserts if [unit_type]'s advances_to is before the id

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4102]
The code checking the `[unit_type]` data asserts if it meets the `advances_to` before the `id`:

https://github.com/wesnoth/wesnoth/blob/23ab6542a35c3d2049b7237178c4661565ea5131/data/tools/wmllint#L1520-L1521

Ageless Era's preprocessed.cfg has all the keys of `[unit_type]` sorted in to alphabetic order, so this triggers on it.

**Comment by jostephd** [comment]
wmllint should really use wmlparser3 or something so it doesn't depend on order of lines.

**Comment by stevecotton** [comment]
I'm wondering if it's a tool to fix, or a tool to just leave as-is.

**Comment by ProditorMagnus** [comment]
I did something similar which I use to validate the ageless preprocessed WML https://github.com/ProditorMagnus/WML_tree_tools/blob/master/py_files/find_patterns.py

**Comment by jostephd** [comment]
@stevecotton I don't know about wmllint specifically, but in general, time spent on writing lint tools is time well spent. We can make the effort incrementally too, port the wmllint checks to wmlparser3 one by one...

**Comment by soliton-** [comment]
In general it's difficult to use a proper parser for a tool like wmllint that for example should upgrade old syntax or check macro usage where a parser would perhaps error out or not give you the needed info because macros are already expanded. Using comments as directives as is done now will likely also be very difficult to support.

Certainly some checks like this one would benefit from a proper parser though...

**Comment by jostephd** [comment]
> Using comments as directives as is done now will likely also be very difficult to support.

I think it's possible. The parser would need to remember a line number for every syntax element, and the line number that every comment appeared on, but it's not like we have to invent the wheel.

Agree with your remark about old syntax / macro usage.
