### ISSUE TITLE
In South Guard, when you side with humans, outlaws can't attack.

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#4115]
I have found out that when you select to side with outlaws in Wesnoth 1.14.7, South Guard, scenario 5 Choice in the Fog, then outlaw units you receive can move but can't attack for the turn when you receive them.

**Comment by GregoryLundberg** [comment]
It's been a while but, if memory serves, they've already had their movement and attack phase, and, originally, could not move at all. So I set their movements to zero (allowing them to move) so you could move them out of harm's way instead of receiving a bunch of units, possibly quite damanged, only to watch them die.

I see the current behavior as correct. But will leave this Issue open in case someone else wants to take it up.

**Comment by jostephd** [comment]
I tested this in debug mode, giving Afalas some gold on turn 1 and discovering him on turn 3, and found that:

- Urza Afalas can move and attack
- Afalas units outside the encampment can move and attack
- Afalas units in the encampment - that's units that were recruited in Afalas' last turn - can move but can't attack

I'm guessing that what happens is that that engine sets attacks_left=0 on a newly-recruited unit and sets it to 1 when a side turn starts, so Afalas and the units that he recruited on turn 1 had had their attacks_left set to 1 at the beginning of turn 2, but the units he recruited on turn 2 still had `attacks_left=0` when my scout saw them, at the beginning of turn 3. So maybe we want the "Deoran sides with Afalas" event to also set attacks_left on all of Afalas's units to the same value? It's confusing that some of them can attack and some can't.

Other events that would normally take place at the start if side 2's turn won't happen either for the turn that Deoran joins Afalas on. For example, Afalas' units won't receive poison damage, rest healing, or village healing on that turn.

@nemaara might know more.

**Comment by GregoryLundberg** [comment]
I can answer that: you are correct. IIRC I specifically reset the movement-used to 0, by hand, so the player could move his units.

**Comment by jostephd** [comment]
> IIRC I specifically reset the movement-used to 0, by hand, so the player could move his units.

Yes, you have:

https://github.com/wesnoth/wesnoth/blob/aa901478c22be3dc0c32cdcf4c4807f19af2f428/data/campaigns/The_South_Guard/scenarios/05_Choice_In_The_Fog.cfg#L793-L813

Should we add `attacks_left=0` or `attacks_left=1` there too?

**Comment by GregoryLundberg** [comment]
Well, my opinion was, and remains, this is as-intended. But you've found where you need to change and I won't argue it either way.

**Comment by jostephd** [comment]
I don't know whether to set attacks_left=0 or attacks_left=1 or just to leave it as it is now. However, I think that unless we set attacks_left=1 on all units we should add a narrator message warning that some outlaw units can't attack this turn. Otherwise, the player might start executing an attack plan and find only partway through that some outlaws can't attack.

**Comment by GregoryLundberg** [comment]
Agreed. If I'd have thought of it, I'd have done the narrator warning that many of the outlaw troops joining your forces are exhaused from battle and cannot attack this turn, but, nonetheless, have promised to withdraw to better positions.

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/compare/ff9b8d7734f2...b700678c353c addresses this issue; please reopen if anything else is desired or this isn't satisfactory.
