### ISSUE TITLE
Adding woptipng.py to GUI of python maintenance tools

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4174]
Woptipng is written in python – and such, it can be included to the GUI.pyw

Unlike the other tools it requires some additional software to be installed though:
- optipng
- advancecomp
- imagemagick
- and woptipng itself, which is not in data/tools/, but in utils/ dirctory. This directory is by default not packaged – it's only in Debian based distros (package wesnoth-1.14-tools) and the git version.

So there would need to be a check if the software is available, maybe explaining it to the user or just hiding it.

**Comment by Elvish-Hunter** [comment]
I looked into this issue.
While the idea on its own makes sense, the real problem is (as you correctly pointed out) woptipng itself.
First of all, we must keep in mind who the intended audience of GUI.pyw is (from the README in data/tools):

> WML developers frightened of the command line.

Now, such kind of developers work mostly on Windows, and if you want to try running woptipng on Windows you need to download all the packages you listed. However, only imagemagick has an installer for Windows: all the other packages are "portable", so a WML developer has either to place their .exe files in the same directory of the script (assuming that it'll be considered as your working directory) or to add their paths to the PATHEXT environment variable (this is needed by the `shutil.which()` function).
As you can see, for your average UMC author (that is, a potential GUI.pyw user) woptipng is too complex to get running. On Linux, instead, it's easy to install the required dependencies with a package manager, but Linux users aren't usually afraid of the command line, are they?
Because of this, I'm going to close the issue; however, feel free to reopen it if you think my reasoning isn't correct.
