### ISSUE TITLE
The --validate-addon option doesn't print any error if the addon's directory is typo'd

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4224]
If the add-on's directory is typo'd, --validate-addon gives no error message about it.
```
wesnoth-1.15.dev.debug --nocache --validate-addon Tactics_Puzzlessssssssssssss
Battle for Wesnoth v1.15.0+dev
...
Setting mode to 1920x1080
Checking lua scripts... ok
```

Comparing that with non-typo'd run, which mentions an error in the add-on.
```
wesnoth-1.15.dev.debug --nocache --validate-addon Tactics_Puzzles
Battle for Wesnoth v1.15.0+dev
...
Setting mode to 1920x1080
20190814 18:25:15 error validation: Invalid key 'path=' in tag [textdomain]
at ~add-ons/Tactics_Puzzles/_main.cfg:5
Checking lua scripts... ok
```

**Comment by stevecotton** [comment]
It seems there's more missing with `--validate_addon`. Even when given `--nocache --validate-addon Tactics_Puzzles --preprocess-defines=CAMPAIGN_TACTICS_PUZZLES`, it doesn't seem to be checking the scenario files for errors.

**Comment by CelticMinstrel** [comment]
The `--validate` and `--validate-addon` options are not scripting options. They validate WML _as you play_. So, if you use `--validate-addon` but don't play the target addon, then it won't find anything. Also I believe `--preprocess-defines` are not used for these two options.

I'd say the key point about this issue is still true, though - it should complain if you try to validate an addon that doesn't exist. It probably just needs a check somewhere in the command-line post-processing phase.

**Comment by stevecotton** [comment]
Thanks @CelticMinstrel. I misunderstood how --validate-addon is meant to be used, and feel I should share what I have so far, but warn that I'm not working on it now, instead I hope that it will be salvaged by someone else.

Progress so far is in my `user_friendly_validation` branch, in the 0f111af commit that's auto-linked itself to this issue.
