### ISSUE TITLE
HttT S18 A Choice Must Be Made, Orcs and Undead are allied for no reason

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4261]
It would be nice and make more sense if this would be changed, so they are enemies.

**Comment by Wedge009** [comment]
From my recollection of the scenario, I can only suppose that this is done for game-play reasons, to ensure they focus on Konrad's team instead of potentially going for each other. Although I'll grant this seems unlikely given the position of the teams. Perhaps it's possible to update the scenario so that they are independent but the AI gives priority to attacking the player.

Also, I believe the scenario is 18.

**Comment by GregoryLundberg** [comment]
Good idea but would need rebalacing kicking up the difficulty to offset the enemy losses against each other.

**Comment by Konrad22** [comment]
It is close to impossible for the enemy sides to inflict meaningfull losses on each other.

**Comment by Wedge009** [comment]
I don't know about 'impossible', but that was generally my recollection as well - IIRC in this scenario Konrad's team is stuck in the middle and the two enemy sides are on opposite ends of the map. Perhaps Konrad22 can manually edit the scenario file (even if not adding the prioritisation of Konrad's team as a target) and see if there's any discernible difference in behaviour (ie are there significant occasions where the enemies engage each other instead of Konrad's team). Although I suppose there's always the possibility that they will take targets of opportunity (low health, etc) that aren't in Konrad's team.

**Comment by GregoryLundberg** [comment]
One thing to try would be to send disposable units into contact with each opponent and try to draw them into conflict with each other while your main force hides off to the side somewhere, or something similar.  If it's possible to get them to deplete each other's forces, someone will figure it out and the scenario becomes a cake walk.

**Comment by Konrad22** [comment]
Doing so would probably only work if you aim for the orcs and it would be fairly difficult. Maybe even more so than taking the orcs head on.
I put down some explanations how I'd try to do it and why I think it wouldn't be really easier.
[HttT-A Choice Must Be Made Turn 1 explanation.gz](https://github.com/wesnoth/wesnoth/files/3532230/HttT-A.Choice.Must.Be.Made.Turn.1.explanation.gz)

**Comment by stevecotton** [comment]
Is the issue that they're allied, or is it that the user can see they're allied?

For the latter, we can simple set user_team_name to `_ "Orcs"` and `_ "Undead"` respectively, without changing the team_name that makes them allies.

**Comment by Wedge009** [comment]
Up to Konrad22, but I think at the very least the player seeing they are allied in the status table seems odd. From a story point of view there is no indication or reason that the undead and orcs should be allied. From a game-play point of view it seems reasonable for them to gang up on you as your team is right in between them.

If it's possible to change the team names while still keeping them allied against the player I suppose that might be acceptable and maintain game-play balance, though an observant player may wonder why they never see them fighting each other (for example, late in the scenario if the Konrad's team has stayed mainly in the middle and the battle lines are getting thin).

**Comment by Konrad22** [comment]
If possible, I'd like to make them enemies, but have the orcs stay north of the river and the undead south of the river. (If you make them only enemies in name, the player can still easily figure out that they are not actually enemies.)
If they can't clash, then they can't deplete each others units and it matches the story. Why would the orcs  go so far south? Why the undead so far north? Just let them stick to their territories.

If that's not feasible/possible, sure, change just the teamnames shown. A small improvement is still an improvement. ^^
