### ISSUE TITLE
wmlxgettext does not handle objectives.lua's turn counter

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4275]
Running `data/tools/wmlxgettext --domain wesnoth -o temp.pot data/lua/wml/objectives.lua` will find most of the translatable strings in objectives.lua, but it misses both of turn_counter's strings:

https://github.com/wesnoth/wesnoth/blob/62a005f4cfa56259d4467afcd5e8d83a06dc5e65/data/lua/wml/objectives.lua#L57

**Comment by CelticMinstrel** [comment]
Huh? I was pretty sure `wmlxgettext` was already extended for this case... I recall bringing it up quite some time ago when plural strings in Lua was first implemented.

**Comment by jostephd** [comment]
@stevecotton I don't think the turn counter is the problem. Your command indexes `_ "this turn left"` but doesn't index `_("this turn left")`. It seems the parentheses are the problem.

**Comment by CelticMinstrel** [comment]
Um, neither of those are actual strings in _objectives.lua_? Also I'm not even sure what you mean there.

**Comment by CelticMinstrel** [comment]
Also, this thread requires input from @AncientLich, as the person who implemented this version of wmlxgettext and (I'm pretty sure) also implemented the exact feature in this issue report.

**Comment by stevecotton** [comment]
@jostephd the examples you've given don't use the plural feature. We're looking at the feature added in 91c9677b222e, and last bugfixed in 90956117ab7a (#3481).

**Comment by jostephd** [comment]
@stevecotton So the example I gave is an independent bug?

@CelticMinstrel I know those strings don't exist in that file. I was giving a minimal example. If I modify the lua file to have `_ "foo"` that does get picked up by wmlxgettext. If I modify it to have `_("foo")`, that doesn't get picked up.

**Comment by CelticMinstrel** [comment]
Well, `_("foo")` should indeed be picked up, ideally, but that's just a syntactic variant of `_ "foo"`, whereas the code in the opening post of this issue is a separate feature equivalent to `_n("(this turn left)", "($remaining_turns turns left)", turn_count)` in the C++.

**Comment by AncientLich** [comment]
I will investigate this corner case. However I remember that wmlxgettext does not actually parse lua code as a lua parser, but uses it regexpes in order to check and register translatable strings. So if you create a translatable string using custom rules (for example creating a translatable string with custom functions and add them to wesnoth as a variable) than wmlxgettext can't do any magics.

If the corner case fit one of such situations, the issue cannot be considered a bug (because it is impossible to cover every possible programmer choice with regexps) and that case the issue should be considered placed in the lua code itself (although it is a legal lua code)

I will inform you in the following days as soon as I understand better the reasons why the sentence is skipped.

**Comment by CelticMinstrel** [comment]
Could it be that the latest wmlxgettext was committed to master, but not to 1.14? Just a thought.

**Comment by AncientLich** [comment]
I have no clues this moment. I will take a couple of days in order to understand exactly what happened (and the reason of the problem)... I will inform you here (and I will notify when pull request will be ready)

**Comment by stevecotton** [comment]
Hmm - I don't know if it's the right fix, but the code prior to #3481 had a regular expression that would swallow `.*` before the underscore. Changing the code to `c` will add the translation to wesnoth.pot.

```
>>> input=r'turn_counter = _("(this turn left)", "($remaining_turns turns left)", turn_count)'
>>> a = re.compile(r'((?:_)|(?:.*?\s+_))\s*\(')     # a = old version, before #3481
>>> b = re.compile(r'\b_\b\s*\(')                   # b = #3481
>>> c = re.compile(r'.*\b_\b\s*\(')                 # c = re-adding the .* to b
>>> a.match(input)
<re.Match object; span=(0, 17), match='turn_counter = _('>
>>> b.match(input)
>>> c.match(input)
<re.Match object; span=(0, 17), match='turn_counter = _('>
```

**Comment by CelticMinstrel** [comment]
Does it add it to the pot file as a plural string, like this?

```
msgid "(this turn left)"
msgid_plural "($remaining_turns turns left)"
msgstr[0] ""
msgstr[1] ""
```

**Comment by AncientLich** [comment]
The wmlxgettext version published at the dedicated repository already can do it. But I am not committing anything right now because I need: 1) to reboot my fork in order to be allowed to do pull requests 2) to bring some time to understand what happened and if other changes could be needed before adding the pull request.
