### ISSUE TITLE
1.15.1 Campaign menu issues

### ISSUE THREAD

**Issue by Earth-Cake** [wesnoth/wesnoth#4318]
1.15.1: DiD doesn't have a scenario number and difficulty in the campaign menu.

Also, WoV has forum topic in its description. https://forums.wesnoth.org/viewtopic.php?f=8&t=49140

**Comment by Wedge009** [comment]
I'm guessing you meant scenario count - DiD's is present in 1.14 but not 1.15.

Also WoV's forum link may be deliberate but it could also be a left-over from when it was just an add-on. Pinging @sigurdfdragon for his thoughts.

**Comment by stevecotton** [comment]
Speaking of forum links, let's ping @Konrad22 too. Is it time to create (or move the existing) forum thread and UMC replay threads to the mainline section?

**Comment by Konrad22** [comment]
I think it is time indeed to create a subforum for WoV and create some feedback threads as well. It is after all part of mainline now and I doubt it will be removed.
I don't think we should move the UMC replays threads, because they ask a different kind of questions and they have not been made by the 'Content Feedback'.
But the forum thread for WoV would probably do very well in the Mainline Campaign Development forum, but that's sigurds call.

**Comment by sigurdfdragon** [comment]
The forum link is deliberate (along with the version number) for ease of tracking/feedback with both the 1.14 & 1.15 versions. I'm intending to remove them when 1.15 is in it's final stages.

It may be time for a mainline campaign development thread. or it might be easier for me to deal with it if it waits until 1.15 is in the final stages. I'll think about it.

**Comment by Wedge009** [comment]
Weird, the scenario count for DiD is still present in master but not displaying...
https://github.com/wesnoth/wesnoth/blob/ae73e5cd1546997b59e1156d8be3a7a9c0dbf79e/data/campaigns/Descent_Into_Darkness/_main.cfg#L23-L25

**Comment by jostephd** [comment]
> Weird, the scenario count for DiD is still present in master but not displaying...

Some variant of #3443? It does show if the text in parentheses is changed.

**Comment by stevecotton** [comment]
The scenario count for DiD displays in en_US but not en_GB. That seems to be spacing - changing `neighbouring` back to `neighboring` makes the first line split after "orcs", instead of before "orcs", and the scenario count appears.

**Comment by jostephd** [comment]
Is there anything interesting in the `gui/layout` debug log? See https://github.com/wesnoth/wesnoth/issues/3443#issuecomment-414088584

**Comment by Wedge009** [comment]
When I check 1.14.9 release, using French but falling back to default en_US because the translation isn't present, there is no scenario count. I notice that the width for the campaign list is wider (because of translations), making less room for the campaign summary text. So it does appear to be a spacing issue - the spacing appears to be done on the basis of the default en_US text with default en_US layout.

**Comment by nemaara** [comment]
Hi hi hi, I've been testing DiD on 1.15.2 (with all my recent redialoguing and adding events) and didn't see the campaign menu bug. Maybe it got fixed?

**Comment by Wedge009** [comment]
Yes, the layout redesign work-in-progress seems to fit the text in the allocated space now. With #3443 still present, I think we can close this for now but as always, re-open if anyone deems it necessary.
