### ISSUE TITLE
HttT: Delfador's portrait faces left

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4345]
Delfador's portraits faces left:

https://github.com/wesnoth/wesnoth/blob/1.14/data/campaigns/Heir_To_The_Throne/images/portraits/delfador.png
https://github.com/wesnoth/wesnoth/blob/1.14/data/campaigns/Heir_To_The_Throne/images/portraits/delfador-elvish.png

Portraits generally face right or forward. Delfador's portrait should either be flipped or be shown on the right, like Arvith's portrait in AOI.

**Comment by Earth-Cake** [comment]
Showing him on right would be much easier, because if you rotaze him the shading should be changed as well.

**Comment by Wedge009** [comment]
Just wondering, is there a specific reason for the convention that portraits face right vs left? (The placement of the portrait in dialogue?)

**Comment by GregoryLundberg** [comment]
I like the portaits the turn toward the center, yes. If two alternate, it's like they're talking to each other. Flipping usually won't work because, then, the shadows and highlights flip sides. This is especially true if one character is usually on the left but is on the right once or twice, in reply to another.

**Comment by jostephd** [comment]
Further complication here:

https://github.com/wesnoth/wesnoth/blob/1.14/data/campaigns/Heir_To_The_Throne/images/portraits/delfador.png faces left
https://github.com/wesnoth/wesnoth/blob/1.14/data/campaigns/Heir_To_The_Throne/images/portraits/delfador-mentoring.png faces right
https://github.com/wesnoth/wesnoth/blob/1.14/data/campaigns/Heir_To_The_Throne/images/portraits/delfador-mad.png faces forward

(The -elvish portraits are the same)

We probably don't want Delfador's portrait to be shown on the right when he's mentoring and on the left normally, so I guess we need new art here? Unless these specific images happen to look good even flipped.

Also, looking at the portrait I'm not sure what Delfador's dominant hand is. -mentoring and -mad show him holding the book and the staff in the same hand, but I'd expect him to hold the staff in his dominant hand and the book in his non-dominant hand?

**Comment by Wedge009** [comment]
Watching my brother replay the tutorial in 1.15.1 (just for fun, he's coming back after not having played since 1.12) I saw that Delfador's portrait was on the right, probably for the reasons discussed above. Is there an inconsistency to how Delfador's portraits are oriented throughout the campaigns?

And yeah, that's a bit bothersome that mentoring is the odd one out. Do we have the artist available to consult on this? eg Can we simply mirror that one or would that change the artistic intention (while people are generally symmetrical, asymmetry is inherent in all of us)?

**Comment by Wedge009** [comment]
I updated all the left-facing Delfador images I could find, both in HttT and DM, to be displayed on the right side of the dialogue. Basically default Delfador and Delfador-in-elvish-dress in HttT and 'young' and 'old' (but not 'younger') versions of Delfador in DM. Delfador in the Tutorial is already displayed on the right.

Please re-open if I've missed anything. I didn't check if there are other left-facing portraits in other campaigns.

**Comment by jostephd** [comment]
Thanks!
