### ISSUE TITLE
Not all MP lobby links are highlighted

### ISSUE THREAD

**Issue by PiotrMakarewicz** [wesnoth/wesnoth#4387]
I logged off and rejoined the MP server to see the updated tournament announcement and in the new announcement not all the links were highlighted. However, all of them worked on click.

![](https://cdn.discordapp.com/attachments/231976805987385345/626351862475390996/unknown.png)

**Comment by soliton-** [comment]
If you have some idea how to reproduce this that'd be great since you mentioned on next login it worked correctly. Maybe window size is a factor or resizing the window or so.

**Comment by ForPeace-Wesnoth** [comment]
You may take the following steps:
1: Log in to MP server
2: Update server lobby message, adding new links
3: Log off the MP server but do NOT exit the game application
4: Rejoin the server
5: See whether the bug occurs

This is how the bug appeared to me. I should add it was on 1.14.7 Windows version.

**Comment by ProditorMagnus** [comment]
#2934

**Comment by Wedge009** [comment]
Agreed duplicate.

**Comment by soliton-** [comment]
Not sure why this is an obvious duplicate. There is no URL being broken across lines here. Infact no line is word-wrapped or anything. It displays exactly as the motd is set.

Given the reproduction steps I'd rather guess it has something to do with joining the server multiple times? Still odd that 1 of 4 links is displayed correctly.

What is the same is that clicking works and it's just a visual issue though.

**Comment by Wedge009** [comment]
#2934 is a sub-set of this one, then.

**Comment by stevecotton** [comment]
> Given the reproduction steps I'd rather guess it has something to do with joining the server multiple times?

@seanyeh's fix explains this - each URL was only linkified the first time it was shown. I guess the MOTD changed between the two logins in the screenshot, causing one of the 4 URLs to be linkified.

The reproduction steps can no longer be followed on the official server in 1.15, as since f996803cf6262317ce10c70db7c7d8fa73bf32be the MOTD is only shown once. However, I'm sure that @seanyeh's PR fixes the underlying issue.

**Comment by Wedge009** [comment]
I had a look at 1.14.14 release, 1.14.14-dev and 1.15.6-dev. Confirming that 1.15 only displays the message once, 1.14 still has this issue on repeat messages. Thanks for checking on this.

**Comment by stevecotton** [comment]
Backported to 1.14 in b85c5dc8adbc7c2ece48be3f1441aac8a67e6894

**Comment by Wedge009** [comment]
Confirming repeat messages properly display links in 1.14 now. Thanks.

**Comment by seanyeh** [comment]
I would like to point out that I just noticed that we still have issues with recognizing URLs that are within parentheses, which you can see from the motd: `The latest development release is 1.15.6 (https://changelog.wesnoth.org).`

This is because we are tokenizing the texts and checking for things looking like URLs (and parentheses mess that up). Unfortunately, I think this is theoretically "impossible" to get right 100% of the time, because parentheses are allowed in URL's ([example](https://en.wikipedia.org/wiki/Python_(programming_language))). There is no way for a program to know if I meant `https://a.com/)` or `https://a.com`.

A couple possible solutions:
1. Change the motd to have spaces around the parens to make that link work, and accept that this is basically impossible to get 100% right anyway. I don't see this as a big deal honestly
2. A _somewhat-smart_ approach: if we see if a token is surrounded by parentheses, then we can check the inner text to see if it looks like a URL. This may involve some annoying changes but should be doable.

**Comment by soliton-** [comment]
I would simply not count parens as valid in URLs. Sure, maybe technically they are but how useful is it?

The email reader I used to view your notification for example did not consider the closing parensesis as part of the URL regardless if there are matching opening and closing parens or not.

**Comment by seanyeh** [comment]
@soliton- I don't think we can ignore all parens in URLs. Many wikipedia page URLs, for example, have parens. example: `https://en.wikipedia.org/wiki/Python_(programming_language)`. I personally think that getting a URL like this to work is more important than getting urls surrounded by parentheses (e.g. `(http://a.com)`) to work. If we're okay with that, then we can stick to our existing approach

**Comment by soliton-** [comment]
Ok, wikipedia using it is a good point. Curiously that example did work in my email reader as well. I wonder how they implemented that...
