### ISSUE TITLE
Wesnoth does not render well with SDL 2.0.10

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#4510]
### Game and System Information
master and 1.14 on Windows 7 and Linux with SDL 2.0.10.

### Describe the bug
Aside from the default batched renders introduced with SDL 2.0.10 (see #4237 and #4245), it looks like Wesnoth is still using SDL in a way that may not be intended by SDL developers and so we have graphical artefacts like #2742 returning.

### To reproduce
There are many ways to find errors, including the aforementioned #2742, but scrolling seems to be a good way to achieve this. One way is:

1. Start Wesnoth
2. Open Help
3. Open a unit entry and scroll up and down
4. Result in screenshot below - note the un-redrawn text and picture elements accumulated above and below the scroll area.

### Expected behaviour
Normal rendering behaviour as it stands with SDL 2.0.9 or earlier.

### Screenshots
![badrender](https://user-images.githubusercontent.com/13679322/67305630-5a68ae80-f541-11e9-98ae-1dcf7330fc3f.png)

**Comment by Wedge009** [comment]
@sevu Your confirmation is on Linux?

**Comment by sevu** [comment]
yes

**Comment by Wedge009** [comment]
Another example is to move around the map while in game, and note the white mini-map rectangle outline leaving a trail behind.

**Comment by jostephd** [comment]
As in #3255?

**Comment by Wedge009** [comment]
Yes, but as discussed previously, that case appears to be related to virtual desktops whereas this one is most definitely from SDL 2.0.10 version specifically. Same symptom, but apparently different cause.

**Comment by shikadiqueen** [comment]
Why is this marked Upstream even though we have no real confirmation yet as to whether it's our bug or theirs?

**Comment by Wedge009** [comment]
> Issues that are or involve issues with libraries, tools, or platforms Wesnoth uses.

Wesnoth code may still be ultimately responsible but it's clearly affected by the different library versions too. Feel free to remove the label if you deem it necessary.

**Comment by grz0** [comment]
Is this the same issue as on my screenshot?
![scroll_minimap_glitch](https://user-images.githubusercontent.com/3605541/71219553-c4919b80-22c5-11ea-8a93-29ae8498c6ad.png)

The Battle for Wesnoth version 1.15.2+dev (a6d3ecae-Clean)
Running on Linux 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64

Libraries
=========

Boost:             1.66
OpenSSL/libcrypto: 1.1.1d (runtime 1.1.1d)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.44.6 (runtime 1.44.6)
SDL:               2.0.10 (runtime 2.0.10)
SDL_image:         2.0.5  (runtime 2.0.5)
SDL_mixer:         2.0.4  (runtime 2.0.4)
SDL_ttf:           2.0.15 (runtime 2.0.15)

**Comment by Wedge009** [comment]
@grz0 That is but one of the symptoms, yes.

**Comment by shikadiqueen** [comment]
I had a look at this using the help browser in particular as a guinea pig.

What seems to be happening is that the `sdl::draw_rectangle()` call buried deep in `help_text_area::draw_contents()` (`src/help/help_text_area.cpp` around line 534 on master right now) resets the screen surface's clipping rectangle as a surprising side-effect, which can be observed in the underlying `SDL_Surface` directly. It only happens when the help browser needs to draw a "box" (whatever that means) and apparently that is needed for the unit description pages in particular.

```cpp
void draw_rectangle(const SDL_Rect& rect, const color_t& color)
{
	SDL_Renderer* renderer = *CVideo::get_singleton().get_window();

	SDL_SetRenderDrawColor(renderer, color.r, color.g, color.b, color.a);
	SDL_RenderDrawRect(renderer, &rect);
}
```

Now I'm not sure why that would be a side-effect of this since I don't grok SDL 2, but I reckon it might have to do with the fact that the render API has its own approaches at stuff in general. It even provides its own clipping rectangle get/set functions.

Paging @Vultraz since he changed the implementation of this and other functions in commit 4cbd6529e3d5f378d4dd0080dda8a47025b0d50d to the render API-based implementation.

**Comment by Arcanister** [comment]
I have a graphical glitch, which might be somehow related. When I select a unit on screen, then move the cursor to other unit without deselecting the first one, I see digits such as level partially overlapping on the right side info panel, however it's SDL 2.0.5 on GNU/Linux. 1.14 from git, self compiled. The click on the other unit makes the panel update properly.

**Comment by Wedge009** [comment]
Seems to have resolved the most obvious symptoms that I've found. Thank you.
