### ISSUE TITLE
DM S12 – event conditions don't fit

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4614]
DM S12 has many sides, and many events which trigger upon sighting or moving onto a village.
 And many issues with them triggering unexpectedly.
- [x] walked onto a few destroyed houses south of the keep. At one two events were triggered.
- [x] went to the west, sighted orcs: triggered message tells about them being at the ford, which they aren't.
- [x] sight the humans: talk is about undead creatures, which haven't shown up yet.
- [x] that event gave control over human units, which did trigger the next event by sighting side 3 units. Dialogue is about undead creatures, but only adepts were sighted.
- [x] moving onto a red-flagged village on 34,25 triggers a green draug. This could be intentional or not.
- [ ] turn 7: Delfador talks about a 2nd attack wave, but there is nothing that indicates where he could have that knowledge from. Maybe he just wanted to tell that the sun goes down … or he knows secrets about the scenario coding.

And lastly, revealing the whole map and thus seeing the keep locations is a spoiler.

**Comment by UnwiseOwl** [comment]
Have made PR #4774 to fix these.

1: Fixed by moving village
2: Fixed by changing dialogue to be less specific.
3: Have not fixed. It makes sense that loyalist leader knows about the undead already.
4: Fixed by changing dialogue to be less specific.
5. Have not fixed. Intentional, though the village should not be flagged, mattsc is looking into the AI behaviour at the moment.
6. Fixed by changing dialogue.
7. Have not fixed. Could add shroud everywhere except the path to the ford, but this is such a common problem that I don't think it's worth fixing unless it's policy to change it everywhere.
