### ISSUE TITLE
Package wesnoth with AppImage for any GNU/Linux distribution.

### ISSUE THREAD

**Issue by mzs114** [wesnoth/wesnoth#4623]
### Game and System Information
 - What OS are you running?
GNU/Linux

### Describe the desired feature

The game distribution for any GNU/Linux distribution should be as simple as a user downloading a single file and executing it to start the game!

- Neither Flatpak or Snapd provide this convenience, but AppImage does[1].
- AppImage does not need a prerequisite daemon process like Flatpak or Snapd do.
- Using Appimage will bring the experience of running any game/application at par to user experience like on Andorid(.apk)/Mac(.dmg)/Windows(.exe).
- Not all people are connected to the internet[2] to effectively use Flatpak and Snapd, AppImage works well for such users, as it can be downloaded and distributed, this is from my personal experience. This is true for a major chunk of world's population, especially developing countries, Windows .exes work well in such cases.
- With Appimage, multiple versions of Wesnoth can be installed on the host and run in parallel, not sure about Flatpak/Snapd, this is something that works well on Windows, afaik.

I have enjoyed Wesnoth with my friends and family, but the version compatibility hits us every time during LAN gaming, like some of us are on various GNU/Linux distributions and somebody on Windows. And the user using Windows will be able to match versions on GNU/Linux, but not GNU/Linux users themselves(Like Debian vs Ubuntu LTS). Creating a road block, in such cases AppImage file will resolve this issue for GNU/Linux users.

Appimage recommends that the Upstream does the packaging[3], and it supports multiple ways to package a application[4], including using the existing .deb/.rpms[5], but the recommended one is to use OBS to automate based on a trigger to the repository.

A table comparing Appimage to Flatpak and Snap exists[6].

### Screenshots
[1] https://docs.appimage.org/introduction/quickstart.html#ref-quickstart
[2] https://en.wikipedia.org/wiki/List_of_countries_by_number_of_Internet_users
[3] https://docs.appimage.org/packaging-guide/upstream.html
[4] https://docs.appimage.org/packaging-guide/ways.html
[5] https://docs.appimage.org/packaging-guide/pkg2appimage.html
[6]  https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison

**Comment by Pentarctagon** [comment]
Thanks for suggesting this, however we're not looking to support AppImage at the moment.

**Comment by loonycyborg** [comment]
I'm not sure that appimage would be feasible for wesnoth because wesnoth has a lot of dependencies that might be at incompatible versions in different distros. At least flatpak has shared runtimes, allowing one to build against that runtime instead of particular distro.

**Comment by mzs114** [comment]
Thanks @loonycyborg for the details, these help, rather than just closing the issue without little to no explanation.

Please know that packing in AppImage might be easier as this was done earlier, but only for 32bit:

https://portablelinuxgames.org/game/battle-for-wesnoth

AppImage was used here:
https://portablelinuxgames.org/#info

**Comment by loonycyborg** [comment]
It's not a matter of how easy it is, but rather a matter of not artificially inflating downloads by providing loads of dependency libs like pango, cairo etc that are strictly speaking part of base system but might end up being at different incompatible version for this particular distro. Flatpak can provide those libs in single pack called "runtime" which I don't have to maintain(like wrt security fixes) and is shared by other flatpak apps. I doubt appimage can have shareable runtimes like this since it would be hard to achieve without compromising other appimage's goals, such as being standalone.

**Comment by mzs114** [comment]
@loonycyborg I lack the knowledge about this, then how do Mac and Win Wesnoth packages manage such complexities?
I mean they are also standalone, correct?

**Comment by GregoryLundberg** [comment]
That's up to the packager.

Most Windows packages (not just Wesnoth) simply require a certain set of externals. If you have them, great. If you don't ... well ... expect some cryptic error message to pop up as the program dies.

Some will include all the required packages. But that's rare.

Occassionally, you'll see some packagers including some Microsoft re-distributable packages (like the C runtime).

For many, if it becomes an issue, they'll link "statically" to include the runtime within the executable instead as a separate library.

I might be wrong, but I think much of Wesnoth chooses this approach. It doesn't solve all the issues but it does the best we can, and leaves the rest for the user to fix after seeing that cryptic error message.

---

The question for AppImage is it's another build system and another packaging system.

See [XKCD](https://xkcd.com/927/)

**Comment by gfgtdf** [comment]
> Some will include all the required packages. But that's rare.

Im my experience this is the usualy behaviour and not rare at all.

Iirc even the wesnoth windows downloads (or was it my  self-build wesnoth?) included at some point 3 different versions of the libpng library dlls, because the dependencies of wesnoth used differnt versions of this lib. This sounds a little funny but didnt cause any problem iirc.

**Comment by AI0867** [comment]
They do it by some combination of:

- being much less diverse (there are many distros, and many can be configured in widely different ways, there are only a few mostly-compatible versions of MacOS and windows that are supported)
- a standard set of libraries, plus some redistributable runtimes
- distributing libraries with the executable
- static compilation (including libraries into the executable)
- ignoring the problem (if it works for a default install, and it doesn't work for you, then your system must be broken)

I'm not sure which of these items are actually used for our releases.

**Comment by mzs114** [comment]
> The question for AppImage is it's another build system and another packaging system.
> 
> See [XKCD](https://xkcd.com/927/)

@GregoryLundberg  thanks for the reply, yet I disagree with the postscript, AppImage existed much before Flatpak and Snap arrived. In fact, their inspiration was AppImage.

**Comment by loonycyborg** [comment]
Windows and Mac are stuck with providing dependencies. I'm not doing mac packaging so I don't know much about it, but with windows I at least figured out a way to improve this a bit: reuse dependencies from [msys2](https://www.msys2.org). Still need to provide them but at least there's a streamlined way to update them.

**Comment by GregoryLundberg** [comment]
I'll contact Arch team immediately: pacman has gotta go! Can't have some new fangled tools like that messing up the perfect world created by AppImage, Flatpack and Snap.

**Comment by Pentarctagon** [comment]
To add some context to my original reply - it's not that I don't think AppImage wouldn't be beneficial in some certain situations.  However, Wesnoth is already distributed 3 different ways on linux (repositories, flatpak, and Steam), and it seems like a serious stretch to say we need to add a 4th.

**Comment by eugenialoli** [comment]
I personally prefer appimages to flatpaks. They are smaller than flatpaks, because of the massive surrounding libraries that also need to be downloaded. I'm on a slow internet line in this Greek village, I'd appreciate an appimage.

**Comment by loonycyborg** [comment]
For case of slow internet you're better off with a distro package. AppImages eventually always break due to glibc updates and I'd have to bundle lot of dependencies in them anyway, increasing risk of breakage or incompatibility even more. I believe they're simply not a good fit for app with huge number of deps like Wesnoth.

**Comment by mzs114** [comment]
> For case of slow internet you're better off with a distro package.

I guess you missed the people who don't have internet who can depend on other avenues to download and distribute, also check the initial post, we can use torrents, this is the way one of the projects were distributing their AppImages.

> AppImages eventually always break due to glibc updates and I'd have to bundle lot of dependencies in them anyway

This likely is not true for the stable distros like Debian and their based distros, even the RHEL ones(Alma, Rocky) fall in this category.

It is fine if this project does not want to provide Appimages, (this request is already closed), rather than giving such excuses.

**Comment by AI0867** [comment]
Distro packages can also be distributed by torrent or sneakernet.

AppImage would have the advantage of being distro-agnostic (as far as the distro meets the requirements of the image), but has the downside that someone has to take on the responsibility of creating a build recipe, decide which versions of which libraries to include or not, creating an image each release, and updating the recipe as required. Are you volunteering to do that?

**Comment by eugenialoli** [comment]
I'm on Linux Mint. This means a 2 year cycle. Wesnoth gets too old eventually. My only solutions are either Steam (which I don't use, it's a dog to install for just 1 game, since I'm not a gamer of most commercial games -- I usually play only gpl games, most of them not on steam), or Flatpaks, which I can't do, being on a slow line here in Greece (they pull environment libraries that are huge, a few months ago it wanted a 6 GB UPDATE over 1 app I had installed from there!!). Appimages are much, much more economical, easy to deal with. You don't like it? It's a delete away! You like it? You can easily integrate it with cinnamon-menu-editor on Mint. That's why I'd prefer an appimage plz. Please reconsider!

**Comment by mzs114** [comment]
> Distro packages can also be distributed by torrent or sneakernet.

Other than a select few(like Debian) that torrent the entire archive I am not aware of any other distros that torrents apps or games individually or even the entire game genre(FPS, TBS, RTS, etc) or the entire game archive.

And coming to sneakernet, you need supporting tooling and OS in place to download the necessary dependencies( like say with `apt-offline`), whereas with the AppImage, it is just one file targeting a group of distros, just like `.exe` or `.dmg` for Win and Mac, respectively. These two solutions are wide apart in the user experience.

There is an uptick of Windows users after MSFT sunset Windows 10, eventually more will seek these simple solutions.

We can have these published here too:  https://portablelinuxgames.org/

> Are you volunteering to do that?

I need to learn on how to prepare AppImages and I can target Debian Stable and Old-Stable, as these are what I use, If this is ok, please let me know what I need to do next.
I am even willing to seed and torrent these from my PC and raspberry PI(till I reach the data limit of 1 TB/month), if possible can the Wesnoth project provide web seeds?

**Comment by soliton-** [comment]
> We can have these published here too: https://portablelinuxgames.org/

Wesnoth is already listed there. Perhaps you can simply continue whatever was done there.

> if possible can the Wesnoth project provide web seeds?

No clue what that means. If you can explain what you expect us to do then perhaps we can.

**Comment by eugenialoli** [comment]
Anything on this? I'm still on Linux Mint, and the version of Wesnoth available to me would still be 1.16 by December. I can't use Flatpaks as I explained above.

**Comment by loonycyborg** [comment]
If you absolutely don't want to download any unneeded gigabytes you're better off doing a git checkout of 1.18 and building that from source. As far as flatpak goes wesnoth itself depends only on freedesktop runtime which brings extra 1 Gigabyte of downloads and needs update every year or so. Though flatpak can do delta updates of both wesnoth itself and the runtime, which is only download parts that have changed. I'm averse to AppImages in particular because they make you(as developer) bundle your dependency libraries which is harder to maintain and can't be shared with other installed apps. While multiple flatpak apps can share same runtime, as long as it's the same version.
