### ISSUE TITLE
OOS in replays from victory events

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4667]
Synced choices from victory events cause OOS in replays, wesnoth 1.14.5, play the following scenario win with any side and see hoe the replay gives an OOS at the end:

```
[multiplayer]
    name="01_STARTUNIT_TEST"
    id= "01_STARTUNIT_TEST"
    map_data = "Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, 2 Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, 1 Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
"
    {DEFAULT_SCHEDULE}
    [side]
        side=1
        id= "leader1"
        controller=human
        team_name= "team1"
        type = "Elvish Archer"
        canrecruit="yes"
    [/side]
    [side]
        side=2
        id= "leader2"
        controller=human
        team_name= "team2"
        type = "Elvish Archer"
        canrecruit="yes"
    [/side]
	[event]
		name="victory"
		[set_variable]
			name="aaa"
			rand="1..2"
		[/set_variable]
	[/event]
[/multiplayer]
```

This OOS only effects replays not mp games.

**Comment by stevecotton** [comment]
I've been looking at the replay attached to #6268 and haven't yet tried to reproduce with the test code in #4667 (although I'll gladly switch, as it's a much shorter replay). I suspect the bug is in the writing-a-replay code, however so far I've traced it through the reading-a-replay code.

I suspect the bug might be triggered by a unit leveling up from the attack that triggers the victory event.

The replay attached to #6268 ends with:
```
	[command]
		from_side=1
		[attack]
			attacker_lvl=1
			attacker_type="Bowman"
			defender_lvl=3
			defender_type="Orcish Warlord"
...
		[/attack]
...
	[/command]
	[command]
		dependent=yes
		from_side="server"
		[random_seed]
			new_seed="dd979f46"
		[/random_seed]
	[/command]
	[command]
		dependent=yes
		from_side=1
		[choose]
			value=0
		[/choose]
	[/command]
	[command]
		dependent=yes
		from_side="server"
		[random_seed]
			new_seed="851dc04f"
		[/random_seed]
	[/command]
[/replay]
```

The first trick is to put a conditional breakpoint on `src/random_synced.cpp:48`, just before synced_rng::initialize() returns; this allows stopping the replay when `gen_.random_seed_ == 0xdd979f46`, the random number from the final attack of the scenario. At that point walking up the stack shows that `do_replay_handle (one_move=true)` is handling the config with `from_side = 1\n[attack]\n\tattacker_lvl = 1\n\tattacker_type = Bowman\n\t...`, and it returns `REPLAY_FOUND_END_LEVEL` to `replay_controller::play_side_impl`. However, `resources::recorder->at_end()` is false, and we end up back in `do_replay_handle (one_move=true)` with the next config being the `...new_seed="851dc04f"...` one.

Therefore, either
* something is writing a spurious `[command][random_seed]` at the end of the replay,
* the replay of the attack is reading the `[command][choose]` when it shouldn't, thus that command isn't being processed, or
* the `[command][choose]` should have read the random seed too.

Not sure which of those yet. I think the `choose` is triggered by the Bowman leveling up to Longbowman (that's the only advancement from Bowman).

**Comment by soliton-** [comment]
I reproduced the issue in NR1 without the killing unit leveling up and the replay ends in:

```
        [command]
                dependent=yes
                from_side="server"
                [random_seed]
                        new_seed="39d8b820"
                [/random_seed]
        [/command]
        [command]
                dependent=yes
                from_side="server"
                [random_seed]
                        new_seed="a4c95bae"
                [/random_seed]
        [/command]
```

So I'm voting for option 1.

**Comment by soliton-** [comment]
Judging by a random replay from 1.12 a final `[command][random_seed]` is not new but looks like there is one too many now.

Btw, quite confusing to have `[multiplayer]` and `from_side="server"` stuff in a campaign save/replay.

**Comment by gfgtdf** [comment]
There are probably two seeds because the victory/defeat and the attack that did the final blow happen on different "synced context". This is mainly for technical reasons because the "synced contexts" are handled via c++ "raai" objects (so it is tied to the c++ stack) and the victory event is fired outside of the usual game (play(single)_controller.cpp) loop.


here is where the victory event is called: https://github.com/wesnoth/wesnoth/blob/7e67bc5d081ae4025bbe3cb49f810e84762d3f18/src/playsingle_controller.cpp#L323

here is the replay game/action loop:
https://github.com/wesnoth/wesnoth/blob/7e67bc5d081ae4025bbe3cb49f810e84762d3f18/src/replay_controller.cpp#L169 , it I might be enough just to return there on `REPLAY_FOUND_END_LEVEL` here not sure though.

Alternatively one could try to refactor the fireing of the victory event into the last action that did the kill, from a synchronization point of view this might make more sense but it might break other things (ui wise when campaign designers assume its fired at that point.).

**Comment by gfgtdf** [comment]
actually it might be possible that the replay code currently simply cannot handle the execution of victory events because it assumes that its always is the main play_controller loop, while the victory event is fired outside of that.

**Comment by gfgtdf** [comment]
This is kinda the same underlying problem as #4236 and should maybe be fixed together with that.

**Comment by white-haired-uncle** [comment]
Can the comment here be removed?

https://wiki.wesnoth.org/EventWML#victory

**Comment by gfgtdf** [comment]
Yes i think we can

**Comment by white-haired-uncle** [comment]
Done.  Thank you.
