### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by jefferson2z** [wesnoth/wesnoth#4692]
The portuguese translation of the dialogs during the campaings is alternating between english text and portuguese.

Note: The house style of Wesnoth uses a good many words and constructions that
are archaic, poetic, or dialectal. If you speak modern English as a second
language you may incorrectly read these as errors. Please see
[NotSpellingMistakes](https://wiki.wesnoth.org/NotSpellingMistakes) for a list
of things you will encounter that may look like spelling or usage errors but
are not.

Note that the mainline campaigns are now using correct typography,
including sexed quotes and en and em dashes. These will appear as three byte
sequences if you are not using a viewer that supports UTF-8. 

### Text Issues: Typos, grammar mistakes, suggested improvemetns

* Is the text in English? If not, what language is it in?

* What campaign does the text appear in? If it's not in a campaign, say where it is:

* Please quote the text verbatim. You can use `**bold**` to point out the mistaken part:

* _(optional)_ What do you propose to change the text to?

**Comment by stevecotton** [comment]
Wesnoth currently has a "Portuguese" and a separate "Brazilian Portuguese" translation. I'm don't know the language, but the statistics suggest that the country-specific `pt_BR` is up to date while the main `pt` is not. Would it be better to make pt_BR the only version listed in the languages menu?

* https://www.wesnoth.org/gettext/?view=langs&version=branch&lang=pt
* https://www.wesnoth.org/gettext/?view=langs&version=branch&lang=pt_BR

@jefferson2z in the translation stats, green means that the translation will be shown; both orange and red mean that the English will be shown instead.

Pinging @ivanovic , @trewe  and will email Earl Khonrad.

**Comment by stevecotton** [comment]
There have been a lot of updates to the pt_BR translation after 1.14.9. I think my previous comment is off-topic for this issue, and that the issue reported will be fixed in 1.14.10 as a result of all the updates.

@jefferson2z, did Wesnoth default to running in Portuguese, or did you change the language to Portuguese in the language menu?

If Wesnoth is using the system default language (the language menu shows the first item selected), then which of these is the label on the title screen's "map editor" button?
* "Editor do Mapa" (indicates `pt`)
* "Editor de Mapa" (indicates `pt_BR`)

**Comment by jefferson2z** [comment]
@stevecotton 
It indicates the pt_BR version, that is 'Editor de Mapa'. 
I've noticed that the version that comes with Raspbian is 1.14.5, and with my main system with Fedora is 1.14.9

**Comment by Wedge009** [comment]
Isn't the 'alternating between English and Portuguese' simply a factor of incomplete translation? ie Strings that aren't translated would be displayed in default US English.

At any rate, I understand 1.14.10 is scheduled for release soon and there will be a translation update as part of that.

**Comment by Wedge009** [comment]
1.14.11 was recently released - has there been any improvement and are there any specific concerns relating to this translation?

**Comment by Wedge009** [comment]
I understand @sheepo99 is hard at work, taking over primary responsibility for the Portuguese (Portugal) translation and while it will take time, I'm sure it'll be a great boon for Portuguese readers. Given that, the lack of response since the initial interaction in January 2020, and the fact that questions of translation progress generally aren't dealt with on GitHub (to my knowledge), I'm inclined to close this (otherwise we could arguably have open issues for any language that doesn't have a very high completion rate).

There's always the option of contacting the translation maintainers or taking up responsibility for it: https://wiki.wesnoth.org/WesnothTranslations

**Comment by sheepo99** [comment]
> I understand @sheepo99 is hard at work, taking over primary responsibility for the Portuguese (Portugal) translation and while it will take time, I'm sure it'll be a great boon for Portuguese readers. Given that, the lack of response since the initial interaction in January 2020, and the fact that questions of translation progress generally aren't dealt with on GitHub (to my knowledge), I'm inclined to close this (otherwise we could arguably have open issues for any language that doesn't have a very high completion rate).

Indeed, I am currently retranslating the game to PT-PT from scratch because the current translation is utterly broken. This is will take some time, but the final results will be worthwhile.
