### ISSUE TITLE
Recruit list shows experience in blue

### ISSUE THREAD

**Issue by IskarJarak** [wesnoth/wesnoth#4736]
### Game and System Information
 - 1.15.2
 - website download
 - Windows 10

### Describe the bug
Unit that cannot further advance (e.g., Gryphon Master, Lancer, etc.) show experience bar in blue in the **recruit** menu. 

### To Reproduce
Found in NR, tested for various factions in arbitrary Era of Heroes maps. So far as I can tell the issue is global.

### Expected behavior
Exp bar should be violet to show that now further advancements are possible. (Same as in recall, etc.)

### Screenshots
![bugreport_exp_bar](https://user-images.githubusercontent.com/44609951/74093249-88add200-4acf-11ea-9447-b957cabe8e7e.PNG)

**Comment by Wedge009** [comment]
I can't recall any particular scenario where you are permitted to recruit such advanced units straight away - can you give some examples for testing?

**Comment by IskarJarak** [comment]
Hey, for testing I'd advise to start a multiplayer game with Era of Heroes (Multiplayer -> local game -> choose Era of Heroes on the right side, select any map, start the match), then you can recruit all level 2 units of your faction (e.g., Loyalists have Lancer and Javelineer which can't advance).
Otherwise, I met the problem in Northern Rebirth - I think you can only recruit non-advanceable level 2 units (Gryphons) in the last one or two scenarios though (depending on branch).

**Comment by Wedge009** [comment]
My guess is that since this situation of having fully-advanced units available for recruiting is so rare, it's easy to see how this one got missed. It could also be a deliberate decision, though I don't see a reason for it to be.

Anyway, confirmed on master and 1.14, with the penultimate scenario for Northern Rebirth, 'Get the Gold'.

**Comment by Wedge009** [comment]
If I've found the right place I think the issue is here:
https://github.com/wesnoth/wesnoth/blob/396b2582033c222a6e80c7adea1ba05714900c09/src/gui/widgets/unit_preview_pane.cpp#L343-L357

The problem is that in this particular spot we're looking at generic unit types, not a specific unit. Otherwise we can use `unit::xp_color()` as we do in most other places:
https://github.com/wesnoth/wesnoth/blob/396b2582033c222a6e80c7adea1ba05714900c09/src/gui/widgets/unit_preview_pane.cpp#L503-L517

Since the colours are hard-coded at the moment (not a great situation to begin with), the unit type display would need to know if a given unit type is the max level for that line of units and then change the colour of the display accordingly. Is there a method to determine if a given unit type is the last in its line?
