### ISSUE TITLE
AI takes former castle hexes into account

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4749]
![recuit](https://user-images.githubusercontent.com/21158813/74868210-2cac3e80-5356-11ea-95d7-d139b5ef8752.png)
on the 1.14 branch

**Comment by mattsc** [comment]
Hmm...
So that's with the ExpAI (in 1.14), I assume?  The ExpAI recruiting caches a whole bunch of things, including the castle locations.  So the fix for this is simple, in principle, just don't cache things.

That brings up a conundrum, of course.  The caching is done for a reason (some of the operations are quite expensive; not necessarily finding the castles, but even that one can be depending on the map).  But, as pretty much anything can be changed in events, I don't really see a way around that.

**Comment by mattsc** [comment]
Well, there should be some things for which it is quick to check whether something has changed in a way that the expensive calculation needs to be redone, but the castle hexes are not one of those. We don't only need to check whether a hex is still a castle/keep, but also whether new ones have been added, so the entire map needs to be rechecked.

**Comment by sevu** [comment]
Yes, ExpAI on 1.14.

I'm fine with closing this then.
But it's a seldom enough use case, which is likely not relevant to anybody, including me.
If it would be a problem one could still work around it by swapping the recruiting aspect.

Maybe the value could be re-scanned in case of an error. But that's probably opening a can of worms.
