### ISSUE TITLE
Remove leading T in campaign acronyms

### ISSUE THREAD

**Issue by UnwiseOwl** [wesnoth/wesnoth#4796]
Change the campaign acronyms from TSG, TRoW and THoT to SG, RoW and HoT respectively, to match with SoF and to avoid the unfortunate use of thot, which has gained negative connotations in recent years.

**Comment by Wedge009** [comment]
Is there anywhere in code or documentation that these acronyms are used? Consistency is nice, but I imagine these are from whatever the community has come up with as a matter of habit. How do we 'resolve' this?

Also I don't follow Internet lingo, a lot of is American-influenced anyway, what is 'thot' supposed to mean? I'm not aware of it being a word.

**Comment by gfgtdf** [comment]
> Is there anywhere in code or documentation that these acronyms are used?

The savegame filenames use acomyns

**Comment by Wedge009** [comment]
Ah, good point. And just as with other titles, it makes sense to drop the 'The' when sorting.

**Comment by IskarJarak** [comment]
I'm not sure if I like the suggestion. For one, the use for save files already came up, for another, the acronyms have a long-standing history and are widely recognized. If some teens get a chuckle because they can't discern between an acronym and modern slang, where's the hurt in that?

Would you rename UtBS to _Under Burning Suns_ as well? It is as much _the_ rise of Wesnoth as it are _the_ suns...

**Comment by Wedge009** [comment]
UtBS would not be applicable because the 'the' is within the title. It's common - at least from my recollection of when people used to go to a physical library - to drop the 'The' when it's at the start of a title.

I also mentioned above that the acronyms seem to be whatever the community have been accustomed to. And I also see no harm in THoT even after looking what what the fuss was about (shakes head at Internet in disgust at its puerile stupidity).

**Comment by CelticMinstrel** [comment]
Dropping 'the' for sorting is fine. I don't know if actually changing the acronyms is worthwhile though.

**Comment by stevecotton** [comment]
> Is there anywhere in code or documentation that these acronyms are used?

The textdomains use them too.

**Comment by shikadiqueen** [comment]
This is just never gonna happen simply because of tradition. An exception could be made for THoT perhaps, but I have a feeling nobody feels that strongly about it.

**Comment by shikadiqueen** [comment]
Leaving open in case you decide to repurpose this ticket specifically for THoT. The Won't Fix label is primary to avoid people wasting their time submitting PRs for it without coming to a real agreement first.

**Comment by UnwiseOwl** [comment]
I don't feel strongly about it, just thought it was worth considering. I'm not that familiar with normal practice, but it seems suboptimal to leave issues open if the consensus seems to be that they're not issues.

**Comment by Pentarctagon** [comment]
Closing then.
