### ISSUE TITLE
Dialog box too large. Non-ergonomic text reading. (in campaign introductions / story telling)

### ISSUE THREAD

**Issue by luffah** [wesnoth/wesnoth#4817]
The dialog box are really large in campaign introduction.
Text content is put in 1 line while the same text would fill 2 lines in a book or any random article.
It make the story difficult to read (or just skipped), and make the introduction looks cheap compared to the overall quality of the game.

**Comment by Pentarctagon** [comment]
You're saying the text being displayed should use less of the screen's width (I assume on wider screens only)?

**Comment by luffah** [comment]
Yes, the purpose is to have a max-width for text-container like in a website.

**Comment by Wedge009** [comment]
Personally I've always hated restricted-width text in web-site design - it's been around for many years, long before 'responsive' design was a thing. But I recognise I'm very much in the minority with this opinion.

Anyway, I assume this request is to do with the story scenes, and yes, they do use as much of the available width as possible, at present.

**Comment by shikadiqueen** [comment]
Worth noting that the current story screen UI's measurements have remained almost entirely unchanged from the ones I used when refactoring the GUI1 version one decade ago.

Back then I rewrote the whole code from a flat monolithic unit akin to the old Credits screen into something more modular in order to implement a few aesthetic changes including the `[message]`-like border and overlay (only present when the background image is set) and the ability to use Pango markup. It never even crossed my mind to restrict the line length because I pretty much exclusively used 1280x800 laptops. At that resolution you'll find that each line winds up having a far more reasonable character count at our current font size. Full HD (1920x1080) and larger resolutions weren't a thing that felt realistic to me, as silly as it sounds.

Come 2012, I finally got a desktop and a 1920x1080 screen. Since then, for every UI I have touched that didn't have a horizontal size limit already set, I have added one. It's not just a design trend, it's a standard intended to reduce the amount of eye movement required to continue scanning a single paragraph. In general, the longer the distance your eyes need to travel from the end of one line to the start of another, the more easily some people can become distracted from parsing the actual content. (On the other hand, do note that eye strain from spending prolonged periods of time looking at a screen is a whole different issue that's completely beyond the scope of this ticket or Wesnoth in general.)

With the background for the current situation out of the way, I agree that in this world of ridiculously huge screens we need to fix this. Not quite sure yet exactly how the line length limit should be implemented, though. It could be either in characters per line, or pixels. It could be either fixed (e.g. 1280 pixels) or variable (2/3 of the screen) or a mix of the two (5/6 of the screen up between 800 and 1280 pixels, then 1280 pixels for higher resolutions).

Before somebody goes and randomly commits a quick WML change (because, let's face it, some people are too eager to get a PR in) I'd be interested in seeing what different possibilities look like with the average text density we have in mainline story screens, and also compare to more text-heavy story screens found in UMC.

**Comment by AI0867** [comment]
A related feature request might be (optional) multi-column text, to make best use of available screen real-estate. Newspapers figured all of this out centuries ago.

**Comment by stevecotton** [comment]
Noticed while testing with HDPI: clicking on most of the story screen does nothing. The story screen's "Skip" and arrow buttons are small and far from the centers of attention, so the mouse feels unresponsive. Clicking on the picture should probably advance the story, the same as pressing the spacebar.

**Comment by Wedge009** [comment]
Are 'pure story' scenarios handled differently? I just noticed very restricted width in the dialogue for when Tallin's refugees meet the dwarves in Northern Rebirth. I looked at the scenario code and don't see anything relating to text display, plus I recall there may be some slight differences because the normal game view (such as the side-bar on the right) is not present.

![Untitled](https://user-images.githubusercontent.com/13679322/133884274-d7f3ac06-ca33-4b12-b01f-e127880e34c1.png)

**Comment by stevecotton** [comment]
This issue is about text shown by `[story]`.

That picture of Hamel is an in-game `[message]` combined with `[scenario]theme=Cutscene_Minimal`. There's a couple of issues about the width of those in connection with `[message][option]` (#1915 and #5633), but they're unrelated to this issue.

**Comment by Wedge009** [comment]
So `theme=Cutscene_Minimal` is what produces this fixed-width output?

**Comment by stevecotton** [comment]
`theme=Cutscene_Minimal` hides the sidebar; `[message]` produces the fixed-width output.

**Comment by Vultraz** [comment]
This is resolved in 1.19. The story screen has a max width so it doesn't stretch across the whole screen.
