### ISSUE TITLE
Incorrect terrain code in Random Marsh

### ISSUE THREAD

**Issue by virtualghetto** [wesnoth/wesnoth#4886]
### Game and System Information
Wesnoth 1.14.9
Debian sid package.

### Describe the bug
On line 160 of data/multiplayer/scenarios/Random_Scenario_Marsh.cfg

The terrain code might be incorrect, I think it's supposed to be
`convert_to=Ds^Vda`

**Comment by soliton-** [comment]
Probably was just missed here https://github.com/wesnoth/wesnoth/commit/0abbca6#diff-052016e5667ea8a9b06b472a2a9ae6d2

Perhaps you want to make a PR for this.

**Comment by virtualghetto** [comment]
Please go ahead with the fix if possible.
I'm rapidly running out of disk space and can't clone to do a PR.
Thank you.

**Comment by Wedge009** [comment]
I'm not familiar with terrain codes or WML, but at a guess it looks like it's converting any village on a desert tile to just a plain village. It might be deliberate, since this is randomising for a marsh region - either way, there doesn't appear to be any desert tiles generated (or shouldn't be).

I tested before and after the change (generating marsh map in MP and Editor) and didn't observe any difference. If the desert omission is deliberate, should comment this. If not, it could probably be corrected.

**Comment by soliton-** [comment]
Good point, Ds is not actually specified to get generated at all. Was probably copied from the generic random map but the Ds generation was changed to shallow water (specified for height 5 and 30, which can be simplified).

I think the desert (or really sand) omission is on purpose. So those tags referencing Ds should be completely removed instead since they don't do anything.
