### ISSUE TITLE
No ai controlled side in test scenario

### ISSUE THREAD

**Issue by virtualghetto** [wesnoth/wesnoth#4890]
### Game and System Information
Wesnoth 1.14.9
Debian sid

### Describe the bug
In the guardians test scenario, both sides are controlled by the human player.

Details are in this thread.
https://forums.wesnoth.org/viewtopic.php?f=21&t=52406

**Comment by mschoeck-zz** [comment]
Interestingly, this only happens when you start the guardians test scenario from the Micro AI switchboard scenario by moving to a sign post.  When you start guardians directly from the command line with `-tguardians` or from the main menu, it works just fine.  That's the reason why I did not notice it in so long, I always start the MAI test scenarios directly.

I'll fix this shortly.

**Comment by mattsc** [comment]
Actually, I had not closed this because I have not ported it to 1.15 yet (as trivial as that is).
