### ISSUE TITLE
Audio/Sound always stop working few minutes in gameplay

### ISSUE THREAD

**Issue by joeljpa** [wesnoth/wesnoth#4941]
- What version of the game are you running?
The Battle for Wesnoth version 1.14.12
Running on Microsoft Windows 10 (10.0.18362)
Distribution channel: Steam

- Describe your issue.
Audio always stops working a few minutes into playing the game. By restarting or going to audio settings and re-ticking all four options, I can get it to work again.

- Can you reproduce the problem? If you can please provide steps to do it.
Just start the game, begin playing any campaign or multiplayer match, a few minutes into it, audio completely stops working.

- Attached the relevant files.

[wesnoth-build-information.txt](https://github.com/wesnoth/wesnoth/files/4746794/wesnoth-build-information.txt)
[wesnoth-20200608-200353-7728.log](https://github.com/wesnoth/wesnoth/files/4746771/wesnoth-20200608-200353-7728.log)
[wesnoth-20200608-201229-1076.log](https://github.com/wesnoth/wesnoth/files/4746774/wesnoth-20200608-201229-1076.log)
[wesnoth-20200608-202430-15152.log](https://github.com/wesnoth/wesnoth/files/4746776/wesnoth-20200608-202430-15152.log)

**Comment by joeljpa** [comment]
Would add that I have been experiencing this issue ever since I started playing this game months ago. Just never got the time to report it.

**Comment by Wedge009** [comment]
I remember the occasional audio-related report such as #1434 and #1446. I don't think we ever tracked them down as there was so little information to go on. At a first guess, since it doesn't look like anyone else has reported this recently, it's possible the problem is specific to your hardware/driver configuration. But if there's a reliable way to replicate the issue, we can certainly try to investigate that.

**Comment by Wedge009** [comment]
Is this still an issue? Noting that without the information or ability to replicate it, there's not much we can do.

**Comment by joeljpa** [comment]
Yes it is unfortunately and I understand the futility of trying to address this at this stage. It's bearable since all I need to do is retick those audio options to get it working again. Also, given that it's likely that I'm the only one having it due to my old laptop hardware specs, it makes this issue even more trivial.

**Comment by Wedge009** [comment]
Thanks for reconfirming. It doesn't look like anyone else is having the issue and I assume this is the only application where this happens for you. Additionally, I assume it happens without any input, eg accidentally pressing the mute hot-key is not a possibility (and even then, mute only toggles the first two options if I recall correctly, sound effects and music).

BTW, you submitted the issue for 1.14 - I assume it will still happen for 1.15/1.16 as well? Also, is there any consistency to the time when the sound switches off? You say 'few minutes', just out of curiosity could you maybe time a few of those intervals, see if there's any pattern?

You say you have to 're-tick' all four sound options - does that mean when you open the Preferences they are all un-ticked after the problem happens or you need to un-tick them first, then re-tick them, then sound resumes? If the former, I can't imagine what would cause that. But if the latter, then perhaps it's something related to drivers - as far as I know Windows audio is mostly software-driven, since Vista days I think.

I'll leave this open for the record, at least until perchance it stops being a problem for you.

**Comment by joeljpa** [comment]
Answering all your points in order:

Yes, it happens without any input. 

1.14 is all I can confirm at the moment since it appears that Steam's latest version is only that (just checked, it's 1.14.17).  Yes, I said "few minutes" first since that's possibly the least amount of time it can occur during gameplay. Sometimes it takes maybe longer, say five minutes. I can't see any pattern besides it happening as soon as I have a game loaded (not on the game menu).

Ah, sorry about the ambiguity here. It's that latter case, I untick and retick all four options and only then it works again. You saying that Windows drivers may be the issue seems to be the Occam's razor here.

I'll definitely keep you updated on this then later when I play more intensively again. Thanks for your time!

**Comment by Wedge009** [comment]
You can opt-in to beta on Steam or manually download 1.15.17 (as a stand-alone package) if you wish, but in a couple of months - all being well - you'll be bumped to 1.16.0 anyway.

So there's no apparent pattern to the audio cut-off - it really does sound like a random problem then.

So audio only works again by triggering an audio reset. It makes more sense that you need to un-tick the box first but it also means it's harder to diagnose. Since it seems to be an external problem my guess is the impending update to 1.16 probably won't make a difference for you.

As best as I can tell, all audio - whether music tracks or sound effects - go through `play_sound_internal()`:
https://github.com/wesnoth/wesnoth/blob/bd12eeb504cb24ff9779f76df71d1a23c9a4bcb8/src/sound.cpp#L951-L1019
I'm not an audio expert, but it doesn't look like there's any explicit resetting of audio hardware here - Wesnoth uses SDL to handle audio. So just guessing wildly, it could be a specific issue with how SDL interprets your audio drivers - but SDL is fairly common, are there any other games/applications you use that also use SDL? I suppose that could be hard to determine unless a game explicitly advertises that they are doing so.

Any idea what your audio hardware is? You are running on a desktop or laptop, using motherboard integrated audio, monitor speakers via HDMI, analogue speakers, or USB audio, etc? If you have more than one audio hardware option, does the issue still occur? I'm not expecting you to try everything, but just going through some ideas to try to isolate the issue. Even if Wesnoth is the only application where you encounter this odd behaviour, it's still worth trying things to try to narrow down possibilities or even just to find a possible work-around.

**Comment by joeljpa** [comment]
Yea, I think if I recall I used to face this issue ever since I started playing Wesnoth on Windows 10 via Steam, so that dates possibly even months before I opened this issue here officially. So even I don't expect it to go away when there's a major update.

SDL, hmm, I just looked up games that use that and found Counter Strike there, that's one game I've played on my laptop for a moderate time and don't remember any audio issues.

I'm not good at this but I'll try to furnish you with my tech specifications. I'm on a Lenovo Thinkpad 68861E6 and either use motherboard integrated audio or my USB headset (mostly headset though). The sound device is listed as Conexant 20671 SmartAudio HD. I probably need to test this more thoroughly but I remember noticing it happen irrespective of whether I was on my laptop's speakers or on the headset. But that was too long ago. I'll keep all this in mind for later, I won't be able to play for a long time now and the last time I played properly was a week ago.

**Comment by Wedge009** [comment]
If it's the original Counter Strike I just wonder if it's an older SDL. Probably not worth investigating further since I'm only assuming that the issue could be with SDL's handling of audio for your particular device.

Conexant is pretty common for audio hardware, and I assume Windows 10 will keep you updated anyway. Assuming that you've only played with laptop speakers recently, I'd be curious to know if you still find the issue occurring with your USB head-set.

No rush - I'll probably ping you next time I do a sweep of outstanding issues if you haven't updated by then.

**Comment by joeljpa** [comment]
Got some mildly good news. I've played a lot in the past week and notice that it happens way less frequently now. So rare and when it does, it's like almost an hour after playing. I managed to do some experiments when it did happen and can reconfirm that it occurs irrespective of whether I'm on my headset or using the laptop's speakers. I'm still on 1.14.17 and not much has changed on my side.

**Comment by Wedge009** [comment]
I suppose that's good news, but still odd that it happens at all. It still sounds like something specific to your system even though you only experience it in Wesnoth.

**Comment by Wedge009** [comment]
1.16.x has been released for a while now. Assuming you're still playing Wesnoth often enough, does this still happen?

**Comment by joeljpa** [comment]
No, sorry haven't logged into Steam in months and stopped playing before that. Usually, I eventually play it again sooner or later, it is, after all, my third most played game on Steam :) I'll be sure to update here when I do or if you want to close this now, let me know.

**Comment by Wedge009** [comment]
No worries, just checking.

**Comment by joeljpa** [comment]
Sorry for the delay. I think you can close this if you want to. My windows PC has been dead for months and I won't be playing the game on it or on Windows anytime soon. Towards the end of our contact, I did find it hard to reproduce the bug so maybe it's gone or at minimum, unconfirmed. I can always reopen it should it happen again and reference this.

**Comment by Wedge009** [comment]
Indeed. Thanks.
