### ISSUE TITLE
Load Game dialog is abnormally large

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#4969]
Compared to version 1.14, the Load Game dialog takes up a disproportionate amount of space, almost filling up the entire screen. I would assume this change is not intentional since it goes opposite to previous (and future, such as issue #4817) efforts to limit line width across the board for easier reading and tidier layout.

![image](https://user-images.githubusercontent.com/489895/85812929-ed409500-b72f-11ea-9b7f-46d2b8c6d1ec.png)

The culprit is PR #4860 / commit f3a472ab963a5ff04b738ccb90de1c151039c1b6 specifically, as reverting it fixes the issue:

![image](https://user-images.githubusercontent.com/489895/85813031-2da01300-b730-11ea-9fc0-89933e65e734.png)

**Comment by Pentarctagon** [comment]
@gwhitney Would you be able to take a look at this?

**Comment by gwhitney** [comment]
Mea culpa. My physical screen is not large (38cm diagonal), but has lots of pixels, and I am generally loading saves from days ago, not hours ago, so with the font scaled to a physical size that is comfortably readable, there is nowhere near enough horizontal space to fit the preview map column, filename column, and date column at the old screen fraction and actually see the information needed to select a save file. So I just bumped up the limit to be a large fraction of the screen size, and since everything likes to expand, it always takes up that fraction of the screen.

The faint highlight/boxing of the current line means, to me, that the first screenshot above is not really problematic to use, but I totally respect the needs/desires/judgment/design of other more experienced players and of course the developers of the game.

What design suggestions do you have for something that would look nice for a broad cross-section of players but will actually display enough information to be usable for folks in situations like mine?

I can think of two possible directions to go, the first more convenient for coding than the second:

1) In addition to a fairly large screen-fraction cap on the size of the dialogue, determine an additional cap on the number of "ems" wide and "exs" high the dialogue should be in terms of the font in which the file names/dates are rendered. Then I can figure out how to get/approximate the em and and ex dimensions of the font and make the dialogue respect that cap in addition to the loose screen-fraction cap (i.e., basically choose the smaller of the two caps). Judging from the second screenshot, I'd guess _very_ roughly 50 ems wide by 60 exes high, but if anyone has a better sense, I'm happy for guidance

2) Find the natural max width each of the three columns needs to display its content, and never go any larger than that, even if that's not as big as the screen-fraction cap (while respecting the cap if it's not enough room to display everything, as in a very long filename for one save file). That's the main drawback to this approach -- if I happen to save just one game with a very very long name, it would recreate the layout in the first screenshot that is being objected to.

I am of course open to other suggestions as to how to resolve this tension, which I feel ultimately results from most everything in the game being denominated in widely varying (from player to player), structural terms like pixels and screen size, rather than content dimensions like ems and exes. I agree that to accommodate everything from smartphones to wall-size displays, one absolutely needs some influence from things like physical screen dimensions, but the more that can successfully be put in terms of content dimensions, the better off things will be in terms of scaling to different physical circumstances, and I think it's almost never useful these days to think in terms of pixel dimensions for high-level organization of a game interface.

Sorry to belabor my two cents -- the bottom line is I am happy to create and submit a PR for a solution here that encompasses both the concerns expressed in this issue, and the need to actually show a useful amount of information on physically small screens. Just let me know what method of mediating between these potentially differing desires for determining the dialogue size you'd like me to implement as the next try of producing an interface that works for as broad a selection of players as possible.

Thanks!

**Comment by Pentarctagon** [comment]
Taking a closer look at this, it seems as though there might also be a GUI2 bug being hidden by [this line](https://github.com/wesnoth/wesnoth/blob/8eba5615e1f75b068d4580a98c095e7d18bd3788/src/gui/dialogs/game_load.cpp#L195) which truncates the displayed file name to 40 characters.

Deleting that and creating a very long filename results in a vertical scrollbar:
![scrollbar](https://user-images.githubusercontent.com/3030250/85915292-cd7e9f00-b80b-11ea-8417-eeae441c2c1e.png)

Adding `characters_per_line = 40` to [the label](https://github.com/wesnoth/wesnoth/blob/8eba5615e1f75b068d4580a98c095e7d18bd3788/data/gui/window/game_load.cfg#L201-L205) then adds the vertical space to the label, but doesn't actually enforce the character limit in a sensible way (I'm guessing it unconditionally adds vertical space without checking if it actually cut off the current line at the character limit?):
![characters_per_line](https://user-images.githubusercontent.com/3030250/85915305-dff8d880-b80b-11ea-9d49-832997592a1b.png)

Adding `wrap = true`, either by itself or with `characters_per_line` also present does not seem to have any effect.

**Comment by shikadiqueen** [comment]
@Pentarctagon `characters_per_line` has issues, making it the main (only?) culprit of the conspicuous blank space gaps in the full descriptions of some of the Advanced Preferences items. Hard from the only issue we have with measurements that involve Pango in some capacity (see issue #3443).

@gwhitney I'm going to begin by explaining the logic at the time I decided some dialogs should not extend past 800 pixels horizontally (or in some cases, 600). Back then, high DPI screens were relatively rare outside of the Apple ecosystem (which we had more serious issues with in the form of the game being displayed tiny instead of upscaling with dpi, as well as fullscreen mode not working). I didn't have access to high DPI screens myself, so all the UIs I touched I did so under the assumption that the game would run on a 1920x1080 96 DPI screen at most.

Obviously times have changed, which means that the pixel-based approach doesn't scale well (pardon the pun) unless you *scale the pixels* too, which is what web browsers do with their CSS engines. We can't quite do that though because unlike CSS, a lot of our chrome is raster data (this includes things such as the icon button seen in that dialog, and the backgrounds of buttons, listboxes, etc.).

I feel like solution 1 is the most reasonable approach but it's also probably not going to be as easy as you expect because of the aforementioned issues with `characters_per_line` and other Pango layout measurement. Now, ideally, the end result should be that the dialog's maximum width *in character measurements* remains the same as before, instead of the dialog growing proportional to the game window's size; because, again, the latter isn't an indicator of how tiny/large pixels are on the screen. Then again I understand that we have functionality now to obtain that data point and use it in a way that makes sense.

Also, regardling filename length, that's another issue entirely. Yes, the dialog has always ellipsized filenames — under GUI1 it was to avoid the filename labels overflowing the available real estate (!), and under GUI2 it's to avoid the horizontal scrollbars. As you know, most mouses don't have horizontal scrollwheels/buttons, so in general horizontal scrollbars should be avoided as much as is humanly possible so the user doesn't need to perform extra actions to see information that should be immediately available to them.

(As a side note, right now the Preferences dialog also has an issue with an extra vertical bar showing up to allow scrolling about 4 pixels of the "tab menu"-style listbox on the far left.)

**Comment by gwhitney** [comment]
OK, actually after puzzling around on this for a bit, I came up with a (slightly cop-out but apparently quite practically workable at the moment) third route in the PR I just filed: Since the original given pixel sizes of the window matched up well with the old fixed pixel size of text, I just scaled the dialogue size by exactly the same factor as the text, capped by a fraction of the screen size (and making sure to never make it smaller than it would have been before #4860 so as not to upset older, smaller-pixel-dimension layouts). It's a simple config-only change and it seemed to work pretty well for me at a variety of screen sizes and pixel pitches.

Of course, this doesn't get us any closer to the possible goal of expressing UI dimensions in text-based units like em and ex. It's just that as predicted by shikadiqueen, it was tricky to see how to support an "em_size" or "ex_size" variable in the width expression of a window. Since a window is a styled_widget, it does have a text_font_family and text_font_size attribute. But (a) I am not sure that those attributes are generally getting filled in for most dialogue-level windows in general or the load game dialogue in particular, and (b) I felt that untangling question (a) **and** then figuring out in the code how to read those variables, use cairo/pango/whatever to translate to em and ex dimensions, and then populate a couple of variables in the configuration with those dimensions all before the width and height expressions were evaluated, would have been going a bit above and beyond the call for just a single dialogue, especially when this stopgap seemed to work fine at the moment.  I was just worried with various deadlines pressing in my "real life," I might not have gotten to any fix at the moment if I went down that route now.

So let me know if PR #4972 seems adequate under the circumstances.
