### ISSUE TITLE
"Registered Users Only" checkbox is checked with no option to clear it on lan servers with no user registration mechanism

### ISSUE THREAD

**Issue by yousifS** [wesnoth/wesnoth#4980]
### Game and System Information
 - What version of the game are you running? 
1.14.13

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
website for mac, flatpack for linux

 - If you're using a custom build, what compiler did you use, and what commit did you build at?
not custom

 - What OS are you running?
linux and mac

### Describe the bug
When hosting a lan server on linux box, the linux and mac clients are not able to uncheck the "Registered Users Only" option. Even though the server does not support registered users

### To Reproduce
1. From a mac or linux client, log into the official servers and create a game with the option "Registered Users Only" checked.
2. leave the game
3. log out
4. Start a locally hosted lan server
5. log into the local lan server from mac or linux client
6. Creating a game will have the  "Registered Users Only" checkbox checked on by default, with no way to uncheck it.

### Expected behavior
If the client is connecting to a local lan server that does not support registered users, the "Registered Users Only" checkbox should not be checked by default, even if the last game created by the client had the option turned on.

**Comment by Pentarctagon** [comment]
It might be best to remove this option entirely at this point.  The primary official server requires all users to have an account, and on the alternate server (or any custom/lan server) having registered users who want to prevent unregistered users from joining seems like an unlikely situation - the alternate server simply because of the low volume of people using it and custom/lan servers since it's unlikely they'd have registration setup in the first place.

**Comment by soliton-** [comment]
Besides removing the option it would also be good to check if the underlying issue is that the game does not reset the registered state when disconnecting or at least when connecting again. That would be worth correcting unless that state is completely removed anyway.
