### ISSUE TITLE
Review how practical the new mainline macros are

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5054]
Also, implement changes to mainline macros based on said review.

@sevu can you add some detail on what this means?  Which macros are you looking at, what are you thinking might need to change, etc.

Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.6_.2810.2F17.2F2020.29).

**Comment by sevu** [comment]
Mostly it's not directly about the new macros, but another change: it's now standardized that every loyal units get's an overlay with the current macros, previously it was the case with some and with some others not. I would rather go into the opposite direction, and give an overlay only on demand.
Firstly, too many overlays are just noise, and there can be plenty of.
Secondly, marking loyals specifically makes only sense for allied units, while the unit generating macros are used for all sides.

The main idea behind the changes seems to be to glue overlay & ellipse handling to the trait (which is a good idea), and there are about 5 new macros to help with that.

**Comment by Pentarctagon** [comment]
So said macros would be changed to have an optional argument for whether to add an overlay or not, I would guess?

**Comment by gfgtdf** [comment]
> It's now standardized that every loyal units get's an overlay with the current macros

This is partly true: TRAIT_LOYAL has an optional  parameter to disable it.


> So said macros would be changed to have an optional argument for whether to add an overlay or not, I would guess?

this is more or less what the basic TRAIT_LOYAL macro currently does. but the default value is _yes_

> Firstly, too many overlays are just noise, and there can be plenty of.

I disagree, in particular in mainline i have not yet seem overlay to an extent where it get confusing.

> Secondly, marking loyals specifically makes only sense for allied units, while the unit generating macros are used for all sides.

Well, it has an optional parameter to disable it, Also i think  confusing the player by missing the overlay is worse than accidental having it on an enemy unit so the having it my default default makes sense to me,

Also if we are already talking about this i'd like to suggest getting a little more consitent with how loyal heroes are displayed in the game, in particular currently some campaigns  prefer to make the loyal jsut via the icon, others prefer to also have teh LOYAL text in the trait list https://github.com/wesnoth/wesnoth/blob/66fb021a6f7669ac515f3e238a52e852c72db125/data/core/macros/traits.cfg#L39


That said, during https://github.com/wesnoth/wesnoth/issues/5049 i _might_ want to change the behavior again since optional parameters don't really  match fit together with making then available via id.

**Comment by CelticMinstrel** [comment]
> it's now standardized that every loyal units get's an overlay with the current macros, previously it was the case with some and with some others not. I would rather go into the opposite direction, and give an overlay only on demand.

I disagree, I think standardizing it is the right option. In fact, I'd recommend going even further than the current implementation and treating it the same as the leader overlay - it'll automatically be added to any unit with `upkeep=free` regardless of whether they actually have the loyal trait.

**Comment by gfgtdf** [comment]
> In fact, I'd recommend going even further than the current implementation and treating it the same as the leader overlay - it'll automatically be added to any unit with upkeep=free regardless of whether they actually have the loyal trait.

I dont think this is a good idea in all cases, for example i have seen campaigns where upkeep is disabled in certain scenario, by temporarily adding an invisible loyal trait to all units

**Comment by CelticMinstrel** [comment]
I think disabling upkeep would be better handled at the scenario level rather than by modifying all units. I'm not sure if there's any scenario settings that control upkeep but I imagine one could be added, maybe an `upkeep_per_level` key or something? This could then be indicated to the player in other ways rather than as a loyal icon.

**Comment by sevu** [comment]
The question is, what is the overlay for? On the player side, it's signalling that this is a unit which you may let die, but it will be a bigger loss – take care.

For enemy sides it would tell, if you kill this unit you will not give the enemy a slight income bonus in return because of not having to pay upkeep anymore.
The way some scenario are designed it may also warn the player that he doesn't has to be afraid of this unit, as it may have status=guardian at the same time.
For both I wouldn't highlight the unit with an overlay.

> Also i think confusing the player by missing the overlay is worse than accidental having it on an enemy unit so the having it my default default makes sense to me

Makes sense. The 2-3 macros for placing loyal units could optionally set the overlay as well.

Some places in mainline:
- Lisar's royal guards at the Ford of Abez are loyal. They once had a marker, but I think the look better without.
- Some dwarves in NR02 have/had no upkeep for no particular reason. Rewritten in 1473f60.
- Some scenarios in TSG, probably for balance reasons.

> CelticMinstrel

That's also a way. This would then be an UI for the player to look up upkeep, and scenario authors should not secretly mess with it anymore then.

A way to disable this for scenarios may not be enough though, e.g. 5p The Wildlands has a side where gold in general makes no sense (they can't recruit), and to not have the gold counters go all red they have an object which makes them upkeep-free.

I could imagine to use upkeep=loyal to apply a marker and upkeep=0 to not apply a marker (because L0 units also have upkeep=0). Though no, these changes aim to remove modifying upkeep directly.

Thinking this a bit farther … it could be like the orbs? Applied automatically, but only visible to you yourself. But then again like overlays having a way to override it … -.- Well, something tells me that orbs are it's entire own thing.

> TRAIT_LOYAL_HERO_NOSLOT

Maybe removing? If the unit is not loyal it can use MAKE_HERO / UNMAKE_HERO, if it is loyal it should have the trait too. Needs to drop another trait for some units to adhere to the 2 traits convention / UI limit, but loyal is the best trait anyway.

But I see another problem here, if the unit has TRAIT_LOYAL_HERO, can't use UNMAKE_HERO when the point comes that the "hero" played it's part and may now die without the player losing.

We have just too many ways to do the same things in wesnoth.

…

But it can be resolved by not having TRAIT_LOYAL_HERO, but adding to MAKE_HERO besides the new overlay also
```
id=hero-overlay
take_only_once=yes
[effect]
    apply_to=overlay
    remove="misc/loyal-icon.png"
[/effect]
```
for the case it's a loyal hero, and having UNMAKE_HERO use [remove_object].
If both is used, it should get the loyal overlay back then.

In that case the IS_HERO macro be implemented by just adding the same object like MAKE_HERO.

**Comment by gfgtdf** [comment]
> if the unit has TRAIT_LOYAL_HERO, can't use UNMAKE_HERO when the point comes that the "hero" played it's part and may now die without the player losing.

How so?

**Comment by gfgtdf** [comment]
So Let me explain how it is "currently" (1.15, after i added these traits) _supposed_ to work (not saying it does): Related to 'loyal' there are states a unit can be in

1) Not-loyal
2) Loyal
3) Hero-loyal
4) Leader


for each of those there should be a {MAKE macro, that transforms the unit  into that state, independent to the state it was in before, furthermore these state are by default exclusive, meaning it makes for example no sense to have a unit with both canrecruit=yes and a loyal trait.

**Comment by sevu** [comment]
So, getting back to this …
For the code, I originally overlooked that it's possible with the current one too. But for the code change, I think it makes sense in that the two macros don't need to be deprecated, and that loyal is always the same.

One thing which is interfering with the idea of the new macros is, the unwritten rule that musthave traits should be first, and loyal too (after them), and then the 'normal' traits, while adding a trait add it always as last. Though, maybe this rule can be implemented as engine feature?

What I'm not sure is whether it helps someone to introduce new macros, after all the campaigns were already written.

Are there other cases than the 4 mentioned? Not really, or, we don't have to provide macros for them. One corner case I know is a scenario, where the leader of another side joins as loyal later, but he doesn't get loyal from the beginning to not spoil it to the player. However, he is resilient (squishy unit), and should have loyal before resilient when he's made a leader later. Wasn't using macros for this in the past either.

===== 

I thought a bit about the other way too, to make it an engine feature. How does sound:
If the unit has no overlay set specifically, i.e. if it is nil, then it provides the loyal icon if upkeep is 0, and neither level is 0 nor canrecruit is true. Similar handling for the leader overlay.

**Comment by CelticMinstrel** [comment]
> If the unit has no overlay set specifically, i.e. if it is nil, then it provides the loyal icon if upkeep is 0, and neither level is 0 nor canrecruit is true. Similar handling for the leader overlay.

This sounds _mostly_ okay? I just don't think it's alright for any random overlay to suppress the default loyal; it doesn't suppress a leader overlay after all. If it's specifically the hero overlay you're worried about, couldn't that just be arranged to completely cover the default loyal overlay? If any overlay suppresses the loyal icon, then some of the loyals in my campaign would lose their icon (at least the treewalker you get in the first scenario).

**Comment by Pentarctagon** [comment]
Is this something that should be moved to 1.17, or closed?

**Comment by CelticMinstrel** [comment]
Changing this now would probably violate the feature freeze, wouldn't it?

**Comment by Pentarctagon** [comment]
It would.

**Comment by cooljeanius** [comment]
This is something that affects porting add-ons from older releases to the 1.16 add-on server

**Comment by Pentarctagon** [comment]
@sevu should this remain open?
