### ISSUE TITLE
add a 'preset advancement' mod to mainline

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#5129]
As said the in title, i think most people agree that the fact that units advancements are chosen randomly using the enemies turn is undesirable. And i think we need a mainline solution for that, Ideally one that also works with amlas. I'm not sure yet whether we should make it optional, like the preset_advacement mod or not. In fact i am not even sure what teh best solution woudl look liek to I'm opening this issue for discussion.

There are a few solutions already implemented in umc campaigns:

1) A 'preset advancement' mod that allows people to choose the advancement in advance.
    I'm not sure how well this works in the rare case when a unit advancements multiple times during an enemies turn.
   The cose as-is probably also wont work for amlas. 

2) LotI has some code that delayed choosing the advancement to the start of that players turn.
  The way it implemented in LotI only works for amlas and also only because all amlas increase the neeed expo by teh same amount afaik.
  I still think the idea is interesting though, although the only clean way to implement this would probably to delay advancement to the next turn completely, so that units coudl no longer advance at all during the enemies which you be a little change to the gameplay, since the '1 xp missing' unit would go from 'really strong' to 'really weak'

**Comment by soliton-** [comment]
Delaying does not sound like a thing that can be implemented sanely.

Random advancement was no big deal for years so I think we don't need to jump the gun and implement anything crazy. IMO just optionally allowing to pre-choose the next advancement (or maybe the whole tree if that's not much more difficult) is plenty. We can see how that goes and look further If that still leaves a lot to be desired.

**Comment by gfgtdf** [comment]
> Delaying does not sound like a thing that can be implemented sanely.

how so?

**Comment by Pentarctagon** [comment]
I agree that this would be a good thing to fix, whether it's #5130, mainlining PYR, or some other option.  Having a unit that you'd been feeding xp to level suddenly get ruined because the game randomly chose an option you didn't want isn't good gameplay regardless of the technical reason behind why it's being done.

**Comment by gfgtdf** [comment]
> mainlining PYR

If we do this we should really imprve it to make it work with amlas aswell and make it a bit more robust robust against other wml codes that change the advancements of a unit.

**Comment by soliton-** [comment]
> Having a unit that you'd been feeding xp to level suddenly get ruined because the game randomly chose an option you didn't want isn't good gameplay regardless of the technical reason behind why it's being done.

Just to be clear there is no technical issue here if you're talking about not having it work like in single player. The issue is usability so you don't have to wait for actions from other sides in your turn. (The random part is not important for that naturally but it needs to be automatic in some way.)


Yes, the addons for pre-picking advancements show that there is room for improvement thus mainlining one (or its functionality anyway) sounds like the logical next step.

I don't see how it suggests that we need game play changes but we can test stuff out certainly.

**Comment by Pentarctagon** [comment]
Would it be worth it to merge #5130 and then get some feedback over the next few 1.15 point releases to see what players think about it?  It doesn't look like a difficult thing to revert, if needed.

**Comment by gfgtdf** [comment]
> Would it be worth it to merge #5130 and then get some feedback over the next few 1.15 point releases to see what players think about it? It doesn't look like a difficult thing to revert, if needed.

Yes, basicially the plan. Although we can surely work on an improved PYA mod at the same time.

**Comment by renom** [comment]
The random advancement bug happens very rarely. The PYR-like stuff looks unnatural and would require extra job to do for the player (especially when it turns to have lots of units). I suggest allowing the player to choose the advancement and pausing the timer while they're making the choice.

**Comment by soliton-** [comment]
> The random advancement bug happens very rarely.

What bug? Are you talking about the expected behavior of choosing a random advancement when leveling out-of-turn?

**Comment by CelticMinstrel** [comment]
I'm _pretty_ sure that it didn't do that in an older version of the game, at least when playing a campaign. I can't reproduce it easily in 1.12 since the enemy absolutely refuses to attack a unit 1 xp away from levelling, so maybe it was in 1.10? But that does mean that random advancements are a regression (assuming I'm remembering correctly), so I think that's enough to call it a bug.

**Comment by Pentarctagon** [comment]
I was actually surprised that it was a random advancement instead of something deterministic.  If it's known ahead of time what any particular unit will level up to if it advances on another player's turn, then there could at least be some degree of planning to deal with it.

For example, if a unit that levels up on another player's turn always advanced to the first unit type listed in the unit's `advances_to`, then I'd know that a Mage that levels up on someone else's turn will always turn into a White Mage.

**Comment by Pentarctagon** [comment]
I think (?) it'd also mean that advancements could be chosen just by swapping around the unit type listed first in `advances_to` which might simplify the implementation of PYA?

**Comment by renom** [comment]
> > The random advancement bug happens very rarely.
> 
> What bug? Are you talking about the expected behavior of choosing a random advancement when leveling out-of-turn?

Well, I mean, this case occurs not as often as you (the wesnoth devs) think. At least that's true for classical maps played with the default era. Most of lvl-ups happen when the unit, which is going to advance, is attacking. The enemy isn't interested in leveling-up your units. Also, not every unit in the game has more than one possible advancement. I have no stats about this case, but I'm pretty sure, you overestimated time-wasting when you said "you don't have to wait for actions from other sides in your turn". Choosing between possible lvl-ups for your units in advance will waste much more time than waiting for your opponent's action in a rare case.

**Comment by renom** [comment]
> I'm _pretty_ sure that it didn't do that in an older version of the game, at least when playing a campaign. I can't reproduce it easily in 1.12 since the enemy absolutely refuses to attack a unit 1 xp away from levelling, so maybe it was in 1.10? But that does mean that random advancements are a regression (assuming I'm remembering correctly), so I think that's enough to call it a bug.

AFAIK, the bug occurs only in mp.

**Comment by AI0867** [comment]
It's not a bug, it's a workaround that avoids having the player whose turn it is having to wait for a different player, who may not even be at his computer.

That is, it's intentional behaviour, though it's far from ideal.
