### ISSUE TITLE
HttT: Lisar Loses Sceptre of Fire upon Leveling Up

### ISSUE THREAD

**Issue by PiotrMakarewicz** [wesnoth/wesnoth#5161]
As described in the [link](https://forums.wesnoth.org/viewtopic.php?p=658500#p658500)

**Comment by newfrenchy83** [comment]
@PiotrMakarewicz i reproduced the bug, but when i create a Princess unit with scptre variation and i i level up in debug mode, she not loses variation, i think what it is because Li'sar take the Sceptre of Fire in 1.15.4 who have a bug in variation. You must be replay the scenario for clean the bug in 1.15.5.

**Comment by stevecotton** [comment]
Fixed in 1.15.5, probably by ae3eea28f82ea0443704e287c6be105d5d928b2e. Many thanks for reporting and debugging.
