### ISSUE TITLE
Does anyone want [story][part][image]scaled=yes ?

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5223]
This is about the `[story][part][image]` tag, not the main `[image]` tag. This tag is documented on the IntroWML page, but is possibly only used by the macros `OLD_JOURNEY`, `NEW_JOURNEY`, `NEW_BATTLE`, etc.

My question is, does anyone want to keep its `scaled` attribute? This undocumented attribute defaults to false, but if you add `scaled=yes` then the image is scaled up to the width and height of the background - not to the same ratio as the background, but to the full size. So if you have a 1000 pixel wide background in an 800 pixel wide window, then `scaled=yes` means each journey-marker is an 800 pixel-wide blob.

The bug is already present in 1.14, haven't checked 1.12 yet. It would be easy to fix, but as no-one's noticed this bug then I'd prefer to just delete it.

Note: the `scaled` attribute doesn't control the positioning of the image. The x and y co-ordinates will still be scaled so that a journey marker that's meant to be on top of a map location is still correctly placed when the background image is scaled.

**Comment by Pentarctagon** [comment]
What do you mean by "possibly used"?

**Comment by CelticMinstrel** [comment]
> This is about the `[story][part][image]` tag, not the main `[image]` tag.

What do you mean by "the main `[image]` tag"?

> possibly only used by the macros `OLD_JOURNEY`, `NEW_JOURNEY`, `NEW_BATTLE`, etc

I _kinda_ doubt this is the only place this tag is used?

> My question is, does anyone want to keep its `scaled` attribute?

It looks like this attribute is undocumented, so assuming it really exists, probably removing it without notification is fine? (Or with a level 4 deprecation message if that's easy to do.) It's not even used in the aforementioned macros though.

I think if anyone _does_ want a scaled image then they can probably use a `[background_layer]` instead of an `[image]`, assuming the engine supports more than one `[background_layer]` in a `[part]`. (It does support more than one `[image]`, which the documentation seems to imply is not the case at least once.) Or if they want it scaled to a specific size, then they can use IPFs.

**Comment by stevecotton** [comment]
> What do you mean by "possibly used"?

I meant that sentence to be split in a different way by the reader. It's possible that the complete list (including UMC) of places that use this tag are those macros, and UMC variants that are very similar to the mainline macros (there are some in Defense of Elensefar).

> What do you mean by "the main `[image]` tag"?

The one in that's listed in https://wiki.wesnoth.org/index.php?title=Template:WML_Tags , which is a TerrainGraphicsWML tag.

**Comment by Pentarctagon** [comment]
Is the key defined in the WML schema?  That'd at least tell us if it's used in mainline or not.

**Comment by stevecotton** [comment]
It's not in the WML schema.

**Comment by Pentarctagon** [comment]
Given it's an undocumented attribute that has a bug which hasn't been reported by anyone over multiple years and it isn't used in mainline, I'm fine with just removing it.

**Comment by stevecotton** [comment]
Cool, will remove it in #5041 .

**Comment by stevecotton** [comment]
The (draft) PR that will close this has been created, and there's no value in keeping this question open any longer.
