### ISSUE TITLE
UtBS all Quenoth units have female alignment names

### ISSUE THREAD

**Issue by PiotrMakarewicz** [wesnoth/wesnoth#5307]
### Game and System Information
1.15.7 from Steam, Win10

### Describe the bug
All Quenoth units' alignments are displayed as though they were female ("praworządna"). Instead, male units should have "praworządny" displayed.

### Screenshots
<img width="960" alt="ss1" src="https://user-images.githubusercontent.com/54529536/99956295-179d8980-2d86-11eb-877e-10a3bd0e8314.png">

**Comment by PiotrMakarewicz** [comment]
I found the same problem in Czech, but not in Russian. Apparently it's the matter of translation, not the game code itself.

**Comment by sevu** [comment]
You're right, it's in the textdomain "wesnoth".
Can you post in [this thread](https://r.wesnoth.org/t3796) to reach the polish translation maintainer, [ForPeace](https://r.wesnoth.org/u140831).
Translations are managed there, because we here can't see what Polish is correct and which is not.

@hrubymar10 pinging you for the Czech part

**Comment by PiotrMakarewicz** [comment]
I am ForPeace myself :)
