### ISSUE TITLE
Load game dialogue: shows difficulty for MP scenarios

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#5321]
But there are exist no difficulties in MP scenarios. It shows »Medium« as fallback. Maybe the whole line can be skipped.
![load](https://user-images.githubusercontent.com/21158813/100483602-d72d6b00-30f9-11eb-8fa7-86bdd76d0e6a.png)

**Comment by Pentarctagon** [comment]
Either skipped, or something more accurate like "N/A" instead of "Medium".

**Comment by sauntheninja2** [comment]
I would like to work on this issue

**Comment by Wedge009** [comment]
Any progress on this?

**Comment by Wedge009** [comment]
I think this is going to be more complex than it appears on the surface. These are the save game types enumerated in code:
https://github.com/wesnoth/wesnoth/blob/20fd6d80ba8394c303be956924317b486fe370b9/src/game_classification.hpp#L37-L42

* Scenario - despite the name this seems to refer to SP games, which are usually story campaigns.
* MP - this seems to refer to all MP games, whether single scenarios or campaigns (currently Legend of Wesmere and World of Conquest available as standard).
* Tutorial - I think this is for the old tutorial format that was strictly distinct from SP campaigns. But in 1.15.x onwards it looks like the Tutorial save game is now treated as SP campaign.
* Test scenario - self explanatory.

Problem:
* Test scenario is easy - it's easy to distinguish and it needs to ignore the difficulty.
* Tutorial is also easy - if I'm right, it will be included in SP campaign behaviour. Even though there's only one difficulty for the Tutorial it's displayed sensibly in the game preview of the Load Game dialogue.
* Scenario, or SP campaign really - this should work fine too, and my original intent was just to filter the 'scenario' save game type for display of the difficulty.
* MP is where things are complicated - at this point it doesn't look like it's straightforward to distinguish between a regular MP single scenario (default difficulty of Medium that needs to ignored) and MP campaign (which should ideally have the same difficulty processing as SP campaign in order to get the nice 'human readable' display string).

Initialisation of 'human readable' difficulty string (which is why MP single scenario games show as Medium):
https://github.com/wesnoth/wesnoth/blob/20fd6d80ba8394c303be956924317b486fe370b9/src/gui/dialogs/game_load.cpp#L356

Checking of different save game types:
https://github.com/wesnoth/wesnoth/blob/20fd6d80ba8394c303be956924317b486fe370b9/src/gui/dialogs/game_load.cpp#L366-L418

I thought about initialising the difficulty to something like null or invalid for MP single scenarios - in the save game itself it's recorded as `difficulty="NORMAL"` - but I'm not sure where this is done. Having a marker to show when difficulty is irrelevant would make this much simpler.
