### ISSUE TITLE
NR S9, Eryssa is created with a loyal marker instead of a silver crown

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5374]
### Game and System Information
 - 1.15.7
 - Steam
 - Windows 10

### Describe the bug
Literally the title.

### To Reproduce

1. Skip to S9.
2. Free Eryssa.
3. Observe that she only has a loyal marker (but her hero death is always with 'lose the scenario' associated, which is also reflected in the scenario objectives).

### Expected behavior
She get's a silver crown so you can just look at her and go 'yeah, this one has to survive'.
(Which is especially necessary for players who know older versions NR, when she was allowed to die.)

**Comment by Wedge009** [comment]
I don't know too much about WML, but at a guess, it's because she's introduced in S8 and it's a bit of an unusual situation (compared with other campaigns) that rescuing her is not a compulsory object. Moving so S9, she's added to the recall list as-is - perhaps that is the point at which she needs to be 'upgraded' to 'hero' status to be consistent with subsequent scenarios making her death an instant loss condition?

Is it as simple as assigning her `TRAIT_LOYAL_HERO` instead of `TRAIT_LOYAL`? Not sure if @sevu is still around and working on this...
