### ISSUE TITLE
SoF S2, the trolls behave passive (which is a difference compared to 1.14)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5394]
### Game and System Information
 - 1.15.8
 - Steam
 - Windows 10

### Describe the bug
The Trolls mostly just wait where they were placed, which makes it harder to remove them fast.

### To Reproduce

1.  First, start SoF.
2. Then, skip to S2.
3. Lastly, play the scenario while disabling shroud. You'll notice that the trolls are not moving to attack unless you close in on them.

### Expected behavior
The trolls rush at your units, because they did so in 1.14 (if I'm remembering this correctly).

### Savefiles
[SoF-Closing the Gates replay 20201228-174459.gz](https://github.com/wesnoth/wesnoth/files/5748127/SoF-Closing.the.Gates.replay.20201228-174459.gz)

**Comment by doofus-01** [comment]
They are guardian, not passive.  Apparently this was made so in a1f855a0a858b422c09e1bd34713cad822b1d38e
@nemaara and @sevu didn't think it was was a problem.  Is it?

**Comment by Konrad22** [comment]
I think it makes it more difficult, but I'll need a couple more attempts to figure out if it makes it unbeatable (for me).

**Comment by nemaara** [comment]
I seem to recall making them guardians since it was really troll for them to waltz down the corridors right at the start of the scenarios to attack you. I also seem to remember it being easier with the change, but maybe I'm remembering wrong. I think I'd rather keep the current behavior though and just adjust the scenario's difficulty accordingly, but can be convinced either way.

**Comment by doofus-01** [comment]
I just tested it, I don't believe this makes things more difficult, and as mentioned, guardian makes sense.

It's good to keep an eye out for AI changes, but I think this scenario is still OK.
