### ISSUE TITLE
NR S13, please switch Hamels (AI) and Krashs (player) sides

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5396]
### Game and System Information
 - 1.15.7
 - Steam
 - Windows 10

### Describe the desired feature
NR S13 is a huge scenario with about 9 sides, 3 of them being under control of the player. I would like for those 3 sides to take their turns one after another, without an AI side inbetween. That way the player can do his part and then leave for a couple of minutes until it's the players turn again. 
Right now it's like this: Player -> 5x AI -> Player -> AI -> Player
I'd like to have instead: Player -> 6x AI -> 2x Player

### Screenshots
![grafik](https://user-images.githubusercontent.com/39015360/103232073-cd399a80-4939-11eb-924a-b7fce06ba001.png)
![grafik](https://user-images.githubusercontent.com/39015360/103232084-d165b800-4939-11eb-94a7-d0abe7a43107.png)

**Comment by hexagonrecursion** [comment]
> That way the player can do his part and then leave for a couple of minutes until it's the players turn again.

I think there is a better alternative:
1. Go to Preferences -> General
2. Check "Skip AI moves". Note: it is somewhat confusingly named because it only skips movement animations but does not affect the attack animations
3. On the same tab set "Accelerated speed" to 16
4. Go to Preferences -> Hotkeys
5. Find the hotkey for "Accelerated". This toggles the accelerated mode allowing you to see your turns nice and slow, but fast forward through the AI turns.

**Comment by Konrad22** [comment]
That's something I'm doing anyway, and it's not the point of this request.
