### ISSUE TITLE
Update xBRZ

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#5474]
The xBRZ lib was added by iceiceice back in 2014 (eeb92161e07ef4e65d1510e81d84e1719e4695a0). Since then, the repo has moved and its source is now here: https://sourceforge.net/projects/xbrz/files/xBRZ/ Unfortunately, updating is non-trivial since iceiceice did a bunch of custom changes to alpha handling to make it work with our usecase, so those would need to be reapplied on top of an update.

**Comment by Pentarctagon** [comment]
Is it documented somewhere what changes he made for alpha handling and why they were needed?  The commit message mentions several changes that needed to be made, but nothing was mentioned about alpha handling.

**Comment by Vultraz** [comment]
Relevant commits are:
- 6040e9bf01427faf9fe23fc43df46431f27529de
- 4e3179496263d3247c906e4d513e1caca8797eb3
- ea23fc4f4a139de0d6ba5a03d1c6a71561ccff5e
- a28082c03a816ac942e3864a3292fe2805cfe0b5

**Comment by AI0867** [comment]
From the first commit message, it sounds like xBRZ flat-out ignores alpha and makes its output fully opaque. Those 4 commits look like an attempt to be mathematically correct, but avoid edge-issues in our usecase.

**Comment by stevecotton** [comment]
There's a lot of commented-out code in the xBRZ file, too.

**Comment by stevecotton** [comment]
While I'm not sure it's caused by the xBRZ adaption, there's two bugs about things getting a green or cyan tinge when scaled: #3937 and #5420.

**Comment by shikadiqueen** [comment]
> While I'm not sure it's caused by the xBRZ adaption, there's two bugs about things getting a green or cyan tinge when scaled: #3937 and #5420.

The scaling algorithm used in either case doesn't look like xBRZ (which was a non-default option in 1.14 for zoom scaling).

**Comment by Andrettin** [comment]
Unfortunately, newer versions of xBRZ are explicitly licensed under the GPL 3.0, which would make them incompatible with Wesnoth. The earlier version of xBRZ which iceiceice for the Wesnoth implementation was licensed vaguely as "GPL" instead, making it compatible with both the GPL 2.0 and GPL 3.0, as per the text of the license (this is a part of any GPL license regardless of version):

"If the Program does not specify a version number of the license, you may choose any version ever published by the Free Software Foundation."

So this issue seems to be non-solvable, unless Wesnoth's license changes to the GPL 3.0.

**Comment by AI0867** [comment]
I was trying to look at what changed in xBRZ during the past 9 years, both before and after the license change, because the changelog seems to indicate they went in the same direction as our local changes, but I can't even find the source code on sourceforge any more. Is that just me, has sourceforge become that terrible, or is the source code located elsewhere, and just not linked from there?

We seem to expose xBRZ directly as an imagepathfunction, which we then also use quite a bit in core, mainline campaigns and C++ (help topics), so removing it isn't really an option.

That seems to leave us with the following options:

1. Leave it as is, with possibly minor modifications to adapt to toolchain/library/other API changes
2. Maintain it ourselves, possibly starting by porting all the pre-license-change updates.
3. Ask Zenju for a license change/exception
4. Replace xBRZ with an equivalent library. I have not done extensive research here, but I found a [permissively licensed C++-implementation of "Super-XBR"](https://pastebin.com/cbH8ZQQT). We'd definitely want input from pixel artists on this.
