### ISSUE TITLE
Why do you insist on breaking player expectations?

### ISSUE THREAD

**Issue by hexagonrecursion** [wesnoth/wesnoth#5505]
You gave scenario authors too much power over the game UI and the core game features. This is to the detriment of the player. When the player notices something behaving unusually she will be surprised. He will think it is a bug. And she will be right. Just because it is intentional does not make it any less of a bug.

Examples:
- [scenario] turn_at. Players expect this to be part of the UI and they expect this to be consistent. Why did you choose to allow scenario authors to change the number of the first turn?
- [scenario] do_healing
- [side] suppress_end_turn_confirmation
- [endlevel] carryover_report
- [endlevel] save
- [endlevel] replay_save
- [endlevel] linger_mode
- AMLA that don't heal to full HP (related #4578)

**Comment by Vultraz** [comment]
All these have uses in specific circumstances and none of them are bugs. I will grant `turn_at` does not make much sense (no idea what that exist), but the others are around for a reason.

**Comment by Pentarctagon** [comment]
As an example, a few of those are useful for scenarios that only contain dialog rather than any combat or other player choices.

**Comment by doofus-01** [comment]
I completely disagree with this "issue".  There are good reasons to have those tags/keys/options.  If it were up to me, this would be closed.

**Comment by CelticMinstrel** [comment]
* `turn_at` - Okay, I can't think of any reason to customize this.
* `do_healing` - Customizing this could for example allow for creating a scenario where a curse prevents people from healing. Merely setting it to false is a bad idea, though - the player should be given some indication that it's intentional, for example through dialogue.
* `suppress_end_turn_confirmation` - This is intended for unconventional scenarios where you're not necessarily expected to move units every turn. The confirmation exists as a safeguard against people accidentally hitting the end turn button before they've started their turn, but if the scenario doesn't expect you to move units at all, then it becomes more of a nuisance than a help.
- `endlevel` stuff - I think that's probably meant mainly for cutscene scenarios, but I actually think you might be right that there's too much customization allowed here. I mean… if you're making a cutscene, you very likely want to change _all_ these parameters, not just one, right? So do they need to be four separate parameters? Are there good reasons to customize one of them but not all? Maybe there are good reasons, I'm not sure, but… merging these into a single setting _might_ be worth considering.

**Comment by soliton-** [comment]
Pretty sure `turn_at` is more an implementation detail of savegames.

**Comment by CelticMinstrel** [comment]
If it's an implementation detail, then it's fine for it to exist, but it should not be documented on the wiki in that case.
