### ISSUE TITLE
private_replay setting gets reset on advancing

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#5511]
### Describe the bug
https://replays.wesnoth.org/1.14/2021/02/02/Ladder_Classic_Maps_Turn_1_(105452).bz2
https://replays.wesnoth.org/1.14/2021/02/02/2p__Fallenstar_Lake_Turn_19_(105453).bz2

These two replays come from the same game by using a map picker that advances to the next scenario with the randomly picked map.

In the first file we can see `private_replay=no` and in the second `private_replay=yes` (I've made it public manually).
I've checked a couple of other replays and it seems like advancing to the next scenario resets `private_replay` to yes.

### To Reproduce
Play a game with a map picker for example the one in the ladder era add-on.

### Expected behavior
The `private_replay` setting should be kept from the previous scenario.

**Comment by soliton-** [comment]
Would be great to get a new stable version out after fixing this.

**Comment by Pentarctagon** [comment]
As a reminder to myself, a couple other bugs I'll be fixing at the same time:
* when advancing to the next scenario of an MP campaign, the list of content sent by the client to be inserted into the database gets the information for each scenario appended by the client.  For example, the first scenario sends the first scenario's ID, the second scenario sends the first scenario's ID **and** the second scenario's ID, etc.  My guess here is that this information just needs to be cleared between each scenario.
* the game history query needs to be updated to return an empty string for the replay URL if the game was marked as being private.  This can be fixed with a simple `case` clause in the SQL query text.

**Comment by Pentarctagon** [comment]
What's the name of the add-on you use to reproduce this issue?  I tried with the LoW MP campaign, and in that case the private_replay flag was preserved as expected.

**Comment by soliton-** [comment]
Sorry, I meant to check this further. The report is from an earlier version (1.14.11). It appears the issue was already fixed at some point.

Feel free to close or keep it for the other things you mentioned.

**Comment by Pentarctagon** [comment]
I'll go ahead and close it.
