### ISSUE TITLE
'Load Game' window should not be shown if there is no saved game

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5517]
### Game and System Information
The Battle for Wesnoth version 1.15.9+dev (c42bf114-Clean) x86_64

### Describe the bug
The current behaviour is a bit weird, you can interact with elements inside the window even if there is no save to load.

### To Reproduce

1. Remove all saved games
2. Click 'Load'

### Expected behavior
'Load Game' window should not be shown when there is no saved game.
There should be a different dialogue window clearly stating that there is no saved game to load.
![Screenshot_20210204_194732](https://user-images.githubusercontent.com/3605541/106945363-fbc04780-6727-11eb-9b5e-eee87a63f786.png)

**Comment by Pentarctagon** [comment]
@Vultraz Can you look into this?  I assume it'd be enough to instead just show a message stating there are no saves to load.

**Comment by grz0** [comment]
BTW, I think this 'Open saves folder' icon should be preserved in this new window containing the message. It makes it easy to find where the directory with save files is located.

**Comment by Pentarctagon** [comment]
I was thinking it'd just be a click-through popup sort of message (there's a proper word for it that I can't remember at the moment) - it's already possible to get to the saves folder from the "i" button on the main menu if someone needs to get to the saves folder without having any existing saves.

And actually that's what already happens on 1.14, so apparently that got lost/deleted on master for some reason?

**Comment by grz0** [comment]
> And actually that's what already happens on 1.14, so apparently that got lost/deleted on master for some reason?

It is also in master, so I think there is no need to preserve 'Open saves folder' icon.

**Comment by Pentarctagon** [comment]
I mean that the popup got lost on master somehow, since on 1.14 after clicking Load with no saves I see:
![Screenshot from 2021-02-04 18-39-47](https://user-images.githubusercontent.com/3030250/106973406-72554900-6718-11eb-8ece-03e55c3336b9.png)

**Comment by Pentarctagon** [comment]
@stevecotton It looks like this happened at https://github.com/wesnoth/wesnoth/commit/b66bdb8a16ec8fbcfffdc14d7a4c4349004f4959#diff-dfa9e816cffc0870dbaf695051b7d276a8daa630bbb0ac4ddd98b614c0c43140L39-L43

**Comment by stevecotton** [comment]
@Pentarctagon thanks for bisecting this, however before I fix it I have to request that you chair the discussion about old save games in #2710. The question that's blocking me is whether #4524's ability to load from other versions is really a good feature for our users, or whether it's a misfeature that results in subtly broken saves which will make the mainline campaigns play badly. By "subtle", I mean changes such as the difficulty being rebalanced in such a way that the player's army has much more XP than it would have at the corresponding point in the campaign if the player had started on 1.16, yet they're facing reduced enemies.

Another thing that's making me think #4524 may be a misfeature is the removed and renamed scenarios from the mainline campaigns. Is it really useful to load a mid-scenario save, finish the scenario, and then get an error that the next scenario_id isn't found?

**Comment by Pentarctagon** [comment]
IIRC there's a warning shown when loading a save from a different stable/dev version of Wesnoth, so I think the feature is fine.  The alternative that currently happens (not so much recently, but certainly when 1.14 was new) is we have players who have upgraded asking where all their saves went and how to move them manually anyway, so I think that automatically making them available while warning players that they may be broken is, while not great, at least a step in the right direction.  Maybe the warning itself could be made scarier and-or more explicit if the current one is too tame.

Ideally there'd be a way to upgrade the save files to fix at least some of the errors (and relatedly that there would be better tracking by all of us of what breaking changes have actually happened since the last stable release) so that old saves are more likely to work, but those parts of #2710 will need to wait for 1.17/1.18.

**Comment by stevecotton** [comment]
> Ideally there'd be a way to upgrade the save files to fix at least some of the errors

Please reread what I said about "subtle". The problem isn't a technical error to fix, it's that the difficulty, the challenge, the _fun_ might be missing.

To "fix" it with an warning, think the warning message should be along the lines of:

Warning: you should restart the campaign
----

You're loading a savefile from a old version. It'll probably load OK, but the difficulty levels might be wrong. If you find it's too easy, it might just be that you've become a better player since you last played this campaign, or it might be that your recalls are stronger that the current implementation of the campaign expects.

**Comment by Pentarctagon** [comment]
I'd be fine with a warning like that, though perhaps somewhat more generic since it would need to apply to more than just campaigns, or even just have it outright say in the warning that it's recommended to use the old version if they want to continue playing the save file.  This should be a fairly simple thing for most users to do as well, since Windows and macOS users will continue to have the standalone installers from SourceForge that would let 1.14 be installed alongside 1.16 as well as for Steam the tentative plan is to put 1.14 as an option available in the BETAS tab there (despite it being the opposite of a beta).

**Comment by Pentarctagon** [comment]
To maybe explain my thought process more clearly: what making saves from previous versions selectable ingame does is make it easier for existing players to do something that they were already probably going to try doing manually on their own anyway, which makes it a good feature.  The fact that anything and everything can break in any particular way, obvious or subtle, between stable versions is a long standing issue with Wesnoth's development, so given it's now easier for players to load old saves then it follows that the warning the game gives about doing so should be as explicit about the risks as possible.

But I don't think that removing the feature is going to stop most players who want to try loading an old save in a new version from doing so, especially since with 1.14+ it's possible to open the saves directory from the main menu screen.

**Comment by stevecotton** [comment]
> I mean that the popup got lost on master somehow, since on 1.14 after clicking Load with no saves I see:
> ![Screenshot from 2021-02-04 18-39-47](https://user-images.githubusercontent.com/3030250/106973406-72554900-6718-11eb-8ece-03e55c3336b9.png)

I'm working on this issue, but think the popup no longer fits - we still want to be able to open the load dialog in the situation that there are files from another version, even when there are no files in the current version's savefile directory, and we need to be able to select an old file and then change back to the current version's directory. I'm currently refactoring the logic so that the load dialog enables and disables buttons based on whether anything is selected.

**Comment by stevecotton** [comment]
Something that I might split into a separate issue: the search for other versions' save directories doesn't handle the different paths of default, Flatpak and Steam builds - it searches for siblings of the current version's userdata directory. At least for the current issue, I'm looking at showing hints in the load dialog if there are fewer than 20 or so savefiles.

Flatpak is security sandboxed and is only expected to be able to read directories from Flatpak versions of Wesnoth.

Default builds could find Flatpak and Steam directories, this would need some extra work in filesystem.cpp's find_other_version_saves_dirs(). I think the same could be done for Steam builds to see default and Flatpak files.

**Comment by Pentarctagon** [comment]
Is it possible for a 1.16 flatpak to look into the 1.14 flatpak or vice versa?  I'm not especially familiar with flatpak, but I don't think it would allow that sort of thing.

**Comment by stevecotton** [comment]
IIUC:
* Both are going to be sandboxed as `org.wesnoth.Wesnoth`, and will be able to access each other's files.
* It would be different if we had `org.wesnoth.Wesnoth114` and `org.wesnoth.Wesnoth116`.

**Comment by Wedge009** [comment]
As I was reading through this I was thinking that there is a pop-up message when there are no save files to load but then Pent already mentioned it. It is true it (currently) does not appear in master/1.15 so would be nice to have that present - whether or not to still display the load dialogue anyway, I don't really have a strong preference.

I also recall an issue/request some time ago about unifying the save games such that one can access them from across different major versions of the game (eg 1.12, 1.14, 1.16, etc).

**Comment by stevecotton** [comment]
![wesnoth_load_hints](https://user-images.githubusercontent.com/101462/108542973-b2095c80-72e4-11eb-894b-83dd6c326d54.png)

I'm thinking along the lines of this screenshot, with the hints being hidden when there are more files than this in the directory. The wording definitely isn't right yet, please offer suggestions.
* Expecting to see more files here? Depending on the platform that you downloaded Wesnoth from, the savefile directory may be different — the icon at the bottom-left will open a file browser in this directory.
* There are savefile directories from other versions — access them via the drop-down next to the top-right search box.

**Comment by Wedge009** [comment]
Hmm, I just rebuilt and tested master (1ff1ada2) and when I click Load after removing any save files I just get the blank dialogue. Did anything change?

**Comment by Pentarctagon** [comment]
The popup only appears if all save directories have no save files, not just the current version.

**Comment by Wedge009** [comment]
Ohhh, I didn't see the drop-down box for other versions' save games. Elegant solution! Yes, I suppose behaves as expected when there are no save games across all versions.

I suppose this was steve's question about having some sort of notification if the current version's directory is empty but other versions are not. It's a bit disconcerting having an empty load dialogue even with the option to look at other versions.
