### ISSUE TITLE
UtBS: Terrain transition issues with wooden floors in Out of the Frying Pan

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#5539]
In UtBS scenario 8 (Out of the Frying Pan) there is a dungeon room that uses the wooden planks floor terrain, which normally has an orderly transition to water with custom decorated edges. Someone decided that for this particular application of it in UtBS that wasn't enough, however, and added code to replace those transitions with what's apparently supposed to be water blending into the floor, kind of like sandy beaches.

The problem is that the code in question doesn't work in practice on either 1.14 or master, creating a broken terrain look instead:

![image](https://user-images.githubusercontent.com/489895/107864380-61a08380-6e3a-11eb-9160-a076fc72f67e.png)

Furthermore, on master some of the tiles in the room use a different terrain (Old Wooden Floor `Ior` instead of Basic Wooden Floor `Iwr`) that's not accounted for by the code, resulting in a mixture of both broken and default transitions instead of the intended result.

The code can be found in `data/campaigns/Under_the_Burning_Suns/utils/terrain_graphics.cfg` guarded behind `#ifndef EDITOR`.

**Comment by doofus-01** [comment]
Do you happen to still have a save-file handy?  Thanks.

**Comment by shikadiqueen** [comment]
Not quite, but should be able to use this save on master and `:debug` and `:throw new turn` a couple of times to have the water start flooding into the wooden floor room:

[UtBS-Out of the Frying Pan Turn 2.gz](https://github.com/wesnoth/wesnoth/files/5979361/UtBS-Out.of.the.Frying.Pan.Turn.2.gz)

**Comment by doofus-01** [comment]
I think just replacing the `Iwr` wood floor with `Ior` is good enough for BfW 1.14.  It's not perfect, but it doesn't look as broken as current state, or as out-of-place as the crafted edge zookeeper was trying to avoid.
![Screenshot_20210215_2](https://user-images.githubusercontent.com/13510196/107996739-f79cf100-6f95-11eb-992e-f788970e97fe.jpg)
(ignore the hex outlines, that's a zoom artifact - an unrelated bug, might even be fixed in current 1.14)
