### ISSUE TITLE
Feature request: make AI aware of "invulnerable" unit status

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#5558]
Units with "invulnerable" status cannot be killed, yet I see AI trying to attack those units, including berserk suicide against them.

It would be nice to exclude invulnerable units from possible attack targets in AI. Note that GUI battle prediction works correctly saying that you cannot deal any damage to invulnerable units.

**Comment by vgaming** [comment]
CC @jyrkive  not sure if you have some hints on what could be changed?

**Comment by cooljeanius** [comment]
Would it be possible to distinguish between invulnerability that's set for "legitimate" reasons (e.g. by a scenario author), and invulnerability that's set by the player via debug mode in order to cheat? I often used the latter when scenarios get too hard for me and it would be disappointing if enemy units stopped feeding me as much XP when I'm doing that.

**Comment by CelticMinstrel** [comment]
I thought the AI _did_ ignore them already, but I think it's actually correct for them to attack invulnerable units.

**Comment by mattsc** [comment]
> I thought the AI _did_ ignore them already, 

No, it does not.  It ignores petrified units, that's what you might be thinking about.

> but I think it's actually correct for them to attack invulnerable units.

Yeah, I'd tend to agree with that.  One way of looking at it is that they can be attacked and therefore will be attacked by the AI, but that nothing happens to them.  It's a status the generic AI enemy would not know about (I mean that from an in-universe kind of view; technically the AI does know about it, of course).  But I don't have a strong opinion on that, it can be argued either way.

I'm going to assign this to myself.  Since the AI already ignores petrified units, this would be easy to add.  But I'll wait for other comments before deciding whether to implement this.

> Would it be possible to distinguish between invulnerability that's set for "legitimate" reasons (e.g. by a scenario author), and invulnerability that's set by the player via debug mode in order to cheat? I often used the latter when scenarios get too hard for me and it would be disappointing if enemy units stopped feeding me as much XP when I'm doing that.

I do not believe that that is possible, but even if it were, we would not do this.  We are not going to add special conditions to AI code so that a specific way of cheating works.  There are other ways you can do this.

**Comment by vgaming** [comment]
@CelticMinstrel can you please explain, why would it be correct to attack invulnerable units? I thought the intention of AI should be to win?

**Comment by cooljeanius** [comment]
> @CelticMinstrel can you please explain, why would it be correct to attack invulnerable units? I thought the intention of AI should be to win?

If the AI is too good at winning, though, it becomes unfun for the player. IMO the goal of the AI should be to provide a fun experience for the player to play against.

**Comment by AI0867** [comment]
> Would it be possible to distinguish between invulnerability that's set for "legitimate" reasons (e.g. by a scenario author), and invulnerability that's set by the player via debug mode in order to cheat? I often used the latter when scenarios get too hard for me and it would be disappointing if enemy units stopped feeding me as much XP when I'm doing that.

I believe the "cheating invulnerability" is actually set only once the fight starts, so it's not visible when evaluating potential attacks.

**Comment by CelticMinstrel** [comment]
> can you please explain, why would it be correct to attack invulnerable units? I thought the intention of AI should be to win?

The question is, what's the purpose of the invulnerability status? My understanding is that it exists to ensure that plot-critical units don't die too soon and produce strange outcomes. In that usage, invulnerability is temporarily added until some event cutscene that removes it so that the fight can continue normally, but it's strange if the AI completely avoids attacking those units in the meantime. It's less strange if they attack the unit once or twice but miss all strikes.

**Comment by vgaming** [comment]
@CelticMinstrel I'm using invulnerability in Afterlife maps to designate units that cannot -- and should not -- be attacked. I could in theory also petrify the units, but that would make the `Ctrl V` `Show Enemy Moves` suggestions wrong, which is actually a super-neat feature. The units aren't petrified conceptually in case of Afterlife, they're invulnerable

**Comment by mattsc** [comment]
@vgaming Playing devil's advocate here, the fact that you are using it in this way does not mean that that's the intended use.  (I'm not saying that it isn't, I actually do not know what its original intended use was.)  Somebody else may be using it in a way that they specifically _want_ the AI to attack such units.  In fact, with the variety of UMC content out there, it's almost a given that somebody does.

There is another way of keeping the AI from attacking specific units, with the [attacks aspect](https://wiki.wesnoth.org/AiWML#Filtering_Combat_with_the_attacks_Aspect).

Given that there is an existing method to accomplish (my understanding of) what you want, and that there are almost certainly use cases out there that would be affected if we changed this, my choice would be to keep the behavior the way it is.

**Comment by virtualghetto** [comment]
I am 100% against this.

I use invulnerable for my invincible testing mod to playtest the game.
https://github.com/virtualghetto/Heal_Harm_Unit/blob/7dc27a9f38110efb4056f747fd9927abc2a12f3d/_main.cfg#L309

For units that I don't want the AI to attack I use petrify.
https://github.com/virtualghetto/Wild_Frontiers/blob/ce079db92d95e7b1925982a546ab4617254fda77/utils/enemies.cfg#L5046

Maybe there should be an additional status that acts like petrify but does not apply the stone image mask.

**Comment by vgaming** [comment]
@virtualghetto the stone image (grayscale layer) is no problem for me, but the lack of movement reach highlight (`Ctrl V`) is

That being said, I see there's room for interpretation for what invulnerable should do. I would personally prefer the AI to be smart if it can, and don't do things it knows are useless. I wouldn't be afraid of AI being too smart, it's quite beatable with either handicap or experience. But I see this feeling is not unanimous

Closing the issue
