### ISSUE TITLE
Windows 10 installer for 1.15.9/1.15.10 is blocked by SmartScreen and AVG antivirus

### ISSUE THREAD

**Issue by MrTitainin** [wesnoth/wesnoth#5568]
### Game and System Information
 - 1.15.9/1.15.10
 - from wesnoth.org
 - Windows 10

### Describe the bug
My security apps see wesnoth installer as a virus.

### To Reproduce

1. Download latest installer from wesnoth.org
2. Try to install it under Windows 10 (seems to only work once for SmartScreen, as it allows it to run correctly now)
3. Get a red SmartScreen pop-up blocking installation unless you know how to bypass it.

AVG moves installer to quarantine, classifying it as Win32:MdeClass after trying to run it.

### Expected behavior
Windows installer doesn't get blocked by all security apps screaming A THREAT IS FOUND!

**Comment by soliton-** [comment]
Any clue why those programs do that? I mean clearly it's a false positive so not sure what you expect to change in the wesnoth installer. Presumably you should report the false positives to those apps.

Currently https://www.virustotal.com/gui/file/ea2e47d42ea809e3ab35e8d445e9c4a42901abc76e2f7ee7a2825cbd4137b88f/detection shows one detection from VBA32 as "BScope.Trojan.Wallet". Everything else is "Undetected". AVG has a timeout though.

**Comment by Zireael07** [comment]
SmartScreen IIRC flips on anything that is not signed with a certificate.

**Comment by MrTitainin** [comment]
Guess I can report a false positive for AVG. I think you can try getting that certificate or whatever for SmartScreen though?

**Comment by Pentarctagon** [comment]
I don't think using a certificate would actually make anything more secure either?  As far as I know there's no sort of confirmation process that Microsoft has, so just having a program signed doesn't prove much of anything by itself - anyone could've signed it.

**Comment by Pentarctagon** [comment]
So it looks like:
* We can buy a regular certificate (a 3 year regular certificate from Digicert costs $474).  The SmartScreen warning will still pop up anyway even with a regular certificate until it establishes enough positive reputation by having enough users click through the warning and install it anyway.  The number of times people would need to do this is unspecified, so it's not clear how long it would take for the warning to go away for a game with a smaller userbase like Wesnoth.  As far as I can tell, the warning will also re-appear again every time we publish a new version, since trust is built against each particular installer, not the certificate.
* We can buy an Extended Verification (EV) certificate.  Having this would skip all the trust build-up over time stuff above, but getting an EV certificate requires much more effort on our part to prove to the certificate authority that we are who we say we are.  These are also more expensive, with a 3 year EV certificate costing $664 from Digicert.

So a regular certificate is essentially useless - by the time SmartScreen stops complaining it would be past the time that most players would have gone to try downloading and installing it (aka soon after the release).  Also it costs a decent amount of money.

The EV certificate looks like the actual solution, but it's hard to justify the amount of effort and money it would take to get this finished.

Sources:
https://www.digicert.com/signing/code-signing-certificates#Compare-and-Buy
https://docs.microsoft.com/en-us/archive/blogs/ie/microsoft-smartscreen-extended-validation-ev-code-signing-certificates
https://comodosslstore.com/ssl-validation-process/ev

https://security.stackexchange.com/questions/139347/smart-screen-filter-still-complains-despite-i-signed-the-executable-why
https://stackoverflow.com/questions/50956108/codesign-software-still-gives-a-warning-on-windows-10
https://stackoverflow.com/questions/58213713/how-to-preserve-reputation-with-the-smartscreen-filter-in-windows-10-after-previ

**Comment by MrTitainin** [comment]
Well, looks like there's no reasonable way to do that. Ok then, I'll be closing the issue.

**Comment by AI0867** [comment]
On one of those links, I read the suggestion to have a signed "primary installer" whose function it is to download and run the actual one that you update. As long as you don't touch that "primary installer", it should eventually be accepted by SmartScreen.

**Comment by Pentarctagon** [comment]
@loonycyborg could answer what that would mean in practice, but it still doesn't sound like it really solves the problem well - the warning will come back any time the primary installer is changed for any reason, the download itself would need to be made secure somehow, and it would still cost a few hundred dollars to get the regular certificate every three years.

**Comment by loonycyborg** [comment]
> On one of those links, I read the suggestion to have a signed "primary installer" whose function it is to download and run the actual one that you update. As long as you don't touch that "primary installer", it should eventually be accepted by SmartScreen.

That sounds a lot like trojan downloaders work. I think best way would be to poke anti-malware devs to stop using nonsense heuristics rather than adopting malware methods ourselves.

**Comment by AI0867** [comment]
> That sounds a lot like trojan downloaders work. I think best way would be to poke anti-malware devs to stop using nonsense heuristics rather than adopting malware methods ourselves.
When the nonsense heuristics work as an effective method to promote a profitable product, while not impairing the large business customers, that's unlikely to work.
