### ISSUE TITLE
goto micro ai: New option to flip use_straight_line when unit path is blocked

### ISSUE THREAD

**Issue by virtualghetto** [wesnoth/wesnoth#5580]
### Game and System Information
 - What version of the game are you running?
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - What OS are you running?

### Describe the desired feature
Try to explain the desired end result, rather than speculating about how the feature could be implemented

The goto micro ai can move the unit with find_path (use_straight_line=no) or by nearest hex to goal (use_straight_line=yes)

Please add a new option that would flip use_straight_line from no to yes if the unit can't move via find_path because there is another unit in the way, so fall back to trying to move to nearest hex instead.

**Comment by mattsc** [comment]
If I understand this correctly, this can be done already, by adding the MAI twice, once with 'no', and once with 'yes' for 'use_straight_line', and the second one having a ca_score one lower than the first.    Also, implementing this would essentially require to do the same thing, run the path finding code twice, otherwise there is too much computation overhead.  So it would be the same solution, just internal to the MAI.

Given how many options the Goto MAI has already, and that I'm not sure that this is a very common usecase, I would prefer not to add yet another option.

Let me know if I misunderstood the feature request.

**Comment by virtualghetto** [comment]
> Let me know if I misunderstood the feature request.

You got it spot on.

> If I understand this correctly, this can be done already, by adding the MAI twice, once with 'no', and once with 'yes' for 'use_straight_line', and the second one having a ca_score one lower than the first. 

Intuitively, yes that is supposed to be the solution, but in practice it doesn't work.
The goto micro ai doesn't allow the processed unit to fallthru to lower ca score because it terminates with AH.checked_stopunit_moves.

Your solution is actually what I'm doing for my mod, but I had to add my own goto that allows the fallthru first.
I would like it if I didn't have to supply my own goto version. I'd rather use 2 vanilla goto micro ai or have them combined into 1 with this new feature request.

Here are the links to what I'm doing in my mod. I'm using 2 goto micro_ai, notice the higher score one is wf_goto that allows fallthru, the second is vanilla goto with use_straight_line=yes

https://github.com/virtualghetto/Wild_Frontiers/blob/master/utils/enemies.cfg#L4100

Implementation of wf_goto that allows fallthru:

https://github.com/virtualghetto/Wild_Frontiers/blob/master/ai/ca_wf_goto.lua#L232

**Comment by mattsc** [comment]
> The goto micro ai doesn't allow the processed unit to fallthru to lower ca score because it terminates with AH.checked_stopunit_moves.

Ah, yes, I'd forgotten about that.  Okay, assigning to myself, I'll look into this.  Thanks for the added information.

**Comment by mattsc** [comment]
Having had a look at the code, I think I would prefer to add an option `do_not_remove_mp` (when no move is found), rather than `fall_back_to_straight_line`.  That would accomplish the same as what you are currently doing in your code, and I think it would allow for a larger variety of use cases.  You can then also have other MAIs, or the default AI, take over, not only the straight-line option of the Goto MAI.

Does that sound acceptable?

**Comment by virtualghetto** [comment]
Ofcourse, do_not_remove_mp sounds good to me.
Will this be backported to 1.14?

**Comment by mattsc** [comment]
No, this cannot be backported as it would make different 1.14 versions inconsistent with each other.  So unfortunately you will still need a custom version in 1.14.

I think I'll call it `remove_movement` though and have it default to yes.  We generally try to avoid double negations with the aspects.

**Comment by virtualghetto** [comment]
Sounds good, thank you.

**Comment by mattsc** [comment]
Implemented in ea4657c6d4
[Wiki](https://wiki.wesnoth.org/Micro_AIs#Generalized_Goto_Micro_AI_.28ai_type.3Dgoto.29) is updated too.

If this addresses your request, please go ahead and close the issue.

**Comment by virtualghetto** [comment]
Thank you!
