### ISSUE TITLE
[UtBS] S1: Quenoth Mystic still spawns on a deep water hex. 

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5632]
### Game and System Information
 - What version of the game are you running?
 - 1.15.11+dev
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - Github Clone
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - msys2 + latest commit
 - What OS are you running?
 - Windows 10

### Describe the bug
![Screenshot 2021-03-23 053222](https://user-images.githubusercontent.com/5283677/112071191-90c4b600-8b99-11eb-8d89-f8022bede1c7.png)
Screenshot showing the Quenoth Mystic spawning on a deep water hex. Also, I stated this bug before and was told it was fixed...and yet here it is...again.

### To Reproduce
1. load my autosave
[UtBS-The Morning After-Auto-Save13.gz](https://github.com/wesnoth/wesnoth/files/6185889/UtBS-The.Morning.After-Auto-Save13.gz)
2. Move the Tauroch rider unit to the island.

### Expected behavior
The Quenoth mystic at 23,27 should be somewhere else on the island, maybe 24,28?

**Comment by stevecotton** [comment]
Simple solution that lead to further questions - add `passable=yes` to the code that spawns them, and set the `x` and `y` to the location of the tree itself, so that they'll spawn in a vacant hex around it, even if the player waded across the water from the north instead of using the bridge.

This lead on the question of whether `NAMED_GENERIC_UNIT` includes the `passable` flag. It doesn't, therefore I'm thinking of not using it for these units.

Next question:

```
    # Creates a generic unit of TYPE belonging to SIDE at X,Y, which has a
    # generated gender and traits (just like a recruited unit).
```

The uses of `NAMED_GENERIC_UNIT` UtBS S01 scenario seem unusual - that macro is documented as choosing a random gender, but in UtBS S01 it's being used to create units with names that look as if they should have specific genders. In other scenarios it's used with generic names such as "Criminal", "Westin Guard", "Merman Guard", "Goblin Skirmisher", etc.

However, although most of those are gender-neutral in English, they're not gender-neutral in all languages - TSG S02 has a workaround where, after using this macro, it then finds the female ones and sets their name to "female^Criminal" (see PR #5634); better would be to have a macro that takes both the male and female names.

Conclusion: we shouldn't use `NAMED_GENERIC_UNIT` here, and for a different reason we shouldn't use it elsewhere either.
