### ISSUE TITLE
Improve intro screen and scenario story text layout 

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5686]
### Game and System Information
 - What version of the game are you running?
The Battle for Wesnoth version 1.15.11+dev (0575bde2-Clean) x86_64
Running on Freedesktop.org 20.08.7 (Flatpak runtime) x86_64

### Describe the desired feature
Please improve intro screen text layout because it is hard to read it on wide screens. It is inconvenient to read very long lines of text.
Scenario messages could be also improved by increasing the bottom margin.

This is what I mean:
![image](https://user-images.githubusercontent.com/3605541/113940722-331da400-97fe-11eb-8b9c-831136ad78f2.png)

![image](https://user-images.githubusercontent.com/3605541/113940902-8263d480-97fe-11eb-823c-8f6639f2af4f.png)

**Comment by shikadiqueen** [comment]
(See also #4817.)

**Comment by Wedge009** [comment]
Alas, yes, this is a long-standing issue/suggestion of which #4817 is one previously-reported instance - there may be more. I suspect at least one of the reasons this hasn't been resolved already is because of the myriad of cases that need to be tested for this to be resolved - eg there was a minimum-supported resolution that still needed to be considered as well, so it's not as simple as just adding margin/padding around text. (There were other issues reported regarding errors arising from the story/dialogue text box not actually having enough space - not sure if they're still issues any more, haven't seen them for a while.)

I think all this may be an issue that just results from the history of Wesnoth using its own custom GUI code.

**Comment by Pentarctagon** [comment]
Closing as it's a duplicate.
