### ISSUE TITLE
chance of hitting

### ISSUE THREAD

**Issue by rmj555** [wesnoth/wesnoth#5733]
How can the chance of hitting three out of four times be identical to hitting four out of four times?

![Wes_chance](https://user-images.githubusercontent.com/76490126/115965768-89b5fe00-a4df-11eb-81c9-faf42995e259.png)
Elf vs. Troll in water.

**Comment by nemaara** [comment]
Because they're identical. 3 hits = 0.8^3*0.2*4 = 0.41. 4 hits = 0.8^4 = 0.41.

**Comment by CelticMinstrel** [comment]
To give a bit more detail:

* The chance of hitting is 0.8
* The chance of missing is 0.2
* The chance of 4 hits is 0.4 × 0.4 × 0.4 × 0.4, or 0.4⁴ = 0.41
* The chance of missing on one specific hit and hitting on the other 3 is 0.2 × 0.4 × 0.4 × 0.4 = 0.102
* Since there are 4 hits, you could miss on any one of them, so there are 4 ways to end up with 3 hits. Therefore the chance of getting in 3 hits is 0.102 × 4 = 0.41
