### ISSUE TITLE
[Campaign] [HttT] Time references have been carelessly changed.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5740]
Evidence:

In the first scenario of _Heir to the Throne_:
https://github.com/wesnoth/wesnoth/blob/f1344c8574d945402c37f675188af85793c6cddb/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg#L266

In Scenario 21 (Cutscene) of _Heir to the Throne_:
https://github.com/wesnoth/wesnoth/blob/7c29855ac1f410ce3233f413e07c91f0bd4130eb/data/campaigns/Heir_To_The_Throne/scenarios/21_Elven_Council.cfg#L124

In Scenario 24 of _Heir to the Throne_:
https://github.com/wesnoth/wesnoth/blob/7c29855ac1f410ce3233f413e07c91f0bd4130eb/data/campaigns/Heir_To_The_Throne/scenarios/24_Battle_for_Wesnoth.cfg#L58

Commit of September 2019: 4b8d7adf256a8ed793c7ec7e1b9c12a776b6e21b

Summary: 
A change was made the first instance of the date to `twenty` years from `seventeen`. However, the other 3 instances were left unchanged. This leads to the assumption that Konrad was like "-3" years old at the time of being rescued. Absurd.

**Comment by nemaara** [comment]
Woops.

**Comment by soliton-** [comment]
The old commit replaced sixteen with twenty so I assume seventeen should be replaced with twenty one. Or maybe it should be +3 years like the change in the campaign years.

**Comment by stevecotton** [comment]
I think S01 is in the autumn of one year, and S21 and S24 are in the spring or summer of the next year.

S12 is set south of Dwarven Doors: "Swirling, snow-laden winds tore at Konrad’s army, signaling the final exit of autumn and the onset of what would be a harsh winter."
S22: "After spending the greater part of a year in remote, dangerous wastes, Konrad’s heart leapt at the thought this journey was almost over. Though the greatest danger lay ahead, he knew he was finally returning home."

So I think S21 and S24 should have another year added on top of the date in S01. Particularly Parandra's line in S21 counts "winters" rather than "years".

**Comment by nemaara** [comment]
I made them 21 in this commit https://github.com/wesnoth/wesnoth/commit/9e4c770553e493249a989896267d8a8a6a1348a2

**Comment by stevecotton** [comment]
Now that I see it in text, it does look a bit too precise for natural speech. :(

**Comment by CelticMinstrel** [comment]
Could that just be because a speaker would typically slur it a bit (as "twenny-one")? That's not something that should be reflected in the text, though.
