### ISSUE TITLE
Windows CI builds broken with Pango 1.48

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5741]
From the CI log for ac9f6da, which is the last version of master that successfully built on the Windows CI:
```
The following packages will be built and installed:
pango[core]:x64-windows -> 1.40.11#9
```

From more recent builds:
```
The following packages will be built and installed:
pango[core]:x64-windows -> 1.48.0
...
fatal error C1083: Cannot open include file: 'pango/pango.h': No such file or directory (compiling source file ..\..\src\show_dialog.cpp) [D:\a\wesnoth\wesnoth\projectfiles\VC16\wesnoth.vcxproj]
```

**Comment by stevecotton** [comment]
Presumably a problem with vcpkg, as the timing corresponds with https://github.com/microsoft/vcpkg/commit/546813ae7b9e2873dd3d38e78b27ac5582feae10

**Comment by Pentarctagon** [comment]
Opened https://github.com/microsoft/vcpkg/issues/17537 for this.

**Comment by stevecotton** [comment]
The workaround has been merged, but this issue can stay open as a reminder to revert bfe1f51.

**Comment by Pentarctagon** [comment]
It looks like this will be open for a while, since upstream has no intention of fixing the problem and I don't think anyone currently involved in Wesnoth is knowledgeable of both cmake and Visual Studio.  The hack solution there sounds like even if it does work it would frequently break, given it involves version number specific directories.

**Comment by Pentarctagon** [comment]
For reference as well, 75b73043e3349a02b7aa64371858d8550e4f966b was when MSVC support was previously removed due to cmake generally and MSVC specifically being in poor shape.  Given the MSVC-specific things that *were* there though, maybe there's not a lot that would need to be done to get cmake into a minimal working form.

**Comment by CelticMinstrel** [comment]
Bit late to notice this, but at least one person on the vcpkg issue seems to think it should be fixed…

**Comment by Pentarctagon** [comment]
Though thinking it should be fixed and actually fixing it are very different things.  Plus given that one of the vcpkg devs actively doesn't care if they break the integration, it's pretty likely that this sort of problem would keep happening.
