### ISSUE TITLE
Sound sources that are on-screen at the start of the scenario don't play

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5766]
### Game and System Information
Local Linux builds of:
* 1.14.16
* 1.15.10
* Current master with various PRs merged in (this is a bug being logged in the middle of testing them)

### Describe the bug
If a `[sound_source]` is on-screen at the beginning of a scenario, it doesn't make any sound until scrolled off-screen and back on again.

1. Make Wesnoth's window large enough to have the full width of a 35-hex-wide map on-screen
2. Turn music off (probably not necessary, but makes step 4 easier)
2. Start the campaign Eastern Invasion and skip through the intro
3. You should hear the morning cockerel and turn bell
4. Check that the campfire on 33,13 is visible (without moving the map, if it isn't visible then restart with a bigger window)
5. Note that you don't hear any sound from the campfire
6. Make the window smaller, and scroll the campfire off-screen
7. Scroll back, and note that you can now hear the campfire

### Expected behavior
Crackling sound of the campfire right from the start.

### Additional context
Still reproducible even with the sound-effects volume set to 100% in the preferences (compare with #3280).
I haven't tested 1.14.3, 1.14.4, however #3280's reproduction steps suggest this bug wasn't present back then.

**Comment by CelticMinstrel** [comment]
This isn't happening for me on #5537 (after the fix that I'll push shortly). The sound source in the test scenario (ambient birdsong) starts playing immediately.

I'm not sure if that means there's something else going on or if my changes in #5537 accidentally fixed this, though.

**Comment by stevecotton** [comment]
I can't reproduce this in the test scenario. However I can still reproduce it in EI S01, even if I copy the `[sound_source]` block from scenario-test.cfg directly into EI S01 and launch it with `wesnoth --campaign Eastern_Invasion --nocache --campaign-skip-story`

**Comment by CelticMinstrel** [comment]
Interesting… I wonder if there's something in EI S01 that somehow interferes…? Is `[message]` accidentally disabling it maybe?

**Comment by shikadiqueen** [comment]
Related to this, there are now sound sources in one of my campaigns that work on 1.14.x (including 1.14 branch tip) but not on master.

**Comment by Descacharrado** [comment]
Tested by myself, still happens in 1.16.2. Looks like the sound does not play depending on zoom levels. If you are zoomed way back, the campfire does not sound, regardless of what you do. It looks like, for sound sources, the distance to the source is calculated using the center of the screen, and, in **sound_sources.cfg** the campfire sound is defined like:

https://github.com/wesnoth/wesnoth/blob/25e763f29be6223277721ca4eccda6834f43427e/data/campaigns/Eastern_Invasion/utils/sound_sources.cfg#L25-L33

If you are zoomed all the way back your distance would be **campfire_location_x-(map_width/2)=33-20=13** tiles which is more than **range+fade=1+6=7**.

The problem is that changing the values in the {SETUP_CAMPFIRES} macro would make the campfires in S04b sound from further, making them sound weird aswell.

I see two solutions. Adding arguments to the macro (something like SETUP_CAMPFIRES RANGE FADE) or changing the campfire position in the map.

**Comment by CelticMinstrel** [comment]
Huh? That commit fixes the scenario, but is this not a more general problem? Am I misunderstanding something?

**Comment by Descacharrado** [comment]
> Huh? That commit fixes the scenario, but is this not a more general problem? Am I misunderstanding something?

See here: https://github.com/wesnoth/wesnoth/pull/6704#issuecomment-1126913739

I was waiting for steve's response before merging but I guess I did not state that in the PR...

**Comment by stevecotton** [comment]
I'm happy that it merged, but also think this should be reopened for the general problem.
