### ISSUE TITLE
Some log file lines are missing timestamp

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#5942]
### Game and System Information
 - 1.15.14, windows

### Describe the bug
Log file contains lines such as
```
20210709 02:29:32 warning deprecation: special= has been deprecated and may be removed in version 1.17.0.; Please use special_id or special_type instead
20210709 02:29:32 warning deprecation: special= has been deprecated and may be removed in version 1.17.0.; Please use special_id or special_type instead
Invalid WML found: special= has been deprecated and may be removed in version 1.17.0.; Please use special_id or special_type instead (2)
20210709 02:29:32 warning deprecation: special= has been deprecated and may be removed in version 1.17.0.; Please use special_id or special_type instead
Invalid WML found: special= has been deprecated and may be removed in version 1.17.0.; Please use special_id or special_type instead
```
It feels like different types of messages which do not belong in same file. But more visibly some of them are missing timestamp.

### Expected behavior
Either summary messages have timestamp, or they are not logged in same file.

**Comment by CelticMinstrel** [comment]
There could also be something bypassing the log manager? I think `std_print` does that, for example (though I don't think that's the cause here).

**Comment by Pentarctagon** [comment]
Could it be that it's a single log message, just spread across two lines because there are two separate messages?  It looks like they come from different sources too - the "Invalid WML" is what's displayed in-game now on dev versions, so maybe the "warning deprecation" messages are from lua somewhere?

**Comment by Pentarctagon** [comment]
Looking at `show_wml_errors()` at https://github.com/wesnoth/wesnoth/blob/b567f6b8091db918be9501e6999d6e79f4d84ee9/src/game_events/pump.cpp#L381
it looks like this is actually intentional behavior since that method passes `true` as the third argument.  So this looks less like it's a bug and more like it's a question of whether it's desirable for it to continue working this way.

**Comment by ProditorMagnus** [comment]
I cant tell if it is the only way these timeless messages are used, but with this example it just repeats messages already logged.

**Comment by Pentarctagon** [comment]
The `warning deprecation:` lines come from https://github.com/wesnoth/wesnoth/blob/ba8a88c3ee129e17a386d4dc72a3c8e00029d4fa/src/deprecation.cpp#L80

The lines without timestamps come from https://github.com/wesnoth/wesnoth/blob/ba8a88c3ee129e17a386d4dc72a3c8e00029d4fa/src/game_events/pump.cpp#L367

They both end up being output since a few lines later in deprecation.cpp it also writes the same message to `lg::wml_error()`.

Fixing some lines not having a timestamp is pretty simple - just have it be written to the logger rather than directly to std::cerr.  To not have duplicate logged messages, probably deprecation.cpp would need to only use `FORCE_LOG_TO` if it hasn't also written to `lg::wml_error()`.
