### ISSUE TITLE
UtBS S09: Untranslated `$ally_name`, which way should we go?

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#6155]
A bug introduced by dac45d3eb52fba72898a6604941e7e6b20d1cbe1, the commit that's just entered master.

In this line, `$ally_name` contains a unit-id rather than a translated name. It is always one of the hero units "Grog", "Nog", "Rogrimir" or "Jarl", and in many languages the unit-id and the name are the same; however they're different in several languages including `bg`, `el`, `zh_CN` and `zh_TW`.

Options are to use four strings and the `MESSAGE_DEPEND_ON_ALLY` macro, or to just omit the name from the message.

**Comment by stevecotton** [comment]
Clarification: the issue is that Grog's called "Grog", "Грог", "果洛格", etc depending on the language, but `$ally_name` will contain "Grog" irrespective of language.

**Comment by Wedge009** [comment]
Is another option to split the string so that the `$ally_name` is not part of the translation? I'd be very surprised if this is the only place where variables are used in dialogue.

Hmm, I just had a look at `MESSAGE_DEPEND_ON_ALLY` in UtBS, it does look like the original author/s had to rely on quadruplicate strings to accommodate the different potential allies... Ugh, messy, but should probably do the same thing to accommodate this string too.

**Comment by stevecotton** [comment]
In 13 years one player has noticed the capitalisation bug in "which way should we go?", I think we should just remove the name from that text.

**Comment by max-torch** [comment]
> In 13 years one player has noticed the capitalisation bug in "which way should we go?", I think we should just remove the name from that text.

Or, we could say "only one player has bothered to report". :)

**Comment by CelticMinstrel** [comment]
I think the entire way the ally works is suboptimal. Instead of having an `$ally_name` variable, it should set a role. That's beside the point, though. If you want to put the ally's actual name in the text, all you need is a `[store_unit]` call above the message to put the unit in a variable. Then use `$the_variable.name`.

**Comment by Wedge009** [comment]
It does indeed appear the way the ally dialogue is implemented isn't great, but that's another issue.

**Comment by Wedge009** [comment]
> If you want to put the ally's actual name in the text, all you need is a `[store_unit]` call above the message to put the unit in a variable. Then use `$the_variable.name`.

@CelticMinstrel That sounds like it will resolve the quadruplication, but the issue with the name translation still remains doesn't it? Or do you mean to keep the `$the_variable.name` outside of the translated string?

**Comment by CelticMinstrel** [comment]
> That sounds like it will resolve the quadruplication, but the issue with the name translation still remains doesn't it?

I'm not quit sure what you're asking? `$some_unit.name` is the unit's display name, which means it's localized, right? I guess it could still be a problem in a language that declines proper names to agree with the verb or something similar.

**Comment by Wedge009** [comment]
My mistake, I think I understand now - as so often seems to happen this episode was late at night for me.
