### ISSUE TITLE
DM S7 Night in the Swamp: Still required to press End Turn after meeting victory condition

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6173]
### Game and System Information
 - 1.15.18
- Windows 10

### Describe the bug
First, I need to disclaim that I am aware of 20fd6d80ba8394c303be956924317b486fe370b9.
After moving to the hex of the last stone to destroy it, and having no enemies around, the scenario does not trigger victory until the player presses End Turn, and the victory plays out at the start of the next turn. This behavior is unlike other victory conditions in other scenarios throughout the campaigns.

### To Reproduce
Accomplish the alternative objective of DM S7.

### Expected behavior
It should be detected immediately once the player satisfies the objectives so that the victory screen can immediately appear. It should not be checked only at the start of a turn. **Similar to how the game does not require you to End Turn after you have killed an enemy leader for scenarios where the objective is to kill an enemy leader.**

### Screenshots
Victory Condition has been met. Turn 7. Scenario has not yet ended.
![image](https://user-images.githubusercontent.com/41433185/136383968-77f69b21-182e-4818-b630-c4bcffd71703.png)
Victory Condition is now checked. Had to End Turn. You can see in screenshot it is Turn 8. Replay buttons are now greyed out.
![image](https://user-images.githubusercontent.com/41433185/136384260-ed0f72eb-e371-4981-8dae-724ade84052d.png)

### Savefiles
[DM-Night in the Swamp replay 20211006-191338.gz](https://github.com/wesnoth/wesnoth/files/7303282/DM-Night.in.the.Swamp.replay.20211006-191338.gz)

### Additional Context
Secrets of the Ancients S5 Blackwater also has a victory condition requiring the player to kill all enemy units, and you dont have to press End Turn to get the victory.

**Comment by stevecotton** [comment]
The reason it waits for a new turn is that it's just checking that no enemies exist, so has to do the check in an event that allows the monolith's generator function to fire first. For this, it relies on the (reliable but AFAIK undocumented) fact that events with the same `name=new turn` trigger in the same order that they were originally added.

WML can handle it better, with a bit of complexity, it multiple ways. I'm currently wondering which other scenarios have similar events, because I'd prefer to reuse code than to write a new, different way of handling it.

Some options:
* make an array of monoliths, similar to SoF S02's `glyphs`.
* a counter, similar to Liberty S07's `supports_destroyed`.
* add an event with `name=ping_monoliths` `id=ping_{X}_{Y}` that sets a variable to true, and then remove this event at the same time as removing the `generator_{X}_{Y}` event. That would be a new method that I think isn't currently used in mainline.
* study WC's item handling code, and reuse it.
