### ISSUE TITLE
Don't allow story scenario replays to take you to the next scenario automatically at the end

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6180]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### Describe the desired feature
Currently, when you load a _story scenario replay_, at the end of the scenario it loads the next scenario in the campaign. This is the exact same thing that occurs when you load a _start-of-scenario save_ of a _story scenario_.

The behavior that I was expecting, however, was that, at the end of a _story scenario replay_, the next scenario would not load.

### Screenshots
A start-of-scenario save and a replay of a story scenario has the exact same behavior.
![image](https://user-images.githubusercontent.com/41433185/136649080-b363c7ab-5095-448a-90f9-90b3d8156958.png)

### Rationale
Changing story scenario replays to behave like this would make it consistent with any other replay files that you would load, which do not automatically begin loading the next scenario once the end of the replay has been reached. It also gives more of a reason for the two different story scenario files, the replay file and start-of-scenario save, to exist, because there would now be an actual difference between them.

**Comment by stevecotton** [comment]
There's two routes to fixing this, and they're not mutually exclusive: changing the engine to automatically avoid creating a replay, or changing the scenario files to disable the replays on a per-scenario basis.

I'm adding the "campaign" and "good first issue" tags because fixing them in the scenarios is mainly a task of spending time testing the results. It's probably something to do when doing a playthrough of those campaigns.

**Comment by soliton-** [comment]
Why is the replay creation the issue and not the reported behaviour?

I agree that replay creation is an individual scenario decision. The reported behaviour of those replays just sounds like a bug though.

**Comment by max-torch** [comment]
The vision that I am in favor of is this:
All story scenarios save replay files at the end, but watching those replay files doesn't take you to the following scenario after watching.

My reason for wanting this is so that I can go through the complete story of a campaign that I have already finished.
If I want to relive the memory of playing a campaign, it would be incomplete if I just watch the scenario replays but don't have any story replays.

It's a bit like how in some videogames you can even rewatch all cutscenes as a bonus thing that you can do on the main menu after completing the game.

**Comment by gfgtdf** [comment]
Does someone know what the current behavior is, i'm kinda surprised since i cannot find any code that would make the storyscreeen work on replays  in the, so when you load a replay (stopryonly scenario or not) is the story shown again?


Also I'm unsure what the desired behavior is on storyonly scenarios, since those scenarios usually don't want their map to be shown or might not even have a good map, So we probably cannot show the usual replay viewer there.

**Comment by soliton-** [comment]
This is not about scenarios with only `[story]`. It's about scenarios with a proper map but where there is only dialog and then the scenario ends automatically. When replaying this should not cause advancing to the next scenario nor should another replay be saved.

**Comment by gfgtdf** [comment]
So i think for those scenarios the replay viewer should just stay in "linger mode" after showing the scenario regardless of the linger_mode= attribute in endlevel? Still the question remains what the desired behviour is for the case i mentioned ([story] only scenarios, if those still exist)

**Comment by Wedge009** [comment]
gfgtdf's changes were merged for 1.17.15. I'm testing in 1.17.18+dev. Replays are no longer saved for story-only scenarios, but testing such a replay I have from 1.16, I now have linger mode at the end of the replay. However, with no UI (as is usually the case for story-only scenarios) I don't have any means to end the scenario or do anything else except exit to the main menu.

Is this acceptable? If so, I think this should be closed.

**Comment by soliton-** [comment]
> However, with no UI (as is usually the case for story-only scenarios) I don't have any means to end the scenario or do anything else except exit to the main menu.

I'd say that is rather the issue with replays with custom themes as in #7122. IMO this issue is fixed.

> Still the question remains what the desired behviour is for the case i mentioned ([story] only scenarios, if those still exist)

For a scenario with only `[story]` and a prestart event with `[endlevel]` a replay is generated but the load dialog complains `A map needs at least 1 tile, the map cannot be loaded.`

And the story part is not in replays anyway. So there would be nothing to show. I'm fairly sure that was never different.
