### ISSUE TITLE
UtBS: Change the Dust Devil's XP numbers to light blue instead of purple

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6212]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows

### Describe the desired feature
Change the Dust Devil's XP numbers from purple to light blue.

### Rationale
Kaleh's and Nym's XP numbers used to be purple, but later they were changed to light blue. This signals to the player that they are worth giving XP to because they have AMLAs and don't just get a full heal. Since the Dust Devil also has AMLA, it is worth giving XP to, and should have light blue XP numbers for the same reason Kaleh's and Nym's were changed to light blue.

However, if the design intent is for the Dust Devil AMLA to be more like an easter egg than a central feature, or if the AMLA gained by the dust devil is deemed too insignificant, then we can leave it as is.

**Comment by stevecotton** [comment]
I'd go for "too insignificant" - neither +1 damage nor +1 attack seem huge improvements.

**Comment by Wedge009** [comment]
Funny, as I just started 1.16 UtBS recently, I noticed the changed for Kaleh and Nym. Since the Dust Devil had XP highlighted as purple I've been deliberately avoiding giving it XP in favour of other units that can progress to new levels. I forgot that the Dust Devil can get AMLA bonuses, however small. I think it would be good to make this change if only for consistency with Kaleh and Nym - newer players may be puzzled by the current inconsistent colouring.
