### ISSUE TITLE
UtBS S9 Blood is Thicker than Water: Player is punished for adhering to the protagonist's desires

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6229]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### The Issue
In S9 of UtBS, Kaleh, the protagonist, has to put down a rebellion. The scenario objectives get updated to say 
>Defeat Tanstafaal and Eloh

 At the same time, Kaleh speaks this line of dialog:
 >"Thank you, I’m sure you will be very useful in the shallow waters. All right people, I don’t want to kill any more than I have to. Too much blood has been spilled already. Knock ’em out, wound them, kill them only if you must. But we must stop Tanstafaal in his lunacy before he destroys us entirely."

I would like to draw your attention to "I don’t want to kill any more than I have to... kill them only if you must".
**Kaleh wants to achieve the objective while spilling as little blood as possible. He wants to avoid racking up kills.**

When the objective is accomplished, the scenario is not over. There is a new objective taking several turns to accomplish. Also, all the unkilled rebels get transferred to the player - along with all of their upkeep costs. This can seem like a reward in the short-term but is actually a punishment in the long-term because it directly takes away from gold the player takes into the next scenario, which is rather on the challenging side.
**The player is punished for spilling as little blood as possible.**

The reality of this contradiction is noted in the UtBS scenario walkthrough on the wiki:
>Whenever you destroy the apparition and capture Tanstafaal, the remaining elves will automatically switch over to your side. You might not want the extra overhead for the rest of this scenario, though. Besides, they screen Tanstafaal so well that most of them will have to be done in to get to him. Oh, and Zhul comes around after the apparition is gone.

**It is not good design to punish the player for being more aligned with the desire of the protagonist.**

### Proposal
This is more of a suggestion than a proposal, since others may come up with better ideas, or more time may be needed to brainstorm one:
Turn the rebels into allied units rather than part of the player's side so that they don't drain upkeep once the objective is accomplished.

### Screenshots
It is even possible to achieve the objective via assassination with merfolk due to the map design, but this strategy is not rewarded because you gain a lot of units:
![image](https://user-images.githubusercontent.com/41433185/138834499-066acc19-4218-4037-b569-69d308eb6216.png)

The player will be punished for avoiding and ignoring the units crossing the eastern ford. The player will be rewarded for killing them. (Contrary to what the protagonist wants).
![image](https://user-images.githubusercontent.com/41433185/138835283-ee0ff0b0-ea45-4d35-961c-abbc9b23b319.png)

When there is a leader-kill chance to finish the objective the player is punished for keeping nearby rebel units alive before finishing the objective; they will just start draining gold:
![image](https://user-images.githubusercontent.com/41433185/138835583-3b2b8f1e-98f5-483b-9fe6-2e488ba1bc10.png)

**Comment by Wedge009** [comment]
Okay, I've run into this situation now, perhaps in part because of the assassination approach max described in the original report. When I played this back in 1.6 I just charged headlong into the rebel army and probably wiped out most if not all of them before completing the objective. This time I deliberately avoided killing any of the rebels, simply maintaining a defensive position on the beaches to the south while the merfolk - plus one of my Sun Sylphs who managed to flank the defenders - swept around to assassinate the leaders. I went from +11 gold per turn to -14. There are three villages on that island which brings the cost to -8 per turn. I imagine most players will fall somewhere in between those two extremes (of killing all the rebels vs killing none) so I still think the 'punishment' isn't as bad as it sounds.

However, I agree with making the rebels `upkeep=free` upon reunion - given the following line it might seem a bit inconsistent to give them the loyal trait:
https://github.com/wesnoth/wesnoth/blob/e02cb3f8c2882c655859affd9620f31185d6c697/data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg#L2334

**Comment by Wedge009** [comment]
I did a quick bit of testing: `upkeep=free` is synonymous with `upkeep=loyal` - it is separate from the loyal trait - and internally the upkeep is recorded as `loyal` regardless. It's trivial to set `upkeep=loyal` at the same time as they are switched to `side=1`, however the trick is to keep a record of who the rebels were and switch them back to `upkeep=full` upon the scenario end because otherwise they will remain free of upkeep costs into the subsequent scenarios.
