### ISSUE TITLE
1.16 OOS while watching MP-replay with Ladder era add-on 1.0.0

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#6283]
### Game and System Information
Win 10
Wesnoth 1.16 and Ladder era add-on 1.0.0
Web-site

### Describe the bug
While watching MP-replay with Ladder era add-on 1.0.0 sometimes at different turns there could be OOS. If close replay and reopen again - there would be no more OOS.

It's second time I see this bug.

1. Download and save locally MP-[replay](https://wesnoth.gamingladder.info/download-replay.php?reported_on=2021-11-10+20%3A50%3A28).
2. **Open new Wesnoth instance**.
3. Start watching replay.
4. At turn 1 would be OOS.

Probably it's add-on problem, idk.

**Comment by Discontinuum** [comment]
The bug will shoot if you watch a replay IMMEDIATELY after Wesnoth start. Wesnoth throws mistakes that it doesn't know the addon's units. If you try the second time or after some activity, it will work (probably the addon will be loaded finally at that second try)

**Comment by Discontinuum** [comment]
The problem encompasses all user-made eras

**Comment by amokmen** [comment]
It looks like **Wesnoth engine did not use _custom units_ from properly installed add-on while watching replay at 1st time**.
So, _unknown_ units are cause of OOS.

**Comment by Pentarctagon** [comment]
Does this happen if you go to Multiplayer > Local Game > Load Game?

**Comment by Discontinuum** [comment]
@Pentarctagon no. When you are in Load Game of Local Game, you already see units in the left bar, so the era is loaded when you proceed to Local Game.

**Comment by MXB2001** [comment]
> Does this happen if you go to Multiplayer > Local Game > Load Game?

When I try this I get "Replays not supported in Multiplayer mode" or somesuch.

The only way I can load replays is either via main screen load (the one for campaigns) or via the MP load shortcut key CTRL-O (which seems to bypass that message somehow).

**Comment by amokmen** [comment]
Just noticed that **Rav_Color_Mod** add-on also did not work at first replay loading.

**Comment by Pentarctagon** [comment]
I remember looking at the cache loading a while ago for some reason or another, and IIRC what it essentially does is loads a minimal amount of the WML initially so it can display the title screen faster, then once you select Local Game or any of the other options it takes the time to load up everything.  Presumably the issue here is that the "load everything" step is no longer being done when loading replays from the main menu the first time.

**Comment by amokmen** [comment]
If run Wesnoth client from linux terminal something like this error would be shown:
```sh
error engine/team_construction: game_error: unknown unit type: Fire Drake Ladder_1
```

**Comment by Discontinuum** [comment]
Another thing, maybe connected with it: when you observe a game in Ladder Era with Ladder Mappicker (which is 2-scenarios, the first scenario is a dummy one which rolls which scenario will be played and switches there) and players start, observes get "Game over" in the dummy scenario (so like leaders dead), for players it works as intended. No more further info so for info

**Comment by Pentarctagon** [comment]
It looks like the issue is that wesnoth knows that Ladder Era is needed, but when it gets to https://github.com/wesnoth/wesnoth/blob/d44720f81c09fedb96077cb0323a76fcf2fcfac3/src/game_classification.cpp#L146-L153 it can't find the era in the game config. No idea yet why it isn't present or how it becomes present once the replay is loaded a second time.

**Comment by Pentarctagon** [comment]
So it looks like what's happening is:
* Wesnoth starts, but none of Ladder Era's contents is loaded since it's behind `#ifdef MULTIPLAYER` and that hasn't been defined yet.
* When the replay is attempted to be loaded, it attempts to determine which add-ons are required to run the replay **before** reloading the cache with `MULTIPLAYER` defined. Therefore the units of Ladder Era aren't found yet.
* Then, later, it defines `MULTIPLAYER` and reloads the cache.
* When you go back to the main menu, the cache contents created with `MULTIPLAYER` defined are still there, the Ladder Era units are found correctly, and the replay runs as it should.
