### ISSUE TITLE
[modify_unit] returns all units put to the recall list with [put_to_recall_list] on the battlefield

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6295]
### Game and System Information
 - What version of the game are you running? 1.16.0 from flatpak

### Describe the bug
[modify_unit] tag places back all units that have been put to the recall list in this scenario with [put_to_recall_list] on hexes where they stood before being put to the recall list. If several units were put to the recall list from the same hex, only the last of them appears, others are lost (they aren't on the map and no more in the recall list)

### To Reproduce
Dunno how much it is a convenient way to show this, but I made a showcase campaign (WML Guide with the first scenario altered)
[WML_Guide_bug_showcase.zip](https://github.com/wesnoth/wesnoth/files/7534509/WML_Guide_bug_showcase.zip)

1. Install manually the showcase addon campaign
2. Open "WML guide" campaign. You will have menu items "To Recall", "Win" and "Modify" in the first scenario
3. Recruit a unit on some hex, then put it to the recall list with the menu item, then recruit another unit on the same hex and put it to the recall list again.
4. Call [modify_unit] (either with "Modify" or with "Win")
5. Notice how all units put to the recall list returned to their places. And if several units were on the same hex, notice that all but one are now lost (not on the map and not in the recall list)

### Expected behavior
Units get modified but don't reappear on the map from the recall list

**Comment by stevecotton** [comment]
@CelticMinstrel bisecting with the unit tests in #6296, this bug was introduced by aaa2dc4ecebd8bbc4cce55baf8c8eae33e16fa81. Replicating it on that version requires avoiding or disabling `[modify_unit]`'s fast path.

**Comment by CelticMinstrel** [comment]
This seems like it could be a bug in `wesnoth.units.find`. I'm not 100% what the issue would be, but I can see that what it does is slightly different from what `[modify_unit]` did to handle recall lists prior to that commit.

The other possibility is that it's a bug in `[store_unit]` or `[unstore_unit]`. When storing a unit on the recall list, the x and y values _should_ be filled with the string "recall" instead of the x and y stored on the unit, and unstoring the unit should also recognize this special case. But this has always worked before so I'm not sure why it would be broken now…

That leads into the next possibility, which is that `u.valid` is broken and doesn't correctly report that the unit is on the recall list…
