### ISSUE TITLE
Revise Capitalization and referencing of the Academy of Magic in Alduin 

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6310]
In several scenarios and campaigns, the Academy of Magic in Alduin is referenced and featured. The way it is referenced and spelled and typed is inconsistent throughout.
Variations may include:
- Academy
- Academy of Magic
- great Academy
- Great Academy
- great Academy of Magic
- Great Academy of Magic

Just to name a few campaigns that have it we have:
- Secrets of the Ancients
- Heir to the Throne
- Delfador's Memoirs
- A Tale of Two Brothers

**Comment by Wedge009** [comment]
I'm not sure there's as many variations as you list there. I could only find:

### Academy
I assume this is just an informal abbreviation
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Descent_Into_Darkness/scenarios/04_Spring_of_Reprisal.cfg#L20
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Descent_Into_Darkness/scenarios/06_Return_to_Parthyn.cfg#L962
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Descent_Into_Darkness/scenarios/10_Endless_Night.cfg#L1862
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Delfadors_Memoirs/scenarios/01_Overture.cfg#L59
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Delfadors_Memoirs/scenarios/13_The_Return_of_Trouble.cfg#L18
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Secrets_of_the_Ancients/scenarios/01_Slipping_Away.cfg#L83
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Secrets_of_the_Ancients/scenarios/03_Bandits.cfg#L20
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Secrets_of_the_Ancients/scenarios/08_Carcyn.cfg#L308

### Academy of Magic
I assume this is the full, formal title
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Delfadors_Memoirs/scenarios/01_Overture.cfg#L80

### Great vs great
After your proof-reading PRs I think we settled on there being no such thing as 'Great' in the formal title, but that it was just an adjective describing the 'great' Academy. This change is not yet reflected in translated texts due to the string freeze for 1.16.0 and 1.16.1:
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Delfadors_Memoirs/scenarios/02_This_Valley_Belongs_to_Me.cfg#L68
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Delfadors_Memoirs/scenarios/23_Epilogue.cfg#L17
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Two_Brothers/scenarios/01_Rooting_Out_a_Mage.cfg#L58

### Not the Alduin Academy
The 'school of magic' by Lake Vrug is obviously unrelated to the Academy on the Isle of Alduin:
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Eastern_Invasion/scenarios/10_Lake_Vrug.cfg#L218

Likewise, a dwarvish rune-crafting academy would be unrelated to a human school of magic:
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Sceptre_of_Fire/scenarios/3t_The_Council_Regathers.cfg#L236
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Sceptre_of_Fire/scenarios/3t_The_Council_Regathers.cfg#L262

### Conclusion
So I'm not sure what work there is to be done here. Can you point out the references to Academy that are in Heir to the Throne? Because I couldn't find any just now. The only instances I think may be worth reviewing is perhaps capitalising these mentions of academy because they seem to be referring to the Alduin Academy of Magic:
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Secrets_of_the_Ancients/scenarios/02_Dark_Business.cfg#L763
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Secrets_of_the_Ancients/scenarios/07_Meeting_of_the_Minds.cfg#L193
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Secrets_of_the_Ancients/scenarios/11_Battleground.cfg#L20
https://github.com/wesnoth/wesnoth/blob/1c8b0817fcba878a30e5713367376a4fda21d040/data/campaigns/Secrets_of_the_Ancients/scenarios/13_Together_Again.cfg#L166

Would @nemaara object to these being capitalised?

**Comment by max-torch** [comment]
I didnt really recently check heir to the throne but i remembered one scenario is the Isle of Alduin where you fight orcs, which is supposed to be where the academy of magic is - I thought for sure it would be referenced there. If it's not, maybe it should be then? They are practically in that very place and is where Delfador was trained, and now delfador has returned to it.

**Comment by nemaara** [comment]
It seems like sota is the one not consistent, the others all look consistent to me at a glance? "Great" in this case looks like just a descriptor, not part of the title, and doesn't need to be capitalized.

**Comment by rubyFeedback** [comment]
> "Great" in this case looks like just a descriptor, not part of the title, and doesn't need to be capitalized.

This is a good point, but I think it may be better to be consistent every time it is mentioned so that
players don't get confused.

Perhaps these two names, either way, are best to use it consistently:

    Academy of Magic
    Great Academy of Magic

Spelling-wise I think both would be fine. The second one sounds more impressive - you know,
long title and what not. Mages being called "Wise Magus of xyz". :-)

May max-torch again which name he thinks would be best, if one is to use it consistently.

I saw Wedge009 changing the capitalization already. What is max-torch opinion for sentences
such as this one here:

message= _ "Possibly. When an Academy mage completes his studies, he is granted syllables of power, which become his new name. You are well beyond that point, but you are with the free magi now, so choose your own name. I was originally Rassin Tabin, but that is fairly ordinary, and at one point, it no longer suited."

Could become:

message= _ "Possibly. When a mage from the Great Academy of Magic completes his studies, he is granted syllables of power, which become his new name. You are well beyond that point, but you are with the free magi now, so choose your own name. I was originally Rassin Tabin, but that is fairly ordinary, and at one point, it no longer suited."

(If it's just used as-is then it should perhaps even be downcased in the middle of a sentence ... but it should also
be trivial to replace the strings and make them refer to "Great Academy of Magic" instead.)

**Comment by Wedge009** [comment]
> This is a good point, but I think it may be better to be consistent every time it is mentioned so that players don't get confused.

It should be consistent in the code now, as in all are lower-case 'great'. The reason it's not yet consistent in current 1.16.1 release is because the changes (to make it consistent) were done after the 1.16.1 string freeze was concluded, the freeze being in place to give translators something stable to work with.

Now, if you want the full formal title to become 'Great Academy of Magic' that may be a separate issue entirely as we'd be reversing the previous decisions to make 'great' lower-case and not part of the title.
