### ISSUE TITLE
Experimental AI should recognize when it cannot spend the available gold and disregard unit cost when deciding what to recruit/recall

### ISSUE THREAD

**Issue by phoe** [wesnoth/wesnoth#6330]
### Game and System Information
```bash
$ uname -a
Linux helix 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

$ cat /etc/issue
Debian GNU/Linux bookworm/sid \n \l

$ wesnoth --version
Battle for Wesnoth v1.14.17
Started on Tue Nov 23 17:16:03 2021

Battle for Wesnoth 1.14.17

Library versions:
Boost:             1.74
OpenSSL/libcrypto: 1.1.1l (runtime 1.1.1l)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.46.2 (runtime 1.48.9)
SDL:               2.0.14 (runtime 2.0.14)
SDL_image:         2.0.5  (runtime 2.0.5)
SDL_mixer:         2.0.4  (runtime 2.0.4)
SDL_ttf:           2.0.15 (runtime 2.0.15)

Optional features:
JPEG screenshots:               yes
Lua console completion:         yes
Legacy bidirectional rendering: yes
D-Bus notifications back end:   yes
```

### Describe the bug
Experimental AI does not recruit level 2+ units even though:
* they are available for recruitment,
* it has the necessary gold,
* its opponents (e.g. me) do it to crush the AI to death.

### To Reproduce
1. Select an era that has lv2+ units available for recruitment straight from the start.
2. Start a new game with Experimental AI. Assign the AI a large amount of starting gold.
3. Let it work for a few turns so that it recruits the initial lv0 units and uses them to claim some villages.
4. Observe how it never recruits higher-level units despite having all the gold and chance to do so.

### Expected behavior
The AI spends its gold on more expensive units rather than only recruiting lv1 units and not spending its gold.

### Screenshots
![Zrzut ekranu z 2021-11-23 17-19-40](https://user-images.githubusercontent.com/15045546/143062691-2017e5d4-ceba-4115-ad42-3444e05130e9.png)
![Zrzut ekranu z 2021-11-23 17-17-34](https://user-images.githubusercontent.com/15045546/143062695-427b79f1-14c5-4ca6-bfca-64b05e91103c.png)

**Comment by Alarantalara** [comment]
There's nothing stopping it from recruiting level 2 units. It just doesn't think they're good enough for the cost, though I suppose it should prioritize cost less when it's got 3000 and gaining 1000/turn.

There's an undocumented parameter, "high_level_fraction", that can set for the AI to encourage recruiting higher level units. I'm not sure it's good to set it for the default, since such large sums of gold are atypical, though it may make sense to add an adjustment based on available gold/income.

**Comment by phoe** [comment]
> since such large sums of gold are atypical

I guess "it's somebody's use case, no exceptions" works in this case. I like playing long games on 100x100 random maps with hundreds of units and tons of gold, and I remember that the RCA AI made proper (from my point of view) use of high-level units in such situations, whereas the experimental AI does not.

**Comment by Wedge009** [comment]
Similar, but likely unrelated, issue: #4924 (does not recruit from `extra_recruit`)

**Comment by mattsc** [comment]
> I guess "it's somebody's use case, no exceptions" works in this case.

On the contrary, the fact that that parameter exists shows that we agree that there is no "one size fits all."  The funny thing is that we changed the Experimental AI to recruit more level 2+ units at some point.  We got a lot of pushback on that and were told that it should not do that.  But instead of reverting it, we added that parameter.  So much for the history lesson ... 😛 

Now, a practical problem was that these parameters were only modifiable by code, so to improve on that, I just put an add-on called AI Settings Tool onto the 1.16 server that allows you to do so via an in-game GUI.  There is a [forum topic](https://forums.wesnoth.org/viewtopic.php?t=55912) for it to leave feedback.  If this turns out to be useful enough, we might add it to mainline in Wesnoth 1.17/1.18, but even if not, it can remain available as an add-on for future Wesnoth releases.

Does this sufficiently address this issue so that it can be closed?

**Comment by phoe** [comment]
I think so, yes - thank you! I'll check this add-on out.

**Comment by cooljeanius** [comment]
> There's an undocumented parameter, "high_level_fraction", that can set for the AI to encourage recruiting higher level units. I'm not sure it's good to set it for the default, since such large sums of gold are atypical, though it may make sense to add an adjustment based on available gold/income.

Maybe this parameter should be documented at least, then?
