### ISSUE TITLE
Loading spinner missing at startup

### ISSUE THREAD

**Issue by echanaron** [wesnoth/wesnoth#6353]
Cf. https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4729#note_1326899
On GNOME Linux, Wesnoth should implement xdg_activation in order to see the mouse spinning before loading is complete.

**Comment by Pentarctagon** [comment]
Is there documentation/examples somewhere of how this could be implemented?

**Comment by Pentarctagon** [comment]
Also, given this specifically mentions "GNOME Linux", hopefully the expectation isn't that separate code isn't needed for GNOME, KDE, etc.

Though at a glance it sounds kind of strange that a display manager isn't able to tell on its own when an application that has been started has now displayed a window? Not sure if I'm misunderstanding something.

**Comment by echanaron** [comment]
I mentioned GNOME because it's the environment I'm currently using (Fedora 35, to be more accurate).
But, as Wayland is a standard, the fix should work on KDE as well.

**Comment by Pentarctagon** [comment]
Also, what's the feature being requested, specifically? That the mouse be turned into a spinner until the window is displayed, or until the title screen is displayed? The former sounds not especially useful or needed since a window will be displayed pretty quickly, and the later doesn't seem like it would be needed since Wesnoth already has a loading screen.

**Comment by echanaron** [comment]
That's the first one. That during the 1-2 seconds interval between click and window opening, the mouse is turned into a spinner.

**Comment by Wedge009** [comment]
Just for the record, I'm not sure I even have time to even blink my eyes in the interval between starting Wesnoth and when the window appears with the initial loading screen. Though I'll grant I'm running on a fast machine.

**Comment by stevecotton** [comment]
This is something that I'd expect SDL to provide, but I can't find anything relevant when searching for SDL + StartupNotify or SDL + xdg_activation.

My experience is the same as Wedge009's - the startup is quick for me.

**Comment by Pentarctagon** [comment]
So yeah, barring anything else being said, I'd lean towards closing this as not needed.

**Comment by CelticMinstrel** [comment]
If it was about changing the cursor during the loading screen (after the window opens), then I'd say that should be on us; but changing the cursor before SDL has even been initialized is the job of the window manager.

I suppose theoretically the cursor could be changed to the watch cursor first thing after initializing SDL, but I don't think that addresses the request, since the window is created right when SDL is initialized, right?

So, yeah… in my opinion, it's the job of your window / desktop manager to change the cursor to a spinner or whatever when you launch an application, either until the application changes it back or at least until it starts polling for events. This sounds like an issue with GNOME/Wayland, not Wesnoth.

**Comment by stevecotton** [comment]
@CelticMinstrel please look up the things that have already been referenced (xdg_activation etc). This is mainly about how the application signals to the window manager that it no longer needs to show the spinner, if the .desktop file activates the spinner.

**Comment by CelticMinstrel** [comment]
If it's about turning the spinner _off_, then SDL should either provide a callback to do that _or_ (more likely) just do it automatically the first time you poll for events, so I think it's still not an issue with Wesnoth.
