### ISSUE TITLE
TRoW S22 An event throws missplaced dialogue

### ISSUE THREAD

**Issue by Descacharrado** [wesnoth/wesnoth#6376]
Wesnoth 1.16.1. 

The event linked (see below) may trigger when player units have already passed the bridge, thus making the line  "Our advance is thwarted, that monster has destroyed the bridge!" be out of place.

### Desired feature
- A different dialogue line is said.
- The event cannot be triggered at all if the player already has most units below the bridge.
- Change the trigger to something else.

### Screenshots
https://www.youtube.com/watch?v=lHa-h5DG450 minute 1:45:27

### Savefile

https://forums.wesnoth.org/viewtopic.php?p=669899#p669899

**Comment by Wedge009** [comment]
I don't suppose you have or could make a save file that demonstrates the issue?

**Comment by Wedge009** [comment]
I see. It's been such a long time since I played TRoW, I forgot about the bridge-breaking. It looks like an unfortunate case where your combination of units only triggered the destruction of the third bridge _after_ they had already crossed south, given the strange combination of triggering the destruction only with player units between 2 and 8 hexes of the bridge in question and only on a new turn as opposed to a move event. The latter being introduced by @ln-zookeeper in 5e140f227231c3638b7a9c417a709e7fa6174a4a.

With the first two bridges, it's not so bad if that happens because the speaking unit only says something generic:
https://github.com/wesnoth/wesnoth/blob/a202146b892249905d0306fe5777ff9802cb0bd9/data/campaigns/The_Rise_Of_Wesnoth/scenarios/22_The_Rise_of_Wesnoth.cfg#L972
https://github.com/wesnoth/wesnoth/blob/a202146b892249905d0306fe5777ff9802cb0bd9/data/campaigns/The_Rise_Of_Wesnoth/scenarios/22_The_Rise_of_Wesnoth.cfg#L1114

In either case, this seems fine to me because even in the case where player units have already crossed south towards Jevyan, they may be concerned about the loss of the bridge for a retreat situation. If I understand correctly, your specific concern is the third bridge because they explicitly discuss the advance situation, not a retreat:
https://github.com/wesnoth/wesnoth/blob/a202146b892249905d0306fe5777ff9802cb0bd9/data/campaigns/The_Rise_Of_Wesnoth/scenarios/22_The_Rise_of_Wesnoth.cfg#L1291

A 'proper' resolution might be to only trigger such speech if units are still approaching the bridge. However I think it's also fine to just alter the line for the third bridge to simply 'That monster has destroyed the bridge!' with no mention of advance or retreat. That would certainly be more straightforward of a change.

**Comment by Descacharrado** [comment]
I'd prefer to keep the dialogue and add the other possibility: 'Our retreat is thwarted, that monster has destroyed the bridge' but that would be ok too.

**Comment by Wedge009** [comment]
My concern is that it would be rather difficult to determine whether the player has crossed the bridge or not. I'm not even sure how to write that in WML - do you have any ideas?

**Comment by Descacharrado** [comment]
I think [have_unit] with [filter_location] should work, but I do not currently have the time to test it, when I get the time I may try that.

**Comment by Wedge009** [comment]
So a special case for the third bridge where the dialogue changes depending on whether units (or perhaps the absence of units) are detected in the area before or after the bridge. Even with the original filter, there may be the case that there are units both in front and behind the bridge - might be tricky to decide where the 'bulk' of the team is... it might work, but I wonder if, with this edge case, it's worth the effort...

**Comment by Descacharrado** [comment]
I'd add low-priority, for sure, but it is very mood breaking when it happens.
