### ISSUE TITLE
Addons Tab crashes

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6389]
### Game and System Information
 - What version of the game are you running? 1.16/1.17 most recent flatpaks
 - What OS are you running? Ubuntu 20

### Describe the bug
If you click addons tab, Wesnoth crashes, in the command line there is

> Ran out of memory. Aborted.

### To Reproduce
Install manually two addons from this archive [CrashersOfWesnoth.zip](https://github.com/wesnoth/wesnoth/files/7738371/CrashersOfWesnoth.zip)

### Additional context
In the archive there is an empty addon spoilt_base and an addon spoilt1 with a _server.pbl in which spoilt_base is mentioned as a dependency. It's crucial to repro. If you change the dependencies of spoilt1 to be an exisiting addon, it stops crashing. If you change the dependency to a non-exisiting addon (neither published nor locally exisitng), it also works fine. I presume the bug might be when _server.pbl has a mention of some addon which is locally there but not published.

~Also a custom build from commit 91d1296af9 doen't repro~

91d1296af9 and 3cce671, the crash occurs when you try to select the bad addon. If this addon is the first, the crash happens immediately when Addons opened. If it's not the first, to cause a crash you need to select the bad addon

**Comment by Pentarctagon** [comment]
It sounds like this would be pretty quick to bisect then, given an easy way to reproduce the issue and that it was apparently introduced between 1.16.0 and 1.16.1.

**Comment by Discontinuum** [comment]
Built 3cce6719e, there the situation is the following: Addons tab at first don't crash but when you click "Ready to publish" category, the same thing, crash with Ran out of memory. Aborted.

**Comment by knyghtmare** [comment]
I just realized that is identical to #5917 but with more details on how to reproduce it.

**Comment by MXB2001** [comment]
I've seen this too. I upped an addon for which I mistakenly set a dependency which did not exist on the 1.16 addons server. Whenever the addon was highlighted in the addons it would crash Wesnoth with the out of memory error. Since I had the addons sorted by last uploaded it only stopped once someone else had uploaded something new and the addon wasn't at the top (and thus auto highlighted) any longer. Realizing this I instantly deleted the add-on and fixed it. A nasty bug this one...

**Comment by Pentarctagon** [comment]
The issue is triggered at https://github.com/wesnoth/wesnoth/blob/82a8350a94c98832f4df2a6697ee4645cebd5ad2/src/addon/state.cpp#L54

It looks like it's making the assumption that an add-on is either publishable (has a _server.pbl) or has been downloaded from the add-ons server (has an _info.cfg). If it has neither then there's no version information, and dereferencing the iterator of the list of versions causes the crash.
