### ISSUE TITLE
wesnothd fails to launch on MacOS because of missing boost dependency

### ISSUE THREAD

**Issue by tatethurston** [wesnoth/wesnoth#6397]
### Game and System Information
 - What version of the game are you running? 1.16.1
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) Mac App Store
 - If you're using a custom build, what compiler did you use, and what commit did you build at? N/A
 - What OS are you running? MacOS 12.0.1 (Monterey)

### Describe the bug

When trying to launch `wesnothd` on MacOS, the following error occurs

dyld[20128]: Library not loaded: @rpath/libboost_coroutine-mt.dylib
  Referenced from: /Applications/The Battle for Wesnoth.app/Contents/MacOS/wesnothd
  Reason: tried: '/Applications/The Battle for Wesnoth.app/Contents/MacOS/../Frameworks/libboost_coroutine-mt.dylib' (no such file), '/Applications/The Battle for Wesnoth.app/Contents/MacOS/../Frameworks/libboost_coroutine-mt.dylib' (no such file), '/usr/lib/libboost_coroutine-mt.dylib' (no such file)

### To Reproduce

1. On MacOS execute the wesnothd binary 

`/Applications/'The Battle for Wesnoth.app'/Contents/MacOS/wesnothd`

### Expected behavior
The wesnoth server daemon starts succssfully

### Additional context
@CelticMinstrel mentions this on IRC: https://discord.com/channels/231976805987385345/259976436490829825/857115830127165491

**Comment by Pentarctagon** [comment]
Note that given #4795 wesnothd will fail to launch even with this fixed.

@hrubymar10 can you update the macOS packaging to include the necessary libraries?

**Comment by hrubymar10** [comment]
@Pentarctagon macOS package already contains all necessary libraries. it is problem with app sandboxing as described in #4795 . sandboxed executables has to be located in their respective app bundles based on their `PRODUCT_BUNDLE_IDENTIFIER`. As `wesnothd` is located in main game's app bundle then it won't work. On of the possible solutions is move wesnothd executable into its own app bundle located inside main game's app bundle but I don't like that idea very much, because we will have to (probably) duplicate libraries into two places. Second issue is that I don't have required time for this. There may be also different solution but I currently don't know any other way how to make wesnothd work in sandboxed wesnoth version.

@tatethurston can you use wesnoth version provided via Steam, itch.io or SourceForge? These versions are fully compatible with your current saves and settings from mac app store version but they aren't sandboxed so you can use wesnothd server.

**Comment by hrubymar10** [comment]
@tatethurston @Pentarctagon ok, I just verified that there is really missing library in wesnoth 1.16.1 but as I said in post above, mac app store's version of wesnoth still won't work even with that library included. I'll release fixed version of wesnoth marked as `1.16.1a` asap on Steam, itch.io and SourceForge.

**Comment by hrubymar10** [comment]
Thank you for report @tatethurston 

This has been resolved in 1.16.1a release on Steam, itch.io and SourceForge

**Comment by tatethurston** [comment]
Thank you @hrubymar10 !
