### ISSUE TITLE
Lua error when attempting to use coward micro Ai

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#6408]
### Game and System Information
 - 1.16.1
 - Steam
 - Windows

### Describe the bug
![coward](https://user-images.githubusercontent.com/41817546/147756050-470d3c94-8f62-4806-88c8-d583124f4136.JPG)

### To Reproduce
Just try to use coward micro Ai with disctance set at number that is not a null value.

My current mai setup:
```
        [micro_ai]
            side = 3
            ai_type = coward
            action = add
            [filter]
            [/filter]
            seek_y = 1, 33
            [or]
                seek_x = 44
            [/or]
            distance = 10
        [/micro_ai]
```

**Comment by CelticMinstrel** [comment]
I can see there's a problem somewhere in the code (this shouldn't cause the AI to crash), but your code itself is also wrong - `[or]` is not a valid tag there.

**Comment by Hejnewar** [comment]
To be honest I was testing if that ```[or]``` would work in the first place. I didnt even get any error (which maybe should happen).

**Comment by CelticMinstrel** [comment]
There _should_ be an error about an unrecognized tag… although it may be only in the console and thus not very visible?

I have a feeling the error you're seeing is unrelated to that though, most likely caused by having a comma-separated list in `seek_x`. The documentation doesn't say a list is supported.

**Comment by Hejnewar** [comment]
Nope, I checked lua console and there is nothing about that there.

Yeah you are right that is the cause. Still should this be an error instead of information that it isn't supported?

**Comment by CelticMinstrel** [comment]
If nothing else, it should be a more explanatory error that makes the actual problem clear.

**Comment by mattsc** [comment]
> If nothing else, it should be a more explanatory error that makes the actual problem clear.

While this is quite simple to do for this parameter, it doesn't really make sense to do it for this parameter only and not for everything else.  Do we really want/need to do this?  Other WML/Lua code does not check either whether the parameters are the correct type and strange things and error messages can happen when that is not the case.  And also, isn't this what the schema validation is for?

**Comment by CelticMinstrel** [comment]
It's always best for the error message to be as informative as possible. Of course you're right, it doesn't make sense to do it only for this parameter and not for everything else, and it doesn't make sense to do it for `[micro_ai]` and not for other WML tags, and doing it for everything could be quite a lot of work, but I do think it's best to fail fast rather than passing garbage down the line resulting in a cryptic error message later on.

Schema validation would indeed catch this sort of thing. I'm not sure how accessible schema validation is to the average user, though.

**Comment by mattsc** [comment]
I can't really disagree with any of that.  Come to think of it, it might actually be quite easy to do this for the Micro AIs.  The code already has `required_keys` and `optional_keys` tables and complains if anything else is used.  We could change these from
`local optional_keys = { "high_level_fraction", "randomness" }`
to
`local optional_keys = { high_level_fraction = 'number', randomness = 'number' }`
and then we could easily check that it is of the right type.  Still a bit of work given how many MAIs there are, but this is manageable, I might just do that.

That doesn't solve this for other WML tags, but it is one step.  And it would mean that this issue can be closed.  😉

**Comment by CelticMinstrel** [comment]
Would also be nice if it supports `'float'` and `'integer'` as types (you can distinguish these with `math.type`, though I'm not sure if WML correctly sets them when converting a config to a number).

**Comment by mattsc** [comment]
Hmm.  I guess for floats we'd just have to check whether it is of type number, since providing an integer is fine in that case.  And for integers we could simply check whether  it has a non-integer fraction.  I'd let `1.` and `1.0` pass as integers in that case, even though it is not strictly true.  Do we actually have MAI parameters that have to be integers? (Not counting `ca_score`, which is dealt with separately.)  I'll have to check on that.

**Comment by mattsc** [comment]
Did some quick tests and the type of a WML key containing `1.` or `1.0` converted to Lua is `'string'`.  Using `tonumber()` on it then returns these correctly as floats, while `1` is shown as integer with `math.type()`.  Meh, it almost doesn't seem worth the effort, but I guess it's easy enough to do.

**Comment by CelticMinstrel** [comment]
> the type of a WML key containing `1.` or `1.0` converted to Lua is `'string'`.

Huh…? That doesn't seem right…? For `1.` maybe, as that's not really a valid number (notwithstanding some programming languages accepting it), but `1.0` really should be a number…

**Comment by mattsc** [comment]
This should now be taken care of in #6802.  If you use the example of the `[micro_ai]` tag of your original post, it produces this error message:
`error wml: [micro_ai] tag (coward) parameter 'seek_y' must be of type integer`
And after you fix that, you get the following warning:
`Warning: [micro_ai] tag (coward) contains invalid parameter: [or]`

Hopefully this means that it should be pretty easy to track down problems like this in the future.
