### ISSUE TITLE
AI sometimes causes UI freezes for seconds

### ISSUE THREAD

**Issue by Dugy** [wesnoth/wesnoth#6504]
### Game and System Information
 - Wesnoth 1.16.2
 - Downloaded via flatpak on Ubuntu, but it affects other users as well

### Description
Sometimes, when controlling the player's ally with Micro AI Fast or the normal AI, the AI will take moderately long time to make a move, freezing the UI for all this time. It doesn't really lock up, but the freezes lasting for several seconds look very much like a bug.

It affects multiple scenarios, always sides that are the player's allies. It wasn't happening before 1.16 and there were no significant changes in the campaign recently, except for making it work on 1.16.

It's been originally reported [here](https://github.com/Dugy/Legend_of_the_Invincibles/issues/401).

### To Reproduce

1. Load [this save file](https://github.com/Dugy/Legend_of_the_Invincibles/files/7926574/LotI1-Journey.South.Turn.17.gz), requires the Legend of the Invincibles campaign installed
2. Hit end turn
3. The AI will start playing and cause very visible UI freezes

### Additional comments
I don't know if micro AI code is run on the rendering thread, or it just acquires a mutex that the rendering thread waits for, but the problem didn't appear before and looks very visibly like a bug. I'd use a debugger to find where it's spending so much time but it's very impractical now when the Ubuntu release is done via flatpak.

I have removed all custom events and micro AIs from the save file and the problem persists. It also happens before the AI moves a unit, not between moving and attacking.
[LotI1-Journey.South.Turn.17.zip](https://github.com/wesnoth/wesnoth/files/8039466/LotI1-Journey.South.Turn.17.zip)

**Comment by mattsc** [comment]
There are a couple things coming together here. The cause of the freeze is that the move_to_any_enemy (MtaE) candidate action takes a long time to evaluate.  That CA is a Lua CA and, at least for the time being, there is no way to allow user interaction with the UI during Lua CA evaluation.  And the reason why the MtaE CA is used in the first place is that the AI side has no enemy leaders to move toward, so the move-to-targets (MtT) CA, the standard CA moving units toward enemy leaders and villages, never kicks in.

The MtaE CA was only meant as a backup in special cases when it was introduced a long time ago, and not as the main CA for moving many units toward many enemies on large maps.  As such, it is not optimized for speed at all.  I just did a bit testing and I can get the evaluation time of the longer moves down from around 10 seconds to around 0.1s for LotI1-Journey.South.Turn.17.zip.  So that will not only greatly reduce the UI freezing, it will also make the AI side's turn go much faster.  I'll do some more work on this and then put in a PR.  It will be improved in the next release.

Having said that, the MtaE CA isn't ideal for moving many units anyway, it uses an extremely simple algorithm (but currently does a lot of path finding, that's why it's so slow on large maps).  Ideally, you would use the MtT CA instead.  You can do that even for leaderless enemy sides by giving it a few goals with the `[goal]` tag.  That would also work as a workaround until the MtaE CA has been sped up in mainline.

**Comment by Dugy** [comment]
Thanks for looking into it. I've used the workaround you suggested and it fixed the problem.

I don't know how useful this is, but here's how I solved this movement problem once. First, I used pathfinding to calculate the distance of every unit to every location, ignoring temporary blocking by units. Then, when the AI was choosing where to move units, it could quickly obtain the proximity to targets for nearby locations using the precalculated distances. Going towards targets or running away from them was then as simple as following the gradient.

**Comment by Dugy** [comment]
I think that could cause an entire army to focus on a solitary scout while a much bigger army moves somewhere else undisturbed. But that might be hard to exploit because the player always has a leader.

**Comment by mattsc** [comment]
Yeah, agreed (on both parts), but you can make that argument the other way around too.  There are cases when you could exploit the enemy army going for the leader too, for example when you have a fast leader and a slow enemy army, you can lure them away while moving all or part of your own army around for an enemy leader assassination.  In fact, I believe that that is quite a popular strategy.  😉 

Anyway, my point being that there's no one-size-fits-all for this, but that's why there are `[goal]` tags and other customization options, so that the behavior can be modified when the default does not work for the given use case.
