### ISSUE TITLE
[world conquest] [artifacts] Bezoar is broken

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6513]
### Game and System Information
- 1.17.0+dev / MingW64 / Windows10 / Github

### Describe the bug
Artifact is bugged. 

### To Reproduce
Equip Bezoar, see side bar, traits undead/healthy/fearless are not added as they should have been.

### Expected behavior
Not Bugged...I guess?

### Additional context
`[artifact][/artifact]` does not support `[trait][/trait]` but supports `[effect][/effect]`

**Comment by Pentarctagon** [comment]
As commented on Discord recently:
> On the Steam version 1.17.10 the Bezoar seems to only give tenacity without any of the other declared bonuses?

as well as noted originally [here](https://github.com/wesnoth/wesnoth/pull/6515#issuecomment-1039501585).

**Comment by stevecotton** [comment]
> as well as noted originally [here](https://github.com/wesnoth/wesnoth/pull/6515#issuecomment-1039501585).

The code in the PR completely changed after that review comment, so I've no idea if it was working or not when the PR merged.

**Comment by knyghtmare** [comment]
> so I've no idea if it was working or not when the PR merged.

It does not work anymore. I confirmed it just now.

**Comment by gfgtdf** [comment]
To give some additional context:
There are two ways in which this can be fixed:
1) using [effect] directly as the first atttempt in #6515 did.
    This has the advantage that the artifacts effects can be removed  with [remove_object], another advantage is simpler code.
2) allow [trait]s in [artifact]
    This has the advantage that the trait is shown in the sidebar.

When i was writing that function i heavily leaned towards, option (1). Especially when we add a way into the ui to see which artifacts a unit has equipped, showing this into on the right hand side should be superfluous . But since afaik no such option exists i can see the advantage of showing the traits.

**Comment by gfgtdf** [comment]
Fixed in 1.16

**Comment by Pentarctagon** [comment]
Can this be closed then?

**Comment by gfgtdf** [comment]
It's not fixed in 1.17 yet iirc
