### ISSUE TITLE
Crash after pressing TAB in chat line while trying to send private message

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#6539]
### Game and System Information
 - 1.16.0
 - Website
 - Win10

### Describe the bug
Crash after **pressing TAB in chat line** while trying to send **private message**.

### To Reproduce
1. Connect to MP server.
2. Choose any player (or bot), click at nickname, choose "Send Private Message".
3. Input at least 1 any symbol (with empty chat box app would not crash!).
4. Press TAB in chat line.
5. Crash.

**Comment by Discontinuum** [comment]
I believe it's a duplicate of https://github.com/wesnoth/wesnoth/issues/6263 if it's in 1.16.0

**Comment by Wedge009** [comment]
Thanks for highlighting that. On first reading the issue summary I was thinking of #3729 but that's by the same reporter and #6263 sounds a lot closer to the description.

Advise @amokmen to try the current version and confirm if it's still occurring or not. Otherwise I'll close this as duplicate within a day or so.

**Comment by amokmen** [comment]
Yeap, no crash for 1.16.2.

**Comment by Wedge009** [comment]
Great, thanks for confirming.
