### ISSUE TITLE
End turn button partly overflowing hidden

### ISSUE THREAD

**Issue by galegosimpatico** [wesnoth/wesnoth#6544]
<img width="803" alt="Screen Shot 2022-02-26 at 23 42 43" src="https://user-images.githubusercontent.com/53513496/155861381-a6092d6e-fa10-4039-aba6-6a765b4fe36e.png">

800x600

**Comment by Wedge009** [comment]
I've seen this before but I'm not sure if it's been formally reported here previously.

**Comment by galegosimpatico** [comment]
When the scenario ends it turns to a more grave "End scena".

**Comment by stevecotton** [comment]
This is one of the issues in #5620; it's probably helpful to keep this as a dedicated issue for this part of that issue.

**Comment by Wedge009** [comment]
At 1024x768 the End Turn/Scenario button is positioned correctly, and is given the full decoration (https://github.com/wesnoth/wesnoth/blob/master/images/buttons/large-button.png).
https://github.com/wesnoth/wesnoth/blob/70d957575881a0394835b64f50fe77b16185d252/data/themes/default.cfg#L132-L142

When the vertical resolution goes below 768 the button is reduced to the 'normal' version (https://github.com/wesnoth/wesnoth/blob/master/images/buttons/button_normal/button_H22.png) but otherwise appears to be positioned correctly.
https://github.com/wesnoth/wesnoth/blob/70d957575881a0394835b64f50fe77b16185d252/data/themes/default.cfg#L605-L609

However, when the horizontal resolution goes below 1024 the button shifts to the right as shown in the original report. I don't know enough about the GUI handling to see how/why this happens.

**Comment by Wedge009** [comment]
Confirmed resolved in master, thank you.

**Comment by galegosimpatico** [comment]
Nice! Thanks.

Could anyone ping again when this is deployed to Steam?

**Comment by Wedge009** [comment]
I believe it will be included in the next 'beta' release, 1.17.5 I think.

**Comment by mesilliac** [comment]
@galegosimpatico 1.17.5 should be up now, including this fix

**Comment by Wedge009** [comment]
I don't believe there was a commit or change to specifically address this issue so I doubt there will be a back-port - I believe this was resolved as part of mesilliac's (great) work on overhauling the rendering system for 1.17. Since it's such a major change, it belongs in the development builds.

**Comment by galegosimpatico** [comment]
I understand now, this patch could be written only because it's on top of other changes by mesilliac, those other changes can't be backported.

**Comment by mesilliac** [comment]
Hmm... there were actually some separate commits for this. Maybe it could be backported? It was four commits from 91fd53ac4512f3e57b67391acb42a487e895da0d to cf4c265fc3f383999ea43e749f55b28cf164b0ef (fixing some other theme issues as well)

I'm not sure if it would backport cleanly but it might, as the fix was in the themes themselves.

**Comment by Wedge009** [comment]
Oh, that was surprisingly straightforward. Back-port is in #6790.

**Comment by galegosimpatico** [comment]
You are extremely kind.

If that gets merged and there is any regression at any future, I hope that such backport can be rolled back easily.
