### ISSUE TITLE
[Campaign] [SP] Clean Up THoT's code

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6587]
While foraging code from this campaign and NR for the...well, you know, I have stumbled on things which seem to be obsolete code bits and files no longer in use.
Thus, I am listing them here for removal (or moving them to attic).

- [ ] Character Stat Rathlyn
- [ ] Rathlyn's  portrait

Backstory:
This character was a loyal Arch Mage given in High Pass scenario before the campaign was reworked. After the rework, he is no longer present in this campaign but his character stats define and portrait have stayed. They are no longer required.

**Comment by Wedge009** [comment]
I had trouble finding what you were referring to because it looks like the character in question is actually Ratheln, not Rathlyn.

He is still marked for recall in scenarios 9 and 10 - is it the case that if the unit doesn't exist in the recall list, then the recall fails silently (or at least without obvious error)?
