### ISSUE TITLE
[AI] [Micro AI] [BUG] Bottleneck MAI throws an error and then breaks down completely

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6599]
1.17.2+dev latest commit
Github
MingW64
Windows 10 

## Error Message
```js
20220331 12:22:25 error scripting/lua: ai/lua/ai_helper.lua:325: attempt to index a nil value (local 'dst')
stack traceback:
	ai/lua/ai_helper.lua:325: in field 'robust_move_and_attack'
	ai/micro_ais/cas/ca_bottleneck_move.lua:479: in field 'execution'
	[string "local self, params, data, filter_own = ......"]:2: in main chunk
```

## The code used
```ini
      [micro_ai]
            side=8
            ai_type=bottleneck_defense
            action=add

            [filter]
                type=Dwarvish Fighter, Dwarvish Guardsman, Dwarvish Thunderer,Dwarvish Scout
            [/filter]

            # coords where dwarves are defending
            x= 4, 4, 7, 6, 4, 4
            y= 3, 4,15,15,26,27
            # coords where attacks are coming from
            enemy_x= 5, 7, 8, 5, 5
            enemy_y= 4,16,15,26,27
      [/micro_ai]
```
## Additional Context

This bug pops randomly so I dont how it can be reproduced

Might be related to #6519 but I am not certain

**Comment by doofus-01** [comment]
> Might be related to https://github.com/wesnoth/wesnoth/pull/6519 but I am not certain

It probably is, it looks familiar.  Creating a test scenario where this is reproducible seemed daunting at the time, but if other people are seeing this issue as well, maybe I could put a little more effort into it.  The PR did fix a particular save file I had, but it was UMC so there was too much extra baggage for it to really count.

**Comment by knyghtmare** [comment]
I sort of patched on my end and I think it's caused when the side has units which cannot be moved..or if there are its own units on the other sides of the bottleneck. Can be any.

**Comment by doofus-01** [comment]
None of those by themselves are enough to cause it.

**Comment by cooljeanius** [comment]
Hi, I'm running into this while porting TEG to 1.16; try playing S09 ("Unusual Allies") to see

**Comment by mattsc** [comment]
Thanks, @cooljeanius, for providing a test case to reproduce the error.  I had previously tried several times, but always failed.

The problem occurs when a unit tries to move to a hex occupied by a unit of its own side that cannot move out of the way.  There's a safeguard against that in the code, but it only works if the unit is "on the AI's territory".  That's generally fine, because AI units do not try to move onto the enemy territory.  Now the problem is if there are paths around the bottleneck, then own and enemy territory are not necessarily clearly defined.  (The wiki actually states that it does not make sense to use the MAI in that case, but of course people always come up with inventive ways to use Wesnoth features — and if it works well enough, why not.)

Anyway, there is no reason to safeguard against this only on the AI's territory, so just dropping that conditional will fix this problem.  I'll post how to do this in PR #6519.

**Comment by cooljeanius** [comment]
Is this going to be backported to 1.16?
