### ISSUE TITLE
[Campaign] [THoT] Move portrait of Perrin (the elder mage) and righteous flame icon to Attic

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6602]
Hmm...so, we're here again.

Backstory:

Perrin was the Headmaster of the Mage Academy encountered in the scenario "Mages and Drakes" in 1.14 THoT. The campaign was reworked and this scenario and this character has been removed. However, the portrait has remained (in 1.15, 1.16 and now, 1.17)
Thus, I propose the it's moved to the attic.

Similarly, 
the staff of righteous flame icon was part of some kamikaze or "final strike" mechanic of the classic THoT which has been removed as well. Thus, the icon should be moved to the attic as well. (might be useful for something else).

Seeing these assets still present makes players question what happened and ask about them such as https://forums.wesnoth.org/viewtopic.php?p=672546#p672546

**Comment by knyghtmare** [comment]
(also, I wonder if these minor things should be remedied at all given the plans for Roadmap 1.17)

**Comment by knyghtmare** [comment]
> I don't think cleaning up should be blocked on future plans, unless it's known for certain that old resources will be re-used again later. And even if they are, they can always be restored from the attic.
> 
> While you're reviewing all these old resources - do you have any more that you're aware of?

Now that you mention it, I was going to request doofus to update that "Dawarf" unit in UtBS. It's been unchanged since 1.4.6 whereas rest of the utBS custom unit set got updated more or less. Maybe it needs to filed as a feature request.

One thing I noticed was that people remarking on discord that Konrad (HttT protagonist/MC) has kept the same sprite since 1.4.0 whereas Li'sar got her updated set. So, it sort of felt neglecting to them to have the main MC sprites of the flagship campaign stay outdated. Similar argument for Haldric and Jessene (TRoW).

I think it would cool if the current cycle focused on updating these ones instead of bringing in new units out of the blue.

**Comment by Wedge009** [comment]
I only remember 'dawarf' because I wound up correcting a typo in its description - I don't think I've encountered it in a normal play-through! Probably best to record that in a separate request so it doesn't get forgotten.

I did wonder about Konrad's sprites since it reminds me of the older portrait designs that I started Wesnoth in, back in 1.4. It certainly doesn't match his current, more realistic portrait design. Again, this is something that should be recorded separately.

I'll probably move these images in a couple of days so if you're aware of any more outdated resources I can move them at the same time.
