### ISSUE TITLE
Editor: palette's scroll down button can't scroll to last row of items

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6724]
### Game and System Information

- **Version:** At least 1.16.2 (current release at time of report)
- **Downloaded from:** Official Steam release + self-compiled
- **Build info:** MSVC/SCons
- **OS:** Windows and Linux

### Description of the bug

I noticed this while testing #6723 on a laptop (no scroll wheel). The items/tiles panel in the bottom-right side of the Editor window allows the user to scroll via buttons or the mouse wheel. However, I can only access all tiles with the mouse wheel scrolling method.

### Steps to reproduce the behavior

1. Start Wesnoth
2. Enter Editor
3. By default the 'all tiles' option should be shown in the bottom-right panel. Assuming there are more tiles than can be shown in the panel at once (I tested at 1920x1080 and 2560x1440), click the down button to scroll to the end of the available tiles. The last available tile is the 'Fake Map Border'.
4. Use the mouse wheel to scroll even further down. This exposes the two more tiles which are the _actual_ last tiles available: 'Fake Shroud' and 'Fog'.

### Expected behavior

Using the buttons to scroll down should show all available tiles/items. I suspect this inconsistency may have been missed if most developers are using a mouse wheel to scroll through the tiles.

### Additional context

I have a suspicion that there might be a mis-count in the number of items/tiles to render. The user can assign one tile each to the left-click and right-click. Could this be throwing off how the tiles/items are arranged in this panel?

**Comment by stevecotton** [comment]
If the number of tiles doesn't divide exactly by the number of columns, the behavior of the last line is odd - instead of showing the final line with a few empty spaces, it changes which column the display starts on to make the final line fit.

Seen with a 1.17.4+dev build (7d2ee4ef72fb17b714290dbf576fc854a02a1382 + PR #6723 providing extra items)

**Comment by Wedge009** [comment]
Is that an analysis of the code doing the items layout or a confirmation of the behaviour I observed?

**Comment by stevecotton** [comment]
It was a combined confirmation and a note of an additional (but IMO not useful) feature that's seen when scrolling with the mouse-wheel - things jump between columns to fill the spaces. The jumping about seems bad UI anyway (makes it harder to find the items when they move about), so I'm looking at just removing it; and now that I'm looking at the code it'll be easier without that feature.

If you have 10 items, with 4x2 visible in the GUI:
```
a b c d
e f g h
```
then upon scrolling down it jumps to:
```
c d e f
g h i j
```

The original bug reported - that's because, although `editor_palette<T>::can_scroll_up()` and `editor_palette<T>::can_scroll_down()` already exit, there's at least two bits of code that ignore them and implement their own logic instead. Will open a PR about it sometime this week :D

**Comment by Wedge009** [comment]
Oh okay, thanks. I'll be sure to watch for that PR.

And yeah, it sounds like it was an intended 'feature, not a bug' (the re-ordering of the items) and I agree that it's not expected behaviour. It possibly disguised the bug with respect to the 'can scroll up/down' functions being implemented separately.
