### ISSUE TITLE
Hadlin is too full of doubt

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6773]
### Language

English

### Source

SoF S8 Outriding the Outriders

### Original Text

"I see. Well, come on in. I doubt they would be able to capture this fort, even if they did want to start a war. Which I doubt."

### Proposed Change

"I see. Well, come on in. They will not be able to capture this fort, even if they did want to start a war... which I doubt."

**Comment by Pentarctagon** [comment]
@nemaara thoughts?

**Comment by eyalroz** [comment]
@Pentarctagon : Haldin might say "even if they do want to start a war" instead of "even if they did". Not sure which is best here.

**Comment by max-torch** [comment]
> Haldin might say "even if they do want to start a war" instead of "even if they did". Not sure which is best here.

my take on "even if they did" vs "even if they do"

"even if they did" sounds more like it means the notion that they want to start a war is hypothetical
"even if they do" sounds more like it means the notion that they want to start a war is established and certain

a similar phrase:
You can't win even if you wanted to
vs 
You can't win even if you want to

Also, I agree with @eyalroz change regarding joining the sentences, because the last sentence is a dependent clause. Dependent clauses should not be sentences on their own.
The ellipsis is good but it can also simply be a comma. I'm actually in favor of a comma instead of ellipsis.

Anyone agree or disagree?
We can start implementing this if there is consensus, agreement.

**Comment by eyalroz** [comment]
@max-torch : Remember the main point here is dropping the double "doubt". All the rest is secondary IMHO.
