### ISSUE TITLE
MacOS and Add-ons Menu

### ISSUE THREAD

**Issue by daMark-de** [wesnoth/wesnoth#6787]
### Game and System Information

- 1.17.5
- SourceForge
- MacOS Mojave 10.14.6

### Description of the bug

The add-ons are visible only if they have the mouse focus after some steps in the add-on menu.
(See the attachment / small video.)

### Steps to reproduce the behavior

1. start BfW (for me in full screen mode)
2. Click `Add-ons`
3. Select `State: Upgrade Available`
4. Select `State: All Add-ons`
5. move the mouse up and down over the list - only the lines with the mouse focus show up. The others may fade up/down as they get / loose the focus of the mouse.

### Additional context

Uploading BfW_1.17.5_Add-Ons.mp4…

**Comment by knyghtmare** [comment]
@daMark-de can you upload the video again in a separate comment? The Github template sort of breaks when trying to upload attachments

**Comment by daMark-de** [comment]
Let's try another upload.

https://user-images.githubusercontent.com/67341681/174894421-4827c283-06e0-4d06-9a6e-e150a10e7238.mp4

Looking better I guess.

**Comment by CelticMinstrel** [comment]
Hmm, interesting. It looks like it _should_ have a horizontal scrollbar (the button is cut off in the bottom right-hand side) but doesn't… unless that's just the video cropping out part of the screen?

**Comment by daMark-de** [comment]
Dont't look at the video too close. I gave it a try but I have no experience with this kind of things. It is not the original video. I had to reduce the resolution and the quality for the upload.
Please concentrate on the `Steps to reproduce the behavior`. Who can reproduce the behavior?

**Comment by mesilliac** [comment]
I reproduced this on Linux so it isn't a MacOS issue exclusively.

It happens if drawing resolution is greater than 1281x801 and less than the width of the full-width dialog (~1420px wide or so?). The easy fix here would be to correct the gui WML so it changes to the lower resolution form at the correct size, whatever that is.

Not sure why it's drawing the background incorrectly, but that might get overwritten by some of the pending changes in the new_rendering branch. As such fixing the gui wml is preferable.

**Comment by mesilliac** [comment]
I fixed the blackness, but i didn't fix it using the wrong layout at those resolutions.

Someone should fix that.
