### ISSUE TITLE
[MP] Plan Unit advance Modification throws an error when any unit is recruited

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6897]
On recruiting a unit (when the mod if enabled), the following error message is shown:
```java
20220723 01:39:57 error scripting/lua: [string "-- pick_advance/main.lua..."]:164: bad argument #1 to 'get' (expected string or location)
stack traceback:
	[C]: in field 'get'
	[string "-- pick_advance/main.lua..."]:164: in function <[string "-- pick_advance/main.lua..."]:163>
```

## Build Info:
**Battle for Wesnoth v1.17.6+dev (720094361d4-Modified) x86_64**
Github downloaded and built with Msys2

## Additional Info:

The Menu item on the right-click menu is distorted as well:
![image](https://user-images.githubusercontent.com/5283677/180518428-d39f6aa3-b562-4390-a98f-864b4d24504d.png)

**Comment by CelticMinstrel** [comment]
Okay, the issue is that I switched it from `on_event` to `wesnoth.game_events.add_repeating`.

Apparently the callback to `on_event` is passed the current event context. However, `add_repeating` passes an empty WML table instead. I would say the correct fix is to remove the parameter and replace `ctx` with `wesnoth.current.event_context`.

I'll also have to think about whether `add_repeating` should be altered to pass the event context for compatibility with `on_event`.
