### ISSUE TITLE
Inconsistent vertical spacing between attacks 

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#6936]
### Game and System Information

The Battle for Wesnoth version 1.17.6+dev (6eb2246e-Clean) x86_64
Running on Freedesktop.org 21.08.14 (Flatpak runtime) x86_64

### Description of the bug

Spacing between attacks in the sidebar:
![Screenshot_20220803_013410](https://user-images.githubusercontent.com/3605541/182494286-02063954-1371-4177-b769-e879401f5325.png)
No spacing between elements:
![image](https://user-images.githubusercontent.com/3605541/182494504-17a0aae1-dac2-4890-b491-708d767ba1e0.png)
No spacing in Recruit dialogue:
![image](https://user-images.githubusercontent.com/3605541/182494688-e0887e93-6139-4597-9d65-1bcfdf127b64.png)

**Comment by Wedge009** [comment]
Responding to @CelticMinstrel's question in #5264, I've confirmed the issue was introduced with 1b7a0ae3be549f79131e44aba0cc30bd448b8187 (@mesilliac).

There was already a subtle gap between attack listings but the commit above seems to exacerbate the spacing to something excessive.

Before 1b7a0ae3be549f79131e44aba0cc30bd448b8187:
![good](https://user-images.githubusercontent.com/13679322/182531832-4e730165-43c1-4270-9a8d-cb56b20f51f7.png)

From 1b7a0ae3be549f79131e44aba0cc30bd448b8187 onwards:
![bad](https://user-images.githubusercontent.com/13679322/182531886-ba7d35e8-7299-4c9d-bb65-e0bf7e0f4977.png)

**Comment by mesilliac** [comment]
well it seems there are two problems: (1) apparently requesting the size of an empty text does not give the same result as rendering the text and querying the size, (2) it is attempting to render an empty text

The first is what changed in that commit, it no longer tries to render just to figure out the size. When rendered it has 0 size, but when not rendered it returns a one-line height.

I don't really want to touch the text rendering system any more than necessary, so i'll probably just fix (2) to hide the problem...

**Comment by mesilliac** [comment]
This case should be fixed by cda30ba0a70954a72be99deba9031ebfac45203c

There may conceivably still be problems if the text is somehow empty without being empty. Like if it has markup tags but no text, perhaps. There may be a better fix inside the text rendering system but i'm not familiar enough with it to apply anything there. Just making a note in case this comes up again.

**Comment by Wedge009** [comment]
Looks resolved to me. Thanks for the quick response.
