### ISSUE TITLE
Things that need/should/can be changed

### ISSUE THREAD

**Issue by xSkyEndx** [wesnoth/wesnoth#6971]
### Game and System Information

- **Version: all versions excluding 1.16.0 and 1.16.1**

### things that devs can work on

**most important (in my opinion)**

- [ ] **Turn Bell**: Separated Turn Bell and Timer Clock, remove its depending (Sound effects)

- [ ] **in game**: Version after 1.16.1: when you hover over an enemy unit it shows the max- instead of the current reach (u can show it when you click on the unit), make this vice versa (current is far more important)

**Game settings:**

- [ ] preferences are saved, but timer settings will go back to default (means instead of a playable timer you will accidently play with default, because check box is set)

- [ ] **Default** time setting: Change it do something playable (300, 300,300, 0)

- [x] **Timer**: max turn bonus can be increased to set it over 5 min.

- [ ] **Gold**: You can only change gold settings by a multiple of 25 that's not sensitive enough if you want to play with a handicap. Change it to 5. (You win all the time vs your friend, but want to give him a chance)

**second most important, not as important as most important (in my opinion)**

**Replay**:

- - [ ] **Point of View**: rename Human Team (p1) and add p2 perspective

- - [ ] **Older version**: make it possible to watch replays of older version in the lates version (I have 6 different version on my pc)

- [ ] **saves folder**: make it possible to open folders in your saved folder when you load games

- [ ] **Maps**: add labels to Aethermaw

- [ ] **Lobby player list**: you can easily misclick on the wrong person when a player joins the Lobby

- [ ] **Blocked User**: don't highlight them

- [ ] **Friend List**: it's a list of ppl you follow (rename it)

- - [ ] different written names aren’t supported upper/lower (SkyEnd, SKYend, skyend)

**not important, but possible (in my opinion)**

- [ ] Remove or change default color Blue: you can't read player name in chat

**Comment by Pentarctagon** [comment]
> Older version: make it possible to watch replays of older version in the lates version (I have 6 different version on my pc)

This is unlikely to happen, given that even just having 1.14 replays work in 1.16 (#6419) ended up not getting merged. You could perhaps talk with @demario-w and take a look at https://forums.wesnoth.org/viewtopic.php?t=53824 though.

> different written names aren’t supported upper/lower (SkyEnd, SKYend, skyend)

Can you clarify what this means?

**Comment by xSkyEndx** [comment]
> Can you clarify what this means?

It's for the Friend List/Blocked User. You can join the MP-Server with your name differently written, but those lists don't support it. This way I can join with skyend and ppl will not see me highlighted even if they have added me as SkyEnd.

**Comment by xSkyEndx** [comment]
> This is unlikely to happen, given that even just having 1.14 replays work in 1.16 (#6419) ended up not getting merged. You could perhaps talk with @demario-w and take a look at https://forums.wesnoth.org/viewtopic.php?t=53824 though.

Yeah I thought that might not be possible. But with 1.16 you can open older version folders.

Ah right. To open folders in your saves folders should be possible. I actually created 1.4 and 1.6 to have an extra folder.

**Comment by CelticMinstrel** [comment]
This is an utterly terrible format for an issue. I would say it should be closed, and maybe some different issues could be open for specific subsets. Generally it should be one issue per suggestion, though a group of closely related suggestions in one issue is okay… but this is a whole bunch of unrelated suggestions.

Also, the tone of this issue is kinda… how should I put it… it's a bit entitled to come in and say that something absolutely "needs" to be changed no matter what, especially when it's not something utterly game-breaking.

**Comment by xSkyEndx** [comment]
> Also, the tone of this issue is kinda… how should I put it… it's a bit entitled to come in and say that something absolutely "needs" to be changed no matter what, especially when it's not something utterly game-breaking.

It's to value the issues. If you feel personal attacked by this, then it's your matter.

**Comment by CelticMinstrel** [comment]
> It's to value the issues.

I have no idea what you mean, but I'd say needlessly grouping things into arbitrary categories devalues rather than values them.

**Comment by xSkyEndx** [comment]
It was meant to be a list of issues and not made for this format.

I feel that most devs don't play the game and don't see the issues their self, but those mentioned are for sure the most import things to work on.

**Comment by knyghtmare** [comment]
> Maps: add labels to Aethermaw

Do you mean labels which show which hexes are converted to flat on which turn? Or something else?

**Comment by xSkyEndx** [comment]
> > Maps: add labels to Aethermaw
> 
> Do you mean labels which show which hexes are converted to flat on which turn? Or something else?

Yeah those labels. On older version you had them on the start of the game and they vanished with the terrain change.

**Comment by CelticMinstrel** [comment]
Nothing you've mentioned in this thread is anywhere close to high priority.

**Comment by xSkyEndx** [comment]
XD

**Comment by max-torch** [comment]
> This is an utterly terrible format for an issue. I would say it should be closed, and maybe some different issues could be open for specific subsets. Generally it should be one issue per suggestion, though a group of closely related suggestions in one issue is okay… but this is a whole bunch of unrelated suggestions.

This is not an instinct that some new people have. I myself am guilty of having made this mistake #6197 . I try to avoid it now. We can also be a bit forgiving in our tone about such mishaps for first timers, but do let them know the problem.

Something like this also happened in warcraft 3 news recently, I cannot find the link to where I encountered the news, but trust me it's real, what happened was that someone made a mega thread that contained bug reports and suggestions for warcraft 3 and then blizzard deleted it because it didn't follow the "one issue per thread rule", but people in the community of that game actually got mad about and got negative optics for Blizzard and there were even YouTube videos about it.

Point is it's a real honest mistake many people make.

> Also, the tone of this issue is kinda… how should I put it… it's a bit entitled to come in and say that something absolutely "needs" to be changed no matter what, especially when it's not something utterly game-breaking.

Agree with celmin. The part that is a bit entitled is the wording of "need" and "should" in the context of things that are not game-breaking, per se, but rather seem to arguably possibly be a matter of taste.

>I feel that most devs don't play the game and don't see the issues their self

There are devs who actually play the game a lot. The reason why they may not have made the suggestions you made outright, or stated it as "need/should" again is because we could argue that it could be a matter of taste. Now, I don't want to admonish you for making the suggestions you made. **This is good and we are very happy you have communicated your thoughts to us!** Just remember that just because you want something, it doesn't mean it is what everyone wants, so my tip is to see if people agree first before declaring that a motion that you put forward is a "need".

**Comment by xSkyEndx** [comment]
> * [ ]  **Turn Bell**: Separated Turn Bell and Timer Clock, remove its depending (Sound effects)

I found this in a Bug report from 2017 (I think). Idk how a 1 min timer mid-game (that's when you realize it) isn't game breaking. 

It's not that I want or expect something from devs. All I want is to support the game.
I don't see that there is much going on, but I at least thought that devs just didn't know the issues. 
Now I think that those issues are either hard to solve or that devs don't care.

It's right, those are issues in my opinion. Ppl don't need to agree on that. There is no reason to address them if there is only me who cares about it. But you could do a survey to find out, how important or wanted those are. That's for sure better, than to see the world only with your own glasses.

Sorry to bee harsh or BM, but that's my honest opinion as an outsider and competitive wesnoth player.

**Comment by Pentarctagon** [comment]
So for
> Default time setting: Change it do something playable (300, 300,300, 0)

@Hejnewar any opinion?

**Comment by xSkyEndx** [comment]
@Pentarctagon 
It's ladder standard. In 1vs1 you can't go much lower. Some few players play with 4:30 min, but still not lower than 4 min. It's recommended to play with 5 min or even more. I am a slow player myself and struggle sometimes with 5 min. For 2vs2 unless it's isar you'll need more time, but other 2vs2 maps are rarely played (mostly in tournaments).

In the 2nd Ladder tournament you had following settings.

_Games should have an 8 min timer (480/300/480/30, this would mean even if you use all of your timer, if you complete 6 "actions" you will still have 8 mins on your next turn)._

But it would be better to be able to set the timer to 8 min without action bonus.

### Enhancement:
Max turn bonus can be increased to set it over 5 min.

**Comment by Discontinuum** [comment]
> in game: Version after 1.16.1: when you hover over an enemy unit it shows the max- instead of the current reach (u can show it when you click on the unit), make this vice versa (current is far more important)

It's https://github.com/wesnoth/wesnoth/issues/6716 I wonder if there is any progress with it

**Comment by Hejnewar** [comment]
> @Hejnewar any opinion?

It's fine. 

> Max turn bonus can be increased to set it over 5 min.

It can be for a long time set to 10 min.

**Comment by stevecotton** [comment]
> **Point of View:** rename Human Team (p1) and add p2 perspective

The "rename" part of that is #2911.

**Comment by soliton-** [comment]
Closing as no one will find the random issues mixed in here.

Comment on already open issues or open new ones for specific issues and use a meaningful title.
