### ISSUE TITLE
wmllint: complaints about `[image]label="some_filename.png"` not being translatable

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#6995]
For example, the `data/campaigns/tutorial/gui/character_selection.cfg` changes proposed in #6966.

Seems a bug in wmllint, if it's not recognising these as wanting image filenames.

_Originally posted by @stevecotton in https://github.com/wesnoth/wesnoth/pull/6966#discussion_r946842999_

**Comment by Pentarctagon** [comment]
Seems like it'd be a pretty simple thing to implement? It'd basically just be "ignore anything that ends with a file extension".

**Comment by CelticMinstrel** [comment]
Or even just "ignore anything inside a `[resolution]` tag" would be sufficient, I suppose…

Speaking of which, these miscellaneous UIs scattered across places are not being schema-validated either, are they? I wonder if there's a way to do it that doesn't involve explicitly listing all the files… but it seems like a pain since it's not starting at the schema root, so maybe it's better to just add a single file somewhere that uses the GUI schema and includes any custom dialogs?

**Comment by spixi** [comment]
Images may be translated, for example if they contain text (e. g. map overlays or buttons) or if they require to be flipped for users using a RTL language (like Hebrew or Arabic).

**Comment by CelticMinstrel** [comment]
Although that's true, isn't there an entirely separate system for that which doesn't involve gettext at all?
