### ISSUE TITLE
Reconsider movement cost colouring

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7017]
### Game and System Information

- **Version:** 1.17.7
- **Downloaded from:** Sources from Wesnoth website
- **Build info:** N/A
- **OS:** Devuan GNU/Linux, but it doesn't matter
-

### Description of the bug

Between v1.17.4 and v1.17.7 the unit info dialog/pane changed. Among other changes, the "Movement Cost" column now also shows the number of hexes, using brightly-colored full-hex-shaped icons, in addition to the movement points cost of passing one hex of the terrain type.

This is a repetition of information that is already available - the movement point cost. But - that is not a bug; the question is - is it worthwhile to add this different graphical representation of the same information.

I believe that it isn't. Why?

1. It looks garish - the screen is full of brightly-colored spots all over; that is distracting and annoying.
2. The number is irrelevant in multi-terrain movement - and movement is usually multi-terrain.
3. The player knows they need to count movement points, and this multiplicative-reciprocal information does not add much.
4. One can easily get the hex count wrong, when there are more than four or five hexes.

Please just drop the colored hexes and bring back the old layout of this column.

_Maybe_ keep the coloring of the number, although I don't like that much either.

**Comment by Pentarctagon** [comment]
This was discussed pretty extensively before merging #5264

**Comment by Wedge009** [comment]
> This is obviously redundant. But - you don't need me to tell you that.

The tone of many of your reports - this included - aren't exactly conducive to co-operative and constructive discussion. While in once sense it could be considered redundant, it does provide a visual or 'graphical' indication of the relative movement points on different terrain. While experienced players may not find this useful I'm sure relative newcomers may benefit from this representation.

I admit I haven't looked at this screen in detail since the change was merged. I'll grant the saturated colours for the hex icons probably could do with some toning down. As for the rest of your objections, well, I've had my own remarks both here and in other projects be dismissed out of hand despite being less subjective and more respectfully phrased.

I don't think your points are strong enough to warrant a removal of this change, however 'redundant' it might seem to you. On the point of the saturated colouring, I think this is perhaps the only thing that warrants this issue remaining open. However, I am similarly just expressing my opinion and I am willing to be overruled.

**Comment by Wedge009** [comment]
For reference.

1.16.6 release:
![image](https://user-images.githubusercontent.com/13679322/191890798-4fb01f6a-b7f7-4f34-b344-5690f2696cb3.png)

1.17.8+dev (d01aabc81fb):
![image](https://user-images.githubusercontent.com/13679322/191890877-b944fe4f-0447-4323-9490-87b1624ed97d.png)

**Comment by eyalroz** [comment]
@Wedge009 : I actually didn't mean the "redundant" part to sound accusatory, but perhaps it does. So, edited the report. I apologize. I did feel let down and annoyed by this change, though - I guess I should have been more tactful in how I relate that impression when reporting the bug.

**Comment by Wedge009** [comment]
#7018 is merged now. If you're able to see if it makes any positive difference for you it would be helpful to have your feedback, otherwise could leave this open till 1.17.8 release. I don't think there's anything else that can be reasonably done to address the concerns listed here.

**Comment by Pentarctagon** [comment]
Barring more people having an issue with it, I don't see this being reverted.

**Comment by eyalroz** [comment]
I call'em like I see'em. I'm hoping/guessing you'll get more negative feedback with 1.18, although who knows. From my [experience](https://events.documentfoundation.org/libreoffice-conference-2022/speaker/WHDWTF/) in LibreOffice, there are bugs which are very painful to dozens of millions of people (= RTL language users), and nobody filed them before I did, because, well, they just shrugged and learned to live with how LO was behaving.
