### ISSUE TITLE
replay.cpp:669: bool replay::add_start_if_not_there_yet(): Assertion `base_->get_pos() == 0' failed.

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7164]
### Game and System Information

- **Version:** 1.17.9
- **Downloaded from:** (built from source)
- **Build info:** GCC 12.2.0
- **OS:** Devuan GNU/Linux Daedalus

### Description of the bug

App crashes when trying to open a save file I've recently saved with it: [LoW-Human Alliance Turn 1-H10.gz](https://github.com/wesnoth/wesnoth/files/10095089/LoW-Human.Alliance.Turn.1-H10.gz) ... after an assertion is triggered:
```
wesnoth: /usr/local/src/wesnoth-1.17.9/src/replay.cpp:669: bool replay::add_start_if_not_there_yet(): Assertion `base_->get_pos() == 0' failed.
```
doesn't happen with other save files from the same or earlier turns in this scenario. Hasn't happened to me before.

### Additional context

Save

**Comment by Pentarctagon** [comment]
Please upload the save that causes this issue.

**Comment by eyalroz** [comment]
@Wedge009 : Done.

**Comment by Pentarctagon** [comment]
backtrace:
```
replay::add_start_if_not_there_yet(replay * const this) (/home/derpy/Desktop/wesnoth/wesnoth-fork/src/replay.cpp:669)
play_controller::start_game(play_controller * const this) (/home/derpy/Desktop/wesnoth/wesnoth-fork/src/play_controller.cpp:1168)
playsingle_controller::play_scenario_init(playsingle_controller * const this) (/home/derpy/Desktop/wesnoth/wesnoth-fork/src/playsingle_controller.cpp:153)
playsingle_controller::play_scenario(playsingle_controller * const this, const config & level) (/home/derpy/Desktop/wesnoth/wesnoth-fork/src/playsingle_controller.cpp:279)
campaign_controller::playsingle_scenario(campaign_controller * const this, end_level_data & end_level) (/home/derpy/Desktop/wesnoth/wesnoth-fork/src/game_initialization/playcampaign.cpp:196)
campaign_controller::play_game(campaign_controller * const this) (/home/derpy/Desktop/wesnoth/wesnoth-fork/src/game_initialization/playcampaign.cpp:279)
game_launcher::launch_game(game_launcher * const this, game_launcher::reload_mode reload) (/home/derpy/Desktop/wesnoth/wesnoth-fork/src/game_launcher.cpp:1021)
do_gameloop(const std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > & args) (/home/derpy/Desktop/wesnoth/wesnoth-fork/src/wesnoth.cpp:963)
main(int argc, char ** argv) (/home/derpy/Desktop/wesnoth/wesnoth-fork/src/wesnoth.cpp:1147)
```
`pos`'s value is 53 rather than 0, which is causing the assert.

**Comment by stevecotton** [comment]
A simple fix would be to change the behavior from asserting to just returning to the title screen with a "file is corrupt" message.

However, there's a second bug here, which is that the game created this corrupt file. @eyalroz, can you remember any details about how it was created? Do you use keyboard shortcuts or the GUI menu to save? I'm thinking there's some race condition about saving while the AI is recruiting.

The file has a `[snapshot]` tag with `init_side_done=yes` but without a `playing_team` attribute, which must be the result of `game_state::write()` when not in the `PLAY` phase. Loading such a file causes `game_state::start_event_fired_ == false`, and triggers `play_controller::start_game` to call `replay::add_start_if_not_there_yet`.

It's a single-player LoW game (Landar is on side 1).

Editing the file and adding `playing_team=0` to the `[snapshot]` avoids the call to `add_start_if_not_there_yet` and loads. Looks like the save was made while side 2 (AI) was recruiting. We don't know whose turn it should be because the `playing_team` was missing, however side 1 has full castles and side 2 has recruited on 11 of its 13 castle hexes with enough remaining gold to recruit more.

**Comment by eyalroz** [comment]
I saved this right after recruiting, I think. I probably used Ctrl+S.

**Comment by gfgtdf** [comment]
In any case. we shouldn*t assert on a faulty savegame, so it's better to replace the assertion with something else.

Still the question remains, how such a savefile could be created, usually `playing_team` should be written to a savefile unless we have not yet started the game (the generation of [replay_start])
https://github.com/wesnoth/wesnoth/blob/1.17.9/src/game_state.cpp#L255

In particular we should always have game_data::START which is set here
https://github.com/wesnoth/wesnoth/blob/1.17.9/src/play_controller.cpp#L402


Do you remember whether  there were any errors before saving the game ?

**Comment by eyalroz** [comment]
> Do you remember whether there were any errors before saving the game ?

I don't remember getting an error, but this was four months ago so I don't remember much of anything about when this happened. Sorry :-(

**Comment by Pentarctagon** [comment]
Given this hasn't been backported yet, does it make sense to close this issue?

**Comment by gfgtdf** [comment]
Still happens with 1.17.22, not sure why this was marked as backport

**Comment by Pentarctagon** [comment]
@stevecotton do you remember why this was marked as Backport?

**Comment by stevecotton** [comment]
Because I intended to backport it after fixing it - sorry if that tagging lead to a misunderstanding about its status in 1.17.

**Comment by Pentarctagon** [comment]
That's still a definite improvement, regardless.

**Comment by gfgtdf** [comment]
Yes looks good i don't think there is a ways for us now to figure out how the file was produced when noone is able to repdoduce it , what we could  do however is to add an extra check when the savefile is  produced like `if(cfg["replay_pos"].to_int(0) > 0 and cfg["playing_team"]..empty()) { show_error_message("Trying to create a corrupt file, please report")}`
