### ISSUE TITLE
Add-on language filter duplicates

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#7169]
Add-ons are not consistent in the language codes they use, which results in there being both `it` and `it_IT` for example, which results in the language filter list containing duplicates for Italian. The language filter list shouldn't display these duplicates.

**Comment by soliton-** [comment]
It should remember a list of language codes per display string then so that once you choose an entry it picks the appropriate language codes.

Another option would be to add the language code to the display string. This way the user can have a little better understanding of what they pick. For example if they pick an entry with language code `pt` they may be able to guess that it's actually not clear what version of portuguese the translation will be. And it will be possible to filter for a specific version of portuguese (i.e. `pt_BR` or `pt_PT`) or any (`pt`).

**Comment by Kingofd** [comment]
The solution I thought of is pushing the `lang_code_to_string()` output trough yet another set.

**Comment by stevecotton** [comment]
I'm in two minds about the options that @soliton- identified. My feeling is to merge #7185 (which implements the first option) and let Github automatically close this issue; however someone can reopen it if they want the second option implemented.
