### ISSUE TITLE
[Terrain] Castle with Crater (^`Dc`) overlay gives sand defence (and not castle)

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7243]
Wesnoth 1.17.11+dev
Windows 10
Build from Github (Msys2)

![image](https://user-images.githubusercontent.com/5283677/209984269-eddb81b1-79b6-4ae3-b82e-4470339cc77d.png)

## Description of Bug
The hex on this map (SSLM's map pack) was randomly generated and has the code `Cd^Dc` (there's a crater overlay on it but doesn't show)

So, one would expect Trapper to have castle defence (60%) on it. But the 30% defence is shown.

## Expected Behaviour:
60% defence in such a case

**Comment by stevecotton** [comment]
I think it's a graphics bug rather than a stats bug. If someone had built a castle in a crater then they would probably either level the ground, leave it as a moat of sand outside the walls, or be in a crater much wider than the castle. So I think `Cd^Dc` is a castle that's later had a crater appeared in it, leaving rubble and sand.

**Comment by doofus-01** [comment]
Ug.  I'm not going to draw special "cratered castle" transitions, but the layering can probably be adjusted to make the crater more visible..

**Comment by stevecotton** [comment]
Looking at it again, changing the random generator to not make this combination sounds better. @knyghtmare , which random generator was it?

**Comment by CelticMinstrel** [comment]
The generator is from an add-on, so that would be up to the add-on's developer… which means, if that's considered the accepted fix, we should just close this.

**Comment by stevecotton** [comment]
Feel free to reopen, but closing on the basis that generating `Cd^Dc` hexes is a bug in an add-on's custom map generator.

**Comment by sigurdfdragon** [comment]
Thanks, @CelticMinstrel. I'll take care of it in the next release of the add-on.

**Comment by sigurdfdragon** [comment]
@CelticMinstrel 
Actually, this bug is in SSLM's Map Suite (Soft Silk Lion Milk), not in my add-on Ultimate Random Maps (previously named Sigurd's Random Maps)
Don't know if it has been fixed in SSLM.
I've pm'd the add-on author.
I've reviewed the code in URM, and terrain combination Cd^Dc does not occur there.
