### ISSUE TITLE
`--help` should imply `--no-log-to-file`

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7310]
### Game and System Information

- **Version:** 1.17.12+dev
- **Downloaded from:** Git
- **Build info:** a few local changes on top of 99bb65d1b3
- **OS:** Linux

### Description of the bug

Running `wesnoth --help` to remember the exact name of an option prints nothing to stdout or stderr, instead it dumps the help text to the log file. It doesn't give a hint about what it's done, where the log file is, or the name of the `--no-log-to-file` option.

### Expected behavior

`--help` should output the text to stdout/stderr.

**Comment by stevecotton** [comment]
I'm wondering if the unit test options `-t` and `-u` should imply this too.

**Comment by CelticMinstrel** [comment]
More generally, anything that on Windows implies `--wconsole` should also imply `--no-log-to-file`.

Note that `-t` and `-u` are, I believe, not included in that. I also don't think `-t` _should_ be, but I could see an argument for `-u`. Perhaps even `--nogui` (and anything that implies it) should imply `--no-log-to-file`? But adding an explicit `--showgui` (without an explicit `--no-log-to-file`) shouldn't?

Feels like this could get really, really complicated…

**Comment by Pentarctagon** [comment]
> More generally, anything that on Windows implies --wconsole should also imply --no-log-to-file.

`--no-log-to-file` should only be an option used on macOS and Linux anyway - Windows logging is handled separately, just as it was before logging to file was added for macOS and Linux. That's why check the result is handled this way: https://github.com/wesnoth/wesnoth/blob/9b235a2dec2749f2914295f12768c015a6761a0a/src/wesnoth.cpp#L1042-L1046

**Comment by CelticMinstrel** [comment]
So, I assume that `--help` doesn't mention `--no-log-to-file` if run on Windows?

**Comment by Pentarctagon** [comment]
> So, I assume that --help doesn't mention --no-log-to-file if run on Windows?

Correct.

> Anyway, I think what this implies is that the checks for things that imply --wconsole are no longer Windows-specific and imply --no-log-to-file instead on Mac and Linux.

I'm not sure what you mean. `--no-log-to-file` simply doesn't exist on Windows - it's behind conditional compilation. Likewise, the `--wconsole` stuff is by definition Windows-specific - it exists because Windows requires specifying whether an app is a console app or a GUI app and GUI apps aren't normally able to write to console, so a console needs to be manually created and attached if you want to see any output that might have happened before the logger is available and able to write to a file.

**Comment by CelticMinstrel** [comment]
I'm saying there is a list of flags that imply `--wconsole` on Windows. Those same flags should probably imply `--no-log-to-file` on Mac and Linux.

**Comment by stevecotton** [comment]
Other suggestions that are feature-creeping this bug report:

Looking at the list, it should probably also apply to `--validate-addon` and `--validate-core` too.

On Windows, `--no-log-to-file` should probably be recognised as a synonym for `--wnoredirect`.

**Comment by Pentarctagon** [comment]
@CelticMinstrel ah, alright. So that'd be everything with `IMPLY_WCONSOLE` in `commandline_options.cpp`, correct?

@stevecotton I'd rather it didn't, since it feels like it's combining two separate pieces of functionality (depending on OS) under the same flag.

**Comment by CelticMinstrel** [comment]
Yeah, I guess so.

> since it feels like it's combining two separate pieces of functionality

What are the two separate pieces of functionality? What does it look like from a user's perspective? If the answer for both flags is "logs are written to standard out instead of a file", then I don't see the issue with recognizing it as a synonym.
