### ISSUE TITLE
[MacOS] No DMG files available for releases after 1.16.6 and 1.17.10

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7413]
There seems to be no macOS releases being available on source forge or itch.io or steam for quite a while now.

<img width="429" alt="Screenshot 2023-02-22 at 8 53 52 PM" src="https://user-images.githubusercontent.com/5283677/220625188-f6bbcbd5-4978-4c61-ad2f-4efec35182bb.png">

Assigned high priority since an entire playerbase has been neglected for quite a while and this just...does not seem fair

**Comment by Pentarctagon** [comment]
(cross-posting from Discord)

My understanding is that notarization is required for steam and itch.io, and macos generally makes it a pain to run non-notarized software. Basically instead of installing, it pops up a warning saying it's not verified and might contain malware, and the person needs to go through a couple system menus to say "yes really install it anyway" (assuming they even know they can do this since nothing in the warning tells them).

**Comment by CelticMinstrel** [comment]
My understanding was that that pain only applies to unsigned or self-signed apps, not to apps signed with an Apple developer certificate (regardless of notarization).

**Comment by Pentarctagon** [comment]
This has now been resolved.
