### ISSUE TITLE
wesnoth_addon_manager broken

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#7431]
There are issues with wesnoth_addon_manager. Below two examples:

```
wesnoth_addon_manager -p 1.17.x -u Arena/_server.pbl
Opening socket to add-ons.wesnoth.org:15017 for 1.17.x
Connected as 42.
Exception in thread Arena/_server.cfg:
Traceback (most recent call last):
File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File wesnoth/data/tools/wesnoth/campaignserver_client.py", line 401, in run
self.data = self.cs.put_campaign(*self.args)
File "wesnoth/data/tools/wesnoth/campaignserver_client.py", line 342, in put_campaign
data.insert(put_file(name + ".cfg", file(cfgfile)))
AttributeError: 'TagNode' object has no attribute 'insert'
wesnoth/data/tools/wesnoth_addon_manager:365: DeprecationWarning: isSet() is deprecated, use is_set() instead
while not mythread.event.isSet():
```

```
wesnoth_addon_manager -p 1.17.x -u Arena
Opening socket to add-ons.wesnoth.org:15017 for 1.17.x
Connected as 42.
Adding directory Arena as Arena.
('Ignored file', '_server.pbl')
wesnoth/data/tools/wesnoth_addon_manager:365: DeprecationWarning: isSet() is deprecated, use is_set() instead
while not mythread.event.isSet():
('Ignored file', '_info.cfg')
Closing socket.
```

**Comment by knyghtmare** [comment]
```js
$ ./wesnoth_addon_manager -p 1.16.x -u C:/Users/Asus/Documents/My\ Games/Wesnoth1.17/data/add-ons/Knyght_RotD/_server.pbl
Opening socket to add-ons.wesnoth.org:15016 for 1.16.x
Connected as 42.
Exception in thread C:/Users/Asus/Documents/My Games/Wesnoth1.17/data/add-ons/Knyght_RotD/_server.cfg:
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\msys64\home\Asus\wesnoth\data\tools/wesnoth/campaignserver_client.py", line 401, in run
    self.data = self.cs.put_campaign(*self.args)
  File "C:\msys64\home\Asus\wesnoth\data\tools/wesnoth/campaignserver_client.py", line 342, in put_campaign
    data.insert(put_file(name + ".cfg", file(cfgfile)))
AttributeError: 'TagNode' object has no attribute 'insert'

```

However, if I do
```js
$ ./wesnoth_addon_manager -p 1.16.x -u C:/Users/Asus/Documents/My\ Games/Wesnoth1.17/data/add-ons/Knyght_RotD
Opening socket to add-ons.wesnoth.org:15016 for 1.16.x
Connected as 42.
Adding directory C:/Users/Asus/Documents/My Games/Wesnoth1.17/data/add-ons/Knyght_RotD as Knyght_RotD.
('Ignored file', '_server.pbl')
Receiving 55 bytes.
Received 55 bytes.
55/55
Add-on accepted.
Closing socket.

```

Not sure how I got it right...but yay me

**Comment by soliton-** [comment]
The first case of using the pbl file as argument is for old style addons where you just have a single config file `addon_name.cfg` (and thus `addon_name.pbl`). While you can still upload those in theory I don't think that's compatible with current wesnoth anymore. Perhaps we should just remove that case.

We should do as the deprecation warning suggests. Does that fix the second case for you? Odd that a deprecation seems to change behaviour.

**Comment by Elvish-Hunter** [comment]
If the first point needs to be fixed rather than removed, it just requires to replace the `.insert()` method (which doesn't exist) with the `.append()` method (which TagNode objects have). That'll probably lead to another error because in sevu's and knyghtmare's add-ons there shouldn't be any `server.cfg` files and the script is still looking for them.
On an unrelated note, mainly for myself, it looks like the script has no way to select which version of a given add-on to download, or to look which versions are available of an add-on, so that's a feature that needs to be added. It'll also be interesting to confirm whether it works correctly with IPv6.

**Comment by Elvish-Hunter** [comment]
Just as I suspected, replacing `.insert()` with `.append()` triggers another error:
```py
$ '/[redacted]/wesnoth/data/tools/wesnoth_addon_manager' --port trunk --upload '/[redacted]/.local/share/wesnoth/1.17/data/add-ons/The_Sojournings_of_Grog/_server.pbl' 
Opening socket to add-ons.wesnoth.org:15004 for trunk
Connected as 42.
Exception in thread /[redacted]/.local/share/wesnoth/1.17/data/add-ons/The_Sojournings_of_Grog/_server.cfg:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/[redacted]/wesnoth/data/tools/wesnoth/campaignserver_client.py", line 401, in run
    self.data = self.cs.put_campaign(*self.args)
  File "/[redacted]/wesnoth/data/tools/wesnoth/campaignserver_client.py", line 342, in put_campaign
    data.append(put_file(name + ".cfg", file(cfgfile)))
NameError: name 'file' is not defined. Did you mean: 'filter'?
```
At this point I had to use Ctrl + C to exit the script. This happened because `file()` is an old function that was present in Python 2.7; it needs to be replaced with `open()`, then we'll see if this uncovers another error.
On the other hand, replacing `isSet()` with `is_set()` fixes the other warning, so I pushed that fix as 1aac405.
Another note for myself: I'll need to check if the script supports SSL and update it if it doesn't.

**Comment by soliton-** [comment]
If you fix the file call it works but when you download such an addon you get a dir back. So it's not usable anymore.

**Comment by soliton-** [comment]
Well, more importantly you get an error in wesnoth with such an addon:

https://github.com/wesnoth/wesnoth/blob/841b42d26cf6463507aef40c91854594d0cab49d/src/game_config_manager.cpp#L417-L421

**Comment by Elvish-Hunter** [comment]
At this point, I decided to remove support for old-style add-ons (the servers that used to accept them are all closed anyway). Attempting to upload anything that isn't a directory will raise a `RuntimeError`.
