### ISSUE TITLE
Selecting a new display resolution does not properly redraw the title screen

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#7436]
### Game and System Information

- **Version:** 1.17.7 onwards
- **Downloaded from:** GitHub
- **Build info:** compiled from source
- **OS:** Linux and Windows

### Description of the bug

Resizing the display window using the preferences menu - in contrast with resizing via mouse manipulation of the window border - does not redraw the title screen properly. The issue is less obvious in-game since the layout of GUI elements is designed to be flexible there. But at the title screen, nothing is redrawn after the new resolution is set.

This illustrates an example of starting at 800x600 and selecting 1024x768 from the preferences menu:
![image](https://user-images.githubusercontent.com/13679322/223011032-d0ee93f7-bf37-47fa-9d24-d08830fb160d.png)
![image](https://user-images.githubusercontent.com/13679322/223011067-a63c74f2-663d-49c5-aebf-9f5aca4f4440.png)

Going the other direction, from large window to smaller, results in similar symptoms to the image shown in #4508 (illustration purposes only, this issue is not directly SDL-related).

### Steps to reproduce the behavior

1. Start Wesnoth.
2. Go to Preferences -> Display.
3. Select a different display resolution.
4. Note that 1.17.6 and earlier redraws the screen at the new resolution and re-centres the preferences dialogue. 1.17.7 and later do not.

### Expected behavior

Same behaviour as before the change (1.17.6 release and earlier).

### Additional context

A git bisect reveals commit 29c82e308a44bf94303553f28fa30f32e4c33909 (between 1.17.6 and 1.17.7), part of @mesilliac's graphics work, seems to be the point at which the redraw behaviour breaks.

One work-around is to toggle to full-screen and back to window, forcing a redraw.

**Comment by irydacea** [comment]
This *appears* to be caused by an incorrect assumption about SDL events on Wesnoth's part.

In `sdl_event_handler::handle_event()` (src/gui/core/event/handler.cpp:444) `SDL_WINDOWEVENT_RESIZED` is handled correctly and translated into a `gui2::SDL_VIDEO_RESIZE`, which according to the [SDL documentation](https://wiki.libsdl.org/SDL2/SDL_WindowEventID) is always preceded by `SDL_WINDOWEVENT_SIZE_CHANGED`. The thing about the latter is that it is described as "followed by `SDL_WINDOWEVENT_RESIZED` if the size was changed by an external event, i.e. the user or the window manager". Apparently toggling fullscreen via `SDL_SetWindowFullscreen()` counts as an external event, but setting the game resolution via `SDL_SetWindowSize()` does not, therefore `SDL_WINDOWEVENT_RESIZED` is not signalled and GUI2 doesn't fire the `gui2::SDL_VIDEO_RESIZE` event that is supposed to trigger a re-layout of all windows.

A trivial fix is to translate both `SDL_WINDOWEVENT_RESIZED` and `SDL_WINDOWEVENT_SIZE_CHANGED` as `gui2::SDL_VIDEO_RESIZE`, however if the SDL 2 documentation is correct this would result in duplicate events of the latter type and a lot of wasted work re-laying out everything twice.

**Comment by irydacea** [comment]
Tentative patch demonstrating the trivial (bad) fix:

```diff
diff --git a/src/gui/core/event/handler.cpp b/src/gui/core/event/handler.cpp
index 64ff87c2c06..f6debf46001 100644
--- a/src/gui/core/event/handler.cpp
+++ b/src/gui/core/event/handler.cpp
@@ -441,6 +441,7 @@ void sdl_event_handler::handle_event(const SDL_Event& event)
 
                case SDL_WINDOWEVENT:
                        switch(event.window.event) {
+                               case SDL_WINDOWEVENT_SIZE_CHANGED:
                                case SDL_WINDOWEVENT_RESIZED:
                                        video_resize(video::game_canvas_size());
                                        break;
```

**Comment by Wedge009** [comment]
Thanks for the investigation. The reasoning makes sense to me based on my observation of current master behaviour. The addition of `SDL_WINDOWEVENT_SIZE_CHANGED` did not appear to have an adverse impact of drawing twice, but maybe that's because my PC is fast enough that I wouldn't notice the duplicate work anyway.

The only issue I found was that selecting the lowest entry in the screen resolution menu, the highest resolution available and I suppose should normally be the native resolution of the physical display, did not redraw the screen as expected. Perhaps the window being resized to maximum - without actually being a 'maximised' window - does not trigger `SDL_WINDOWEVENT_SIZE_CHANGED`. But overall, from a user point of view, this change seems like an improvement.

I grant most users probably aren't changing the window size this way too frequently anyway.

**Comment by irydacea** [comment]
Vultraz suggested a better fix that should do the trick.

> The only issue I found was that selecting the lowest entry in the screen resolution menu, the highest resolution available and I suppose should normally be the native resolution of the physical display, did not redraw the screen as expected.

You mean if the window resolution is already set to that same value? Pretty much all UI codepaths are designed to avoid potentially expensive side-effects (like the UI refresh) if a preferences value is changed from A to A again, turning it into a no-op.

(I seem to also be offered the option to select a resolution larger than the available screen area on Plasma desktop or macOS, doing that then breaks things horribly bad...)

**Comment by Wedge009** [comment]
Sorry, I meant selecting the highest resolution in the menu when on a smaller resolution.

Using the same change as #7639 I get something similar to the images I posted in the original report, but only when selecting the last option. I still think #7639 is an improvement overall and worth merging.

**Comment by irydacea** [comment]
What I personally get from picking a resolution higher than the largest window size the OS window manager will allow is more like Wesnoth rendering out of bounds and having the mouse cursor position go completely out of sync. I think there's a good chance we can't fix that other than detecting when Wesnoth's window size doesn't match our expectations following a resolution change (and maybe call SDL again and re-issue a resolution change back to its current size).

This ideally should be tracked as a different bug though, since its mechanism is completely different.

**Comment by Wedge009** [comment]
Yes, I think that's what I got as well - the native resolution is actually larger than what Wesnoth can use because of both window decorations as well as the shell task bar taking up some horizontal space.

That problem, however, does indeed appear to be something separate. For example, it's present in 1.16 as well.

Thanks for the work this particular issue. I retested in current master and it works well enough.
