### ISSUE TITLE
Dragon sprites look squished

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#7472]
### Game and System Information

- **Version:** 1.17.14
- **Downloaded from:** Steam
- **Build info:**
- **OS:** Windows 10

### Description of the bug

As you can see, their sprites look squished.

![skele d](https://user-images.githubusercontent.com/39015360/227042224-3b7542fa-f1b2-4e57-95d5-d103e366be20.PNG)
![fire dr](https://user-images.githubusercontent.com/39015360/227042230-bd12f46c-d628-4b3b-bfa2-dc2d6d4bc784.PNG)

### Steps to reproduce the behavior

Look at it.

### Expected behavior

Them not looking squished, like they do in 1.16.

**Comment by Wedge009** [comment]
Both unit images have padding on the bottom:
https://raw.githubusercontent.com/wesnoth/wesnoth/master/data/core/images/units/monsters/fire-dragon.png
https://raw.githubusercontent.com/wesnoth/wesnoth/master/data/core/images/units/monsters/skeletal-dragon/skeletal-dragon.png

The images haven't changed for five years. The unit definitions, too, are basically the same between 1.16 and master, aside from the portrait being converted from PNG to WebP.

I'm guessing there was a change between 1.16 and 1.17 in how unit images are displayed in the side-bar window. This contrasts with #7257 in that the Grand Knight unit definition crops the unit image to fit into that window (and wasn't updated to accommodate the larger image in a recent commit).

**Comment by Wedge009** [comment]
This issue was introduced with commit e379aeefe4b91f9bc4b0d254ecc20e13766caa25 (first released in 1.17.5) by @mesilliac. I think it just means we have to keep the square aspect ratio of the side-bar window for unit icons now. My #7473 will work around this for the two dragons but it's possible there may be other unit images distorted by this change, even to an imperceptible degree.
