### ISSUE TITLE
wmlxgettext: capture [achievement]description= as a hint for [achievement]name=

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7526]
### Describe the desired feature

Achievement's names can be cryptic clues, with the description explaining what they really are. For example, #7518's reference to a scenario name in:

```
[achievement]
    id="liberty_hunter"
    name=_"Perfect Hunter"
    description=_"Complete The Hunters with no losses"
```

It could be good for wmlxgettext to automatically include the description as a hint for the translators. Alternatively, we could decide that cryptic names should always have a manual `# po:` hint instead.

**Comment by Elvish-Hunter** [comment]
Probably the `#po:` hint is the best option, not just because it doesn't require updating wmlxgettext, but also because including the description may not be enough to understand cryptic or pop culture references; it's up to the author to explain them without assuming that everyone knows the English version of every book or movie.
