### ISSUE TITLE
WC: Improve dialogue when units join

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7718]
### Language

English

### Source

data/campaigns/World_Conquest/lua/game_mechanics/unittypedata.lua

### Original Text

When you find a unit in World Conquest, there's text based on the unit type. #7716 annotates these with po comments, and notes a few British slang phrases.

A few stood out:

### Drake Fighter

"The ancient spirits tell me my destiny lies with yours. My sword is at your command." is said by a Drake Fighter, with a war blade.

### Ulf

The text about finding an Ulf appears to be based on Native American phrases, possibly clear to `en_US` speakers. As a native `en_GB` speaker, I missed the references, and it came across as a jibe about the dwarf's height. If it's meant to be a reference, then the logic seems reversed - why would another dwarf use the generic form, but a human feel comfortable guessing a name?

* "Chin up, lads. Today is a good day to die!",
* If the speaker is another dwarf: "Brave words. Welcome to The Fight Club..."
* If the speaker is human: "Brave words. Welcome little big man."

### Horseman

This one's more a sanity check, but I just got a "is that a bit sexist?" feel when looking at it. If a female unit discovers a Cavalryman or Horseman, they respond to the rider with, "Of course. How could a girl say no to a man riding a horse?"

### Proposed Change

The Drake Fighter should say "blade". Not sure about the other ones.

**Comment by Wedge009** [comment]
Who wrote all this originally? I also had no idea about the alternate meaning of 'brave words' - I took the phrase literally.

And I suppose the thief's cockney accent is deliberate, I think it's stereotypical enough that it would make sense to en_US readers, but I'm not sure (since some notable British works have had to be 'localised' for American audiences).

I don't care to get too hung up on identity debates. And the text seems to be rather casual in nature. But given the medieval context of Wesnoth's setting, perhaps the cavalryman could be rephrased as a knight submitting himself in service to a lady.

**Comment by gfgtdf** [comment]
> Who wrote all this originally? I

I don't know but the wc2 credits say: `Prose, Grammatical and Text Assistance: TL, Natasiel, Rigor, tekelili` so so far our best  guess is one of those

**Comment by stevecotton** [comment]
It was already present in "World Conquest tek" 0.5.3.2.2, on the 1.10 add-ons server. Couldn't find it elsewhere.

**Comment by stevecotton** [comment]
For the Ulf lines in 1.17, my feeling is to leave the "Chin up, lads. Today is a good day to die!" and the dwarf-to-dwarf "Brave words. Welcome to The Fight Club..." as-is, but completely delete the human-to-dwarf response.
