### ISSUE TITLE
Broken map_file handling

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#7720]
https://github.com/wesnoth/wesnoth/blob/e1d84253dd9cd97ab4eaebb4ce9830abc9aa932c/src/saved_game.cpp#L478
This code assumes that map data can never contain the string "map_data". This is not true since you can name a location id something that contains that string.

I don't see why this hack needs to exist at all. You can just include a config file normally. There should be no need to interprete map_file as a config instead of map data. (If there is a need for this in the editor then don't abuse map_file for it. Make something new.)

**Comment by stevecotton** [comment]
I can't remember why, but when I was thinking about it, it seemed logical enough that I documented it rather than raising a bug.
https://github.com/wesnoth/wesnoth/blob/e1d84253dd9cd97ab4eaebb4ce9830abc9aa932c/data/core/editor/help.cfg#L392

**Comment by gfgtdf** [comment]
> This code assumes that map data can never contain the string "map_data". This is not true since you can name a location id something that contains that string.

I think the chances of someone ever running into i are pretty low, but i guess we can just check for `map_data=` instead of `map_data` since location ids cannot contain that character.


>  don't abuse map_file for it. Make something new

Using a different key depending on whether the map data contains additional metadata seems very unintuitive to me.

**Comment by Pentarctagon** [comment]
In my mind, this isn't map metadata or extradata - it's plain WML, and WML should be separate from the map data.

**Comment by soliton-** [comment]
> > This code assumes that map data can never contain the string "map_data". This is not true since you can name a location id something that contains that string.
> 
> I think the chances of someone ever running into i are pretty low, but i guess we can just check for `map_data=` instead of `map_data` since location ids cannot contain that character.

They sure can right now. See #7721. I don't see why we need to double down on the hack if we can just make a sensible design instead. I was certainly surprised to learn that what map_file points to can be anything but a plain file with the map data.

> > don't abuse map_file for it. Make something new
> 
> Using a different key depending on whether the map data contains additional metadata seems very unintuitive to me.

It seems very weird to me that you would call the actual map data and WML that contains a map_data key with that data the same thing. If they were the same thing the code would not have to guess which is which and handle them differently. Using the same key for both is what is counter-intuitive and introduces the need for hacks in the code.

If you want more data similar to location ids in the map data then extend the map data format. Making map files contain partial scenario data makes no sense. It's already trivial to include a config file wherever you want.

**Comment by soliton-** [comment]
Ok, so this needs to be fixed as well.
https://github.com/wesnoth/wesnoth/blob/e1d84253dd9cd97ab4eaebb4ce9830abc9aa932c/data/core/editor/help.cfg#L423
So far no one has done this in any uploaded addon at least. (Or if so they didn't call it .cfg)

**Comment by stevecotton** [comment]
> If you want more data similar to location ids in the map data then extend the map data format. Making map files contain partial scenario data makes no sense. It's already trivial to include a config file wherever you want.

Now I remember my reasoning from the previous discussion - if we make an extended map format containing the equivalent of `[time_area]` tags, then it seems likely that we'll end up using WML-style tags and the extended map format will end up looking like WML. I'd agree with a design that takes us to a different destination, but before we say "this shouldn't be WML", let's see what the alternative destination is.

**Comment by Pentarctagon** [comment]
That gets back to the same question though, doesn't it? Why would we need that in the map data in the first place? All the map data is supposed to do is describe the hexes that make up the map.

**Comment by soliton-** [comment]
I did not say whatever data should not be WML. Using WML is perfectly fine. Then pretending it's part of the map data which is clearly not WML is what is nonsense.

If for whatever reason the data really should be part of the map data. Perhaps because it is inherently tied to it and no matter where the map data is used that data must be there as well. Then it needs to be an actual part of the map data.

**Comment by Pentarctagon** [comment]
Right, I agree with you on that. The example given previously for [time_area] is what I don't like, since if you add existing WML features into a map header, then IMO essentially that ends up being just another way of having a scenario config with embedded map data rather than "map metadata".

**Comment by soliton-** [comment]
Right, I agree. I was responding to stevecotton anyway. You just posted very shortly before me.

**Comment by gfgtdf** [comment]
> I did not say whatever data should not be WML. Using WML is perfectly fine. Then pretending it's part of the map data which is clearly not WML is what is nonsense

You are only seeing this from the perspective of a person who is used to having a map_data and an editor that can only produce map_data and thus assumes the map_file corresponds to the map_data attribute. When a newcomer wants to start writing a scenario it's very natural to think map_file loads just whatever the editor produces (or can load) without having to know about the details about which file format it uses.


Furthermore you are using a theoretical bug that noone  will probably ever experience as an excuse to remove a feature that was 


> So far no one has done this in any uploaded addon at least


Well yes the scenario editor is still a bit clunky with things hidden inside random menus also people usually learn by copying existent stuff so new features will take a but to.e before being used. The plan was, that as soon. As the map editor always starts in

**Comment by Pentarctagon** [comment]
> When a newcomer wants to start writing a scenario it's very natural to think map_file loads just whatever the editor produces (or can load) without having to know about the details about which file format it uses.

It doesn't seem at all natural to assume that **map**_file could be used to load files that aren't maps.

It's also at odds with its lack of use by any add-on on the add-ons server at all, as well as [this poll](https://forums.wesnoth.org/viewtopic.php?t=53724) which pretty clearly indicates that the large majority of people don't even use the editor's scenario creation functionality in the first place. It's simply not a feature that's used.

**Comment by CelticMinstrel** [comment]
> i guess we can just check for `map_data=` instead of `map_data`

Not exactly. It would be a regex match on `map_data\s*=`, because there can be an arbitrary amount of space after the attribute name. (Possibly `[ \t]*`, I don't recall if `\s` includes newlines.)

**Comment by CelticMinstrel** [comment]
> I don't see why this hack needs to exist at all. You can just include a config file normally.

I thin gfgtdf mentioned earlier that including the config file normally gives undesirable behaviour with respect to side definitions, whereas the so-called "hack" means that side definitions in the map file and side definitions in the scenario file will be sensibly merged together.

> In my mind, this isn't map metadata or extradata - it's plain WML, and WML should be separate from the map data.

Time areas can _definitely_ be thought of as map metadata. They're literally giving a name to a set of locations – a simple extension of the location ID concept.

Most of the other stuff that appears in editor-produced scenario files is more arguable, but the fact remains that it is included in editor-produced scenario files and as gfgtdf says it's kind of nice to be able to just use an editor-produced file without caring which format it's in.

> It seems very weird to me that you would call the actual map data and WML that contains a map_data key with that data the same thing.

I do agree that the choice to format an editor scenario file as just the contents of a scenario tag with a map_data attribute is a little bit weird. But I don't think it's all that weird to want to bundle all that data into a single file, one way or another.

> I did not say whatever data should not be WML. Using WML is perfectly fine. Then pretending it's part of the map data which is clearly not WML is what is nonsense.
> 
> If for whatever reason the data really should be part of the map data. Perhaps because it is inherently tied to it and no matter where the map data is used that data must be there as well. Then it needs to be an actual part of the map data.

Although you do have a point that embedding something like a time area into the map data directly in a format specific to the map data makes a lot of sense, it does create a minor downside where we can represent the same information in two completely incompatible ways – as a `[time_area]` tag, or as whatever the format is in a map file. Removing the `[time_area]` tag is probably not an option, because there is support for adding them dynamically in the middle of a scenario.

Still, embedding it using the previously-obsoleted map header feature is just one possibility, and the current scenario-based format is just another possibility. You could come up with any number of other ideas. I do think that using WML one way or another is a good way to keep things simple, but it's not required – you could invent an entirely new super-complicated syntax for defining units directly in the map data, if you wanted. Although if you're intending to go that route it might actually be simpler to obsolete the current map file format and design something new from scratch. Maybe something where you alternate rows of "tiles" with rows of "metadata", for example.

> The example given previously for [time_area] is what I don't like, since if you add existing WML features into a map header, then IMO essentially that ends up being just another way of having a scenario config with embedded map data rather than "map metadata".

I think you could think of it as "map metadata in WML format". Using the same WML tags as what you'd put in a scenario file is technically unnecessary in context but does make parsing it easier, as you can just merge the map metadata into the scenario config – just like what map_file already does, in fact.

> It doesn't seem at all natural to assume that **map**_file could be used to load files that aren't maps.

I think the issue here is that you have a rather narrow definition of what constitutes a map.

I would argue that any scenario with no events in it could be called a map, whether it's produced by the scenario editor or hand-coded.

**Comment by Pentarctagon** [comment]
> I thin gfgtdf mentioned earlier that including the config file normally gives undesirable behaviour with respect to side definitions, whereas the so-called "hack" means that side definitions in the map file and side definitions in the scenario file will be sensibly merged together.

What situation would require that kind of functionality for side tags though? If it's because there are a bunch of attributes that don't exist in the editor's edit side dialog, then I'd say that the solution would really be to add them to the dialog.

> I think the issue here is that you have a rather narrow definition of what constitutes a map.
> 
> I would argue that any scenario with no events in it could be called a map, whether it's produced by the scenario editor or hand-coded.

My definition of a map is that it's the thing with the .map file extension :P

Scenarios are the things with the .cfg file extension which contains WML, lua, etc and references a map file.

**Comment by CelticMinstrel** [comment]
> What situation would require that kind of functionality for side tags though? If it's because there are a bunch of attributes that don't exist in the editor's edit side dialog, then I'd say that the solution would really be to add them to the dialog.

How about a situation where you want to use the same map for multiple scenarios, but with slightly different side settings?

> My definition of a map is that it's the thing with the .map file extension :P
> 
> Scenarios are the things with the .cfg file extension which contains WML, lua, etc and references a map file.

Then rename your editor-created scenario to be a .map if you care that much about a naming convention. It doesn't change that that's essentially what it is.

**Comment by doofus-01** [comment]
> How about a situation where you want to use the same map for multiple scenarios, but with slightly different side settings?

Edit the settings in some simple .cfg file that calls the map data file.  A macro, if necessary.  Like it's been done for years...

> Then rename your editor-created scenario to be a .map if you care that much about a naming convention. It doesn't change that that's essentially what it is.

How rude.  It does matter.  A clean map file can be pulled into some scenario part-way through, and it's intuitive to keep that data separate.  At least, it's intuitive to anyone looking at the files; someone clicking away in the editor won't care either way.

**Comment by Pentarctagon** [comment]
Yeah, I was thinking that would just be something defined in a macro. While admittedly that wouldn't have the same config merge functionality, I'm not sure when that would be needed - the side settings that are constant for the scenarios would be in the macro and the side settings that vary between the scenarios would be in each scenario file.

**Comment by CelticMinstrel** [comment]
> Edit the settings in some simple .cfg file that calls the map data file. A macro, if necessary. Like it's been done for years...

Well, doing that with `[+side]` probably does work, admittedly. It's definitely a bit nicer if the engine can do it for you in a sensible way, though – for example, if you only wanted to change side 7, it would be nice not to need 6 empty `[+side][/side]` above it.

> A clean map file can be pulled into some scenario part-way through, and it's intuitive to keep that data separate.

That's true, the map can be replaced at runtime, so most of the time it probably does make more sense for things like schedules and units to not be included in that data… tho the replace map tag could easily have keys to make it pull only part of the map data, instead of all of it. However, at least `[item]` and `[time_area]` still make sense to stay as part of the map data. An `[item]` is frequently used as special one-off scenery, after all – one that's _actually_ an item would still be added dynamically.

I still think it makes sense to _support_ putting units in the map data. I'd probably recommend not doing it most of the time, but I think there are times when it would be extremely useful to be able to place a bunch of units in the editor and just have them work when you apply that map to a scenario. I guess they could be done without requiring the sides themselves to be defined in the editor, if that helps. Units specified to belong to a side that's not defined, or with a type that's not defined, would probably just be dropped (with a warning) when loading in the map data.

> While admittedly that wouldn't have the same config merge functionality, I'm not sure when that would be needed

???

What? Why would it not be needed? Why would it not have the config merge functionality? What exactly do you envision this code would look like? See my first comment in this post.

**Comment by Pentarctagon** [comment]
> What? Why would it not be needed? Why would it not have the config merge functionality? What exactly do you envision this code would look like? See my first comment in this post.

Maybe I completely misunderstood, but wasn't there some difference between including via a macro vs via map_file?

**Comment by CelticMinstrel** [comment]
I haven't looked closely, but I think including via map_file is roughly equivalent to this:

```
{path/to/editor/generated/scenario.cfg}
[+side]
    # side 1 extras...
[/side]
[+side]
    # side 2 extras...
[/side]
# ...etc
```

(Or maybe it was in reverse, with the "extras" first and then it's as if the included file used `[+side]`.)

Which becomes like this with map_file:

```
map_file="path/to/editor/generated/scenario.cfg"
[side]
    # side 1 extras...
[/side]
[side]
    # side 2 extras...
[/side]
# ...etc
```

**Comment by Pentarctagon** [comment]
Right, so why would "side 1 extras", "side 2 extras", etc need the equivalent of [+side] rather than using a macro?

**Comment by CelticMinstrel** [comment]
Your macro approach needs one macro per side. My augmenting tags approach can define all the sides in a single macro. I don't think I can argue that either approach is better in general though. They both seem like a reasonable thing to want in some circumstance. That said, if sides are defined in data that's generated by the scenario editor, then my approach seems more viable.

**Comment by Pentarctagon** [comment]
True. The macro could instead have all the [+side] tags in it as well though, couldn't it? So like:
```
#define COMMON_SIDE_ATTRIBUTES
[+side]
    # side 1 extras...
[/side]
[+side]
    # side 2 extras...
[/side]
# ...etc
#enddef

[side]
    # side 1 extras...
[/side]
[side]
    # side 2 extras...
[/side]
# ...etc
{COMMON_SIDE_ATTRIBUTES}
```

**Comment by CelticMinstrel** [comment]
> The macro could instead have all the [+side] tags in it as well though, couldn't it?

Yes, that's a slight variation on the code that I posted. I'm not sure which order makes more sense.

**Comment by soliton-** [comment]
> You are only seeing this from the perspective of a person who is used to having a map_data and an editor that can only produce map_data and thus assumes the map_file corresponds to the map_data attribute. When a newcomer wants to start writing a scenario it's very natural to think map_file loads just whatever the editor produces (or can load) without having to know about the details about which file format it uses.

I absolutely disagree that an attribute called `map_file` leads anyone to think that it includes partial scenario config that is generated by the editor.

> Furthermore you are using a theoretical bug that noone will probably ever experience as an excuse to remove a feature that was added via a normal or, it you don't like it there are surely nicer ways to express you concern.

I cannot really parse that sentence. Are you saying I'm being rude because I call the quoted code a hack? It seems very difficult to call arbitrarily looking for a simple string anywhere in a file to detect if it's map data or WML (both structured data) anything else.

Also I don't mind the feature I mind how poorly it is implemented. If you want an attribute that points to an editor generated partial scenario config then add a new attribute with a name that better reflects that. There is no reason to piggyback on the formerly perfectly simple and understandable map_file. Sure a newcomer probably does not care but that does not mean that this is intuitive for anyone whether newcomer, UMC author or wesnoth code maintainer.

I find it unfortunate how little you seem to care about the interfaces we introduce. "It works most of the time" is at best acceptable when adding some workaround for a bug or something. IMO it is absolutely not useful to approach a new interface or changing an existing interface with that mindset. That leads to more and more technical debt and makes it so much harder to maintain and extend wesnoth.

**Comment by Pentarctagon** [comment]
For reference, the related issue is #4804 and PR is #4803.

**Comment by Pentarctagon** [comment]
> I cannot really parse that sentence. Are you saying I'm being rude because I call the quoted code a hack? It seems very difficult to call arbitrarily looking for a simple string anywhere in a file to detect if it's map data or WML (both structured data) anything else.

Admittedly, this is essentially what the editor currently does to determine what a file is via regex tests for `map_data=` and any of [scenario]/[multiplayer]/[test]/[tutorial]. In that case though, it needs to be done that way (not regex necessarily, but by checking for particular strings) since the editor can't handle a variety of things in case someone wants to load a map from a hand coded scenario.

**Comment by soliton-** [comment]
If the editor code does not correctly differentiate between valid map data and valid WML then it is bad as well.

If this is to decide what an unknown file that the user wants to open is then I can see why you actually need to detect the file format. (Something that is _not_ necessary for map_file since there is no need to use it for map and scenario data.)

There are plenty better ways than checking for particular strings though unless particular string here means a specific first line like "This is an editor generated file. Do NOT touch!" or something. There should be no need to search randomly in the file for a string or regex. You could go by extension for example. (I think .map or .mask is pretty consistently used?) Or you could simply try to load it as map data and see if you get an error.

**Comment by Pentarctagon** [comment]
The issue comes down to the editor attempting to find and load the map file when given a scenario file that it can't directly read into a config. The current logic essentially is:
* Use `R"""(map_data\s*=\s*"(.+?)")"""` to check whether a `map_data` attribute exists. If not, attempt to load it like it's a plain .map file.
* If `map_data` is found, use `R"""(\{(.+?)\})"""` to check if `map_data` references the map via file inclusion. If it appears to reference a file via inclusion, attempt to load the file it references as a plain .map file.
* If `map_data` doesn't appear to reference a file via inclusion, use `R"""(\[(scenario|test|multiplayer|tutorial)\])"""` to see if it contains any of those tags. If it does, then this is a hand coded scenario with embedded map data so attempt to read it that way. Else, attempt to load this as an editor-generated scenario.
* Loading a plain .map file from the `map_file` attribute is not supported.

With #7719, which is changing the editor-generated scenario format to have a top level [multiplayer] tag, it changes to:
* If the file extension is not .map or .cfg, error out.
* If the file extension is .map, then attempt to load it as a plain .map file.
* If it does not contain any of "multiplayer", "scenario", or, "test", then this is a scenario generated by the editor before the PR, so attempt to load it. [tutorial] is not checked since that shouldn't be used anymore.
* Attempt to find the `map_data` attribute by string search. If found and its value contains `{`, then this looks like file inclusion, so attempt to read that file as a plain .map. Else this is an embedded map, so attempt to read that string as the map's data.
* Else, attempt to find the `map_file` attribute by string search. If found, attempt to load the scenario. If loading the scenario fails, then attempt to find and load the referenced map as a plain .map file.

**Comment by soliton-** [comment]
So it seems to me all the regex string processing is done to support `map_data="{file.map}"`. I would remove support for that, map_file makes it obsolete. Then you can just load the scenario normally and check map_data/map_file. I also would support .mask besides .map. At least in mainline that is consistently used.

**Comment by Pentarctagon** [comment]
There are probably a large number of scenarios which still use that form. Though I suppose the answer is to just load the .map directly rather than selecting the scenario cfg to load the map.

**Comment by soliton-** [comment]
Since using `map_file` to include scenario config is now deprecated (use `include_file` instead) and will be removed eventually this can be closed.
