### ISSUE TITLE
Review the English text in GUI.pyw

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7724]
PR #7627 made the strings in GUI.pyw translatable, but didn't change the English text. The current text probably isn't clear enough for an English-speaking audience, at least not to a wide enough audience to be ready as an input to translation.

For example:

* "Ignore refcount 0 on names matching regexp", should probably be described as unused functions and variables, however I haven't reviewed what exactly it does.
* "Ignore files matching the specified regular expression", should say filenames.

I think we should review the entire text before adding `wesnoth-tools` to the stats on https://gettext.wesnoth.org/ , and we should warn the translators that it's still being revised in the 1.17.18 release announcement.

(The "Prose" tag doesn't quite fit, but it's the closest for "text that will need translation".)

**Comment by CelticMinstrel** [comment]
I don't think the prose label fits even slightly. Prose is a particular type of writing that is not present in the wesnoth-tools domain at all.

**Comment by Slayer95** [comment]
> Ignore refcount 0 on names matching regexp

That text doesn't actually exist in master anymore. It currently reads ``"Allow unused macros with names matching regexp:"``

> "Ignore files matching the specified regular expression", should say filenames.

Not sure whether that actually improves the readability in English, but a translator note would help.

**Comment by stevecotton** [comment]
We should apply the [UI Style Guide](https://wiki.wesnoth.org/UI_Style_Guide), for example dialog titles should be title case.

Placeholders in strings could be consistent. There's some using `{}`, and some using `{0}`. None are using named placeholders, but named placeholders would be consistent with our C++ and WML styles.

A lot of the strings seem to be strings from the individual tools, so maybe we need to translate them and then update the strings here.

These will need string changes (#7728 might work in English, but would need a translation hint)
* #7726
* #7727
* #7728 

Comments on strings:
```diff
+# Where is this displayed? If "open" is a verb, why is there an option in the program to open itself?
 #: data/tools/GUI.pyw:58
 msgid "Open a Graphical User Interface (GUI) to WML Tools"
 
+# What about the language? Why is this in caps?
 #: data/tools/GUI.pyw:59
 msgid "LANGUAGE"
 
+# More helpful would be to use the references that the translators are already looking at,
+# for example, to point to the list of languages on g.w.o., assuming that the languages that
+# use only two letters in their .po file names use the two_TWO format for this option.
 #. TRANSLATORS: ISO 15897 "Procedures for the registration of cultural elements" specifies use
 #. of underscores in the locale id. For example, use en_GB, not en-GB.
 #: data/tools/GUI.pyw:65
 msgid ""
 "Launch GUI.pyw in the given language. Language code must follow ISO 15897 (e."
 "g. en_GB)."
 
+# There's a "Select All" in wesnoth-lib, should this similarly be in title-case?
 #: data/tools/GUI.pyw:408
 msgid "Select all"
 
+# Is this "Select none"?
 #: data/tools/GUI.pyw:488 data/tools/GUI.pyw:527
 msgid "Clear"
 
+# Context? Might be geometry.
 #: data/tools/GUI.pyw:575 data/tools/GUI.pyw:944
 msgid "Normal"
 
+# This doesn't clarify what "normal" means, and the hint doesn't clarify what the msgid means.
 #. TRANSLATORS: Explanation for Normal.
 #: data/tools/GUI.pyw:583 data/tools/GUI.pyw:953
 msgid "Perform file conversion"
 
+# Makes sense knowing the tools, but wouldn't without knowing the tools.
 #. TRANSLATORS: Explanation for Revert.
 #: data/tools/GUI.pyw:627
 msgid "Revert conversions using *.bak files"
 
+# Why does the list change? Presumably a verbosity level...
 #: data/tools/GUI.pyw:643
 msgid "List changes"
 
+# Meaning what?
 #: data/tools/GUI.pyw:651
 msgid "Name files before processing"
 
+# Might make sense if it's a verbosity level, otherwise "show logfile details" would be better but still not right.
 #: data/tools/GUI.pyw:659
 msgid "Show parse details"
 
+# "Options for wmllint" would be clearer
 #: data/tools/GUI.pyw:667
 msgid "wmllint options"
 
+# "duplicate inclusions of resource files"? Or scan for images that are duplicates?
 #: data/tools/GUI.pyw:748
 msgid "Check for duplicate resource files"
 
+# Meaning what?
 #: data/tools/GUI.pyw:756
 msgid "Make definition list"
 
+# ... and put it where?
 #: data/tools/GUI.pyw:780
 msgid "Extract help from macro definition comments"
 
+# Where should a non-programmer look up what their language's standard translation of "untyped formals" is?
 #: data/tools/GUI.pyw:788
 msgid "Report all macros with untyped formals"
 
+# Where should a non-programmer look up what their language's standard translation of "regexp" is?
 #: data/tools/GUI.pyw:813
 msgid "Exclude files matching regexp:"
 
+# Should "n" be translated as "standard way for indicating a number in a box that's placed on the right of this"?
+# Shoutout to the Arabic translator that we remember RTL languages, but it probably won't be supported in GUI.pyw.
 #: data/tools/GUI.pyw:847
 msgid ""
 "Report only on macros referenced\n"
 "in exactly n files:"
 
+# This is a label, but it's missing the ":" that its neighbours have (and that the UI Style Guide requires)
 #: data/tools/GUI.pyw:866
 msgid "Report macro definitions and usages in file"
 
+# Hint means what to a non-programmer?
 #. TRANSLATORS: regexp is "regular expression".
 #: data/tools/GUI.pyw:884
 msgid "Allow unused macros with names matching regexp:"
 
+# What's the purpose of running the tool then?
 #: data/tools/GUI.pyw:1019
 msgid "Do not generate output"
 
+# "exist", no "s" on the end
 #: data/tools/GUI.pyw:1302 data/tools/GUI.pyw:1368 data/tools/GUI.pyw:1403
 #: data/tools/GUI.pyw:1427
 msgid "The selected directory does not exists"
 
+# Could leave the "You" out of several of these messages. Just "No directory selected.\n..." would say the same.
+# Could be "no directory selected". Could also merge with the wmlscope version, if it said "No directory selected.\n\nThe tool will only be run on the Wesnoth core directory.".
+# Not for wmllint, but the GUI for some tools has both "Directory" and "Output dir", and those messages should probably clarify which one.
+# Given that wmllint currently makes lots of changes in mainline (issue #5799), this dialog should have a "Cancel" button (feature request #7728). In English this string still works, but the translation hint should talk about the button.
 #: data/tools/GUI.pyw:1298
 msgid ""
 "You didn't select a directory.\n"
 "\n"
 "wmllint will be run only on the Wesnoth core directory"
 
+# Unclear what this means
 #: data/tools/GUI.pyw:1433
 msgid "Overwrite confirmation"
 
+# So why not use {filename} instead? Some messages are using {0}, let's have a coding style; my preference would be named placeholders.
 #. TRANSLATORS: {} is a placeholder for a file name, and not meant to be modified.
 #: data/tools/GUI.pyw:1435
 msgid ""
 "File {} already exists.\n"
 "Do you want to overwrite it?"
 
+# Is "tools" part of a proper noun, and if it is, why isn't it capitalised?
+#
+# This appears in a TkInter "showinfo" message box, and the title is too long for the
+# titlebar (the size seems to be based on the line-length of the message).
 #: data/tools/GUI.pyw:1505
 msgid "About Maintenance tools GUI"
 
+# "Elvish_Hunter" is a name, and he's still about so why are we only saying 2014-2016?
+# Is there a standard translation of the Tango attribution somewhere on Tango's website?
 #. TRANSLATORS: {} is a placeholder for Wesnoth's current version, and not meant to be modified.
 #: data/tools/GUI.pyw:1507
 msgid ""
 "© Elvish_Hunter, 2014-2016\n"
 "\n"
 "Version: {}\n"
 "\n"
 "Part of The Battle for Wesnoth project and released under the GNU GPL v2 "
 "license\n"
 "\n"
 "Icons are taken from the Tango Desktop Project (http://tango.freedesktop."
 "org), and are released in the Public Domain"
 
+# This is the title of a dialog box. Commenting that would be helpful, but it should also be in title case.
 #: data/tools/GUI.pyw:1519
 msgid "Exit confirmation"
```

**Comment by Pentarctagon** [comment]
So, it's too late to come back to this now, but I assume a review didn't end up happening so far?

**Comment by Wedge009** [comment]
If there is still time, I can try to review if someone can point me to what I should be looking at. Is it the `GUI.pyw` file or a po file somewhere?

**Comment by stevecotton** [comment]
@Wedge009 GUI.pyw is meant to be a GUI wrapper that helps UMC authors use the tools. There's a few different target audiences to consider; I'd suggest you start at one of these two points:
* A UMC author, for which the best start is probably to choose an existing UMC, run the tool, and try to use the tools on that UMC.
* A translator, for which the best start is probably to take the .po file and see if you can understand the text with only the context that the .po gives you.

**Comment by Wedge009** [comment]
I only just realised wesnoth-tools was added a few months ago but I never reviewed anything for en_GB because it was already marked as 100% localised, I suppose that's why this issue was lodged in the first place. (Can we avoid that in the future? Assuming that the source text is 'good enough' for en_GB, I mean. I'm pretty sure I did a full review of other new domains like WoF.)

> Where is this displayed? If "open" is a verb, why is there an option in the program to open itself?

`argparse` description. It's only displayed when running `./GUI.pyw --help`.

> What about the language? Why is this in caps?

Command-line explanation: `--lang=LANGUAGE`

> More helpful would be to use the references that the translators are already looking at, for example, to point to the list of languages on g.w.o., assuming that the languages that use only two letters in their .po file names use the two_TWO format for this option.

In #7870, soliton explained to me that Wesnoth uses POSIX locale names. Apparently ISO 15897 is the actual standard for POSIX locales, but I'm sure most people wouldn't know that automatically - maybe clearer just to state POSIX locale names here as well?

> There's a "Select All" in wesnoth-lib, should this similarly be in title-case?

This is from the context menu.
![image](https://github.com/wesnoth/wesnoth/assets/13679322/12525dc2-d3b9-487a-9b1f-3e5880866da2)

The cited style guide states menus should use title case. For reference, Firefox has 'Select All' in its context menu.

> Is this "Select none"?

Clear button for clearing the directory text box.

> Why does the list change? Presumably a verbosity level...

I understand the difficulty in comprehension without context. List is a verb here, perhaps 'show changes' is better. I don't really know what the other verbosity levels mean either so perhaps someone like @cooljeanius who is familiar with using these tools can suggest improvements.

> Options for wmllint" would be clearer

Actually, I prefer the text as-is - it makes more sense when you see it in the GUI.

> Where should a non-programmer look up what their language's standard translation of "untyped formals" is?

This sounds like something specific to WML rather than a general programmer term. I don't know what an 'untyped formal' is.

> Hint means what to a non-programmer?

I would replace 'regexp' with the full term - abbreviations in UI text is generally not a good idea, in my opinion. As for the term itself, even for a non-programmer I think it's okay to translate it directly. eg Even though I'm not a native Francophone, _expression régulière_ makes sense to me and I think that's what they use in the literature.

> my preference would be named placeholders

As a relatively new Python developer (only a couple of years) I prefer new-style f-strings which intrinsically includes named parameters. But I think this may cause confusion for translators - even with translation notes - and they could try to translate the parameter name inside the braces which would break the code. So probably better to stick with numeric string replacement - or just `{}` if only one replacement is being made.

> why are we only saying 2014-2016?

I'm not really sure why end dates need to be there in the first place. I notice the copyright notices for every C++ file gets updated every year because of this. Is it a requirement for copyright statements?

I've put my review in #7971. Because I don't know what all the options mean (in order to rephrase them better), it's not a complete review.

**Comment by Wedge009** [comment]
Option strings that may need further review because I don't fully understand what they mean:

`wmllint`:
<img width="575" alt="image" src="https://github.com/wesnoth/wesnoth/assets/13679322/9ab67742-a663-403e-9804-7714b7c1052a">

`wmlscope`:
<img width="766" alt="image" src="https://github.com/wesnoth/wesnoth/assets/13679322/21ec0cf3-e66f-4cf7-9bfa-0436f0d12e43">

`wmlindent`:
<img width="583" alt="image" src="https://github.com/wesnoth/wesnoth/assets/13679322/92bdd402-9e52-49cd-bedd-21d737b4cb9c">

`wmlxgettext`:
<img width="510" alt="image" src="https://github.com/wesnoth/wesnoth/assets/13679322/9e78fdbb-4eee-488a-8d22-6c1866411176">

**Comment by Wedge009** [comment]
> > "Ignore files matching the specified regular expression", should say filenames.
> 
> Not sure whether that actually improves the readability in English, but a translator note would help.

I only just noticed this. In English, 'file name' refers to the name of the file while 'file' would refer to the file object on disk. I'll update this in my PR as the difference is meaningful.

**Comment by Pentarctagon** [comment]
The options seems generally fine? At least in the sense that for some of them there's not really any way around needing to understand what they're talking about. Like for "Convert EOL characters to Unix format" you could maybe spell out "end of line" instead of using EOL, but there isn't really a clearer way to word it that would also fit on a single line.

**Comment by Wedge009** [comment]
I added translation note for EOL in #7971 in case that's not already known. But more broadly, I don't really know what some of the explanations mean without knowing more about what the tools do. But if there's no further information on what the options are supposed to do, then I suppose that PR can be merged as-is.

**Comment by cooljeanius** [comment]
> > Why does the list change? Presumably a verbosity level...
> 
> I understand the difficulty in comprehension without context. List is a verb here, perhaps 'show changes' is better. I don't really know what the other verbosity levels mean either so perhaps someone like @cooljeanius who is familiar with using these tools can suggest improvements.

Oh I actually don't use `GUI.pyw`; I just use all the tools for which it provides an interface from the command-line instead... maybe @Elvish-Hunter would be better to ask?

**Comment by Wedge009** [comment]
Someone with knowledge of the tools could still provide some feedback on the description of the options. (:

**Comment by CelticMinstrel** [comment]
> I prefer new-style f-strings

I would say these are a total translation nightmare and should never, ever be used for translatable strings. They interpolate arbitrary code into the string. You should use either `string.format` or the `%` operator for anything translatable. Both of these can also be automatically checked by gettext tools to ensure the translation didn't break the formatting arguments.

> I don't know what an 'untyped formal' is.

I don't understand the derivation of the term, but I do know what it refers to. This is about macro arguments, which wmlscope attempts to guess the type of based on the name. For some reason, it seems to refer to the arguments as "formals", so an "untyped formal" would be one where it can't guess the type.

> I would replace 'regexp' with the full term - abbreviations in UI text is generally not a good idea, in my opinion. As for the term itself, even for a non-programmer I think it's okay to translate it directly. eg Even though I'm not a native Francophone, _expression régulière_ makes sense to me and I think that's what they use in the literature.

I don't particularly mind expanding "regex(p)" to "regular expression", but it _is_ technically inaccurate to do so, as regex is technically _not_ a regular expression (unless you're using GNU basic regex, which almost no-one does these days). I don't think it's all that uncommon to use the abbreviation, but I may be biased. I've also seen some tools call it "grep", even if it's not technically using the grep tool.

> Option strings that may need further review because I don't fully understand what they all mean:

Are you saying all the option strings in those screenshots need review, or pointing out specific ones? Looking over them, I think most of them are fairly well-explained, though there's probably room for improvement. I don't have any specific suggestions though. The only string I think seems questionable is the "Normal" option for wmllint and wmlindent mode. It _might_ be okay since it's presented alongside the alternatives, but I'm not sure.

**Comment by Wedge009** [comment]
> I would say these are a total translation nightmare and should never, ever be used for translatable strings. They interpolate arbitrary code into the string. You should use either `string.format` or the `%` operator for anything translatable. Both of these can also be automatically checked by gettext tools to ensure the translation didn't break the formatting arguments.

Yes, after I wrote that, I saw the general consensus for anything to be used with `gettext` seems to be to stick with `str.format()`. But for general text, my preference stands (otherwise I expect f-strings would have never been developed in the first place).

> I don't particularly mind expanding "regex(p)" to "regular expression", but it _is_ technically inaccurate to do so, as regex is technically _not_ a regular expression (unless you're using GNU basic regex, which almost no-one does these days).

I expanded to 'regular expression' in #7971, which seems to make sense to me in the context of this tool. Are you saying it should remain as 'regexp'?

> Are you saying all the option strings in those screenshots need review, or pointing out specific ones? Looking over them, I think most of them are fairly well-explained, though there's probably room for improvement.

The question was asked in the context of steve apparently saying that the strings in the wml-tools po file - at least read in isolation - may not necessarily be easy to fully comprehend the meaning of, and therefore may cause troubles for translators (hence this issue).

**Comment by CelticMinstrel** [comment]
> But for general text, my preference stands (otherwise I expect f-strings would have never been developed in the first place).

For anything that's not translatable, I agree that f-strings are nicer, yes.

> I expanded to 'regular expression' in #7971, which seems to make sense to me in the context of this tool. Are you saying it should remain as 'regexp'?

This isn't something that I think is definite one way or the other. The term "regular" is a technical term that refers to a specific type of language. The original "basic regex" used by grep satisfies the definition of a regular language, which is where it gets the name "regex" or "regular expression" from, but modern regex does _not_ satisfy the definition of a regular language. For that reason, I prefer to use the abbreviated name (without the P; I just think it sounds better) instead of expanding it into "regular expression". But that's just my opinion, from the perspective of someone who has _actually studied_ computer science, or in other words, not really the primary target audience for this tool. I don't know which is better for someone with less experience who just wants the tool to run.

> The question was asked in the context of steve apparently saying that the strings in the wml-tools po file - at least read in isolation - may not necessarily be easy to fully comprehend the meaning of, and therefore may cause troubles for translators (hence this issue).

I that context, "Normal" is definitely a problem. Possibly also "Clean", "Diff", and "Revert", not sure. I don't see any other _obvious_ issues with those strings but I am viewing them in context so I could be a little biased.
