### ISSUE TITLE
1.18 Elevation decision

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#7729]
### Game and System Information

- **Version: 1.17.18+**
- **Downloaded from: github**
- **Build info: 3e494faaeba**
- **OS: Linux**

### Description of the bug

#6927 and #6975 introduced elevation, which is currently only a cosmetic aspect.  There is just a higher/lower distinction, no visual difference between High->Low versus Flat->Low.  As long as this is merely decoration, it does not matter much.  But if we want to have a standardized way of making this affect game-play, this has to change.

Making the transition images go beyond higher/lower will cause the required rules & graphics to explode.  Probably a good task for Generative AI, but that's not an option right now.  If we want to punt until 1.20, it might be an option.

If we do want to make elevation more than just a cosmetic aspect, I can come up with some indicator to the player that there is more than +/- 1 jump, such as an extra shadow on the west side.

This issue is basically a question on whether this elevation stuff needs to be ready for Prime Time in BfW 1.18, or whether it can be a mere cosmetic detail, basically as it is.

### Steps to reproduce the behavior

n/a

### Expected behavior

n/a

### Additional context

This is an example of different transitions that would be needed to take levels into account, just the default graphics without corners or new rules. 
![Screenshot_20230618_](https://github.com/wesnoth/wesnoth/assets/13510196/dcd5b5d8-6688-4960-91fd-9d0e76d1df92)

**Comment by Pentarctagon** [comment]
I would say it's probably fine for it to be just a cosmetic aspect for 1.18. Having the full engine-level implementation ready would definitely be nice, not IMO not a requirement.

For the engine level changes, we also need to determine the ways in which is would be allowed to affect gameplay - there's visual indicators of the relative elevation difference and a way to access that information via WML/lua would definitely be needed, but also if there's anything else.

**Comment by CelticMinstrel** [comment]
When we do an engine level change, I think the elevation markers should not be overlays anymore – elevation could instead be a separate piece of data associated with every tile.

**Comment by doofus-01** [comment]
All right.  For now I will try to document what there is and this will be part of it.

> elevation could instead be a separate piece of data associated with every tile.

Well, yeah, of course.

>  people who want to do the extra work can still get mechanical effects out of it.

We will, thank you.  https://forums.wesnoth.org/viewtopic.php?p=682219

**Comment by knyghtmare** [comment]
For now, cosmetic is "okay"...
For gameplay, I think adding +/- 5% DEF per layer of elevation would be something.
I say **5%** because taking 10% raw would make the outermost ones have a 40% difference which is very...disruptive.
***
| deeper | deep | Normal | high | higher |
| ------  | -----  | ------ | ----- | ------- |
| -10% | -5% | 0% | +5% | +10% |

***
Also, you're bringing this up now, but some UMC authors have already started using elevation terrain in their maps on the assumption that it's purely cosmetic, so this might cause breakage/disruption. I suggest contacting them to notify that their maps might need to be adjusted (this includes the mainline candidate campaign: Eastern Invasion Revised)

**Comment by Hejnewar** [comment]
> When we do an engine level change, I think the elevation markers should not be overlays anymore – elevation could instead be a separate piece of data associated with every tile.

Honestly this alone is big enough issue for me to be a blocker. Simply not being able to place anything on / in the places make them nearly useless / siituational imo because I cant put villages there. For example I cant put villages there without breaking elevation because villages are overlays etc. 

There is absolutley no need to introduce any gameplay function for them, beyond maybe movement one at some point, or even better only for specific terrains. KISS.

**Comment by CelticMinstrel** [comment]
> For example I cant put villages there without breaking elevation because villages are overlays (without using markers that not always do what I want spilling all over the place) etc.

You could always make a custom village terrain that's not an overlay if you really need to put a village at the edge of a cliff.

**Comment by Pentarctagon** [comment]
It would be nice to allow UMC to implement elevation related gameplay elements. By default though it probably shouldn't have any effect like that.

**Comment by doofus-01** [comment]
> Honestly this alone is big enough issue for me to be a blocker. Simply not being able to place anything on / in the places make them nearly useless / siituational imo because I cant put villages there.

Just for the record
![Screenshot_20230619_](https://github.com/wesnoth/wesnoth/assets/13510196/5c3cd715-d050-49cb-b69a-0b2ae48c0a11)

**Comment by doofus-01** [comment]
Question answered
