### ISSUE TITLE
[Bug] Planning mode was not activated at MP game start with enabled corresponding setting

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#7820]
### Game and System Information

- **Version:** 1.16.9
- **Downloaded from:** Steam
- **OS:** Ubuntu 18

### Description of the bug

When every MP game starts, I have disabled planning mode and manually turn it on every time.
Setting "Enable planning mode on start" is checked.

This started at 1.16.9 probably.

### Steps to reproduce the behavior

1. Check "Enable planning mode on start".
2. Join to MP game Isar's Cross (hosted by bot IsarFoundation).
3. After game starts, planning mode would not be active.

### Expected behavior

Planning mode is active at game start.

**Comment by gfgtdf** [comment]
Whats happening is that the code that should set whiteboard active is somehow blocked by https://github.com/wesnoth/wesnoth/commit/0eae27a474f44c6f0eb8715fa840a43ae3193919 , i am currently unsure why it calls `can_modify_game_state` since just activating the whiteboard shouldn't really change the gamestate.

**Comment by gfgtdf** [comment]
Reopen for 1.16 backport
