### ISSUE TITLE
Check that mainline campaigns are present

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#7875]
On starting Wesnoth, it should check that all mainline campaigns are present and show a popup listing any that are missing with general instructions for how Linux users can get them installed as well as state that any add-ons which depend on a missing campaign will not work. This:
* Helps players who accidentally install the wrong package on Linux distros that package campaigns separately from the base game.
* Helps ensure that add-ons can rely on the mainline campaigns being present, if they decide to use content from them.

The popup should have a "don't show this again" option for players who do intentionally install only the base game and individual mainline campaigns.

**Comment by gfgtdf** [comment]
While it might be technically true that they "accidentally installed the wrong package" I want to point out that afaik installing wesnoth from the Ubuntu Software center (or however it's called) installs the package without the campaigns. And people who install it from there might now want to bother with install8things via commandline.

**Comment by Pentarctagon** [comment]
It would be good if someone could confirm that the Ubuntu Software Center does that. If it does then we should open a bug with them to make it install the full set of packages, and if they're intentionally doing that then frankly I'd prefer they don't package Wesnoth at all. If someone installs Wesnoth and all they see are a tutorial, then IMO that's actively detrimental to Wesnoth since it makes it look like an empty game and will give everyone who installs it that way a negative impression.

**Comment by gfgtdf** [comment]
For example:

https://forums.wesnoth.org/viewtopic.php?p=681557&hilit=Ubuntu+Software#p681557

Although this was some time ago and there is a chance that it was fixed. also I'm pretty sure that we had this discussion already at some point.

**Comment by Pentarctagon** [comment]
Yeah, that does sound familiar now that you mention it.

**Comment by Wedge009** [comment]
I prefer to control packages directly myself so I don't use tools like the Software Centre. I think the KDE equivalent is Discover and I was troubled to find the 'Show dependencies' link seems to indicate that it's only installing the `wesnoth-1.16-core` package instead of the `wesnoth` meta-package.
<img width="1940" alt="image" src="https://github.com/wesnoth/wesnoth/assets/13679322/733c3474-241c-477c-ab3d-2d2195a5ad74">

On that same Discover page for Wesnoth, there's a review dated July 2022 that states 'But except tutorial there are no campaigns at all'.

This seems like an issue with the software sources used by the front-end rather than with Discover itself (since presumably the same source is used for the Software Centre in GNOME).

---

As for the enhancement itself, I think the check might be better suited for the campaign selection dialogue when it's getting the campaign details from the engine:
https://github.com/wesnoth/wesnoth/blob/2630b5bb630fd20cdc3f9fe98292781381798178/src/gui/dialogs/campaign_selection.cpp#L316
I tried to find where `create_engine` gets all the information from but giving up for now - it makes sense to me that wherever it's reading from the `data/campaigns/` directory, that's where it should check if it has more than just the tutorial campaign.

How would such a check know what campaigns to expect, though? It wouldn't make sense to me to keep some sort of fixed list as that would need to be kept synchronised with the contents of the campaigns directory. And that would be cumbersome.

**Comment by Pentarctagon** [comment]
I think that checking if there's more than one campaign would be reasonable.

**Comment by CelticMinstrel** [comment]
> I tried to find where `create_engine` gets all the information from but giving up for now - it makes sense to me that wherever it's reading from the `data/campaigns/` directory, that's where it should check if it has more than just the tutorial campaign.

I don't think this approach actually works, as "reading from the `data/campaigns/` directory" is right in the middle of the WML preprocessor run and thus not a place where we can easily inject arbitrary code. Probably the check would have to be completely independent of the actual WML load.

Alternatively, if campaigns were loaded "as if" the campaigns directory were a secondary add-ons directory, that might also work. It's a much bigger change though.

By the way, if I'm not mistaken, the `create_engine_` is literally just iterating through the loaded game config WML to find all the `[campaign]` tags. I'm not sure if those tags have injected data that identifies them as mainline campaigns though. For add-ons I believe the game injects the add-on name at some point during the load process, but there is no add-on name for mainline.

**Comment by stevecotton** [comment]
Instead of a pop-up dialog, I suggest a fake campaign which is ranked to appear just below the tutorial, if it appears at all. This way it won't annoy a player until they've played the tutorial, and it'll always be there when they're later wondering about missing campaigns, or when they've added add-on campaigns that depend on the mainline ones.

This mock-up was done before I saw your new wording:
![image](https://github.com/wesnoth/wesnoth/assets/101462/5668c3e7-05dc-4384-970f-5e41ddb07c36)

**Comment by Pentarctagon** [comment]
I don't think it makes sense to show the error only after someone has played the tutorial - I expect many players would open the campaigns dialog, see there's no content, close Wesnoth, and go do something else.

**Comment by stevecotton** [comment]
That fake campaign would be in the campaign list when they first open it, so they see there's a "missing campaigns" tab that they can click on as soon as they see the list.

**Comment by Wedge009** [comment]
I think a user would still be able to try the tutorial even with the pop-up, though this fake campaign message might seem more elegant. Just wondering about the 15 value, if it's hard-coded. On the other hand, the number of scenarios in a campaign's introduction text is hard-coded as well, I think. I suppose the 'more than' phrasing helps, although the number of official campaigns goes down on occasion too.

**Comment by stevecotton** [comment]
I'm thinking that "more than 15" would be accurate enough for a rarely-seen error message, but wouldn't break the translations if the actual number changes. The number is a little ambiguous anyway, we currently have 19 mainline campaigns, but that includes the tutorial and multiplayer-only World Conquest.
