### ISSUE TITLE
[remove_unit_overlay] issue

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#7896]
https://github.com/wesnoth/wesnoth/commit/b2cd1cf made [remove_unit_overlay] use an object_id key and unlike [unit_overlay] does not fall back to "overlay_" + image. At least the UNMAKE_HERO macro uses  [remove_unit_overlay] without object_id.

I've added minimal documentation of object_id to the wiki but this does not look like it all fits together...

It seems [unit_overlay] and [remove_unit_overlay] are kinda deprecated?

**Comment by CelticMinstrel** [comment]
If they are deprecated then I guess they should emit a deprecation message? And `[remove_unit_overlay]` should probably have the same fallback as `[unit_overlay]`.

**Comment by soliton-** [comment]
Would be good to hear thoughts from @stevecotton and @gfgtdf on this.

**Comment by gfgtdf** [comment]
When looking a at this code im a bit worried that multiple uses of [unit_overlay] and [remove_unit_overlay] clutter a units wml with useless objects (that cancel each other out, but the objects are still stored in the unit)

Since the (UN)MAKE_HERO macros already use an objects for the ellipse, it probably makes sense if the just added the overlay= effect to he object.

also i wonder whether UNMAKE_HERO should just remove the object added via MAKE_HERO

**Comment by CelticMinstrel** [comment]
> When looking a at this code im a bit worried that multiple uses of [unit_overlay] and [remove_unit_overlay] clutter a units wml with useless objects (that cancel each other out, but the objects are still stored in the unit)

I would say that both `[unit_overlay]` and `[remove_unit_overlay]` should be "smart" and either remove or add an object to get the desired effect. That is, if there's an object that does nothing but add the overlay, `[remove_unit_overlay]` should remove that object. Otherwise, it should add an object that removes the overlay. Similarly, if there is an object that does nothing but remove the overlay, `[unit_overlay]` should remove that object. Otherwise, it should add an object that adds the overlay.

> Since the (UN)MAKE_HERO macros already use an objects for the ellipse, it probably makes sense if the just added the overlay= effect to he object.

I don't think it makes sense to mix overlays into (UN)MAKE_HERO.

> also i wonder whether UNMAKE_HERO should just remove the object added via MAKE_HERO

Yes, it should.

**Comment by gfgtdf** [comment]
> I don't think it makes sense to mix overlays into (UN)MAKE_HERO.

?, Adding the heo overlay is exactly what MAKE_HERO currently does.

**Comment by CelticMinstrel** [comment]
> ?, Adding the heo overlay is exactly what MAKE_HERO currently does.

Adding the _hero_ overlay, yes. Other overlays shouldn't be mixed in with that.

**Comment by gfgtdf** [comment]
> Adding the hero overlay, yes. Other overlays shouldn't be mixed in with that.

I never talked about other overlays, i'm just talking about the implementation of (UN)MAKE_HERO.

**Comment by Pentarctagon** [comment]
Why is this a new stable blocker?

**Comment by soliton-** [comment]
Because it should be resolved before the release. The current situation makes little sense.

I suppose at a minimum `[remove_unit_overlay]` should work the same as `[unit_overlay]`. Though that is a bit moot if the actual goal is to deprecate them. I don't know the plan that is why I asked.

**Comment by Pentarctagon** [comment]
@stevecotton can you answer that?

**Comment by stevecotton** [comment]
I'm trying to work out why `[remove_unit_overlay]` needs an id, and currently the only reason I can think of is that WML wants to remove the object later; doing this would have the effect of temporarily hiding the overlay, but when the object gets removed the overlay comes back.

I agree with the argument that automatically generating an id would be consistent with `[unit_overlay]`, but I'm not sure why we'd really want the object to have an id, except in the case that WML wants to use it (in which case, it will probably provide its own id).

**Comment by stevecotton** [comment]
@soliton- did you see any reason why it should need an id? Is the issue just that the two methods seem inconsistent?

**Comment by soliton-** [comment]
I don't understand why it makes sense to have a default id with `[unit_overlay]` but not with `[remove_unit_overlay]`. Either it makes sense for both or none?

According to 5442d92 the reason for the default id is to be able to remove the objects. Presumably to avoid piling up a lot of useless objects. That commit just added the default to `[unit_overlay]` though.

**Comment by stevecotton** [comment]
Because having an overlay suggests that a unit is special in some way, and removing an overlay suggests that whatever caused that has ended. For example, a dehydration mechanic where, at the start of the turn, every unit that's stood on a water hex has the overlay removed; and then all units that still have that overlay take damage.

However, once the overlay has been removed, what's the difference between that unit and other units which never had the overlay? Having an id for `[remove_unit_overlay]` suggests that someone would code "if the unit previously had this overlay, remove the object that hid the overlay" rather that just "if the unit doesn't have this overlay, add it".

**Comment by soliton-** [comment]
> Having an id for `[remove_unit_overlay]` suggests that someone would code "if the unit previously had this overlay, remove the object that hid the overlay" rather that just "if the unit doesn't have this overlay, add it".

Do you mean having a default for the id suggests that? Because `object_id` exists already. What you mentioned there can already be done. (I don't know why that commit says it adds `object_id` since it clearly doesn't.)

AFAICT what having a default for the id changes is the ability to interact with overlay use that is not under your control. So if some code you cannot change uses `[unit_overlay]` without `object_id` you can still use `[remove_object]` to undo that. If similar code uses `[remove_unit_overlay]` without `object_id` then currently you cannot undo it. If the code is under your control then you can set `object_id` in either tag and do whatever you want regardless of the default.

**Comment by CelticMinstrel** [comment]
I think you could argue that there's a use-case for temporarily removing the overlay – apply an object that removes the overlay, then remove the object later on.

**Comment by stevecotton** [comment]
Temporarily removing an overlay for a turn or for a scenario could be done by using `duration=`, doing it for a single event's animation could be just a `[store_unit]` and overwrite afterwards. That doesn't cover everything, but I think the remaining cases are likely to be as easy to handle by storing a list of unit ids, and applying new `[unit_overlay]`s rather than removing a `[remove_unit_overlay]`.

@soliton- the main thing I'm saying is "why would anyone use that?". What code will want to undo the removal of an overlay, yet not know enough about that overlay to just put a new one on the unit?

**Comment by gfgtdf** [comment]
i actualy don't really rememerb the rationale for my last commit 

> I don't understand why it makes sense to have a default id with `[unit_overlay]` but not with `[remove_unit_overlay]`. Either it makes sense for both or none?
> 
> According to [5442d92](https://github.com/wesnoth/wesnoth/commit/5442d922c464caf0eb65e28f8bac937cadec99a2) the reason for the default id is to be able to remove the objects. Presumably to avoid piling up a lot of useless objects. That commit just added the default to `[unit_overlay]` though.

So firstly, i think there was a rebasing and the actual addition  of object_id is in an earlier commit of https://github.com/wesnoth/wesnoth/commit/1a7724e547201d0ff1fda048b6079559d6da560c mine, that's why the commit message was misleading it was still intentional, but the commit message is a bit misleading.

I think (not 100% sure) that my idea was to have the default in [unit_overlay] and then to remove that object in [remove_unit_overlay], but it turned out to be a bit more complicated than that. The main usage for such a default value was to use it in [remove_unit_overlay] and not users who wanted to use [remove_object], if users wanted to remove a unit overlay object via [remove_object] they should specify object_id and use that.

Since remove_modification can filter by arbitiary attributes, we can also remove the default object id, and use another attribute for that.

**Comment by Pentarctagon** [comment]
So... is there something that needs to change here? Does this need to be a stable release blocker?
