### ISSUE TITLE
[UtBS] blowgun.png path clash

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#7907]
The icon exists in core and UtBS, but is slightly different.
Need to decide for one or rename it.

**Comment by Wedge009** [comment]
Just to be clear on what the images are, I'm assuming it's these two:

https://github.com/wesnoth/wesnoth/blob/master/data/core/images/attacks/blowgun.png
https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Under_the_Burning_Suns/images/attacks/blowgun.png

**Comment by CelticMinstrel** [comment]
I kinda like both of them…

**Comment by cooljeanius** [comment]
The difference between the two is really subtle... I think it's just that there's an extra ring around the tube in the first one?

**Comment by CelticMinstrel** [comment]
No, I think they're made of completely different materials. Rather than the difference being subtle, I don't think there's anything in common between them other than both being blowpipes.

**Comment by cooljeanius** [comment]
They're both the same size (in terms of taking up the same amount of space in the image), both facing the same direction (from the upper left corner towards the bottom right one, stopping in the center), and they're both relatively dark-ish colors. I guess I can maybe see the "different materials" thing, but I'd still say they have more in common between them than just both being blowpipes.

**Comment by stevecotton** [comment]
We can put the images inline for easy comparison.

The only unit in core that uses the blowgun.png is the Dunefolk Alchemist, which has a mace and a blowgun. So opening the unit's help page will show either the two images on the left or the two images on the right.

![mace](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/attacks/quarterstaff.png?raw=true) ![mace](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/attacks/quarterstaff.png?raw=true) Dunefolk Alchemist's mace
![core blowgun](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/attacks/blowgun.png?raw=true) ![UtBS blowgun](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Under_the_Burning_Suns/images/attacks/blowgun.png?raw=true) core (left) and UtBS (right) blowguns

The UtBS blowgun seems to match the mace, almost as if they're the same item with a removable mace head. For me, that looks correct for a moment, and then wrong when I try to work out whether it's a very light mace or a very large diameter blowgun. The mace image is actually quarterstaff.png, and using this pair of images for a hollow metal quarterstaff with a removable tip that's dented from being used as a quarterstaff makes perfect sense to my eyes, until the point that I consider the dents' effect on the accuracy.

Summary: I think core's blowgun.png is the correct choice for the Dunefolk Alchemist.

![sword](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/attacks/sword-elven.png?raw=true) ![sword](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/attacks/sword-elven.png?raw=true) Quenoth Flanker's sword / Quenoth Ranger's sword
![core blowgun](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/attacks/blowgun.png?raw=true) ![UtBS blowgun](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Under_the_Burning_Suns/images/attacks/blowgun.png?raw=true) core (left) and UtBS (right) blowguns

Neither blowgun matches the sword. Reading the marks on the UtBS blowgun as decoration rather than dents fits the sword hilts on Kaleh and Nym's portraits, but my eyes still want to read them as dents. When I look at this closely, neither seems to quite fit, however core's blowgun doesn't trigger that deep thinking while the UtBS blowgun does.

Summary: I think core's blowgun.png is the better choice for the UtBS units.

@doofus-01 : ping

**Comment by doofus-01** [comment]
None of these were tailored for Dunefolk or Quenoth.  If we want to do that, it should be simple enough.  I think the UtBS version was the original.  Is it too late to rename an image?

**Comment by CelticMinstrel** [comment]
I don't think renaming an image affects anything with respect to string freeze. It would violate feature freeze only if it's in core, so renaming the UtBS blowgun is totally fine but renaming the Dunefolk blowgun is not.

**Comment by doofus-01** [comment]
>  It would violate feature freeze only if it's in core,

Interesting, I'd thought everything was frozen.  There's no way UMC or MP can depend on mainline campaigns?

**Comment by cooljeanius** [comment]
> > It would violate feature freeze only if it's in core,
> 
> Interesting, I'd thought everything was frozen. There's no way UMC or MP can depend on mainline campaigns?

I have UMC that depend on mainline campaigns (TEG depends on THoT, and DoT depends on everything)

**Comment by CelticMinstrel** [comment]
> There's no way UMC or MP can depend on mainline campaigns?

Depending on mainline campaigns is considered to be unsupported as far as I know. It's technically possible for an add-on to do so, but we don't officially support it, which means that nothing in the campaigns counts as public API.

**Comment by doofus-01** [comment]
@stevecotton and @Pentarctagon are probably the right people to confirm this?  (That core is frozen, but mainline campaigns can be changed - and if so, to what extent?)

**Comment by Pentarctagon** [comment]
IMO it's fine to change it.

**Comment by doofus-01** [comment]
Cool, thanks.  Are the details of what freezes mean documented somewhere?

**Comment by Pentarctagon** [comment]
I don't think it's formally defined anywhere. Personally I've only ever interpreted it as meaning an API freeze - WML, lua, etc.

**Comment by doofus-01** [comment]
I was wondering if it made sense to put a ribbon telltale on the UtBS blowgun, to make it look more like the elf sword, so I consulted Wikipedia, as one does.  There I learned my understanding of blowguns, that I probably got from cartoons or _The A-Team_ reruns, is that of an 18th-century Briton (i.e. mostly b.s.): https://en.wikipedia.org/wiki/Sumpit

So, given how "fantasy" the Wesnoth blowguns are, might as well have a ribbon.
