### ISSUE TITLE
[filter_ability] issues

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#7992]
https://github.com/wesnoth/wesnoth/blob/6b9a7627b90f90c0fc4f2065d19b179df4682280/src/utils/config_filters.cpp#L49-L51

Checks like this seem to be intended to test if an ability supports the attribute or not. This cannot be checked in these `*_matches_if_present` helper functions though since they have no idea what ability type they're checking.

For `value` there are some `tag_name` tests but `multiply` for example is checked regardless of what the `tag_name` is. Really the tests for `value` look wrong anyway since they also look at `cfg` as if it tells you what an ability supports.

So the logic in https://github.com/wesnoth/wesnoth/blob/6b9a7627b90f90c0fc4f2065d19b179df4682280/src/units/unit.cpp#L1424
must make sure to only call the `*_matches_if_present` helper functions on attributes the given `tag_name` actually supports. When checking an unsupported attribute the filter must fail to match.

Also all code that checks the given `cfg` for what an ability type supports must be removed since it is simply wrong.

**Comment by stevecotton** [comment]
What should be the responsibility of the engine, and what should be the responsibility of the code using the engine?

I feel that it's the responsibility of the WML author to only filter for attributes that are supported by the ability that they're looking for.

**Comment by newfrenchy83** [comment]
> What should be the responsibility of the engine, and what should be the responsibility of the code using the engine?
> 
> I feel that it's the responsibility of the WML author to only filter for attributes that are supported by the ability that they're looking for.

Sorry, but I have the distinct impression that my repairs will cause more problems than anything else; and if an author used an ability like tailwind with value or add, the repair will exclude value filtering for this ability because it does not have the right tags. Indeed the problem raised here cannot be solved in engine.

**Comment by Pentarctagon** [comment]
Is this a valid issue then?

**Comment by soliton-** [comment]
> What should be the responsibility of the engine, and what should be the responsibility of the code using the engine?
> 
> I feel that it's the responsibility of the WML author to only filter for attributes that are supported by the ability that they're looking for.

Btw, what should happen if you filter for a heals ability and the attribute `value = 0`? Does ABILITY_UNPOISON match?
What if you filter for drains and `value=50`, should WEAPON_SPECIAL_DRAIN when used as an ability match?
Worse, what should happen if you filter for `multiply = 1` on any ability that does not explicitly set multiply but does use value?

That you filter for a supported attribute does not mean that a specific ability has that attribute explicitly set. And with combined attributes like multiply/divide/sub/add

**Comment by newfrenchy83** [comment]
> > What should be the responsibility of the engine, and what should be the responsibility of the code using the engine?
> > I feel that it's the responsibility of the WML author to only filter for attributes that are supported by the ability that they're looking for.
> 
> Btw, what should happen if you filter for a heals ability and the attribute `value = 0`? Does ABILITY_UNPOISON match? What if you filter for drains and `value=50`, should WEAPON_SPECIAL_DRAIN when used as an ability match? Worse, what should happen if you filter for `multiply = 1` on any ability that does not explicitly set multiply but does use value?
> 
> That you filter for a supported attribute does not mean that a specific ability has that attribute explicitly set. And with combined attributes like multiply/divide/sub/add it gets even more complicated...

if value=50 is used as filter a drains ability then what value=50 whether specified or not, drains matechera unless add, sub, multiply or divide is used to change this value, this is intended.

the same for ability_unpoison, because without a numerical value specified, the value of heals is zero. On the other hand, if we check value=0 for hides, it will not match because hides abilties will not return a default value, and the same for [dummy] abilities.

**Comment by soliton-** [comment]
> if value=50 is used as filter a drains ability then what value=50 whether specified or not, drains matechera unless add, sub, multiply or divide is used to change this value, this is intended.

Can you explain the intention? Why does it make sense to match a drains ability with `value,multiply=50,1` and not `multiply=1`? Both abilities behave exactly the same, no? Why does it makes sense to match `value,multiply=50,2` and `value=50` even though they do not behave the same?

> the same for ability_unpoison, because without a numerical value specified, the value of heals is zero. On the other hand, if we check value=0 for hides, it will not match because hides abilties will not return a default value, and the same for [dummy] abilities.

Thus even if the WML author only filters for attributes that are supported by the ability that they're looking for the engine is responsible for doing that correctly depending on which ability it is.

Whether that means assuming how dummy abilities work is another question. IMO that should only be done for attributes the engine truly handles for dummy abilities as well. Matching a dummy ability with `apply_to=self` if that is not actually set in the ability seems dubious.

**Comment by newfrenchy83** [comment]
@soliton-  if the multiply attribute is present whatever the value, then the system assumes that the value 50 is changed, if I have to make a correction, it will be for 1.19, I already have a PR waiting for @Pentarctagon  to want it merge into master if he does, which is not sure, and I promised not to bother him again before version 1.19 so that he can concentrate on other more priority problems.

As for [dummy] abilities, some developers manage to integrate and use value (tailwind), so why can value not be checked under the pretext that it is not an engine ability? The case of other attributes is more complex, but that will have to wait.

**Comment by soliton-** [comment]
> @soliton- if the multiply attribute is present whatever the value, then the system assumes that the value 50 is changed, if I have to make a correction, it will be for 1.19, I already have a PR waiting for @Pentarctagon to want it merge into master if he does, which is not sure, and I promised not to bother him again before version 1.19 so that he can concentrate on other more priority problems.

[filter_ability] is a new API for 1.18. If we do not manage to make it work sensibly and document how it works properly then it should either be removed or clearly marked as experimental. I'd certainly be happy if this would go faster as well but with lacking documentation and not getting answers to my questions (for example still no response on what the `cfg` checks are trying to accomplish) it unfortunately takes a while.

> As for [dummy] abilities, some developers manage to integrate and use value (tailwind), so why can value not be checked under the pretext that it is not an engine ability? The case of other attributes is more complex, but that will have to wait.

Not sure what integration you mean. The point is anyway that `value` and all other attributes that are checked at all are checked under the pretext that they do work like in-engine abilities. Some cases like `value` without add/sub etc might currently happen to work for dummy abilities as well but unless you know the code in detail I do not expect any UMC author to figure out which attribute works how without a high amount of trial and error. Better to either disable checking for dummy abilities or make it work the same way no matter the attribute.

**Comment by Pentarctagon** [comment]
If the attribute being filtered on doesn't exist at all, then it can't possibly match it.

**Comment by newfrenchy83** [comment]
> If the attribute being filtered on doesn't exist at all, then it can't possibly match it.

And how do you know if an attribute has the right to be present or not? With value the situation is complex because of taiwind which is not an engine capability but which still has this attribute? And the id, which every ability is supposed to have, should we also make it impossible to filter outside of the engine abilities? And finally, if an author wants to use affect_self=yes in a dummy even if it doesn't bring anything functionally; just to make it a filtering criterion, why tell him “no, you don’t have the right?”
[filter_ability] is there to filter the abilities having this or that attribute with or not the specified value, if this attribute is not supposed to be present, too bad, better that than a filtering of the types of abilities which here will become excessively complicated and will become a source of worse problems than this one.

When (and if) https://github.com/wesnoth/wesnoth/pull/8002 will be merged, I would look into this in more detail.

**Comment by CelticMinstrel** [comment]
I think for custom abilities we'll eventually need a way to specify whether or not it has a value, something like `has_value=yes/no`. Then the Lua API would have a "get ability value" function that returns the value of an ability, or nil if the ability doesn't have a value; and it would work the same for custom and built-in abilities.

**Comment by stevecotton** [comment]
#8050 does most of the renames. There's one deprecation message left in src/units/unit.cpp, where I'm wondering what to do about it - it doesn't seem right to have a deprecation recommend an experimental API as the replacement.
```
deprecated_message("[effect]apply_to=remove_ability [abilities]", DEP_LEVEL::INDEFINITE, "",
    "Use [filter_ability] instead in [effect]apply_to=remove_ability");
```

**Comment by newfrenchy83** [comment]
> #8050 does most of the renames. There's one deprecation message left in src/units/unit.cpp, where I'm wondering what to do about it - it doesn't seem right to have a deprecation recommend an experimental API as the replacement.
> 
> ```
> deprecated_message("[effect]apply_to=remove_ability [abilities]", DEP_LEVEL::INDEFINITE, "",
>     "Use [filter_ability] instead in [effect]apply_to=remove_ability");
> ```

replacement done, i forget to doing that.

**Comment by Pentarctagon** [comment]
The deprecation message should be removed for now. I assume it will be added back to 1.19 at some point once this is sorted out.

**Comment by Pentarctagon** [comment]
Removed the `Blocker: New Stable` tag since they've been renamed as experimental for now.

**Comment by newfrenchy83** [comment]
i like what issue i must fix here because too many here for what i know that what must doing.

**Comment by newfrenchy83** [comment]
@soliton- done an list of issue to be resolved( minus tag_name mandatory because doing an attribute filter mandatory is not an option for me)

**Comment by soliton-** [comment]
I understand your English is not very good and that's just how it is. Nevertheless it is very frustrating time and time again to read your message 5 times and still have no idea what to respond since I have no idea what you said.

I have a feeling it can only be better if you wrote in french and someone can translate it (even with google translate or so) and there is a better chance to figure out what you said.

**Comment by Pentarctagon** [comment]
So as I understand it, Soliton wants there to be code to list out what attributes each ability and weapon special supports in order to prevent UMC from filtering on attributes that don't do anything for a particular ability or weapon special. The current checks with `cfg` aren't correct since there could be invalid attributes in the ability or weapon special's config.

**Comment by stevecotton** [comment]
IIUC, @newfrenchy83 wants to rename the existing `[experimental_filter_ability]` tag to `[filter_ability]`, and is asking @soliton- to identify a minimal set of changes needed for that to be allowed. However, what @soliton- wants (IIUC) is a design with documentation answering all the questions in this issue; including answering @newfrenchy83's own questions in https://github.com/wesnoth/wesnoth/issues/7992#issuecomment-1799533596 .

Let's look at an alternative question - what if we add a new `[filter_ability]` tag, limited to the functionality for which we're all happy with the design and documentation? The `[experimental_filter_ability]` tag would keep its existing name, and this GitHub issue would be renamed to `[experimental_filter_ability] issues`.

We currently have exactly one use of `[experimental_filter_ability]` in mainline, other than the tests. That's in EI S12, added in #8676 because removing an ability by tag name is a useful feature.
```
[effect]
    apply_to=remove_ability
    [experimental_filter_ability]
        tag_name=illuminates
    [/experimental_filter_ability]
[/effect]
```

I suggest adding `[filter_ability]` supporting only `tag_name=`. I believe that's useful enough that it would be worth having in 1.20, even if no other functionality was added, and I think having that wouldn't limit us in future discussions about adding other functionality to the tag.

**Comment by Pentarctagon** [comment]
IMO if we can't reach a conclusion for the existing tag by the time 1.20 is feature frozen, then we're probably never going to be able to.

So I think I'm just going to go ahead and do the things I mentioned in my last post:
> So as I understand it, Soliton wants there to be code to list out what attributes each ability and weapon special supports in order to prevent UMC from filtering on attributes that don't do anything for a particular ability or weapon special. The current checks with `cfg` aren't correct since there could be invalid attributes in the ability or weapon special's config.

These seem (?) simple enough. I think the documentation part is irrelevant until someone can actually define what's even being asked for more clearly. But from what I *think* I understand about it, I don't know why this particular feature is being put under such strict scrutiny compared to so many other UMC API that have been made.

**Comment by newfrenchy83** [comment]
i will implemente check tag_name for exclude engine abilities who don't use some attributes, ok?

**Comment by stevecotton** [comment]
Please wait - I promise that I will reply with details, but I need the time for other stuff first.

**Comment by newfrenchy83** [comment]
@stevecotton Here a list of commit of changes what i already done:
https://github.com/wesnoth/wesnoth/commit/1809af8cdf8dc3355d061c5f4e4c9cd14ffb4158
https://github.com/wesnoth/wesnoth/commit/3d097f29503b9e4fc5411e908593e97603953f97
https://github.com/wesnoth/wesnoth/commit/3f0d65371859d5e239bd633b8def00f7da8214ea
https://github.com/wesnoth/wesnoth/commit/532d17f958969186baa0646c5528c2477bcb65b3
https://github.com/wesnoth/wesnoth/commit/24859f861af77c5298076e905bf923f0932d8379

i hope what it will help you to see that what remain or not.
