### ISSUE TITLE
End credits do not appear for campaigns without a [side] defined in final scenario (DM, LoW, WoF)

### ISSUE THREAD

**Issue by Jonathan-Kelly** [wesnoth/wesnoth#8090]
### Game and System Information

- 1.17.23 and 1.17.22 (possibly much of 1.17.x but issue does not occur in 1.16)
- Windows 10

### Description of the bug

Credits do not appear at the end of campaigns whose final scenario has no sides defined (usually a story or dialogue only 'epilogue' scenario with no map or need for sides). The bug can be worked around by adding `[side] side=1 [/side]` to the campaigns' final scenarios.

### Steps to reproduce the behavior

Use the debug `next_level` command to reach the final scenario of DM, LoW or WoF and then click through or skip to its conclusion.

### Expected behavior

End credits appear after final scenario.

### Additional context

The bug does not happen in 1.16 so it must have been introduced sometime in 1.17.

**Comment by gfgtdf** [comment]
My suspicion is that since these are no sides, this code gets exceuted: 
https://github.com/wesnoth/wesnoth/blob/eda0ed3e16e47ab99170bf5b5e93a3cdcc73642b/src/playsingle_controller.cpp#L435
So the result is no "victory" here https://github.com/wesnoth/wesnoth/blob/eda0ed3e16e47ab99170bf5b5e93a3cdcc73642b/src/game_initialization/playcampaign.cpp#L207

**Comment by Jonathan-Kelly** [comment]
Tested it; the credits and everything else now work as they should. Thanks for the swift work!
