### ISSUE TITLE
Restore the support for old additional advancement definition

### ISSUE THREAD

**Issue by demario-w** [wesnoth/wesnoth#8211]
### Describe the desired feature

The additional advancement for units in campaigns is now defined using {ENABLE_...} macro while it used to be defined by  "#define ENABLE_..." instead. These two modes are using the exact same strings.

In the file src/game_config_manager.cpp there is still some code checking for these extra defines to generate a warning message. The engine knows what a person using these extra defines want to do but blindly drop the code (with a warning) and doesn't activate the additional advancement to update units in the campaign. It would take roughly the same number of lines to actually convert the additional advancement definition and move on.

The proposal is to implement the additional advancement conversion to support campaigns using the old format.

This is blocking loading additional advancement defined in old campaigns when using a core to support older version.

**Comment by stevecotton** [comment]
Something related to the 1.14 method broke in 1.15, which is logged as #4402. I'm not familiar with the bug, just noting the comment in src/game_config_manager.cpp explaining why a compatibility path wasn't added.

**Comment by demario-w** [comment]
> comment in src/game_config_manager.cpp explaining why a compatibility path wasn't added.

I am not clear what you mean. Do you mean that programmatically turning #define ENABLE_... into {ENABLE...} would fail in certain cases? If so, the advice in the deprecation warning for the user to perform the exact same change manually would be buggy too?

**Comment by CelticMinstrel** [comment]
There was some conversion code for this somewhere in the past. It may have been removed, probably because it was wrong. I don't have a problem with adding it back while correcting it.

> > comment in src/game_config_manager.cpp explaining why a compatibility path wasn't added.
> 
> I am not clear what you mean. Do you mean that programmatically turning #define ENABLE_... into {ENABLE...} would fail in certain cases? If so, the advice in the deprecation warning for the user to perform the exact same change manually would be buggy too?

@stevecotton is saying that there's a comment in the source explaining why the conversion wasn't done.

It's not possible to programmatically turn the `extra_define` directly into a macro expansion, because the parsing has long completed by the time it gets to checking for the `extra_define`. It's likely possible to hard-code the expansion of those old macros into the compatibility code though, so for example if it sees `extra_define=ENABLE_DWARVISH_ARCANISTER` it can insert a `[modify_unit_type]` equivalent to the expansion of `{ENABLE_DWARVISH_ARCANISTER}`.

I guess it could somewhat automate that process and avoid duplication (in case the macro definitions change in the future) by constructing a very simple WML file, parsing it, and inserting the result.

**Comment by demario-w** [comment]
> > > comment in src/game_config_manager.cpp explaining why a compatibility path wasn't added.
> > 
> > I am not clear what you mean.
> 
> stevecotton is saying that there's a comment in the source explaining why the conversion wasn't done.
> 
What is wrong with you?

Forget it.

**Comment by CelticMinstrel** [comment]
…
