### ISSUE TITLE
Update xBRZ to latest version

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#8307]
As discussed on Discord, the goal now is instead of removing xBRZ, to update it to its latest version. As far as licensing goes, given that xBRZ is only under GPLv3, is that all contributions to Wesnoth itself will remain as GPLv2+ and only the final wesnoth executable will become licensed GPLv3 for as long as xBRZ (after the update) continues to be included. The multiplayer server (wesnothd) and add-ons server (campaignd) are unaffected as for obvious reasons they don't include xBRZ.

**Comment by CelticMinstrel** [comment]
We should also determine whether that approach requires xBRZ to be linked dynamically, rather than statically.

**Comment by Pentarctagon** [comment]
Why would that make a difference?

**Comment by CelticMinstrel** [comment]
I'm not sure. I think I've read that it can make a difference. We need to be sure of whether or not it does.

**Comment by Pentarctagon** [comment]
As far as I'm aware, there's no difference between which you use.

**Comment by CelticMinstrel** [comment]
I think there are circumstances where it makes a difference. In particular, the Steam API came up as one case where we'd be able to dynamically link but not statically link. So we just need to be certain.

**Comment by Pentarctagon** [comment]
As far as the GPL is concerned, all linked libraries are part of the combined work. We can no more dynamically link to the Steamworks SDK than we can statically link to it: https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic

**Comment by CelticMinstrel** [comment]
Ah, right, that case required IPC, not dynamic linking. Probably IPC wouldn't be needed in this case.

**Comment by pehjota** [comment]
@Andrettin (Wyrmsun developer) in #5474 said that xBRZ in Wesnoth doesn't specify a GPL version and therefore can be used under any version, but this doesn't appear to be true.  Commit eeb92161e07 which added xBRZ included [a copy of GPL version 3](https://github.com/wesnoth/wesnoth/blob/eeb92161e07/src/xBRZ/License.txt) (like [current versions](https://sourceforge.net/projects/xbrz/files/xBRZ/) of xBRZ do).  Wesnoth xBRZ header comments include an (unversioned) URL to the GPL; xBRZ was first published sometime between [2012-09-17](https://web.archive.org/web/20140413023755/http://sourceforge.net/projects/hqmame/) and [2013-10-30](https://web.archive.org/web/20140413024207/https://sourceforge.net/projects/hqmame/files/), by which time the unversioned GPL URL pointed to GPL-3.0 (published 2007-06-29).  Commit fddb0ac8a92 removed the GPL-3.0 copy, which along with the unversioned GPL URL in header comments likely led to everyone else failing to notice xBRZ's license version.

So Wesnoth is already under GPL-3.0(-only?).  Everything else in Wesnoth as far as I've found is licensed under GPL-2.0-or-later or other licenses compatible with GPL-3.0, so this is OK.

**Comment by Pentarctagon** [comment]
The comments in the xBRZ code in Wesnoth mentions there being some sort of exception:
> It is not possible to extend the MAME 'special exception' to all of
> the Battle for Wesnoth project, however, the special exception is
> granted for my derivative forms of this work.

**Comment by pehjota** [comment]
> The comments in the xBRZ code in Wesnoth mentions there being some sort of exception:

Right, see the "not":

> It is **not** possible to extend the MAME 'special exception' to all of
> the Battle for Wesnoth project,

The exception applies only to linking xBRZ with "the MAME library (or with modified versions of MAME that use the same license as MAME)".

> however, the special exception is
> granted for my derivative forms of this work.

This part just means that @cbeck88 granted the exception for his modifications to xBRZ (apparently still just for linking with MAME).

**Comment by pehjota** [comment]
In other words, I'm just letting you know that the wesnoth executable has already been licensed under GPL-3.0(-only) since 1.13.0, and legally that's OK.  IANAL and TINLA, but I've been reviewing the code copyrights and I see no incompatibilities.

(Well, there's the pre-3.0 OpenSSL license issue, which [Debian](https://lists.debian.org/debian-devel/2020/10/threads.html#00165) and Fedora avoid by now considering OpenSSL a "system library" under the GPL.  And OpenSSL's new Apache-2.0 license is considered incompatible with GPL-2.0, so if not for the "system library" theory, OpenSSL 3.0 would be another reason to consider wesnoth to be licensed under GPL-3.0.)

**Comment by cbeck88** [comment]
Just saw these in my emails --

I thought I had done my homework on the licensing around xBRZ being compatible with Wesnoth.

I remember asking Zenju in a chat if it's okay to use xBRZ in wesnoth, and especially, if he thought it was correct to use it in a "gpl v2 or v3 at your option" project. And I remember that he said yes, and that it would be really cool if xbrz was used in wesnoth, so that was why I thought this was okay.

I hope it's all sorted and hasn't caused any problems. If there's something more I can do to be helpful, lmk. Cheers

**Comment by soliton-** [comment]
It would be cool if we could use xBRZ without making wesnoth GPLv3.
