### ISSUE TITLE
[SoF] Scenario 2/Closing the gates: warnings triggered on scenario load

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#8350]
### Game and System Information

- **Version:** 1.17.25+dev
- **Downloaded from:** GitHub
- **Build info:** Msys2 (latest commit)
- **OS:** Windows 10 (I dont trust Microsoft enough to go to 11)

### Description of the bug

I loaded the second scenario, and then I see engine warnings in the Msys2 64-bit terminal.
```sh
20240205 21:11:14 warning engine: Could not find move_unit_fake route from 11,16 to 22,12: ignoring complexities
20240205 21:11:34 warning engine: Could not find move_unit_fake route from 21,12 to 32,12: ignoring complexities
```

### Steps to reproduce the behavior

[SoF-Closing the Gates.gz](https://github.com/wesnoth/wesnoth/files/14167555/SoF-Closing.the.Gates.gz)
Load Save File
Wait for start event sequence
Check the terminal for the warnings

### Expected behavior

No warnings shown for a mainline campaign

**Comment by knyghtmare** [comment]
FYI, the campaign-wise labeller does not seem to work so someone should really check that out.

**Comment by stevecotton** [comment]
Confirmed - saw these messages when doing the `[allow_undo]` fix for #8346.

The labeller recognises campaigns for PRs from the files that they change, I don't think it has any info to know which campaign an issue belongs to.

**Comment by soliton-** [comment]
If this is about https://github.com/actions/labeler than that is indeed for PRs. We have nothing automatically labeling issues.

**Comment by stevecotton** [comment]
The warning message about being unable to find a path is due to shroud. The path is then calculated ignoring shroud, which is why the moves work (of Rugnur to his keep, and Alanin off-map respectively). While we're about it, Alanin's move to the south-east starts by moving north to better terrain, and it would make much more sense for Rugnur to be off keep for that discussion (as he was in 0956ff346aa68fe34c81ce72b5fc9a65c6612fef).

The API looks like it has different assumptions - [`[move_unit]`](https://wiki.wesnoth.org/DirectActionsWML#.5Bmove_unit.5D) supports removing shroud at the destination, but doesn't have an option to ignore shroud when calculating the move itself. That might of course assume that the destination was already visible, and just be clearing shroud for hexes visible from that destination. However, there seems to be a lack of a "move unit into shroud (that stays shrouded for that unit's side" option.

For Rugnur's move, a fix seems simple. We see Rugnur moving and then Alanin gets recalled; if Alanin was put there at prestart then the shroud would be cleared, and the dialogue from S01 fits perfectly with Alanin having ridden all the way into the stronghold first.

For Alanin's own move, it's simpler if he's planned his escape route and cleared shroud a long way into the fort.

**Comment by stevecotton** [comment]
I tested 1.16 and this warning shows up there too, so the warning on 1.17 isn't a regression in the engine's handling of `[move_unit]`
