### ISSUE TITLE
Inconsistent terrain name (Sand or Sands)

### ISSUE THREAD

**Issue by OrekOrek** [wesnoth/wesnoth#8434]
Both “Sand” and “Sands” are used to refer to the same terrain type. Because “Hills” and “Mountains” are always plural, and other singular ones are always singular, this is probably just an oversight rather than an intentional word choice.

I checked help and map terrain in game as well as the unit database (picture below), but there may be other places where “Sand” and “Sands” are used interchangeably.

The questions are;
Q1: Should they be “Sand” or “Sands” ?
Q2: Where are the codes for these?

Unfortunately, I have no idea which file has control over which description. If there is a simple fix by an expert here who can filter through all the files and replace all the relevant “Sand” with “Sands” or vice versa, that would be great.

![HttT Sand(s)](https://github.com/wesnoth/wesnoth/assets/155947547/36825657-fe5a-48da-bc8a-ceabb6eb1323)

**Comment by soliton-** [comment]
https://github.com/wesnoth/wesnoth/blob/8cebaf5b51838d82525835dc67085ec2c9c81433/data/core/terrain.cfg#L3278-L3279

Not sure why but help uses `editor_name`.
Also for all archetype terrains `name` and `editor_name` are the same except for sand, not sure why either.

I suppose we can just make `name` and `editor_name` the same.

**Comment by CelticMinstrel** [comment]
"sand" is generally uncountable, yes. There may be occasions where it's countable if you're talking about individual grains of sand, but I don't think that's very common.

"sands" is the plural, but it's mostly obsolete. There are two non-obsolete uses – the sand in an hourglass (real or figurative) for some reason gets to be plural (at least sometimes), and it's also a figurative term for "desert". So, "desert sands" is technically redundant. It's like saying "desert desert". It's not the worst case of redundancy though and does sound fine.

I don't feel like the current situation is a problem – all those uses of "sand" and "sands" sound fine to me. But I think it would also sound fine if all instances of "sands" were changed to "sand". (Note that "desert sands" and "beach sands" are separate strings, so that's probably 3 instances in total from the source code side.)

**Comment by OrekOrek** [comment]
Thank you all for your opinions / feedback.
I will check https://github.com/wesnoth/wesnoth/blob/master/data/core/terrain.cfg and other files if necessary.
Once I’m done, I will open a pull request to close this.
