### ISSUE TITLE
Laurels shown when changing difficulty mid campaign are always golden

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#8442]
### Game and System Information

- **Version:** 1.17.26
- **Downloaded from:** Steam
- **OS:** Windows 10

### Description of the bug

See title. :D

### Steps to reproduce the behavior

1. Select a scenario start file.
2. Check the 'change difficulty box'
![change difficulty](https://github.com/wesnoth/wesnoth/assets/39015360/ccdf9233-2cd8-497f-a904-98c565cc2caf)
3. Load the save
4. Observe the options shown, each completed difficulty shows as a gold laurel.
![wrong laurels](https://github.com/wesnoth/wesnoth/assets/39015360/79d3d273-162b-40c3-a60e-5a913b6804dc)

### Expected behavior

I expected that the laurels would be the same as shown in the campaign dialog when selecting the difficulty.
![right laurels](https://github.com/wesnoth/wesnoth/assets/39015360/8e71b59d-d64a-42a1-8ecb-18ca04dbef2c)

For me that would make more sense, but if it's an intentional decision, that's fine by me too. It feels like an oversight though.

### Additional context
[DW-Epilogue.gz](https://github.com/wesnoth/wesnoth/files/14373477/DW-Epilogue.gz)
Makes it easiest to confirm, as loading the save with a difficulty selected automatically gives the campaign completion.

**Comment by Wedge009** [comment]
Also confirmed on 1.16.11 release. I agree it appears to be an oversight.

**Comment by Wedge009** [comment]
I had a go at resolving this but I don't know/understand gui2 well enough to make sense of how to change the laurel image. So I put my findings here for the next attempt, whoever might pick this up.

Both the difficulty selection from the campaign dialogue and the load screen hard-code the standard gold laurel in their WML definitions:

https://github.com/wesnoth/wesnoth/blob/90a74e1b965b77b6abca46a4b7f94a297a290ab1/data/gui/window/campaign_difficulty.cfg#L134-L138
https://github.com/wesnoth/wesnoth/blob/90a74e1b965b77b6abca46a4b7f94a297a290ab1/data/gui/window/campaign_dialog.cfg#L80-L85

Difficulty selection from the campaign dialogue sets the standard gold laurel for the top difficulty, bronze laurel for the lowest difficulty, and silver laurel for anything in between. Most campaigns have three difficulty levels or fewer - Dead Water is the only official one with four, I assume that's why Konrad picked it for illustration.
https://github.com/wesnoth/wesnoth/blob/90a74e1b965b77b6abca46a4b7f94a297a290ab1/src/gui/dialogs/campaign_selection.cpp#L98-L110

I assume something similar can be done for the difficulty selection from the game loading, but here all it does is find the 'victory' widget and makes it invisible if the preferences file indicates the associated campaign has not been completed for the given difficulty. This is why the laurel - if it is shown - is always the standard gold version.
https://github.com/wesnoth/wesnoth/blob/90a74e1b965b77b6abca46a4b7f94a297a290ab1/src/gui/dialogs/campaign_difficulty.cpp#L102-L105

**Comment by Wedge009** [comment]
Hmm, actually the laurel selection is done as the campaign tree is being built:
https://github.com/wesnoth/wesnoth/blob/90a74e1b965b77b6abca46a4b7f94a297a290ab1/src/gui/dialogs/campaign_selection.cpp#L432-L449

**Comment by CelticMinstrel** [comment]
> I assume something similar can be done for the difficulty selection from the game loading, but here all it does is find the 'victory' widget and makes it invisible if the preferences file indicates the associated campaign has not been completed for the given difficulty. This is why the laurel - if it is shown - is always the standard gold version.

Sounds like you could use `widget->set_label` at that location.

**Comment by Wedge009** [comment]
'`gui2::widget` has no member `set_label`', at least according to the compiler.

**Comment by CelticMinstrel** [comment]
It's in `styled_widget`, so I guess a `dynamic_cast` is needed… or use the templated `find_widget` instead of `grid.find`.
