### ISSUE TITLE
Loyal Units in Editor Tool

### ISSUE THREAD

**Issue by Rakid1** [wesnoth/wesnoth#8445]
### Game and System Information

- **Version: Windows**
- **Downloaded from: Steam**
- **Build info:**
- **OS:**

### Description of the bug

They didn't work (Polish verion language). You can't click them and they didn't have the gold little thing next to head

### Steps to reproduce the behavior

1. Start Editor
2. Create New Scenario
3. Add a unit
4. Right-click on unit
5. Select 'Loyal' from the menu
6. Observe no change to the unit and right-clicking again indicates no apparent change in the loyal status

**Comment by Wedge009** [comment]
I found the report lacking in information, so if I understand the issue correctly this is what I did to replicate the problem:

1. Start Editor
2. Create New Scenario
3. Add a unit
4. Right-click on unit
5. Select 'Loyal' from the menu
6. Observe no change to the unit and right-clicking again indicates no apparent change in the loyal status

No version was specified so I tested in 1.16.11 release but I confirm the issue is in master as well. I take 'the gold little thing' to mean the crown marker indicating loyal status.

![image](https://github.com/wesnoth/wesnoth/assets/13679322/3c74e65f-a372-476d-bc37-9286e531b933)

**Comment by Rakid1** [comment]
> I found the report lacking in information, so if I understand the issue correctly this is what I did to replicate the problem:
> 
> 1. Start Editor
> 2. Create New Scenario
> 3. Add a unit
> 4. Right-click on unit
> 5. Select 'Loyal' from the menu
> 6. Observe no change to the unit and right-clicking again indicates no apparent change in the loyal status
> 
> No version was specified so I tested in 1.16.11 release but I confirm the issue is in master as well. I take 'the gold little thing' to mean the crown marker indicating loyal status.
> 
> ![image](https://private-user-images.githubusercontent.com/13679322/307200069-3c74e65f-a372-476d-bc37-9286e531b933.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzUxNDksIm5iZiI6MTcwODg3NDg0OSwicGF0aCI6Ii8xMzY3OTMyMi8zMDcyMDAwNjktM2M3NGU2NWYtYTM3Mi00NzZkLWJjMzctOTI4NmU1MzFiOTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE1MjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NWVkNjZmMGQ0MWIzODMzN2NiNDMwYzQzZjRlODBlMTJkZDE3MWNlYjU0ZmIwMDk5OGU0YjhkODM2NTQxYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m78fe006aCqJgRb10NQYvxMx3RzwMhPFNx2MUVMBfhM)

Thank you for help
