### ISSUE TITLE
Effect ``apply_to=hitpoints`` ``heal_full=yes`` doesn't work

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#8460]
### Game and System Information

- **Version:** built from 40fc9a8be70bbbf4108303f9034392e38e63081b

### Description of the bug

[Bug_with_heal_full.zip](https://github.com/wesnoth/wesnoth/files/14397875/Bug_with_heal_full.zip)

Here is the test scenario. It uses RECRUIT_UNIT_VARIATIONS macro to allow recruit either usual zombies or troll zombies. Troll zombies have 21 max hp. 

The code of the macro includes the following to heal units. In 1.16 it works fine, in the recent version it doesn't
```
                   [effect]
                        apply_to=hitpoints
                        heal_full=yes
                    [/effect]
```

![изображение](https://github.com/wesnoth/wesnoth/assets/68666085/3852ae89-05d3-47b3-b7a3-f252b1e367fa)

### Steps to reproduce the behavior

1. Install the scenario above
2. Start the game
3. Recruit zombies until you get a troll zombie, it would have 18 out of 21 hp

### Expected behavior

Full hp troll zombies

**Comment by gfgtdf** [comment]
This is probably specific to the RECRUIT_UNIT_VARIATIONS macro since it uses, the "apply_to=variation" effect which is a bit problematic sometimes.

While we should fix the cpp part there is also no reason for this code to use [object] at all.

**Comment by gfgtdf** [comment]
The problem is that this code, https://github.com/wesnoth/wesnoth/blob/a2c9d2627ebe80fa76709b3559d0539e3942c862/src/units/unit.cpp#L2488 always applies the `apply_to=variation` effect last, so the other healing has no effect.

**Comment by gfgtdf** [comment]
> But how are we supposed to do the task of making a random variation then? And overall, this logic, used for many versions, seems legit: you transform a unit and heal it full in the case of different hp of the variation

i think it would work  if you put the [effect] in [modify_unit] instead of [object], since the lua code in [modify_unit] applies all the [effect]s seperately.

Imo it would also make sense to if we allowed  [transform_unit] to change the variation (the underlying lua api already supports that.).

The reason why to me using [object] looks wrong though is that [object] is usually used for changes of the units stats that should be reapplied whenever the unit is rebuild, and neither healing nor setting the variation falls in that category ("naturally" generated corpses also don't have an object in them)

**Comment by Discontinuum** [comment]
If we don't use [object] for variations, won't it mean that the variation will reset on level up?

**Comment by gfgtdf** [comment]
> If we don't use [object] for variations, won't it mean that the variation will reset on level up?

No, leveling/up rebuilding the unit doesn't reset its variation.

**Comment by gfgtdf** [comment]
Needs backport for 1.18
