### ISSUE TITLE
Disabling Log File button when not using a log file

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#8691]
Can we grey out the button for the log file when logging to the terminal with `--no-log-to-file`? It tries to use the current working directory.
![no-log-to-file](https://github.com/wesnoth/wesnoth/assets/21158813/343a3e9a-67d5-46f5-975d-f5c4682d843f)

**Comment by Wedge009** [comment]
https://github.com/wesnoth/wesnoth/blob/71c2f65a825e3f77e3d07bb727e14eb4be1e1ab7/src/gui/dialogs/game_version_dialog.cpp#L111-L140

The paths are collated into a map and added to the dialogue one at a time, with accompanying open and copy buttons. I suppose one could check that the paths are valid and disable the open button in the cases where it is not.

**Comment by Wedge009** [comment]
It looks like this is not an issue in Windows because a default logs directory gets created if one doesn't already exist.

**Comment by sevu** [comment]
It is about using the command line option `--no-log-to-file`

**Comment by Wedge009** [comment]
Yes, I know. Even using `--no-log-to-file`, the logs directory still gets recreated for me. BTW, you didn't specify which version - I was testing official 1.18.0 release and self-compiled 1.18 branch, though I presume master/1.19.0+dev would behave the same way.

**Comment by Wedge009** [comment]
Can anyone replicate the underlying bug for this request and specify the details, please?

**Comment by sevu** [comment]
I mean that it should not offer the button at all. The button is for opening the log file, and as it is specified on command line to not use a log file, there cannot be a correct path. It does not matter whether the logs directory exists. If it exists, then there is no file to open (and should not be).

I use a self-compiled 1.18.0, though with current 1.18 branch.

**Comment by soliton-** [comment]
I think there is a misunderstanding about what is meant. I think sevu means the log file button on the lower left of the dialog. Not the button to open the log dir.

**Comment by Wedge009** [comment]
![image](https://github.com/wesnoth/wesnoth/assets/13679322/9e397050-585f-4381-96dc-42772e7f2a02)

I ran Wesnoth with `--no-log-to-file`. The bottom-left icon just copies a report into a buffer and I can paste this text as normal. I should not think disabling logging should affect this in any way.

Since the logs directory gets recreated, I cannot replicate the error in the original report, no matter what button I try.

**Comment by soliton-** [comment]
In your screenshot the button in question is the one saying "Fichier de journalisation". The one that explains it opens the current log file in the tool tip.

When I press that button in the flatpak build I get the error `Failed to open '/home/wesnoth/.log': No such file or directory`.

**Comment by Wedge009** [comment]
Okay, I feel pretty silly now, seeing it stare at me in the face. I've never used that button before, I've always just gone straight to the logs directory myself.

Strangely, in both Windows and Linux (specifically, KDE/X11), when using `--no-log-to-file`, I _still_ can't replicate either of your errors. Instead, no action occurs when the log file button is clicked - error messages go to the log console rather than shown in a separate dialogue. Nonetheless, I agree that the button should be disabled with the no-log-file option - while no action is better than the error messages you're reporting, it's still a problem.
