### ISSUE TITLE
EI: In S12 Evacuation, Prefer Non-Ogre Veteran Speaker For Units Left Behind

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8746]
### Describe the desired feature

If Evacuation is completed by destroying the bridge and units are left behind, the game places a batch of doomed recalls and selects an L2+ unit to speak a line of dialogue.

Ogres have a distinct speaking style and the line is much more eloquent and formal than the Ogre-specfic dialogue lines.

It doesn't make sense to make alternate lines for all dialogue an Ogre could speak but:
1) This is part of a story beat
2) It is likely that a non-Ogre veteran will be available to speak instead

Alternately, Ogres could be forbidden from saying this line outright.
![Screenshot 2024-04-02 00 54 54](https://github.com/wesnoth/wesnoth/assets/81496259/e82f0b3a-2f77-4f60-992a-405ca5bb0e73)

Other Notes:
Is this line intended for units that have been left behind?
The line "From here, we must ride swift..." seems a little off because the speaker will soon be dead. It should probably be "you" instead of "we" or the "From here, we must" should be deleted (-> "Ride swift...")

**Comment by stevecotton** [comment]
The main issue reported here can be fixed for 1.18, this is just commenting on a side issue.

> the speaker will soon be dead. It should probably be "you" instead of "we"

Yes, and thanks for reporting this. However, 1.18's strings are already frozen for translation, so that line can only be corrected for 1.19 - there's a hint to the translators so that they can translate the intended meaning, although that doesn't fix the English text.

**Comment by Wedge009** [comment]
@Dalas121 I'm guessing one option is to filter out the ogre race in the same way you are already excluding dunefolk unit.

https://github.com/wesnoth/wesnoth/blob/c62fd51f48d2cee2b91070db5f69fdaea72b4df5/data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg#L687-L698

Are you also aware of other parts of the campaign where ogres might need to be excluded?

(Apologies, I still haven't played the revised campaign though plan to do so at some point.)

**Comment by Dalas121** [comment]
Yes, that seems like a good solution; I'll make a PR.

> Are you also aware of other parts of the campaign where ogres might need to be excluded?

Pretty much every moveto would benefit from a custom voiceline for ogres, walking corpses/soulless, and Dolburras the dwarf (since he talks differently). Unfortunately I don't have the time required to change all those, but I fully support it if anybody else wants to.
