### ISSUE TITLE
WoF:  S09 Ancestor Has a Misleading Objective

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8758]
### Describe the desired feature

Language: English

The scenarios objectives are:
(1) "Gorlack must reach the beacon at the northern volcano"
(2) "From there, make your final stand"

(1) is clear.
(2) is probably deliberately vague to avoid indicating that the player will recieve significant allied reinforcements after completing (1). These reinforcements will easily kill any enemy units still on the map.

"Final stand" strongly implies that the player will have to survive a number of turns once at the volcano. Additionally, the previous scenario involves the player escaping overwhelming enemy forces.

This suggests that leaving units near your starting keep will leave them at risk, and that Gorlack will require allies at the volcano but they will actually both be completely safe.

Possible improvements
"From there, make your final stand" -> "(and) Then kill remaining wildlife"

**Comment by Jonathan-Kelly** [comment]
> This suggests that leaving units near your starting keep will leave them at risk, and that Gorlack will require allies at the volcano but they will actually both be completely safe.

In some cases (especially at the highest difficulties) they are both at risk. Gorlack may be badly injured when he reaches the volcano or the starting keep can become a target for monsters, especially if only the most vulnerable units are hiding there. Each play through of this scenario tends to be a bit different due to the randomization.

**Comment by IskarJarak01** [comment]
Completely safe isn't the right phrase. I think its reasonable for a first-time player to try and escort all of their units to the volcano, but that is way more difficult than the alternative: killing any immediate threats in the starting area and allowing the AI units to thin each other out, then sending Gorlack and a Sky Drake scout north.

Additionally, the monsters only ever seem to target Gorlack if they can't attack something nearby. As per my other issue, they literally stop moving when Gorlack is on unwalkable terrain. 

I've attached my replay of the scenario on Hard (there's a bit where I forget to move a Sky Drake and it nearly dies). 
[WoF-Ancestor replay 20240414-004105.gz](https://github.com/wesnoth/wesnoth/files/14995965/WoF-Ancestor.replay.20240414-004105.gz)

**Comment by Jonathan-Kelly** [comment]
From your replay it looks like the respawn rates are too low for some of the enemies and too many of them spawn on the snow covered mountain terrains (which means too many in the northwest and too few in the south).

This was partly by design, because it was unclear how most players would react to these "wilderness" type scenarios, so making them easier made sense. But since the feedback on them (so far) looks generally positive, I can probably make this scenario play more like its objectives suggest - more and better distributed enemies (outside of Yetis, there are enough of those).

**Comment by Jonathan-Kelly** [comment]
> I think the objective implies significant fighting, if not a second phase to the scenario, after Gorlack reaches the beacon

The objective is there for a couple reasons, the critical one being that the player does not instantly win when they reach the beacon, so if Gorlack is injured and/or being chased by Yetis, he can still die at that moment when the player would expect to be victorious.

The other reason is the objective helps set up a (hopefully) pleasant surprise for players (and one which they could have no foreknowledge of). Their forces may arrive at the beacon in bloody tatters and hopelessly outnumbered, and they are expecting a terrible battle is still to come, But finally their luck changes when a dragon shows up. Similar to how the ancient lich in S08 offers a truce once actively attacked. For better or for worse, this campaign followed the philosophy that while negative surprises should be minimized, positive surprises are okay.

> The current best strategy (at least as far I'm aware) involves Gorlack detaching from the flightless units and juking past the Yetis,

That this is the case is really the core issue and one that will need to be fixed no matter what. From your replay it appears Gorlack alone was able to swing east of the yetis and then continue north because there was no resistance from the north or east. And leaving the saurians behind at the camp had no consequences because no serious predators respawned near there before Gorlack made it to the beacon.

> I would be cautious with the difficulty here because if the player gets forced into a fight with 2 or more Yetis in the middle section of the map, it's likely to be a bloodbath.

Agreed, only increasing the distribution and spawn rates of the bears, wolves and monaxes would be the goal. As well as adding in the "Dark Omen" raven and distributing the gryphons better. There are just too many monsters spawning on the snowy mountain terrain in particular (that should only be where the Yetis are allowed to spawn).

**Comment by IskarJarak01** [comment]
Fair enough; I'll probably close this issue then since the improvements will be under different topics anyway.
