### ISSUE TITLE
SotBE: Make It Clear to the Player That Persistent Allied Sides Also Benefit From Early Finish Bonuses 

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8810]
### Describe the desired feature

In Son of the Black-Eye, at S12 Giving Some Back, you gain two allied orcish leaders with persistent recall lists and gold. They also benefit from early finish bonuses.  

This should be noted in the objectives window or the AI sides could be included in the gold carryover window so the player knows that the early finish bonus is significantly more valuable. 

Notes 

When playing, I didn’t realise that my AI allies also benefited from early finish bonuses until the last scenario because I got a huge early finish bonus. 

The percentage of allied gold carried over isn’t consistent (??).  
The gold the orc allies finish the scenario with – excluding EFB - gets 40% carryover. The exact gold carryover percentage for the EFB itself seems to be different across scenarios, but the ones I checked were above 40%.  (No idea what's going on here, happened in 1.16 as well.) 
Your allies mindlessly spend all their gold when actually playing, so in-game any difference in carryover percentages there will be trivial but it might be confusing if displayed in the normal gold carryover window.  
EDIT: The discrepancy is because your allies have a bonus base income per turn and this is included in the early finish bonus calculation.

**Comment by Wedge009** [comment]
There have been mistakes with how gold carry-over has been implemented in the past, especially with the transition from the 'old' to the 'new' (current) system.

**Comment by IskarJarak01** [comment]
I'm not sure whether the EFB behaviour is a bug or not and I don't believe there's any other persistent AI allies in mainline to check this against. The campaign is probably balanced around the allies having some extra gold, regardless of whether or not it's a bug.

It took a while to work out what was happening with the allies' gold. I did try using the old formula (80% or nothing). To be clear, my results are from observations in debug (killing enemy leaders and using GUI debug tools to modify side gold) rather than any poking around in the code.

**Comment by Wedge009** [comment]
I think Legend of Wesmere has what you might qualify as 'persistent AI allies'. Although some would say that campaign has serious issues so it may not be a good reference.

I'm not sure what to do about this one, I was just pointing out that inconsistent gold carry-over has been a problem in the past so what you're observing may be an actual bug, or it could be intentional by design. I don't really know.

**Comment by gfgtdf** [comment]
I'd be suprised if this "dublication" of carryover gold is intentional, and i'd vote for removing it.

**Comment by IskarJarak01** [comment]
It isn't bugged: I was using the player's early finish bonuses and had forgotten that the allied sides have more flat income per turn and this is included in their early finish bonus.

**Comment by Wedge009** [comment]
Okay, thanks. If you find there's still something amiss, we can re-open.

**Comment by IskarJarak01** [comment]
Just for future reference, should I avoid filing Enhancements (as opposed to Bugs) for "older" campaigns like SotBE?

**Comment by Wedge009** [comment]
Generally, I think better to report than not, although I find sometimes people object to their reports being flagged as duplicate because of some subtle variation on past issues and so we have an unnecessary accumulation of issues (not so long ago used to sit at around 1000 instead of the current 1200).

I don't see a distinction between 'old' or 'new' campaigns. If they're part of the officially-distributed campaigns, they can be discussed here.
