### ISSUE TITLE
:droid should either do something or error when given a null/empty side

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#8879]
As the title says. Currently there is no error or action on doing `:droid 3` in the tutorial for example.

The relevant code is:
https://github.com/wesnoth/wesnoth/blob/c57251ef34065aa96890e7fbc08fb9e41054a764/src/menu_events.cpp#L1462-L1570

**Comment by Pentarctagon** [comment]
There are 3 sides in the tutorial, so I'm not sure this is an issue?

**Comment by soliton-** [comment]
Side 3 is valid. The issue is that you get no feedback on the command if the side is null/empty. The case is simply not handled at the moment.

The simplest would be to just show an error. Another possibility is to actually switch the side to AI/human. Not sure if that might need special handling though.

**Comment by drewdaemon** [comment]
Okay, so to check my understanding: `menu_handler_.pc_.get_teams().size()` is the number of total teams that can/will be in play at some point, but some of them may not be in play yet (`team.is_empty() == true`).

I can't think of a reason that this is a meaningful distinction from the user's PoV; in either case, they don't see a team in play. Because of this, I lean toward showing the same error that we do if the index is outside of the number of teams.

WDYT?

**Comment by soliton-** [comment]
In the tutorial side 3 is hidden but that is distinct from being empty. You can see that Delfador is a unit from side 3 as well so it is a meaningful distinction for the player.

**Comment by drewdaemon** [comment]
Understood. Okay, so we will show a different message, something like `Side 3 is not a human or AI player.`

As a stretch goal, I can also look into how we might actually support the `droid` command for empty teams.
