### ISSUE TITLE
Assert at start when logging is enabled

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#9111]
### Game and System Information

- **Version:**1.19.1dev+
- **OS:**windows10

### Description of the bug

when i try to start game with https://github.com/wesnoth/wesnoth/commit/4f40c9deb5453e7cc99da4495251f60cb30436a0 commit it return "Attempted to access userdata location before userdata initialization!" window and i can't fix that without replace assert(!user_data_dir.empty() && "Attempted to access userdata location before userdata initialization!");by old code in filesystem.cpp line789.

### Steps to reproduce the behavior

try to start game.

Read error windows

Same if a change part name of Wesnoth1.19 userdata folder, it's same issue too with sippress of preference file.

**Comment by soliton-** [comment]
As a short-term workaround you can start the game with `--no-log-to-file`.

**Comment by newfrenchy83** [comment]
> As a short-term workaround you can start the game with `--no-log-to-file`.

Where i added this

**Comment by newfrenchy83** [comment]
with your commit i can start what if i use command line, i don't aggree with this and i don't know where put --no-log-to-file.

**Comment by newfrenchy83** [comment]
i don't undestand why `if(user_data_dir.empty()) {
		set_user_data_dir(std::string());
	}` was removed if create issue

**Comment by Wedge009** [comment]
What's going on besides just 'start game'? I haven't encountered this before.

**Comment by soliton-** [comment]
`--no-log-to-file` is a command line parameter. You can also set the environment variable `WESNOTH_NO_LOG_FILE`.

Obviously the issue that the assert triggers when logging is enabled was not noticed before. The assert now nicely shows that the logging setup is not well placed since it requires the user data dir location before it is set.

So if you used `--userdata-dir path/to/my/dir` to put the user data dir where you want it before the assert, the user data dir was anyway set up at the standard location first and log files created there before the setting took effect and the user data dir was set up again at the correct location. That was already broken before and now really needs to be fixed.

**Comment by Pentarctagon** [comment]
From a quick look, it seems like the fix would be to just move the `commandline_options` processing out of `do_gameloop` and put it right before logging initialization.

**Comment by soliton-** [comment]
Yeah, that should also get rid of the pre-parsing of some commandline arguments that is currently done.
