### ISSUE TITLE
remove wml_test of CI / ubuntu (scons, gcc, g++, debug  checking

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#9167]
because increasing number of wml test the checking in debug the time of checking is more longer and soon attain the time limit. I suggest what wml_testchecking will be removed of Debug ubuntu check like is already done in windows and Macos debuf checking.

**Comment by soliton-** [comment]
Since it seems like it takes about 6 times as long to run the tests on the debug build and doesn't appear to provide much benefit I agree that that's not a useful use of CI time.

**Comment by stevecotton** [comment]
Are we sure that there's possibility of the debug build catching something that the release build doesn't?

I know that Microsoft's STL puts in a lot more bounds-checking for debug builds, but in this case I (surprisingly) know less about the non-Microsoft world.

**Comment by soliton-** [comment]
What kind of guarantee are you looking for?

IMO this is about a trade-off in usability vs the off-chance a debug build ever catches something in WML tests.

If you're really worried a WML test run on a debug build will find an issue that no other test shows we could run that every day/week/month instead of every push on every PR.
