### ISSUE TITLE
Fix PNG Metadata or just convert to WEBP

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#9312]
### Describe the desired feature

Part of the goal to moving copyright data to images instead of a separate tracker was to get free of the separate bookkeeping and meta-work (https://github.com/wesnoth/wesnoth/issues/8863), but with PNGs this doesn't seem to work out so well with common tools like GIMP.

Speaking of GIMP issues, we could have converted everything to WEBP (https://github.com/wesnoth/wesnoth/pull/6611#issuecomment-1094105647), but didn't.  One of the reasons, though I didn't seem to mention it there, was that the version of GIMP available to me at the time couldn't handle WEBP, so terrain or animations required working in PNG, then converting to WEBP, making it a PITA to test.  But this doesn't seem to be an issue anymore, so:  **Maybe it's time to convert the PNGs to WEBPs?**

GIMP does seem to add thumbnails to the metadata, making the size of little images blow up, but that's easy to strip out at least.  There's probably a way to stop that, but I haven't figured it out yet...

**Comment by babaissarkar** [comment]
> There's probably a way to stop that, but I haven't figured it out yet...

maybe the save thumbnail option in the export dialogs? (GIMP 2.10.34)
![Screenshot from 2024-09-07 18-58-28](https://github.com/user-attachments/assets/018ced73-9e18-4449-993a-2334b6001764)
![Screenshot from 2024-09-07 18-58-07](https://github.com/user-attachments/assets/3ca446ec-ba66-4b15-9589-1952066f625c)

**Comment by doofus-01** [comment]
I don't have that option (GIMP 2.10.30), but sounds like it's not going to be an issue for anyone for much longer in that case.

**Comment by babaissarkar** [comment]
FWIW ImageMagick also seems to pickup the PNG metadata just fine: (ancient-wose.png)
![Screenshot from 2024-09-07 19-08-29](https://github.com/user-attachments/assets/a168fd36-ca84-45d2-b92d-0f2d881f5774)

So that's most probably a gimp bug.

**Comment by CelticMinstrel** [comment]
From the other thread, I think they weren't converted because it was deemed the savings weren't worth it? Maybe it even made things worse in a few cases.

**Comment by Pentarctagon** [comment]
The first post of #6611 has a csv showing the size changes - 34 out of 15532 images got slightly larger. IIRC the reason it wasn't done for everything was mostly that at the time there wasn't code to check for a .webp file if someone uses a .png file that doesn't exist.

**Comment by CelticMinstrel** [comment]
I think that CSV also showed that the savings was minimal for most of the terrain and unit graphics.

**Comment by doofus-01** [comment]
Why do you think that?

**Comment by CelticMinstrel** [comment]
> Why do you think that?

I looked at it briefly and saw a lot of >90% entries for unit or terrain graphics. I admittedly didn't look at all of them, but there's so many that that just isn't possible…

**Comment by Pentarctagon** [comment]
There are 527 images which would be compressed by less than 10%, which still means the vast majority of images would have their size reduced more than that.

**Comment by CelticMinstrel** [comment]
Metadata also seems like a poor reason for converting them.

Overall, I can't say I like the idea of converting all images to webp, but I also can't say I really have a _reason_ to feel that way.

There's still the question of the files that got larger – is it worth converting them in that case? The fact that they got larger might be an indication of some kind of issue with them that can be fixed, though. Like, maybe they have completely transparent pixels that aren't white, or something.

**Comment by Pentarctagon** [comment]
I think it'd be good to do for consistency at least, given the sum of the size increase for those is only ~85kb.

**Comment by Pentarctagon** [comment]
[conversion-good.xlsx](https://github.com/user-attachments/files/16920929/conversion-good.xlsx)
[conversion-bad.xlsx](https://github.com/user-attachments/files/16920930/conversion-bad.xlsx)
updated results - good vs bad is just whether it meets the "at least 10%" reduction threshold of the script.

**Comment by Elvish-Hunter** [comment]
> but with PNGs this doesn't seem to work out so well with common tools like GIMP.

That's an understatement. I tested the development version (2.99.18 via Flatpak) and not even that one is capable of handling `iTXt` and `tEXt` chunks (which are the way we currently store metadata); a quick search also proves inconclusive about other editors (like Paint.NET or Corel Paint Shop Pro), so it looks like the only ones that can handle those chunks are image viewers like XnViewMP (which I use) or IrfanView (I didn't test this one). *I didn't expect the situation to be this dire.*
There's another option whic can be tried: move the PNG metadata to an `eXIf` chunk, which supports proper EXIF information and is part of the PNG specifications since 2017, at the risk of still being at the mercy of whatever bug or missing feature the image editor used have (how many software will handle those chunks correctly and not incinerate or overwrite them?). At least, `exiftool` and the Pillow library since version 6.0.0 support it.
And if everything else fails, I'd like to remind everyone that we can always bail out and revert to the CSV file for tracking images (it's still in place for audio assets): although it's somewhat cumbersome to handle, all it requires to be updated is a spreadsheet like LibreOffice (which has enough sorting functions to allow inserting new records in the correct place at the first try) and any of the many tools available to compute MD5 hashes. This option has the advantage of _being independent of the other programs' foolishness_.

**Comment by babaissarkar** [comment]
Opened an issue here: https://gitlab.gnome.org/GNOME/gimp/-/issues/12017

**Comment by Vultraz** [comment]
Right now, we have the problem that basically any edit to an image has the potential to erase the EXIF data and cause the metadata CI check to fail (see #9297). I don't like the giant spreadsheet, and I sympathize with how annoying it is to keep track of the copyright info, either in the sheet or in the metadata itself. I wish we didn't have to do either. But I don't think the current status quo is tenable, wherein we have to be wary that even saving a png image is going to cause CI failures.

**Comment by CelticMinstrel** [comment]
> Corel Paint Shop Pro

I _might_ be able to check this actually… I think I have a copy of it. Do you think it's worthwhile though? Sounds like it might not matter.

> it's still in place for audio assets

Come to think of it, assuming the EXIF tracking _isn't_ reverted, it might be nice to move audio tracking into ID3 tags (for WAV) or Vorbis comments (for OGG) – just for consistency. (I bet the OGGs at least already have that info in them.)

**Comment by doofus-01** [comment]
> And if everything else fails [...]

Or we could not be wedded to PNGs.  I haven't seen any real reason for it.

**Comment by Elvish-Hunter** [comment]
> Or we could not be wedded to PNGs. I haven't seen any real reason for it.

Let's try inverting the question, because that's what would happen: is there any real reason to remove all PNG files from mainline? Image editors and viewers have started only recently to support WebP and that support might be still buggy or incomplete (see test below), so we might be throwing out one of the most used (and open) image formats for one that isn't so widely used yet.

> I _might_ be able to check this actually… I think I have a copy of it. Do you think it's worthwhile though? Sounds like it might not matter.

It's another additional piece of information, so it's always worthwhile.

I also tested how IrfanView (which is one of the most known image viewers; it also runs on WINE) handles our files. Well... EXIF information is shown only for JPEG files, while for WebP files is completely unsupported (the WebP format itself is unsupported unless a set of plugins is installed); for PNG files, only one chunk of metadata (probably the first one found) is shown in the Image -> Information... -> Comment dialog.
If this is indicative of how the general situation is, then moving everything to WebP isn't going to solve our woes.

**Comment by Pentarctagon** [comment]
If support for EXIF is fragmented regardless of image format, then at least webp also reduces file size for nearly all images. I'd also expect that people who'd need to edit that metadata would already be using an image editor rather than an image viewer.

**Comment by Vultraz** [comment]
FWIW (since they’re not used yet), SDL_Image can’t save WEBP files, so the spritesheets have to be generated as PNGs

**Comment by Pentarctagon** [comment]
Are the spritesheets relevant to the licensing information? IIRC they would get generated locally and then cached rather than being part of the repo.

**Comment by Vultraz** [comment]
No, they would be part of the repo.

**Comment by Pentarctagon** [comment]
I'm not sure how we'd handle copyright attribution in that case - it wouldn't really make sense to just list out 10+ authors on each spritesheet.

**Comment by Vultraz** [comment]
Actually, now that I think about it, each sheet gets its own `_sheet.cfg` file that data for each of the constituent images. It could go in there.

**Comment by Elvish-Hunter** [comment]
> If support for EXIF is fragmented regardless of image format, then at least webp also reduces file size for nearly all images.

OK, fair point (which by itself doesn't exclude using PNGs whenever it's more convenient for us). And one constant I seem to have found is that EXIF data is almost always handled correctly for JPEG files, probably because such images are often created by digital cameras and smartphones, which always embed EXIF information inside them.

> I'd also expect that people who'd need to edit that metadata would already be using an image editor rather than an image viewer.

However, I'd also expect an image viewer to show me everything that's in a picture, including metadata.
Speaking of editors, I also tested Paint.NET, which has a rather peculiar behavior: it doesn't allow viewing or editing metadata at all (maybe there's a plugin for this, but isn't part of the installer), however when saving the edited image all the available EXIF information is preserved for both JPEG and WebP. For our current PNG setup, instead, the text chunks are destroyed.
What we need to do now is test how a proper `eXIf` chunk is handled in PNG files, which means using `exiftool` to create one.

**Comment by babaissarkar** [comment]
GIMP supports EXIF metadata on PNG, but not png chunks, from here: https://gitlab.gnome.org/GNOME/gimp/-/issues/12017#note_2218515

**Comment by Elvish-Hunter** [comment]
I played a bit with `exiftool`, which supports `eXIf` chunks since version 10.59 (mine is 12.76). I used it on the Elvish Archer sprite to remove the previous PNG text chunks and move everything to `eXIf`, with this command line:

`exiftool -Artist= -Copyright= -CreateDate= -EXIF:Artist="unknown;(doofus-01)" -EXIF:Copyright="GNU GPL v2+" -EXIF:CreateDate="2022:05:01 00:00:00" '/<path removed>/archer.png'`

This is the resulting file, zipped because to avoid having its metadata stripped: [archer_png.zip](https://github.com/user-attachments/files/17003894/archer_png.zip). I already tested it with XnView, which shows the metadata correctly (no surprise here) and The GIMP 2.10.36, which shows the EXIF metadata correctly too but *does not allow editing them*.

This last point is a problem, because we can't force every artist to learn how to use a command line tool, can we?

**Comment by Elvish-Hunter** [comment]
> This last point is a problem, because we can't force every artist to learn how to use a command line tool, can we?

Further research shows that there are two GUIs for `exiftool`: [an old and unsupported one](https://exiftool.org/gui/) and [a fork of it that's currently maintained](https://github.com/FrankBijnen/ExifToolGui). Both of them are only for Windows.

**Comment by Elvish-Hunter** [comment]
There's one interesting message from loonycyborg in `#development` on Discord.

> total size of data increased from 541.5 MB to 587.7 MB according to steam

If adding the metadata increased the data size by 46 MB, it might be a point in favor of the previous system.
There's also another thing: I haven't got any feedback on the updated sprite I attached, so I was thinking that I could made a PR once I design a way to automatically update all the PNG files. However, this made me realize a thing: if anyone, be it in a pull request or in a direct push, decides to alter the metadata in a few, or even a lot of, images (maybe while also editing them), what indications do we have of what happened, besides `git` telling us that those files have been modified? Before, a `git diff` or GitHub's website showed us the differences in the CSV file, but that doesn't work for binary files.

**Comment by Pentarctagon** [comment]
That can't possibly be right. I mean, I see that it did actually happen, but the old copyrights.csv is only ~2.5 MBs. How did adding less data than exists in a 2.5 MBs file cause a file size increase of 46 MBs?

**Comment by CelticMinstrel** [comment]
> what indications do we have of what happened, besides `git` telling us that those files have been modified? Before, a `git diff` or GitHub's website showed us the differences in the CSV file, but that doesn't work for binary files.

Hmm… I guess we could have an action that shows metadata changes in a comment…

**Comment by doofus-01** [comment]
> This last point is a problem, because we can't force every artist to learn how to use a command line tool, can we?

Every artist isn't committing to the repository.  We could expect every artist to know their own name, and agree to to the accepted license.  We could expect the person committing the images to know how to run a script from command line.  This is no different from how it has been.  

As an an actual art contributor, I can say the old method wasn't a great experience.  The new method certainly has some issues that make it no improvement, but they are all solvable and I still think it would be better in the end.  I don't want to spend my available time arguing over this (or when file size matters or doesn't matter), so if there is general agreement that the project should go back to the old method, that's fine.  Otherwise, I'll slowly work on fixing the issues with the new method.

**Comment by Pentarctagon** [comment]
What's the list of issues that'd need to be fixed currently?

**Comment by soliton-** [comment]
> However, this made me realize a thing: if anyone, be it in a pull request or in a direct push, decides to alter the metadata in a few, or even a lot of, images (maybe while also editing them), what indications do we have of what happened, besides `git` telling us that those files have been modified?

The image meta data work flow prints the new meta data. If it's important that could be made into a comment in the PR.

**Comment by Elvish-Hunter** [comment]
Then I guess that we can try moving all the metadata in PNG files to the proper `eXIf` chunks, instead of the current `tEXt` and `iTXt`, and see if that's an improvement.
I suppose that updating all the metadata can be done with some sort of script (it'll be used only once), then the workflow will need to be updated to collect the metadata from the correct chunks. Do we need anything else?

**Comment by doofus-01** [comment]
There doesn't even need to be a script; exiftool can copy one tag to another in batches.

But that doesn't fully address the GIMP bugs.  Using Dublin Core XMP instead of EXIF works great with GIMP, but that seems to make the files ~0.5kb bigger.  There might be a way around that, I'm not sure, need to look into this more.

**Comment by soliton-** [comment]
Here is a file size comparison of the different metadata variants on the example of `data/core/images/units/human-loyalists/horseman/horseman-ne-breeze-1.png` as PNG and WEBP. After running `utils/woptipng.py` on it it has a size of 1436 with no metadata and conversion to webp results in a size of 1062. After adding author and license metadata in the different variants we get the sizes with metdata and with CreateDate and ModifyDate added we get the given size increase (same increase regardless of image format):

| size (PNG) | size increase | metdata type | size (WEBP) |
| --- | --- | --- | --- |
| 1500 | +62 | PNG | |
| 1576 | +130 | EXIF | 1224 |
| 2003 | +206 | XMP | 4046 |

Especially for small files and especially for WEBP XMP does add quite a bit and also appears to add the most for each additional tag.

**Comment by doofus-01** [comment]
So, you are saying we shouldn't migrate everything to XMP?  Or XMP isn't worth it for anything, including PNGs?

If we ever use sprite sheets, it would side-step the size issue.  It might even make terrain graphics easier to understand, but it would be a significant effort to get that part converted. 

I've created a wiki page for metadata, so the info and discussion isn't so scattered and hard to find.  https://wiki.wesnoth.org/ImageMetadata

**Comment by soliton-** [comment]
Well, what is the advantage of using XMP over EXIF? I don't know how much of an impact the file size has on performance but at least for WEBP the size increase is fairly ridiculous just in terms of storage alone.

If the impact on usability in different apps is not significant I'd rather stick to EXIF for JPEG and WEBP and move PNG to EXIF as well so we have some consistency in the metadata.

**Comment by doofus-01** [comment]
XMP was really just for usability in image editors, for PNGs.  WebP & JPEG  don't get touched as often, so no need to think about moving them to XMP.  This is in the context of the decision here to keep all the little images as PNGs.

I wasn't sure where the balance of benefits/drawbacks fell, that's why I didn't batch convert all the PNGs to XMP yet.  GIMP has other issues when it comes to optimizing file size (corrupted import of indexed color types), so giving up on accommodating it and going with EXIF is fine with me, but what do others who need to commit little PNGs think?  

@babaissarkar  @czyzby - is there any value in the metadata dialogs in image editors, or can we just bail on XMP?

**Comment by czyzby** [comment]
Not sure if I'm the best person to ask here, I just recently found out about the metadata requirement. So far my workflow has been GIMP → `woptipng` → `exiftool`, with the tags usually copied from the edited images. I'm fine with either set of tags, my only suggestion would be to add more examples of `exiftool` scripts to the wiki such as:

* Copying tags from another image with a new `Modify Date`.
* Converting between XMP and EXIF tags. (I had some PNGs with unexpected set of tags that didn't pass the CI job.)
* Adding an extra creator.

**Comment by soliton-** [comment]
We should adjust `utils/woptipng.py` to keep the tags we care about.

**Comment by Elvish-Hunter** [comment]
> We should adjust `utils/woptipng.py` to keep the tags we care about.
> 
> Regarding CI I would like it to make sure images are properly optimized in addition to having the right metadata. It looks like currently we have thousands of images that are not optimized.

I suppose that the script can be modified to read the metadata with `exiftool`, store them into some kind of variable and re-apply them once the compression is done. There's an issue with this approach: `woptipng` stores the initial size of the file and uses it to check if the optimization brought any results, which logically would always happen if we compare a file with metadata against its stripped version. 

By the way, our version of `woptipng` is outdated: the latest version (at https://github.com/matthiaskrgr/woptipng/tree/master) doesn't just run `optipng`,  ImageMagick's `convert` and `advdef`, but also `oxipng`.

I also kind of remember that, once upon a time, we used `pngcrush` to reduce the files' size, but now we don't. I wonder if that tool (or any other tool, for that matter) can improve the optimization and if it's worth adding to `woptipng`.

**Comment by doofus-01** [comment]
Adjusting CI and `woptipng` to get this all streamlined is a good idea.  It's beyond anything I'm going to try to implement, but I'll do my best to support and cooperate.

>   Not sure if I'm the best person to ask here, I just recently found out about the metadata requirement. So far my workflow has been GIMP → woptipng → exiftool, with the tags usually copied from the edited images. I'm fine with either set of tags, my only suggestion would be to add more examples of exiftool scripts to the wiki such as:

    Copying tags from another image with a new Modify Date.
    Converting between XMP and EXIF tags. (I had some PNGs with unexpected set of tags that didn't pass the CI job.)
    Adding an extra creator.

You work with PNGs and git/github.  XMP was an attempt to make the process simpler for someone like you.  It doesn't sound like it was useful at all, so that's another nail in the coffin for XMP.  Thanks for the feedback on the wiki.
