### ISSUE TITLE
Splitting MP and SP unit stats

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#9389]
Given all the acrimony that MP balance changes have caused, I think it's probably worth revisiting whether Default Era and Age of Heroes should share the same units as are used in SP content. So yeah, that's what this issue is for discussing.

**Comment by knyghtmare** [comment]
Let me start things off.

Splitting MP and SP balance might be a solution, however, there will always be shockwaves to any solution followed and executed.

We currently design UMC using core units on the notion that the core library will be more or less be staying stable, as no drastic changes. 
This change will preserve SP content (as the units would stay the same), which is one key ask. 
On the other hand, MP content (eras/survivals/MP campaigns) will be heavily impacted **if they use core units**, which seems to be the case with a majority.

However, we forget one small thing: we have some addon types called "hybrid" campaigns. Now, these are meant to be either SP or MP, depending on the player's choice of play (solo or with friends). These will be heavily affected. As in balance tuned for SP cannot be the same for MP (which is usually seen in some of these cases). If we even consider adding MP prefix to the multiplayer specific core units, these might end up broken. Since we are on the topic, adding this will make the synthesis of hybrid add-ons even more complex than it already is, as more attention is needed of the designer to cater for the tweaking of both game modes.

Additionally, there is this "feature" where you can play an SP campaign in MP from the MP create game. Now, what of these cases? The SP side of these may be okay and preserved but playing an SP work from the MP side with the swapped MP unit stats? These will just lead to some unpleasant experience, as the balance that was decided in SP mode, will be demolished by the split stats.

Another argument is the UX of things. Player experience. Players playing purely SP are okay, players playing purely MP (never having touched a campaign in SP) are okay. However, players playing both SP and MP: they are going to be just confused. For them, when they see one unit (whose stats they know of) in SP and MP, and see they are different between game modes, it will cause a confusion.
One example: Elf Fighter. We assume of the situation: in SP, elf fighter stats are they now, but in MP, they are maybe... +2 HP but -1 ranged damage. When these players play any elf SP campaign in MP mode (with the notion of having friends join in to chat while they play), these demographics of players will be confused. Since they have to keep track of not one set of core units, but now, an extra subset of changed units. This is not a good thing at all.

 Woah, five paragraphs already. 
Anyways, to summarize:  I do not think this is the solution that should be done in the end. 
We can do better. 
There has to be something better than this course of action.

**Comment by Pentarctagon** [comment]
To clarify: this isn't a proposal to have Wesnoth auto-swap stats depending on the mode. It'd be to have, for example, `id=Elvish Fighter` (the SP unit) and then `id=MP Elvish Fighter` (the MP unit). Therefore:
> When these players play any elf SP campaign in MP mode

they'd still see the same SP stats since the campaign would reference the SP unit type.

**Comment by ForestDragon-wesnoth** [comment]
from version 1.0 until version 1.16 there has not been any need to divide SP and MP. I believe the problem here is less about the SP vs MP divide and more about the current vision for unit balance being very controversial among the community.

Therefore, I think the newer 1.18 balance approach is the fundamental problem, while a split would only address some of the symptoms, but create new major problems in the process.

**Comment by ProditorMagnus** [comment]
Freeze 1.16 stats to current ids, with deprecation to 1.22. Create new unit types for both mp and sp, and that also gives good opportunity to fix #1847.

**Comment by ForestDragon-wesnoth** [comment]
> Freeze 1.16 stats to current ids, with deprecation to 1.22. Create new unit types for both mp and sp, and that also gives good opportunity to fix #1847.

That is a backwards compatibility nightmare, and would require a ridiculous amount of code rewrites for mainline and UMC

**Comment by AnekronCZ** [comment]
For what my opinion is worth, please don't.

Another issue I don't believe anyone mentioned yet is what would happen to the skirmishes. If they exclusively used MP stats, it might discourage campaign players who want to have a quick match against some AIs or a hot seat match with some casual friends.

It will also break all rookie / training campaigns since some knowledge that player obtains won't presumably be relevant in MP. This touches even some UMCs, as my own campaign is trying to teach people how to play Northerners.

I'd still rather have to deal with the impact of MP changes, such as the 1.18 Slurbow buff (which impacted my add-on significantly), than having to keep track of two similar but differing sets of stats to play a single game. I remain confident that MP and SP can coexist and only wish colder heads would prevail and the balance discussion could become less heated and accusatory.

**Comment by Tezereth** [comment]
I don't know how much I can say that hasn't already been said, but regardless, I'll put my insight on the matter.

I believe the fact this is even considered should light up an even bigger issue with the way Wesnoth is heading nowadays.
Wesnoth, since it's very beginning, had ALWAYS managed to make SP coexist with MP. The balance has been quite fine tuned to ensure has much, even if nothing is truly 100% perfect.

Yet, and it is mostly visible with 1.18, changes have become wilder, more controversial, and now to the point where splitting stats between MP and SP is even considered. Before even starting on the learning, tutorial and technical issues, the simple fact prior to that, Wesnoth has lived very long without theses issues, should serve as proof that the problem isn't ancient. There's issues in the way the game is heading.

As for examples of why splitting is a problem, we can already start with the issues of tutorials. All the knowledge you may learn on units and strategies suddenly become irrelevant, to a different degree depending on units.

Campaigns, on top of serving of tutorial or hard challenges to hone your skills, should make any player knowledgeable of units and factions strength, and should be able to head into multiplayer matches with reliable knowledge of what they know about the game, only having to learn and adapt their strategies to real players, as they fight differently than AI's. Having to relearn the game and keep track of differences is simply a pain, one that many players will likely not want to go through, and at best drive them away from MP (and vice versa), or at worse drive them away from THE GAME ITSELF, if they played enough campaign content and simply wished to have some multiplayer experience, just to find out they're practically playing a different game.

As for technical issues, it mostly has to do with potential problems with existing content, both mainline and UMC, but there's another problem. MP, is not JUST simple pvp maps. From survival maps, to more gimmick maps, to coop, a lot of them can be thrown off balance very easily. Another issue I see is peoples that may consider making campaigns with the MP units stats, adding to the confusion, and peoples complaining a certain unit stats that are either in sp should be in the mp version, and vice versa, creating more problems all around.

Another issue peoples seems to not think about often is what I like to call the "pandora's box" issue. If we allow wider and wilder change to one side, then this sets a precedent, which will serve to justify even wider changes in the future, making EVERY POINTS TALKED ABOUT EVEN WORSE. Sure, some changes are rather small NOW, but what's to say it'll remain that way?

From many standpoints, this split creates many issues in many areas, and I cannot support it.

**Comment by DuncanusDillius** [comment]
Hullo, hullo. Seems like every voice helps - so I might as well put in my input:

I was actually orginally for splitting mp and sp. It seems like and easy way for people to be happy each way, and a way to keep balance and lore seperate. The key word in this statement is **orignally**. I now see many problems with this, such as tutorials being useless, mp creators (somehow I never knew those existed) and more. 

This whole thing seems to come from 1 root, bad design choices. Althought they may be a great idea, there is a balance between perfect and fun. If you want the game to be balanced, get rid of levels and terrain, and make everybody a peasant :shrug:. We shouldn't have to create a split because the design choices ruin the synergy. I'm not saying that we should keep all the stats from 1.14 (which I wouldn't be against, but I see problems), but we should make sure that we don't redo balance and such just for the sake of it.  Imho I feel updates shouldn't even exist unless there is an outright problem, or improvement that people want.

Just my ideas though :/


Your's sincercerly, Duncan Dill

**Comment by hladkyjakub** [comment]
I'm not going to dive into discussion, just saying that this seems like a hella bad idea :/, to split SP and MP units.

**Comment by amakriLexa04** [comment]
Well, I didn't expect that someone would actually come up with the idea of using the same units in singleplayer and multiplayer, but with different stats. Does this have any lore or logical justification other than “why not”? I have big doubts about this, because wesnoth has existed for more than 20 years and there has never been a need for this, but now for some reason there is such a proposal. 

In general, I don't understand why it is necessary to even change the stats of units back and forth every version. It seemed to me that in 1.16, and even in 1.12, everything was good enough to never touch the topic of balance ever again.

If the split happens, there will definitely be a lot of confusion. Older players may still somehow adapt to the changes (or just play only the old versions of the game), but for newcomers it will be another bad factor from the game, because it will be strange for them to see different stats for units that look exactly the SAME. And there are almost no newcomers anyway, in case you all have forgotten, because of the outdated UI and the little love of modern gamers for "complex" strategies. 

So please don't do this, it's a very very very VERY bad idea.

**Comment by Discontinuum** [comment]
My primary objective to this is that MP is very diverse, so it won't solve the arguments. There are a lot of MP modes, their balancing needs are conflicting. So either you pick one particular mode arbitrarily and all other modes have to handle these stats instead of SP stats (so basically the same situation as now). Or you keep fragmentation going making distinct unit stats for all the popular game modes. But I don't think mainline should go that way, if there is a need in better balance in a certain mode, they will make an addon.

So I think it's not feasible, better just ship the same standard pack of units in the Wesnoth core

**Comment by kameramen0106** [comment]
Hello everyone. I understand that I am out of place and that community interactions should be as civil as possible. However, I believe that these changes should be discouraged at all costs.

There is no need to go out of our way to eliminate the simplicity of the game. The reason I have continued to play this very good game called Wesnoth until now is that it has not undergone any major changes (with the exception of 1.18) and has remained old in the good sense of the word. Well, the problem is that the recent updates with significant unit changes are starting to destroy that.

But this should be considered to some extent as another discussion. Sorry to be so abstract, but I cannot help but feel that splitting SP and MP would have huge negative impact on the original stance of Wesnoth, which is to maintain simplicity. The original designer of the game is Dave, and I would like to see second thoughts on whether or not this is respectful of his original design philosophy.

That is my very subjective opinion. I have two personal questions. One is that the option to keep the current status quo does not exist. The other is that the option to solve this by releasing an official mod has been eliminated.

**Comment by Dalas121** [comment]
Wow, this topic is popular.

I won't repeat the reasons others have already listed against this change - I agree with them. But I do want to add that I feel this proposal attempts to fix the wrong problem.

There is NOT a massive disconnect between the SP and MP communities in Wesnoth. Looking at Hej's forum post that prompted all this, the only MP players who responded were just as critical as the average SP player.

Rather, the current controversy is about how frequently and how dramatically unit stats should change. On one side there's highly conservative players who want an absolute minimum of changes, preserving historic unit stats as much as possible. On the other side, there are much more liberal players who want more aggressive fixes to perceived gameplay/lore issues. And of course, there's many moderates in-between.

Conservative/liberal are the two sides in the current issue, not SP/MP.

**Comment by hladkyjakub** [comment]
> Rather, the current controversy is about how frequently and how dramatically unit stats should change. On one side there's highly conservative players who want an absolute minimum of changes, preserving historic unit stats as much as possible. On the other side, there are very liberal players who want more aggressive fixes to perceived gameplay/lore issues. And of course, there's many moderates in-between.

Nicely said, Pointing out that for example undead buff and arcane resistance balance makes sence for me :D

**Comment by ForestDragon-wesnoth** [comment]
While I think the terminology Dalas used here seems a bit too US-politics-y, I do agree with the overall point that instead of a SP/MP divide there is a divide between people who want to preserve the game they love, and people who want to turn it into something else, and from my observation, the former position is significantly more popular among players while the latter is more popular among devs

**Comment by Dalas121** [comment]
> While I think the terminology Dalas used here seems a bit too US-politics-y
Yeah, I was literally googling synonyms but couldn't find anything great. Maybe "traditionalist" and "progressive"?

**Comment by ForestDragon-wesnoth** [comment]
>      Yeah, I was literally googling synonyms but couldn't find anything great. Maybe "traditionalist" and "progressive"? I'll edit.

ok, that works

**Comment by Gothyoba** [comment]
Oh no. I would’ve loved this to be added.
