### ISSUE TITLE
combat_phase Lua engine real-ranged attacks

### ISSUE THREAD

**Issue by hladkyjakub** [wesnoth/wesnoth#9536]
Hi,
Would be there any problems with replacing cpp combat_phase with same-structured Lua combat_phase?
(all API are there, works fine for me)
Real-ranged attacks are slowly making it into the game (not mainline) and I have finished Lua AI code, that on top of regular combat, works with real-ranged attacks.
So would be there problem in replacing the cpp combat_phase with Lua ?
(another advantage, would be that it would become easier for modders to work with AI, when it's in Lua)

**Comment by CelticMinstrel** [comment]
I don't think this is really something to consider at this time, since the AI system is modular enough that you can just use your Lua CA in place of the built-in combat_phase CA. Perhaps we can consider it sometime in the future once real ranged attacks are more mature and prevalent. Personally I'd prefer updating the existing C++ CA instead of replacing it with a new Lua CA, though.

**Comment by hladkyjakub** [comment]
> I don't think this is really something to consider at this time, since the AI system is modular enough that you can just use your Lua CA in place of the built-in combat_phase CA. Perhaps we can consider it sometime in the future once real ranged attacks are more mature and prevalent. Personally I'd prefer updating the existing C++ CA instead of replacing it with a new Lua CA, though.

I have working Lua combat-phase + ranged attacks, so updating existing c++ CA is nonsens from my lens... I won't do that at least.

**Comment by CelticMinstrel** [comment]
I'm not asking you to update the existing C++ CA. I would prefer that over replacing it with a Lua one, but I'm not completely opposed to replacing it at some point in the future.
