### ISSUE TITLE
Author credits not showing properly in add-on UI when using secondary_authors with forum_auth

### ISSUE THREAD

**Issue by MrTitainin** [wesnoth/wesnoth#9547]
### Game and System Information

- **Version:** 1.18.2
- **OS:** Windows

### Description of the bug

When using forum_auth=yes, secondary_authors don't show in author field in the UI, while putting multiple people into author field causes forum_auth login form to list them as one nickname, preventing access.

### Steps to reproduce the behavior

1. Create an addon with .pbl file
2. Put forum_auth = true in it
3. Fill author field
4. Fill secondary_authors field and put it below forum_auth (missleading error if not below!)
5. Check preview in add-ons window and secondary authors are not shown in "author" collumn

### Expected behavior

Either secondary_authors are credited (in author collumn of add-on UI), or there's a way to override author key in either its login or display functions (e.g. credits/primary_authors key).

**Comment by soliton-** [comment]
IMO the change of meaning of the `author` field for forum auth was not a good idea. It should mean the same thing as without forum auth. Since the established and documented use is similar to a credits section for an addon ("If several people have contributed significantly to the add-on you may want to list all of their names.") where there is no expectation that the mentioned names even correspond to a forum account it should not be used for access control.

I suggest to add a `primary_authors` field for access control and handle the author field as without forum auth.

**Comment by Pentarctagon** [comment]
Assigning myself, but I'm not sure when exactly I'll get to this, so anyone else should feel free to take this on in the mean time.

IIRC the main issue isn't showing it on the add-on manager UI (appending the `secondary_authors` value to the authors field on the UI would be trivial), it's that currently the add-ons server doesn't send the `secondary_authors` value when providing a client with the list of add-ons so a change to campaignd is needed as well. Adding a new `primary_authors` field would of course also require a change to campaignd.
